### ISSUE TITLE
PollQueryUntilCompleted sometimes throws MissingMethodException

### ISSUE THREAD

**Issue by smadigan-dexcom** [GoogleCloudPlatform/google-cloud-dotnet#1010]
We're getting this exception, but not every time it's called.  This is on the latest version of the bigquery api (1.25.0.836).

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException
   at Google.Bigquery.V2.BigqueryClientImpl.PollQueryUntilCompleted(Google.Apis.Bigquery.v2.Data.JobReference, Google.Bigquery.V2.GetQueryResultsOptions, Google.Api.Gax.PollSettings)

**Comment by smadigan-dexcom** [comment]
tried a workaround, this also failed:

System.MissingMethodException: Method not found: '!!0 Google.Api.Gax.Polling.PollRepeatedly(System.Func`2<System.Nullable`1<System.DateTime>,!!0>, System.Predicate`1<!!0>, Google.Api.Gax.IClock, Google.Api.Gax.IScheduler, Google.Api.Gax.PollSettings)'.
   at Google.Bigquery.V2.BigqueryClientImpl.PollJobUntilCompleted(JobReference jobReference, GetJobOptions options, PollSettings pollSettings)

**Comment by jskeet** [comment]
It sounds like you've got some mismatched versions somewhere - not in the Google.Apis.BigQuery.v2 package, but in the Google.Cloud.BigQuery.V2 package. If you've got some code built against an old beta and some built against a newer beta, this is precisely what you'd see.

**Comment by smadigan-dexcom** [comment]
Hi Jon,

Thanks for looking at this.  I agree it must be a mismatched version somewhere, but the intermittent behavior is strange.  Sometimes it works, other times we get this exception.
ALL google libraries are updated to latest versions, and I’ve been unable to find the mismatch.  Note we are NOT using mixed versions of any libraries anywhere (that I can find).

**Comment by jskeet** [comment]
Can you give more details about the context? What sort of application is this, and where is it being deployed? How are you building it? Which version of `Google.Cloud.BigQuery.V2` are you using, and which version of `Google.Api.Gax`? I'd urge you to find the differences between deployments that work and those that don't... there's not a lot we'd be able to do without more information.

**Comment by smadigan-dexcom** [comment]
The context is a straight-forward query:

                                                var table = Client.GetTable(ProjectId, DatasetId, GlucoseRecordTableId);
                                                var sql = $"SELECT patientId, recordedSystemTime, recordedDisplayTime, streamType, transmitterId, status, internalStatus, isBackfilled, sessionStartTime, transmitterTime, trendArrow, trendRate, value FROM {table} WHERE patientId in UNNEST(@PatientIds) AND DATE(recordedSystemTime) >= DATE(@MinTime) AND DATE(recordedSystemTime) <= DATE(@MaxTime)";

                                                var command = new BigqueryCommand(sql);
                                                command.Parameters.Add("PatientIds", BigqueryParameterType.Array).Value = patientIds.ToArray();
                                                command.Parameters.Add("MinTime", BigqueryParameterType.Timestamp).Value = MinDate;
                                                command.Parameters.Add("MaxTime", BigqueryParameterType.Timestamp).Value = MaxDate;
                                                var results = Client.ExecuteQuery(command).PollUntilCompleted().GetRows().ToList();

Normally this executes in a windows service, but I’ve also reproduced the problem in a simple test.

From packages.config

  <package id="Google.Api.Gax" version="1.0.1" targetFramework="net451" />
  <package id="Google.Api.Gax.Rest" version="1.0.1" targetFramework="net451" />
  <package id="Google.Apis" version="1.25.0" targetFramework="net451" />
  <package id="Google.Apis.Auth" version="1.25.0" targetFramework="net451" />
  <package id="Google.Apis.Bigquery.v2" version="1.25.0.819" targetFramework="net451" />
  <package id="Google.Apis.Core" version="1.25.0" targetFramework="net451" />
  <package id="Google.Bigquery.V2" version="1.0.0-beta04" targetFramework="net451" />

Using visual studio build (not command line msbuild)

**Comment by smadigan-dexcom** [comment]
Worth noting but maybe already obvious to you, this seems to only occur on long-running queries where polling is actually needed.  Successful calls are on queries that complete with the initial call.

**Comment by jskeet** [comment]
Ah - you're not using `Google.Cloud.BigQuery.V2` at all - you're using the *very old* package `Google.Bigquery.V2` (that isn't even listed any more). That's why you're getting the problem.

Update to `Google.Cloud.BigQuery.V2` - which will *mostly* just be a matter of updating your `using` directives, in terms of code - and all should be well.

**Comment by smadigan-dexcom** [comment]
Doh! (blush), that's not confusing at all :) Not sure what you mean by "not listed anymore" -- it shows up as a released library in Nuget PackageManager, and the capitalization matches Google.Apis.Bigquery.v2 to make it more confusing.  

Fix confirmed.

Thanks for your very quick help on this Jon, very appreciated.

**Comment by jskeet** [comment]
By "not listed any more" I mean it's not listed on nuget.org - search there and you won't find it.
You can go to the page directly - https://www.nuget.org/packages/Google.Bigquery.V2 - and there it will tell you that it's not listed for searches. This is basically the closest that nuget.org has to deleting a package.

Anyway, glad it's all sorted. (And yes, sorry it's confusing - we delisted the package to at least prevent *new* users getting confused.)
