### ISSUE TITLE
Generate service-specific poll settings

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1011]
#730 is a hand-written example of this, but we need GAPIC and codegen support.

**Comment by jskeet** [comment]
@chrisdunelm I believe this is done now, given [this code](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/a3ac49b8de636615893a264e4f182ec6bc4ead61/apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/SpeechClient.cs#L197) for example.

Can we close this, or is there anything more that you believe needs doing?

**Comment by chrisdunelm** [comment]
Yes, this is done. Closing.
