### ISSUE TITLE
GCS can't download data and get metadata in single request

### ISSUE THREAD

**Issue by pkese** [GoogleCloudPlatform/google-cloud-dotnet#1014]
When I upload my files to GCS, I also set some `x-goog-meta-...` keys that I need to return when getting data back from GCS.

However there doesn't seem to be any way to do both GetObject and DownloadObject at the same time although the HTTP API on the cloud does return both at the same time.

**Comment by jskeet** [comment]
Could you explain what you mean by "the HTTP API on the cloud"? I'm not aware of any way of doing this through the API at https://cloud.google.com/storage/docs/json_api/

Ultimately I think fetching the content and the data at the same time would end up with a fairly confusing API, even if it were feasible using the REST API we're using. I would suggest fetching the metadata, then explicitly downloading that generation to make sure you get the right version. You could write your own extension method to do that if you need it frequently, but I'm reluctant to put it into the Google.Cloud.Storage.V1 package API.

**Comment by pkese** [comment]
Sorry, maybe I was wrong (I haven't checked though). And I'm a bit unaware about 'generations' at GCS.

I'm in the process of porting some code from Amazon S3 to GCS and I was naively assuming Google's REST API was equivalent to Amazon's: in S3 you simply add additional meta tags as extra HTTP headers when you upload the file and then you get those same HTTP headers back at each GET request. The APIs follow that pattern as well.

It could be that GCS doesn't do that... in which case I'd find it a bit disturbing, having do two separate requests for what is practically the same information.

I should probably find a way around it. 

Thanks. Your help was appreciated. Feel free to close the ticket.

**Comment by jskeet** [comment]
GCS has the *XML* API which I believe is designed for compatibility with S3, and that may behave the same way... but the JSON-REST API isn't the same as that.

I'll ask internally whether there *is* any way to do this, although even if there is I'd then still need to think about how/whether to expose that in this library. Will close this for now, but update if I find out more.

**Comment by jskeet** [comment]
Have heard back, and yes, the XML API does return metadata in headers - but the REST API we're using doesn't.

**Comment by pkese** [comment]
Thanks. That is a valuable information.
