### ISSUE TITLE
DateTimes stored as strings 

### ISSUE THREAD

**Issue by smadigan-dexcom** [GoogleCloudPlatform/google-cloud-dotnet#1016]
In our bigquery tables, we store datetime as a timestamp, but we also store the datetime as the original string provided by the ultimate data source.

When attempting to retrieve the string form of the date, an illegal cast exception is thrown:
`   at Google.Cloud.BigQuery.V2.BigQueryRow.ConvertSingleValue(Object rawValue, TableFieldSchema field)
   ...`
 on a statement like:
`    var value = row["dateTimeRaw"];`
It appears that the value has already been internally converted to a DateTime (though it should not have been) and that an attempt is being made to cast that to a string and failing.

**Comment by jskeet** [comment]
Hmm. I have a sneaking suspicion I *may* know what's going on - and if I'm right, it could be a pain to fix :(

Could you give me an example of the value, in exactly the same text format you're saving it in?

**Comment by smadigan-dexcom** [comment]
2016-01-09T23:30:43.262Z
or
2016-01-09T17:10:41.924-06:00

**Comment by jskeet** [comment]
Okay, I can't easily check within BigQuery itself right now (I'm converting all our project.json projects to csproj, which leaves my working directory somewhat messy) but I'm pretty sure this example will explain it:

```csharp
using System;
using Newtonsoft.Json;

namespace JsonBug
{
    class Program
    {
        static void Main(string[] args)
        {
            string value = "2016-01-09T23:30:43.262Z";
            string json = $"{{ 'text': '{value}', 'timestamp': '{value}', 'mystery': '{value}' }}"
                .Replace('\'', '"');
            var settings = new JsonSerializerSettings();
            // Comment or uncomment to see different behaviour
            // settings.DateParseHandling = DateParseHandling.None;
            
            var data = JsonConvert.DeserializeObject<Data>(json, settings);
            Console.WriteLine(data.Text);
            Console.WriteLine(data.Timestamp);
            Console.WriteLine(data.Mystery);
            Console.WriteLine(data.Mystery.GetType());
        }
    }
    
    public class Data
    {
        public string Text { get; set; }
        public DateTime Timestamp { get; set; }
        public object Mystery { get; set; }
    }
}
```

By default, `Mystery.GetType()` returns `DateTime`. With `DateTimeParseHandling` of `None`, it returns `System.String`.

I believe this only affects deserialization where the result type is `object`, so Json.NET has a choice.

So what I think we *want* to do is:

- Disable the automatic date parsing
- Make sure the `BigQueryRow` code can do any parsing it would need to *start* doing that it didn't do before

The tricky bit is the first bullet. We don't know what else is sharing the same serializer, given that `BigQueryClient` can be passed a `BigQueryService`. We really want to find a way of controlling the serialization *just* for requests that this library makes, so it gets full control.

I'll need to look into this - it's likely to be somewhat hairy. For the moment you *could* try setting the underlying service's serializer yourself, but even that's not quite as simple as it might be - I suspect we'll need another release of Google.Apis to allow a `NewtonsoftJsonSerializer` to be constructed with settings.

// cc @chrisdunelm - I'll almost certainly be talking to you about this :)

Thanks very much for reporting this though. Better to make my life tricky now than after a release :)

**Comment by smadigan-dexcom** [comment]
No problem -- I can work around this for now, so it's not a hair-on-fire situation
