### ISSUE TITLE
Biquery column access with bad column name throws uncatchable exception

### ISSUE THREAD

**Issue by smadigan-dexcom** [GoogleCloudPlatform/google-cloud-dotnet#1017]
if you try to access a value with row["badColumnName"] it throws an uncatchable(?) exception across a managed/unmanaged boundary.  This would not be a problem if there was a row.ContainsKey() or something like that.  Combination of the two makes it impossible to avoid/handle.

![image](https://cloud.githubusercontent.com/assets/23220993/25505196/8f2ceb3a-2b55-11e7-9d1a-030abdc7d53e.png)

**Comment by jskeet** [comment]
There's no managed/unmanaged boundary here - not in our code, anyway - so there should be nothing stopping you from catching the exception.

You could find out which columns are available using the schema for the row if you need to. Use [`BigQueryRow.Schema`](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.BigQuery.V2/api/Google.Cloud.BigQuery.V2.BigQueryRow.html#Google_Cloud_BigQuery_V2_BigQueryRow_Schema) to access the schema, then [`TableSchema.Fields`](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.BigQuery.V2/api/Google.Apis.Bigquery.v2.Data.TableSchema.html#Google_Apis_Bigquery_v2_Data_TableSchema_Fields) to get at the fields of the schema.

**Comment by smadigan-dexcom** [comment]
well, the exception wasn't caught by the catch() that was in place and the process crashed.  My reality disagrees with you :) On the other hand, straightforward to use the schema for a pre-look to avoid the problem from happening in the first place, so I'll close this.  Thanks!

**Comment by jskeet** [comment]
If you have the time to give me a bit more information, I'd be very interested in your context. Here's a simple console app showing that the exception can be caught:

```csharp
using System;
using System.Linq;
using Google.Cloud.BigQuery.V2;

namespace BqBug
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = BigQueryClient.Create(args[0]);
            var results = client.ExecuteQuery("SELECT value FROM UNNEST([0, 1, 2, 3, 4]) AS value");
            var row = results.GetRows().First();
            try
            {
                Console.WriteLine(row["invalidKey"]);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Caught {e}");
            }
        }
    }
}
```

**Comment by smadigan-dexcom** [comment]
Ok i finally figured out that this was an interaction between the resharper test runner and the debugger (?) -- anyway, not your issue to be sure.

Thanks again for your help, Jon.
