### ISSUE TITLE
AddGoogleExceptionLoggingBase uses Singletons

### ISSUE THREAD

**Issue by Jetski5822** [GoogleCloudPlatform/google-cloud-dotnet#1033]
Hey GC team,

At the moment when you call AddGoogleExceptionLogging, and intern AddGoogleExceptionLoggingBase, it pushes the services to a Singleton. would it be possible to push this to a Scoped instead?

I am using a multi tenant setup (Orchard Core) and all Singleton instances are pushed to the application services. 

Alternatively, could the classes that the AddSingletons use, be turned to Public, so that I can call AddScoped?

Cheers, Nick

**Comment by jskeet** [comment]
(Assigned to Ian as our library author on this one.)

**Comment by Jetski5822** [comment]
Closing, as not an issue.
