### ISSUE TITLE
Write correlation-id with log entry metadata

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-dotnet#1038]
By writing a correlation-id into the logging metadata, users can get request-correlated logs in pantheon. See https://gist.github.com/JustinBeckwith/43dd04cfbc4551ddd8996a5b803da0b0 for details.

**Comment by iantalarico** [comment]
cc: @csells

**Comment by jskeet** [comment]
Ian: I've set the priority of this as P2, but feel free to adjust up...

**Comment by iantalarico** [comment]
@JustinBeckwith The link you have here 404s now.  Do you have updated context on this?

**Comment by amanda-tarafa** [comment]
This has been addressed for several use cases already in #2120 and #5388. 
We can expand for different use cases if there's demand, but this issue can be considered addressed.
Removing from backlog.
