### ISSUE TITLE
Google.Cloud.Diagnostics.Common.Tests.RateLimiterTest.CanTrace_StressTest is flaky

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1044]
Running the test in net452, I'm getting occasional failures, e.g.

```text
[xUnit.net 00:00:09.8397567]     Google.Cloud.Diagnostics.Common.Tests.RateLimiterTest.CanTrace_StressTest [FAIL]
[xUnit.net 00:00:09.8407245]       Assert.InRange() Failure
[xUnit.net 00:00:09.8408755]       Range:  (6 - 7)
[xUnit.net 00:00:09.8409397]       Actual: 2
```

**Comment by iantalarico** [comment]
How often are these failures happening?  I'm having trouble repoing.

**Comment by jskeet** [comment]
I ran the code locally and it was about 50/50. My pull request earlier today had to be restarted a few times :(

**Comment by jskeet** [comment]
Hmm. I can't reproduce either now. Will close for the time being.
