### ISSUE TITLE
UrlSigner using active GoogleCredentials

### ISSUE THREAD

**Issue by Jonathan34** [GoogleCloudPlatform/google-cloud-dotnet#1056]
Hi,

I deploy ServiceA in GAE project A using the default GAE service account.
ServiceA accesses buckets in projectB. The service account (and my username) has been given access to the projectB.

Code is straightforward and works fine
```
 var bucket = client.GetBucket(bucketName);
 foreach (var obj in client.ListObjects(bucketName, "bc593da7")) {...}
```
I want to generate sign url using the **current credentials** being used but I am having a difficulties.

`GoogleCredential credential = await GoogleCredential.GetApplicationDefaultAsync();`returns the UserCredentials when I test locally, and will, I believe, return the service account credentials when deployed to GAE.

UrlSigner is all about ServiceAccountCredential. So i cannot even do:
```
GoogleCredential credential = await GoogleCredential.GetApplicationDefaultAsync();
var cred = credential.UnderlyingCredential as ServiceAccountCredential;
UrlSigner urlSigner = UrlSigner.FromServiceAccountCredential(cc);
```
as it gives me UserAccount cannot be casted in ServiceAccount when testing locally

Question: is there a way to sign an url using current credentials without storing/deploying the json key with the app?

**Comment by jskeet** [comment]
As per the [Storage API docs](https://cloud.google.com/storage/docs/access-control/create-signed-urls-program) I don't *think* you can sign URLs with user credentials - only service account credentials.

@evildour Do you know if I'm right in that assumption?

**Comment by evildour** [comment]
That's my assumption as well. To create the signature in the signed url, we need to use a private key of a service account credential. You might want to look into using the App Engine App Identity service to create the signed url manually (see [here](https://cloud.google.com/storage/docs/access-control/signed-urls#signing-gae)).

**Comment by Jonathan34** [comment]
Ok but is there any way to retrieve the private from the account that is currently being used in GAE rather than publishing the key as part of our CI or in the source code...? our service may be deployed to different environments, so storing it in the git is not a solution, and publishing it via CI is a bit awkward and does not help local developments.

**Comment by jskeet** [comment]
I'll ask internally.

**Comment by Jonathan34** [comment]
Ok I ended up publishing the key via CI and in our git and enforced use of the service account key we use for development.
I also noticed APIs are not 100% harmonized on the way we lost from a json file:
```
                UrlSigner urlSigner = UrlSigner.FromServiceAccountPath("key.json");
                Stream jsonKey = System.IO.File.OpenRead("key.json");
                var client = StorageClient.Create(GoogleCredential.FromStream(jsonKey));
                jsonKey.Close();
                jsonKey.Dispose();
```
there is no way to load credentials once from one file and reuse in both urlsigner and storageclient

**Comment by jskeet** [comment]
You're right - there isn't really a good way of doing that at the moment. I'll put some thought into that - it's a matter of trying to avoid `Google.Apis.Auth` from being a leaky abstraction, but `UrlSigner` needing a specific kind of credential :(

I'm still trying to investigate whether `UserCredential`-based signing is feasible.

**Comment by jskeet** [comment]
Okay, I've heard back, and basically it's infeasible for user credentials.

There *is* another way of signing URLs without service accounts, using an HMAC. You [set up a key](https://cloud.google.com/storage/docs/migrating#keys) and then [sign the request with an HMAC-SHA1](https://cloud.google.com/storage/docs/migrating#authentication). We don't support that in the library at the moment, and it sounds like it wouldn't really help you anyway.

Are you happy to me to close this as basically infeasible for your original request?

**Comment by Jonathan34** [comment]
Sure, if there is no solution, then there is no solution :)
I will workaround that by pushing the key from our CI when deploying so that the key is not stored in our VCS.
Thanks Jon!

**Comment by minherz** [comment]
@jskeet, this limitation makes it nearly impossible to use `UrlSigner` in conjunction with implicit service account that is associated with GCE instance. When running an app on GCE instance and calling to `GoogleCredential.GetApplicationDefault()` the `ComputeCredential` is returned. There is no way to get an instance of `ServiceAccountCredential` from an instance of `ComputeCredential`.
I would expect that since both are based on `ServiceCredential` type, they both can be used for signing URLs. But the library is very strict on the matter.

**Comment by jskeet** [comment]
@minherz: I'll investigate whether this is logically feasible. I know it isn't for user credentials, but I don't know whether that's the case for compute credentials. I'm not sure whether there's an "implicit service account" for a GCE instance, so much as service *credentials* - which are slightly different.

Anyway, I'll look into it - but I've raised #2316 for this to be more specific than this issue.

**Comment by minherz** [comment]
@jskeet thank you. I have contacted Google Support and got similar answer, claiming that I have to have private key of the service account in order to create an instance of `ServiceAccountCredential` and without the instance I cannot use `UrlSigner`. This chain of dependencies is troublesome. I will follow up #2316.

**Comment by neil-119** [comment]
I wanted to share how we worked around this problem. We created a new Service Account and gave it the necessary permissions, and then we uploaded its JSON string to GCP Secret Manager. Since Secret Manager can be accessed with the default credentials, we stream the JSON from Secret Manager to create the credential, like so:

```
...
if (scopes == null)
                scopes = new string[] { "https://www.googleapis.com/auth/cloud-platform" };

            var json = ...; // grab it from Secret Manager
            using MemoryStream stream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(json));
            return (ServiceAccountCredential)GoogleCredential
                .FromStream(stream)
                .CreateScoped(scopes)
                .UnderlyingCredential;

...
```
