### ISSUE TITLE
Stackdriver Trace for ASP.NET Core works running locally but not when deployed to App Engine Flex

### ISSUE THREAD

**Issue by jsimonweb** [GoogleCloudPlatform/google-cloud-dotnet#1059]
For the following sample:
https://github.com/jsimonweb/csharp-docs-samples/tree/addTraceExample/appengine/flexible/Stackdriver

When running locally, traces work as expected and the traces show up in the Trace UI of Google Cloud Console. But when I deploy the sample to App Engine Flexible Environment and ping the sample's pages, the traces do not show up in the Trace UI of Cloud Console.

**Repro:**
=====================================================
Sample repo clone command:
git clone -b addTraceExample https://github.com/jsimonweb/csharp-docs-samples.git

Working: Running the sample locally via Visual Studio and clicking the "Initiate a trace" link
results in a trace showing up in the Google Cloud Console's Trace section.

Not Working: Deploy the sample to Google App Engine Flexible Environment and click the
"Initiate a trace" link. This fails to create the expected trace in the Google Cloud Console's Trace section.

Note: To run the sample, you have edit the sample's appsettings.json file, replacing "your-google-project-id" with a valid Google Cloud Project ID.

**Comment by iantalarico** [comment]
@jsimonweb I haven't had a chance to take a close look at this but my guess is you need to enable the Trace API.  I don't fully understand why but when you are running as yourself you don't need to have it enabled but when you are using a service account you do.

We have an open bug about how we handle failure that will help with this #842

**Comment by iantalarico** [comment]
I spoke with Jonathan offline this was fixed by upgrading to the latest version. It seems that the machine health checks were overwhelming the traces recorded.
