### ISSUE TITLE
gRPC native code not found with indirect references

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1066]
This is effectively due to a change in how nuget packages are produced in the new csproj format compared with the old project.json format. See https://github.com/grpc/grpc/issues/11279 for details - this issue is about what we'll do in *our* projects.

Plan:

- Autogenerate a direct dependency from each of our API packages to Grpc.Core with the relevant element to fix anything that depends *directly* on our API packages
- Write a FAQ entry explaining what to do if you're in an indirect dependency scenario
- Work with the .NET community and MS to see if there's a better option

**Comment by chrisdunelm** [comment]
A user has reported coming across this problem trying to use Google.Cloud.Pubsub.V1 v1.0.0-beta10.
A workaround is to put a direct dependency on [Gprc.Core](https://www.nuget.org/packages/Grpc.Core/) within your own project.
