### ISSUE TITLE
Error deploying ASP.NET Core applications to App Engine Flexible Environment

### ISSUE THREAD

**Issue by jsimonweb** [GoogleCloudPlatform/google-cloud-dotnet#1071]
Encountered error when trying to deploy an ASP.NET Core application to the App Engine Flexible Environment, after successfully deploying the same application numerous times previously.

**Error Message:**
starting build "22940437-0a9b-4586-9842-3133107aaaa"

FETCHSOURCE

Fetching storage object: gs://staging.your-projectid.appspot.com/us.gcr.io/your-projectid/appengine/default.20170524t102110:latest#1495646484925100
Copying gs://staging.your-projectid.appspot.com/us.gcr.io/your-projectid/appengine/default.20170524t102110:latest#1495646484925100...
Step #0: 4558a44eeefc: Verifying Checksum
Step #0: 4558a44eeefc: Download complete
Step #0: 4558a44eeefc: Pull complete
Step #0: 5b0feb2a22c7: Pull complete
Step #0: 315c81299695: Pull complete
Step #0: 949fb28543ef: Pull complete
Step #0: Digest: sha256:fbdfa82b7abdef5bae0a4beab9feb7e65eb1321b7f6ca195a729e955e451abbe
Step #0: Status: Downloaded newer image for gcr.io/gcp-runtimes/aspnetcorebuild@sha256:fcdfa82a7ebdef5afe0a4beab9fca7e65bb1327e7f6fa1755729f955e451abbe
Starting Step #0
Step #0: No valid .NET Core runtime version found for the app or it is not a supported app.
ERROR

**Temporary Workaround:** Run the following gcloud command:
`gcloud config set app/runtime_builders_root gs://aspnetcore-staging/`

This will set your gcloud to get its config from the staging bucket instead of the release bucket.

**Comment by jskeet** [comment]
Will move this to the Visual Studio github repo.
