### ISSUE TITLE
LruCacheTest is failing in AppVeyor and Travis

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1074]
I've just seen this failure three times in a row:

```text
Google.Cloud.Logging.Log4Net.Tests.LruCacheTest.MultithreadedUse()
Failed   Google.Cloud.Logging.Log4Net.Tests.LruCacheTest.MultithreadedUse
Error Message:
 Assert.True() Failure
Expected: True
Actual:   False
Stack Trace:
   at Google.Cloud.Logging.Log4Net.Tests.LruCacheTest.MultithreadedUse() in /home/travis/build/GoogleCloudPlatform/google-cloud-dotnet/apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.Tests/LruCacheTest.cs:line 126
```

**Comment by jskeet** [comment]
Looks like it. Closing.

**Comment by jskeet** [comment]
Looks like it's not fixed :(

https://travis-ci.org/GoogleCloudPlatform/google-cloud-dotnet/builds/236447824

**Comment by chrisdunelm** [comment]
It's timing-out, taking more than 5 minutes :(

**Comment by jskeet** [comment]
I'm able to reproduce this on my Linux box. The threads all start quickly, but then they take ages to finish (if they finish at all).

If the cache's capacity is set to be very large, it finishes in seconds. This is very odd.

**Comment by jskeet** [comment]
(Assigning to myself as we want to get to the bottom of this. It may not be today though...)

**Comment by jskeet** [comment]
Okay, it looks like lock contention on Linux gets really bad around 25-28 threads (on my box, anyway).

If we change the test to use 10 threads (instead of 50) but with each thread doing 5 times as much work, I believe we could lower the timeout to 30s and be absolutely fine. (On my box that takes about 3 seconds.)

@chrisdunelm: Does this sound reasonable to you?

**Comment by chrisdunelm** [comment]
Yes, that sounds reasonable, #1083 already implements this ;)
