### ISSUE TITLE
[Datastore] Don't see an entity with a query after insertion

### ISSUE THREAD

**Issue by markvincze** [GoogleCloudPlatform/google-cloud-dotnet#1079]
I have a problem with the Datastore. Occasionally, when I insert a new entity and commit the transaction, and afterwards I execute a query that should contain that entity, the query does not return the new entity.

I uploaded a small project illustrating the issue: https://github.com/markvincze/gcloud-datastore-invisible-entity, it does 20 iterations trying reproduce the problem, and if I run it a handful of times, I always see the issue happen 1-2 times.

Is this happening because my query is a global query, and for a global query we only have eventual consistency?  
Is there a way through the SDK to somehow mitigate this, and after doing the insertion and commit the transaction, somehow explicitly wait until the new entity is replicated everywhere?

**Comment by jskeet** [comment]
Thanks for the report. I honestly don't know much about Datastore consistency. It's possible that you would see it if you created a second transaction (after the first) in which to perform the transaction.

@pcostell Are you able to give any guidance on this?

**Comment by pcostell** [comment]
If your query is global, then yes this is definitely eventual consistency.

There is no way to mitigate this in the SDK, or based on time (eventual consistency is unbounded).

You need to address this in your data model. Here is a useful guide: https://cloud.google.com/datastore/docs/articles/balancing-strong-and-eventual-consistency-with-google-cloud-datastore/

The tldr; is that you need to use entity groups and ancestor queries for queries that you need to be strongly consistent. Be careful about the write rate limitations to a single entity group (1 write per second). It's generally advisable to put entities into an entity group based on natural boundaries. For example, a user is a great entity group. They won't make modifications more than once per second, any modifications a user does make are strongly consistent (so they don't click save and have something not appear), and if a user doesn't see another user's modifications immediately, that is ok for many types of applications.

**Comment by markvincze** [comment]
Hi @pcostell,

I see, thanks for the info!

(For my actual application this is not a problem, it was only a problem in my integration tests, where I was doing a modification, and then I called the query endpoint immediately. I worked around that by simply waiting between the queries, and it seems to be stable enough for testing purposes (if it'll be flaky I can increase the wait time).)

**Comment by pcostell** [comment]
Note that for testing, we do offer an in-memory local emulator. It has a --consistency flag, which can allow you to force consistency (useful for things like testing that a query returns what you expect).

You can start it up with:

    gcloud beta emulators datastore start --consistency=1.0 --no-store-on-disk

It also has a reset method (by sending an HTTP GET to `/reset`), which will clear out the data -- useful if you want to run a lot of tests without risk of data collision.

**Comment by SurferJeffAtGoogle** [comment]
We encountered this same problem when writing our integration tests for datastore.  You may be able to reuse our solution.  It's called [RetryRobot](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/testutil/TestUtil.cs), and you use it like this:

```cs
        private readonly RetryRobot _retryRobot = new RetryRobot()
        {
            RetryWhenExceptions = new[] { typeof(Xunit.Sdk.XunitException) }
        };

        /// <summary>
        /// Retry action.
        /// Datastore guarantees only eventual consistency.  Many tests write
        /// an entity and then query it afterward, but may not find it immediately.
        /// </summary>
        /// <param name="action"></param>
        private void Eventually(Action action) => _retryRobot.Eventually(action);

        [Fact]
        public void TestRunQuery()
        {
            UpsertTaskList();
            Eventually(() =>
            {
                Query query = new Query("Task");
                DatastoreQueryResults tasks = _db.RunQuery(query);
                Assert.False(IsEmpty(tasks));
            });
        }
```

From https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/datastore/api/TaskListTest/DatastoreTest.cs

**Comment by markvincze** [comment]
Hi @pcostell thanks, this is really good information, I didn't know about the emulator before, I'll certainly give it a try!

@SurferJeffAtGoogle Thanks, this looks really nice!
