### ISSUE TITLE
Google.Cloud.Diagnostics.AspNetCore IServiceCollection extension methods are not idiomatic.

### ISSUE THREAD

**Issue by ILMTitan** [GoogleCloudPlatform/google-cloud-dotnet#1086]
Nearly every example of an **Add** extension method to `IServiceCollection` that takes arguments takes them by taking a setup `Action` and sending it some sort of options object.
```
            services.AddMvc(options =>
            {
                options.RespectBrowserAcceptHeader = true;
            });
```

Examples include AddAntiForgery, AddAuthorization, AddLocalization and many others.

**Comment by ILMTitan** [comment]
This was brought to my attention by my conversation with @SurferJeffAtGoogle on the Google Cloud Visual Studio extension [issue #575](https://github.com/GoogleCloudPlatform/google-cloud-visualstudio/issues/575)

**Comment by iantalarico** [comment]
Fixed, will be out in the next release.
