### ISSUE TITLE
RateLimiterTest.CanTrace_StressTest is very flaky

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1094]
We've seen it failing plenty of times, mostly on AppVeyor. Let's look into it.

**Comment by iantalarico** [comment]
I'm happy to look into this if you'd like, feel free to assign to me.

**Comment by jskeet** [comment]
I think I've worked it out, actually... I think we want a more generous upper bound.

If we're tracing for "just over 2 seconds" with a 1 QPS limit, that could trace 3 times: once at t=0, once at t=1, once at t=2. We're asserting that the count would be in the range [1, 2].

I'm just going to review the failures we've had and see whether that would explain it.

**Comment by iantalarico** [comment]
ahhh yea that would be the problem, nice catch

**Comment by jskeet** [comment]
Hmm... except the current implementation doesn't allow tracing at t=0 (something I'm changing now).
I have a somewhat different implementation - let's see if it helps...
