### ISSUE TITLE
Link references in proto files fail in docfx

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#110]
This is part of a wider issue around the fact that our code generation creates C# with Markdown instead of XML comments (which isn't pleasant in Visual Studio), but for the most part, docfx just handles that. However, it (understandably) doesn't know how to resolve Markdown reference links. For example, in the Datastore proto we have (for `LookupResponse`):

> `// The response for [google.datastore.v1beta3.Datastore.Lookup][google.datastore.v1beta3.Datastore.Lookup].`

That ends up being rendered as-is, rather than being a link to `Lookup`.

I'll investigate how/where we can provide the link target to docfx.

**Comment by jskeet** [comment]
This is still important, but we're not expecting to get to it any time soon - it's likely to be a much bigger project than just this.

**Comment by jskeet** [comment]
Closing for now having added this to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/BACKLOG.md)

**Comment by amanda-tarafa** [comment]
This is now part of a bigger project to improve documentation.
Removing from backlog.
