### ISSUE TITLE
Would you take targetLanguage and sourceLanguage to a Enum

### ISSUE THREAD

**Issue by DavidYamer** [GoogleCloudPlatform/google-cloud-dotnet#1106]
By use, i found i must be remember the language type!

**Comment by jskeet** [comment]
Yes, this is deliberately not an enum as the set of supported languages can change - by keeping it as a string, we can generate the languages known to be supported at the time of generation, but users can specify others that have just become available.

**Comment by jskeet** [comment]
@DavidYamer: Feedback would be very welcome on this, so we can close it if no further action is required.

**Comment by jskeet** [comment]
Closing through lack of feedback.
