### ISSUE TITLE
Do you have a Nuget CI server that is public

### ISSUE THREAD

**Issue by Jetski5822** [GoogleCloudPlatform/google-cloud-dotnet#1115]
Do you have a CI server for Nuget, just so I can live on the bleeding edge for a while? i.e. Google.Cloud.Spanner.Data

**Comment by jskeet** [comment]
No, but we did publish an alpha version of Google.Cloud.Spanner.Data on nuget.org this morning :) No docs, no samples, but guarantees, but do please feel free to try...

**Comment by Jetski5822** [comment]
Perfect!

**Comment by Jetski5822** [comment]
Hey @jskeet I as trying to write an open source connector for YesSql to integrate in Orchard Core for google spanner. Do you know of a plan so I can get this stuff working and not get charged?

**Comment by jskeet** [comment]
No, I don't believe we have any such plan, I'm afraid.
