### ISSUE TITLE
How to list prefixes for Google.Cloud.Storage.V1 ListObjects?

### ISSUE THREAD

**Issue by ctaggart** [GoogleCloudPlatform/google-cloud-dotnet#1122]
[ListObjectOptions](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Storage.V1/api/Google.Cloud.Storage.V1.ListObjectsOptions.html) allows you to set a `Delimiter` such as `"/"`. When you supply that and a prefix that ends in that delimiter, you get a nice subdirectory listing. 

This is simple to [try out](https://cloud.google.com/storage/docs/json_api/v1/objects/list):

![image](https://user-images.githubusercontent.com/80104/27142756-5d62dd4c-512c-11e7-9c24-bc00b9881f57.png)

In [ListObjectsOptions.cs, I see](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/86c2bfd087a7e8f283425d55f5496f15dba4c9f3/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/ListObjectsOptions.cs#L24-L27):
``` csharp
    public sealed class ListObjectsOptions
    {
        // TODO: We can't currently return both objects *and* prefixes. Should we have a separate ListPrefixes method?
        // Something more complex? It's unclear how common this is.
```

How do we get the prefixes to return at all? Based on this code comment, I was expecting that when I set a Delimiter, it would return a list of prefixes for me, but it doesn't. How do I get a list of prefixes? In this example it should be "v4/prod/" and "v4/quick/".

**Comment by ILMTitan** [comment]
Right now, you have to pull the prefixes from the raw responses. The code to do this would look something like this:

```
            var client = StorageClient.Create();
            var prefixes =
                client.ListObjects(
                        "g-cloudsharp-unsignedbinaries", options: new ListObjectsOptions {Delimiter = "/"})
                    .AsRawResponses()
                    .SelectMany(o => o.Prefixes);
```

**Comment by ctaggart** [comment]
Thanks @ILMTitan, that does the trick.

``` fsharp
    let dir = "v4/"
    let options = Google.Cloud.Storage.V1.ListObjectsOptions()
    options.Delimiter <- "/"
    let subdirs =
        (storageClient.ListObjects (bucket, dir, options)).AsRawResponses()
        |> Seq.map (fun obj -> obj.Prefixes)
        |> Seq.concat
        
    printfn "subdirs: %A" subdirs
```
```
subdirs: seq ["v4/prod/"; "v4/quick/"]
```
