### ISSUE TITLE
ASP.NET TraceHeaderPropagatingHandler fails

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#1124]
The TraceHeaderPropagatingHandler on ASP.NET fails.  It appears to be an issue with no span being available after the request has finished.

reported by @jsimonweb 

To repo:

git clone -b addTrace https://github.com/jsimonweb/csharp-docs-samples.git
cd csharp-docs-samples/trace/
Open Trace.sln (build and run)

**Comment by bigdisk** [comment]
Any update on this?

**Comment by iantalarico** [comment]
@bigdisk I was OOO most of June but I am actively working on this now. I will post updates when I have more information.

**Comment by iantalarico** [comment]
Just a quick update here this seems to be an issue with how some async requests are being handled.  I will update with more information when I have more details.

**Comment by JorritSalverda** [comment]
Do you perhaps make use of `.ConfigureAwait(false)`? As the classic asp.net implementation makes use of `HttpContext.Current' this could actually fail if you don't by coincidence end up on the same thread the request started at.

**Comment by iantalarico** [comment]
It was an issue with the HttpApplication EndRequest and BeginRequest being in different threads.  I have  change out that should fix this soon.
