### ISSUE TITLE
Autodetect option not implemented on the uploadCsv function - bigQuery cloud lib

### ISSUE THREAD

**Issue by ssgtcookie** [GoogleCloudPlatform/google-cloud-dotnet#1166]
The [autodetect](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.BigQuery.V2/api/Google.Cloud.BigQuery.V2.CreateLoadJobOptions.html#Google_Cloud_BigQuery_V2_CreateLoadJobOptions_Autodetect) option is not implemented for the [uploadCsv](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.BigQuery.V2/api/Google.Cloud.BigQuery.V2.UploadCsvOptions.html#properties) function. Using the API directly it is possible to use the [--autodetect](https://cloud.google.com/bigquery/docs/schema-detect) flag and achieve this goal. The C# lib is missing this functionality that the API has.

This image shows the option available trough the web-ui. The same thing can not be achieved using the uploadCsv() function in .NET.
![Missing autodetect](https://cloud.google.com/bigquery/images/auto-detect.png "Missing autodetect")

**Comment by jskeet** [comment]
Yes, we need to add this as an option for all the upload-related methods. I expect to *not* default to auto-detecting though - it's something the user should opt into explicitly.

**Comment by ssgtcookie** [comment]
I realize this question might be rude but can you give me an estimated ETA on this? Appreciate your quick replies @jskeet. :) 👍

**Comment by jskeet** [comment]
No, I'm afraid I don't have an ETA - we have a fairly large set of changes planned for BigQuery this quarter, and I don't know whether I'll try to do this before that other set or after. I'd expect it to be this quarter, but I realize that's not very much help.

Note that you can always use the escape hatch of getting the underlying `BigqueryService` and performing operations with that. You could use that just to perform the upload, and do everything else with `BigQueryClient` as a temporary workaround.

**Comment by ssgtcookie** [comment]
Ok very clear. I noticed that Python has the [same issue](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2926).

**Comment by jskeet** [comment]
I wasn't *planning* on doing another NuGet release for BigQuery imminently, but @ssgtcookie if you need this fairly urgently, I could roll one out. Let me know.

**Comment by ssgtcookie** [comment]
@jskeet that would be great! I'm using the lib to build a new tool for a Google 360 account. The auto-detect function plays an very important role in this. Thanks!!

**Comment by jskeet** [comment]
Release 1.0.0-beta13 is now on nuget.

**Comment by ssgtcookie** [comment]
You are amazing, thank you so mutch!

**Comment by jskeet** [comment]
Not so amazing - just found that I didn't do it quite properly, leading to a NullReferenceException. I'm fixing that now, and I'll release a new nuget package immediately after.

**Comment by ssgtcookie** [comment]
Ok thanks for the heads up, it's appreciated.
