### ISSUE TITLE
Consider rename of pubsub "SimplePublisher" and "SimpleSubscriber" classes

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-dotnet#1188]
Before GA release consider rename of pubsub "SimplePublisher" and "SimpleSubscriber" classes.

Suggestions for better names welcome :) Please leave comments here...

**Comment by evildour** [comment]
Not sure if these are much better, but the names "TopicPublisher" and "SubscriptionConsumer" both imply that they work with a single topic and subscription, respectively, so that might be a little clearer than the generic "Simple..."

**Comment by jskeet** [comment]
Given no movement on this in two months, do you think we can close this? I'm "meh" on Mike's suggestions - I don't particularly love them, but I don't dislike them either... unless there's a clear benefit, I'd err on the side of leaving it as per beta.

**Comment by chrisdunelm** [comment]
Yes, I agree to leave it as it is. I still can't think of a better name.

**Comment by chrisdunelm** [comment]
Closing, the current names seem the best we can come up with.

**Comment by chrisdunelm** [comment]
The names `PublisherClient` and `SubscriberClient` are generated using the C# standard naming convention for all C# gRPC-based cloud library code. All C# cloud libraries follow this naming pattern `<service-name>Client` (e.g. taking another service at random: [FirestoreClient](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Firestore.V1Beta1/Google.Firestore.V1beta1/FirestoreClient.cs#L550)). We would be extremely reluctant to change this, as discussed with the pubsub team when we first started on the client work.

We'd be very happy to improve the naming of `SimplePublisher` and `SimpleSubscriber`. I'll contact you to set up a meeting.

**Comment by chrisdunelm** [comment]
This is being followed-up offline.

**Comment by chrisdunelm** [comment]
Still an ongoing conversation with pubsub server team about this.

As far as I know, this is the last issue to be resolved with the pubsub client before it can go GA.

**Comment by chrisdunelm** [comment]
The decision has been made to rename the auto-generated classes to: `PublisherServiceApiClient` and `SubscriberServiceApiClient`.
And the handwritten classes to `PublisherClient` and `SubscriberClient`.

A PR for this is expected in the next few days, and a new beta release will be pushed to nuget.

**Comment by danoscarmike** [comment]
Hi @chrisdunelm, any updates?

**Comment by chrisdunelm** [comment]
@danoscarmike Sorry, was busy with conference/demo for the last week or two. A new beta with this rename will be published in the next day or two. This is expected to be the final beta, with the GA release following shortly.

**Comment by chrisdunelm** [comment]
Fixed by #1843 and pushed to nuget as beta16.
