### ISSUE TITLE
libgrpc_csharp_ext.x64.dylib not found (.net core 2 preview 2)

### ISSUE THREAD

**Issue by Jonathan34** [GoogleCloudPlatform/google-cloud-dotnet#1205]
Similar to: https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/1186
but using .net core preview 2
```
dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

running some integration tests
```
System.IO.FileNotFoundException : Error loading native library. Not found in any of the possible locations: /Users/jdelfour/code/UCP/UDL-API/ihs/test/IntegrationTests/bin/Debug/netcoreapp2.0/libgrpc_csharp_ext.x64.dylib,/Users/jdelfour/code/UCP/UDL-API/ihs/test/IntegrationTests/bin/Debug/netcoreapp2.0/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/jdelfour/code/UCP/UDL-API/ihs/test/IntegrationTests/bin/Debug/netcoreapp2.0/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib
```
This does not work even with a reference to `grpc.core 1.4.x`

**Comment by jskeet** [comment]
Can you provide a way of reproducing this?

**Comment by Jonathan34** [comment]
i ll prepare a test project

**Comment by Jonathan34** [comment]
[testapp.zip](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/files/1139953/testapp.zip)

Note: I am on MacOS

install .net core 2 preview 2
```
cd testapp
dotnet restore
dotnet test
```

**Comment by jskeet** [comment]
Thanks - I'll try to reproduce in the morning. If it turns out to be only broken on preview 2 though, we may not want to consider that a bug in the package... It may be that we need to report it as an sdk bug.

**Comment by jskeet** [comment]
Hmm. It's not building for me with preview 2 on Windows... will try on the Mac now :(

```text
C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\Microsoft.Common.CurrentVersion.targets(1984,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [c:\Users\jon\Downloads\testapp\testapp\src\src.csproj]
Program.cs(7,28): error CS0234: The type or namespace name 'Hosting' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?) [c:\Users\jon\Downloads\testapp\testapp\src\src.csproj]
(lots more of the same)
```

Unfortunately the build log is enormous when using "detailed" mode, making it hard to see which assemblies are problematic.

**Comment by jskeet** [comment]
Ah - extracting the zip file again into a clean directory and trying again reproduces the error on Windows. That'll make things simpler...

**Comment by jskeet** [comment]
Okay, it looks like this is a problem with one of the test runner packages. If you change the versions to:

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170517-02" />
  <PackageReference Include="xunit" Version="2.2.0" />
  <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  <PackageReference Include="Grpc.Core" Version="1.4.0" />
</ItemGroup>
```

... then it works. Changing the `xunit` versions back to `2.3.0-beta*` reproduces the failure. I think it's probably worth you raising an issue with xunit, but I don't think there's anything for us to do here...
