### ISSUE TITLE
TypeInitializationException from TranslationClient.CreateFromApiKey

### ISSUE THREAD

**Issue by Hauglid** [GoogleCloudPlatform/google-cloud-dotnet#1230]
Exception when initialising the TranslationClient with the CreateFromApiKey method. 
This is done in Visual Studio Community 2017 for Mac (Xamarin.Android), testing on Nexus 5X Android 7.1.2

Stacktrace in file
[stacktrace.txt](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/files/1147763/stacktrace.txt)

**Comment by jskeet** [comment]
Looks like `Microsoft.Extensions.PlatformAbstractions.PlatformServices` doesn't work properly in Xamarin :(

Basically this library should work anywhere that .NET Standard libraries work properly, but if there are issues in the platform, we can't really help that :( I suggest you ask Xamarin whether they expect that type to work properly (and show them the stack trace).

Our code is just using

    Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default?.Application?.RuntimeFramework?.Version

**Comment by Hauglid** [comment]
Thanks for the help. 
After investigating a bit more it seems that the ...Platformservices.Default is not working on Xamarin.Android.
