### ISSUE TITLE
Work out why AppVeyor is failing

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1232]
The tests for Google.Cloud.Diagnostics.Common look like they're passing, but we get an odd test runner failure. It used to happen very occasionally - now looks like it's permanent. Investigating...

**Comment by iantalarico** [comment]
I'm happy to take this issue if you want just let me know

**Comment by jskeet** [comment]
Interestingly, after a spate of errors it looks like I've got one build which is actually working.

**Comment by jskeet** [comment]
The failures all have something like this:

```text
[00:07:57] [xUnit.net 00:00:46.1409336] When sending 'PUT http://localhost:1563/api/tests/batch' with body '[{...}] , exception was thrown: A task was canceled.
```

**Comment by jskeet** [comment]
This looks very related: http://help.appveyor.com/discussions/problems/3940-appveyor-test-service-erroring

**Comment by jskeet** [comment]
(I'm not sure how AppVeyor hooks into it though. We're using xUnit 2.2 which looks like it has changes from there already.)

**Comment by jskeet** [comment]
Looks like it autodetects AppVeyor via the `APPVEYOR_API_URL` environment variable. This is how AppVeyor has the tests tab as well as the log.

As this is causing us problems, I think *for now* it might be best to try to disable that. Will send a PR.
