### ISSUE TITLE
Investigate CI speed

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1234]
Builds are taking nearly 25 minutes on AppVeyor, leading to a lot of queuing.

It looks like about half of this is building the docs, which is a lot of time.

Plan:

- Add more logging during the build so we can see where time is going (e.g. any particularly slow tests)
- Potentially only build docs on Jenkins instead, once per day, when we run the integration tests
- Only build docs and run tests for projects which have changed (or where their dependencies have) - rather ambitious, admittedly...

**Comment by jskeet** [comment]
Results of some of the logging (a single build)

AppVeyor
- Solution creation: 10 seconds
- Restore: 50s
- Build: 4m30s
- Test: 5m
- Docs: 12m

Travis
- Solution creation: 40s
- Restore: 50s
- Build: 1m
- Test: 2m

Travis only builds and tests the .NET Core varieties, of course.

**Comment by benwulfe** [comment]
It looks like cloud-ruby is the worse transgressor here:

https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-ruby/history

cloud-ruby runs take *4 hours* -- which mean they completely block the
queue whenever they run.  Its too bad we are limited to a single concurrent
for the entire project.

**Comment by jskeet** [comment]
Did Travis *really* used to finish that fast? Wow. It's now taking 20+ minutes. However, it's not obvious that there's anything we can do here.

We're not building the docs on AppVeyor any more for other reasons - that's now about 20 minutes, usually slightly faster than Travis. Fundamentally, there's a lot of code to build and test...
