### ISSUE TITLE
Big​Query.​V2 -> add timePartitioning.type to uploadCsv

### ISSUE THREAD

**Issue by ssgtcookie** [GoogleCloudPlatform/google-cloud-dotnet#1266]
The uploadCsv function uploads data from a CSV file. It creates a table if need with the [CreateDisposition ](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.BigQuery.V2/api/Google.Cloud.BigQuery.V2.UploadCsvOptions.html#Google_Cloud_BigQuery_V2_UploadCsvOptions_CreateDisposition) option set. The CreateDisposition function is very helpfull but it would be even nicer with support for [timePartitioning ](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#timePartitioning).

The [timePartitioning ](https://cloud.google.com/bigquery/docs/partitioned-tables )can be helpfull when uploading data to BigQuery on a daily basis. The google API seems to have support for this functionality, the C# wrapper does not (if I'm not mistaken).

So my question would be: is it possible to add the"timePartitioning" setting to the uploadCsv function? As a reference, [this is](https://googlecloudplatform.github.io/google-cloud-java/0.19.0/apidocs/com/google/cloud/bigquery/TimePartitioning.Type.html) the java implementation.

For now as a workaround, it's possible to create a table first with the timePartitioning type set, and than upload data to it from a CSV file (do it in 2 steps proces, uploadCsv wont create the table). How nice would it be if the table creation with uploadCsv would be able to create a table with timePartitioning if there is no table exisiting?

Thank you guys, with kind regards.

**Comment by jskeet** [comment]
I don't believe the API allows for specifying time partitioning when creating a load job. Instead, you'd have to create the table first, then use the load job (via UploadCsv) to populate the table. We do support time partitioning when creating a table, using `CreateTableOptions`.

If this is a feature request for the underlying API, I can pass on that on to the BigQuery team, but it's not something we'd want to support in this library without underlying API support.

**Comment by ssgtcookie** [comment]
Ok Jon, thanks for your reply!

I also had thought of the suggestion you made so I will continue to follow that approach and do the uploadCsv process in 2 steps. I fully understand your last comment on not supporting stuff in the c# lib that the official API does not offer.

**Comment by jskeet** [comment]
The good news is that this is now supported in the API, so I'll reopen this issue... exposing it via the library should be simple :)

**Comment by juliuscesarnl** [comment]
That's great! I noticed that there are also other options available for date-partitioning like the [field](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load.timePartitioning.field) option. So while you're at it, could you add these parameters as well? The field parameter would save us tons of queries and code.

**Comment by jskeet** [comment]
We use the `TimePartitioning` type from the "raw" REST library ([Google.Api.BigQuery.v2](https://github.com/google/google-api-dotnet-client/tree/master/Src/Generated/Google.Apis.Bigquery.v2)) - and that has `Field` now. I'm not sure when it was added, but I'll check that our dependency contains it - basically it means that the next release should just get it automatically.

In terms of being experimental, I suspect the docs are up-to-date - I would treat it as experimental until the docs say otherwise. Glad to know it'll be useful though :)

**Comment by jskeet** [comment]
Hmm... just realized that CreateTableOptions specifies the TimePartitionType and TimePartitionExpiry separately, so currently field *can't* be set.

It'll be a breaking change for CreateTableOptions, but I think it's worth encapsulating TimePartitioning in the library.

**Comment by juliuscesarnl** [comment]
Hi Jon,

I noticed in your recent commits that you refactored the way to specify date-partitioning options and then closed this issue, but the Field option is still missing. I don't fully understand your last comment and maybe I'm completely wrong about this, but it seems to me that it's a simple matter of adding it to [TimePartition.cs](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/TimePartition.cs) as an optional parameter.

With kind regards,
JuliusCesarNL

**Comment by jskeet** [comment]
It's not missing in that it's in TimePartitioning, but as it's only experimental at the moment, I don't want to add it to the public API of this library. To use `Field`, you'd just do:

```csharp
var partitioning = TimePartition.CreateDailyPartition(null);
partitioning.Field = "created_timestamp"; // Or whatever
```

You can then use that in the options.

Of course, you don't have to use `TimePartition` at all - it's only a helper. You could use:

```csharp
var partitioning = new TimePartitioning
{
    PartitionType = "DAY",
    Field = "foo"
}
```

**Comment by juliuscesarnl** [comment]
It makes sense that you don't want to add it to the library yet and that we can specify it anyway.
One last question: when do you expect to publish these commits on NuGet?

**Comment by jskeet** [comment]
Not sure on that front, I'm afraid. There are other (breaking) changes I may well want to make this week, at which point I'll write a migration doc for the release, and do another release at that point.

**Comment by jskeet** [comment]
The package has now been pushed - please let me know if you have any problems.
