### ISSUE TITLE
Location property for CreateDatasetOptions

### ISSUE THREAD

**Issue by juliuscesarnl** [GoogleCloudPlatform/google-cloud-dotnet#1275]
Hi,

I'm using the Google.Cloud.BigQuery.V2 package and when I create a dataset, the default location is US. This could be an issue for some of our customers, so it would be great if this property is made available in the [CreateDatasetOptions ](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.BigQuery.V2/api/Google.Cloud.BigQuery.V2.CreateDatasetOptions.html) class.

Thank you in advance for your efforts.

With kind regards,
juliuscesarnl

**Comment by jskeet** [comment]
That looks like it should be quite easy, yes. I'm on vacation this week, but I should be able to add that next week.

**Comment by juliuscesarnl** [comment]
Thank you for the quick response, even though you're on vacation. Next week would be great! Enjoy the remainder of your vacation.

**Comment by jskeet** [comment]
Done in the master branch - but I have some other features to implement before I'm expecting to do another release build.

**Comment by jskeet** [comment]
This is now published in the beta16 build.

**Comment by juliuscesarnl** [comment]
Thank you for your effort!
