### ISSUE TITLE
Push Google.Cloud.DevTools.Common 1.0 or untag it

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1290]
(This is a "middle of the night" worry that I need to address first thing on Monday morning; it's a placeholder to avoid me forgetting.)

We've got a release tag for Google.Cloud.DevTools.Common v1.0, but no corresponding nuget package.
We should only be bumping version numbers as part of the release process - so the time between "tag created" and "package released" should be very small.

There have been commits to the source code since the tag - we need to review those and see whether or not they *should* be in a release of the package. If not, and if everything else is ready, we can build and release 1.0. Otherwise, we should remove the 1.0 tag while we work out when we *do* want to release 1.0.

**Comment by jskeet** [comment]
(cc @benwulfe @chrisdunelm @Deren-Liao)

**Comment by benwulfe** [comment]
@iantalarico has some ideas about making this automated in a way that would prevent this and other holes that currently exist.
we should talk about it next week once you are back.  Do you know who owns this package?  Can this be addressed monday if no one plans on releasing before then?

**Comment by jskeet** [comment]
Yes, it can wait until Monday. I just didn't want to forget about it, and not having any reminder over it was causing me to lose sleep. We shouldn't be releasing anything on the weekend anyway, IMO :)

Deren wrote the code, but there's no "ownership" concept of the code here... if something needs doing, anyone can do it.

I'm all for automation helping with things, but unless it would have stopped the package version from being updated in apis.json to 1.0 prematurely (which it was - *that* shouldn't have happened until we were starting the release) this could still have been a problem. Let's talk about it next week.

**Comment by Deren-Liao** [comment]
Thanks Jon for taking care of this.  

I changed the version because I saw Chris' PR that change the version. Then I changed apis.json too for it would cause build failure without changing that.  I guess there is an automated process somewhere that publish the "release"?

I should have waited you or Chris that took a look at the changes. Fortunately, I think this hasn't caused big problems.    

Thanks again for spotting this and fixed the problem.

**Comment by jskeet** [comment]
No problem. The creation of a GitHub tag/release is done by `tagreleases.sh` which Ben did as part of a *different* project. Basically we only change the version number just before the release, normally. We'll get better at automating this over time...
