### ISSUE TITLE
Can we add instructions for adding tests and running the test framework?

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-dotnet#130]
If we want PRs to be tested before they're submitted, can we add a short note describing how to add tests and how to run the tests before submitting the PR?

**Comment by jskeet** [comment]
Yup, sure. Presumably as part of contributing.md, which I haven't looked at for a while and may already be out of date...

**Comment by jskeet** [comment]
Somewhat addressed in #131, but will need more polish.

**Comment by jskeet** [comment]
I think this is now done as far as it needs to be, actually.
