### ISSUE TITLE
Consider new way of expressing "default" dependency versions in apis.json

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1300]
Came out of #1299. There are two kinds of dependencies here: in-repo and out-of-repo. (We default the versions for GAX and gRPC, for example.)

A few options here:

- "default" for both
- "prioject" for in-repo (as it means a project reference) and "default" for out-of-repo
- "current"
- "latest"

?

**Comment by benwulfe** [comment]
what does default mean in the context of grpc?  latest?

then I would propose we have two different constants  "latest_public" and "latest_private" which mean the latest exposed publicly in nuget vs the latest built internally in the repo.

Looking at this, I would know exactly what's being generated.

**Comment by jskeet** [comment]
It's not necessarily latest - it's the version we know we're currently targeting. (There could easily be a release that we don't particularly need to pick up, and we don't want to force an update unnecessarily. We're currently targeting Grpc.Core 1.4.0 even though 1.4.1 is out, partly because I didn't know about 1.4.1 until today.)

Also note that for at least GAX, we target different versions depending on whether the package we're using it in is prerelease or not. (So currently 2.0.0 for GA and 2.1.0-alpha01 for pre-release.)

Personally I think "project" (or "source"?) and "default" for in/out-of-repo respectively is best. I wouldn't want to use "private" (which could refer to a MyGet feed for example) and thinking about it further, "latest" could be misleading too (as per Grpc.Core above).

**Comment by jskeet** [comment]
Thinking about this even further, when it comes to GA packages, we may want to start filling in the explicit version number for Grpc.Core and GAX anyway, so that if the next release is a patch, we don't accidentally change it... (Then go back to "default" when it's back in pre-release.)

**Comment by benwulfe** [comment]
"it's the version we know we're currently targeting"  But I have no idea
what this means.  Is there some internal constant that this is referring
to?  This looks a bit like magic to me.

If there is a constant specifically stating what the tested GrpC version
is, the version should say that constant.  For example "GAX" indicating
what the current approved GAX version.

for other cases, "REPO" or "SOURCE" is better than "DEFAULT" which doesn't
really tell the reader anything.

**Comment by jskeet** [comment]
> If there is a constant specifically stating what the tested GrpC version
is, the version should say that constant.  For example "GAX" indicating
what the current approved GAX version.

Why would we repeat the GAX part when that's already the key:

```json
"Google.Api.Gax": "GAX"
```

... seems very odd to me.

I think "default" *does* tell the reader something useful - it indicates "It's the default, however that is determined"... which can be applied more consistently across multiple complex situations without specifying exactly how each default is determined. If you want to know that, look at the source code for the project generator, which isn't terribly tricky. I would rather have a shortcut of "default means I'll trust the project generator" than multiple different strings to remember each of which spells it out in painful detail:

```json
"Google.Api.Gax": "prerelease_version_of_gax_unless_this_package_is_ga_in_which_case_ga_gax"
```

Note that the "main" GAX dependency itself is rarely indicated anyway, because that's already included implicitly (the relevant Rest/Grpc version depending on the project type) - so there's already "magic" going on, to avoid everything having to be painful.

And of course, you can always check what the result is by looking at the generated csproj.

**Comment by benwulfe** [comment]
I think we will need to agree to disagree on this one.  Indicating *just*
"default" when "default" ends up meaning quite different things depending
on the context used doesn't help clear anything up:

"Google.Api.Gax": "GaxDefault"
"Trace.V1" : "CurrentSource"

communicates more than:

"Google.Api.Gax": "default"
"Trace.V1" : "default"

in the latter case, its unclear to me that those two things mean completely
different logic.

**Comment by jskeet** [comment]
That's why I was suggesting:

```json
"Google.Api.Gax": "default",
"Trace.V1" : "project"
```

Still different, but with no unnecessary difference between "default for GAX" and "default for Grpc". If we make "default" only valid for the external dependencies, then it's clearly "the default for GAX" because it's the version *for the GAX dependency*. Likewise the "project" fairly clearly means "make it a project reference" IMO.

**Comment by benwulfe** [comment]
ahh ok  I'm in for that as long as "default" can only be used for external
dependencies for which we have declared some internal constant somewhere.

If you try using default on an arbitrary dependency, the gen process will
fail, right?
if so, then sgtm.

**Comment by jskeet** [comment]
Yup. Will implement that tomorrow - just in time for the validation phase I've started writing in the tagger.
