### ISSUE TITLE
AspNetCore Logging_TimedBuffer Test is Flaky

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#1304]
Investigate why the test is flaky.

It looks like warning logs are getting written when they shouldn't

**Comment by jskeet** [comment]
Google.Cloud.Diagnostics.Common.Tests.RateLimiterTest.CanTrace_StressTest is being flaky yet again, too :(

**Comment by iantalarico** [comment]
Leaving open until we have a few runs.
