### ISSUE TITLE
Google.Cloud.Diagnostics.AspNetCore 1.0.0-beta 13 as very high CPU usage 

### ISSUE THREAD

**Issue by Jonathan34** [GoogleCloudPlatform/google-cloud-dotnet#1305]
@iantalarico as discussed on slack

```
 dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

Just starting up the app with one of the following enabled in startup.cs (no need to call a controller or whatever):
```
           // var tracingQPS = 1000;
           // services.AddGoogleTrace(options =>
            // {
            //     options.ProjectId = Configuration["AppSettings:GoogleProjectID"];
            //     options.TraceFallbackPredicate = TraceDecisionPredicate.Default;
            //     options.Options = TraceOptions.Create(tracingQPS);
            // });

            services.AddGoogleExceptionLogging(options =>
            {
                options.ProjectId = Configuration["AppSettings:GoogleProjectID"];
                options.ServiceName = "API";
                options.Version = "1.0";
            });
```
The `Use*()` is commented out but even if it is enabled, issue appears.

`Google.Cloud.Diagnostics.AspNetCore 1.0.0-beta 13 ` -> dotnet goes above 100% CPU.
`Google.Cloud.Diagnostics.AspNetCore 1.0.0-beta 11 ` -> dotnet has normal CPU usage.

Also happens with .net core 1.1.

Note: With such high CPU usage, App engine automatically scaled up the number of instances to the default max (20). Projected billing was around 700$ for three days for all our services...

**Comment by iantalarico** [comment]
@Jonathan34 If you have a minimum code sample to repo it would really help.  If not I can poke around Monday and try to repo.

**Comment by Jonathan34** [comment]
that should do it:

```
mkdir test
cd test
dotnet new webapi
dotnet add test.csproj package Google.Cloud.Diagnostics.AspNetCore -v 1.0.0-beta13
dotnet restore
```
add the calls to `AddGoogleTracing` or `AddGoogleExceptionLogging` to the `startup.cs`
```
dotnet build
dotnet run
```

**Comment by iantalarico** [comment]
I was able to repo this on linux, CPU jumped to 100% right away.  However, Windows does not have the same issue.

**Comment by jskeet** [comment]
Bizarre - but good to know it's easy to repro. Let me know if another pair of eyes would help.

**Comment by iantalarico** [comment]
@jskeet Will do. I'll see what I can figure out today I may see what you think tomorrow if I can't get anywhere

**Comment by iantalarico** [comment]
@Jonathan34 I found the issue.  As soon as the PR is merged I will release a new version.

**Comment by iantalarico** [comment]
@jskeet Random side note: Any ideas why this doesn't show up on Windows?  It seems like everything should have been affected

**Comment by jskeet** [comment]
Will have to delve into your change to think about that :)

**Comment by benwulfe** [comment]
possibly a difference in the inlining behavior of Task.Delay(0).  It should
be synchronous
<https://stackoverflow.com/questions/33407007/task-delay0-not-asynchronous>,
but maybe for some reason on Windows, its doing a context switch and
allowing the task to yield some cycles.

**Comment by iantalarico** [comment]
I will do a release soon.

**Comment by iantalarico** [comment]
@Jonathan34 New packages are now release.  Let me know if you have other issues or questions.

https://www.nuget.org/packages/Google.Cloud.Diagnostics.AspNetCore/1.0.0-beta14

**Comment by Jonathan34** [comment]
seems to be fixed locally on mac. I will let you know if the issue appears once deployed in app engine

**Comment by iantalarico** [comment]
@Jonathan34 Great, thanks for the status update!
