### ISSUE TITLE
Separate out long-running perf/stress tests

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1310]
Currently we have PubSub integration tests that take a very long time, and Spanner stress tests.

While they should clearly be run periodically, it would be good to be able to run the "regular" integration tests without running these.

Options:

- Have categories that are excluded by default (if such a thing exists with xUnit)
- Use an environment variable (ick) to skip/run them
- Separate them into different projects

**Comment by jskeet** [comment]
cc @iantalarico @benwulfe @chrisdunelm

**Comment by iantalarico** [comment]
I think a good end goal (but would require some work) would be to have them be in a separate project.  It would give clear separation about which tests do what.

**Comment by benwulfe** [comment]
Note that if your goal is to improve the running time of the integration
tests, I'm sorry to say that the spanner integration tests spend a great
deal of time setting up the test database (possibly as long or longer than
the stress test itself).  That could be improved or optimized with a bit of
work -- but I'm just saying moving the stress test out by itself wont fix
the test running time.

My other concern is that separating them out and running them less often
will hide issues.
Especially for stress tests, having them run many many times by different
people in different environments will eventually root out obscure threading
issues. And being run on machines with different cores, network latency,
etc all help in rooting these things out vs running them over and over on
the same box (our jenkins).

**Comment by jskeet** [comment]
Point taken on the timing. There's also the potential aspect of cost, if anyone's running against personal projects - some tests cost more than others. But maybe we should just live with it for now.

**Comment by jskeet** [comment]
Closing this for now as we're sticking with "slow but thorough".
