### ISSUE TITLE
When running buildrelease.sh toolsversion.sh cannot find packages the packages directory.

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#1337]

**Comment by iantalarico** [comment]
I don't think this is correct, there may be a different issue.

**Comment by benwulfe** [comment]
iirc, the packages folder is created automatically when nuget is run to
download packages.
when run under releasebuild, it is (by design) placed under releasebuild.

If it doesnt exist there, then possibly it was relying on a previous script
already having called nuget... ?

**Comment by iantalarico** [comment]
I think that's what it's doing.  The script is just assuming we have a packages dir when we only really need it to place docfx in.  I'll send a PR shortly.
