### ISSUE TITLE
Produce .NET Standard 2.0 packages now that it is final

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#1344]
.NET Standard 2.0 now is now final (https://github.com/dotnet/announcements/issues/24).

@jskeet Is this something you/we have on our plans?  I'm happy to test this on our libs.

cc: @Jonathan34

**Comment by jskeet** [comment]
I'd wait until .NET Core 2.0 is out, to be honest - netstandard2.0 is just the specifications, effectively.

When .NET Core 2.0 SDK comes out, we'll almost certainly want to update our build procedures to use that anyway (no more `dotnet restore` required - yay!) but we'll still want to target netstandard1.x. We should probably test on netcoreapp2.0 as well as netcoreapp1.0...

**Comment by iantalarico** [comment]
Sounds good, I'll close this for now and we can revisit when .Net Core 2.0 is final.
