### ISSUE TITLE
Allow runintegrationtests.sh to accept a file to track progress and retries

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#1358]
This will enable easier testing and reporting of coverage.

cc: @jskeet, @benwulfe

**Comment by jskeet** [comment]
This will allow us to run multiple times - especially if we can also keep going on failure. We may want to take a filename for failed tests too.

**Comment by jskeet** [comment]
Fixed in a different way in #1361.
