### ISSUE TITLE
Fix warnings under VS15.3

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1369]
I'm receiving a lot of warnings for NU1603:

> Castle.Core 4.0.0 depends on System.ComponentModel.TypeConverter (>= 4.0.1) but System.ComponentModel.TypeConverter 4.0.1 was not found. An approximate best match of System.ComponentModel.TypeConverter 4.1.0 was resolved.

Haven't delved into it yet. (It's only in tests. Maybe we need to update xUnit...)

**Comment by evildour** [comment]
I'm seeing these too, but they're errors for me (when running build.sh).

**Comment by evildour** [comment]
It looks like Moq just needs to be updated: https://github.com/moq/moq4/issues/375

**Comment by jskeet** [comment]
Hmm. I've been considering updating to 2.0 now that it's out, so I'm not sure it's worth going to 1.1.0.

If we update Moq, where do the build errors appear?

**Comment by evildour** [comment]
They're the same ones reported in #1370 when building the projects. However, it looks like there's no image yet for appveyor, so we might have to wait for that anyway: https://github.com/appveyor/ci/issues/1683. Perhaps it's best to see if we can just update Moq without touching anything else. I can test that out and create a PR to see if the build machines are happy with that.

**Comment by evildour** [comment]
Forgot this part: then we just need to not publish the analyzers locally if we have 15.3 installed so we won't see the analyzer errors.

**Comment by jskeet** [comment]
Thanks. I haven't seen any errors on CI machines due to this - I've only seen problems in VS, which are only warnings. (Admittedly those warnings may appear in the logs - I haven't looked closely, but I have waited for green.)

**Comment by evildour** [comment]
We may have to accelerate plans to update to 2.0. They updated the existing VS 2017 image for appveyor, so now all the builds are breaking.

**Comment by jskeet** [comment]
Yikes, that was quick. Will go back and edit my Noda Time config. It's worth noting that we'll need the core 1.0 runtime as well - not sure whether those will be present by default. Will investigate tomorrow.
