### ISSUE TITLE
Analyzer throwing errors

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1370]
> Analyzer 'Google.Cloud.Tools.Analyzers.InternalOptionalParametersRequiredAnalyzer' threw an exception of type 'System.MissingMethodException' with message 'Method not found: 'System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Semantics.IArgument> Microsoft.CodeAnalysis.Semantics.IHasArgumentsExpression.get_ArgumentsInParameterOrder()'.'.	

Will investigate, until @evildour wants to...

**Comment by evildour** [comment]
Already fixed. Just putting together the PR now.

**Comment by jskeet** [comment]
This is now fixed.
