### ISSUE TITLE
How do I observe errors via PubSub's SimpleSubscriber?

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1395]
In Java, it's possible to listen to errors while pulling messages from a subscription:
https://cloud.google.com/pubsub/docs/pull

**Comment by jskeet** [comment]
P1 in case it's work we would like to get done and into a beta soon. Feel free to reduce priority.

**Comment by jskeet** [comment]
@chrisdunelm: Can you comment on this?

**Comment by chrisdunelm** [comment]
C# works in a similar fashion to Go. Recoverable errors are hidden from the user, and automatically retried. Unrecoverable errors cause the `Task` returned by `SimpleSubscriber` to complete in a faulted state, with the exception being the unrecoverable error. This means if you `await simpleSubscriber.StartAsync(...)` it'll throw unrecoverable errors.

**Comment by chrisdunelm** [comment]
Without having looked into it closely, I don't really understand what Java is doing. What errors are being listened for? Are they recoverable errors or unrecoverable? I suppose being able to listen for recoverable errors may be useful, for logging if nothing else; but an unrecoverable error by necessity needs to shutdown the whole subscribe surely?

**Comment by chrisdunelm** [comment]
Closing, as unrecoverable errors are thrown, and recoverable errors are hidden from the user. Which I think is the correct behaviour.
@SurferJeffAtGoogle Please re-open with more details if this is incorrect.
