### ISSUE TITLE
It's difficult or impossible to initialize a PublisherClient with a json service account credentials file.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1398]
Initially reported here:
https://stackoverflow.com/questions/45806451/authenticate-for-google-cloud-pubsub-using-parameters-from-a-config-file-in-c-n/45844546?noredirect=1#comment78656830_45844546

Reading instructions here:
https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/8e68523527f0f72eada069d0f5a11eb0d0bf26e8/docs/root/faq.md

I wrote this code:
```
            string jsonPath =
                Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS");
            GoogleCredential googleCredential = null;
            using (var jsonStream = new FileStream(jsonPath, FileMode.Open,
                FileAccess.Read, FileShare.Read))
            {
                googleCredential = GoogleCredential.FromStream(jsonStream);
            }
            Channel channel = new Channel(PublisherClient.DefaultEndpoint.Host, 
                PublisherClient.DefaultEndpoint.Port, 
                googleCredential.ToChannelCredentials());
            PublisherClient publisher = PublisherClient.Create(channel);
```
Which is way too many lines of code to do something straight-forward.  Hence it's difficult.

But the code also doesn't work.  When I actually call CreateTopic, it throws an exception:

```
[xUnit.net 00:00:00.5085761]   Starting:    PubsubTest
[xUnit.net 00:00:01.7916516]     GoogleCloudSamples.PubsubTest.TestCreateTopic [FAIL]
[xUnit.net 00:00:01.7944427]       Grpc.Core.RpcException : Status(StatusCode=Unauthenticated, Detail="Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.")
[xUnit.net 00:00:01.7965285]       Stack Trace:
[xUnit.net 00:00:01.7977910]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:01.7984453]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:01.7990554]            at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
[xUnit.net 00:00:01.7995660]            at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
[xUnit.net 00:00:01.8001669]            at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
[xUnit.net 00:00:01.8007408]            at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
[xUnit.net 00:00:01.8012567]            at Google.Cloud.PubSub.V1.Publisher.PublisherClient.CreateTopic(Topic request, CallOptions options)
[xUnit.net 00:00:01.8018031]            at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
[xUnit.net 00:00:01.8023588]            at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
[xUnit.net 00:00:01.8029122]            at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
[xUnit.net 00:00:01.8033824]            at Google.Cloud.PubSub.V1.PublisherClientImpl.CreateTopic(Topic request, CallSettings callSettings)
[xUnit.net 00:00:01.8039021]            at Google.Cloud.PubSub.V1.PublisherClient.CreateTopic(TopicName name, CallSettings callSettings)
[xUnit.net 00:00:01.8043792]         C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\pubsub\api\Program.cs(217,0): at GoogleCloudSamples.Program.CreateTopic(String projectId, String topicId)
[xUnit.net 00:00:01.8049036]         C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\pubsub\api\Program.cs(483,0): at GoogleCloudSamples.Program.<>c.<Main>b__15_0(CreateTopicOptions opts)
[xUnit.net 00:00:01.8054579]            at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 parsedFunc9, Func`2 parsedFunc10, Func`2 parsedFunc11, Func`2 parsedFunc12, Func`2 parsedFunc13, Func`2 parsedFunc14, Func`2 notParsedFunc)
[xUnit.net 00:00:01.8060107]         C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\pubsub\api\Program.cs(473,0): at GoogleCloudSamples.Program.Main(String[] args)
[xUnit.net 00:00:01.8065219]         C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\testutil\TestUtil.cs(136,0): at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments)
[xUnit.net 00:00:01.8070263]         C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\pubsub\api\PubsubTest\PubsubTest.cs(60,0): at GoogleCloudSamples.PubsubTest.Run(String[] args)
[xUnit.net 00:00:01.8075701]         C:\Users\Jeffrey Rennie\gitrepos\dotnet-docs-samples\pubsub\api\PubsubTest\PubsubTest.cs(223,0): at GoogleCloudSamples.PubsubTest.TestCreateTopic()
[xUnit.net 00:00:01.8385964]   Finished:    PubsubTest
```

Source code is here:
https://github.com/SurferJeffAtGoogle/csharp-docs-samples/blob/pubsubChannel/pubsub/api/Program.cs

See the CreateTopic() function.

**Comment by jskeet** [comment]
Hmm. I wonder whether this is another case of a lack of scopes biting us. We *shouldn't* need to specify scopes, but it seems that in some cases we do.

Just for the sake of experimentation, could you try adding:

```csharp
googleCredential = googleCredential.CreateScoped(PublisherClient.DefaultScopes);
```

just before you create the channel?

If that works, that can at least shed light on that part. Then we need to:

- Find out why we need scopes, when I don't think we should
- Look at making it easier to load custom credentials (`GoogleCredential.FromFile` would at least help)
- Potentially make it easier to create a channel with custom credentials for any given service

**Comment by SurferJeffAtGoogle** [comment]
```
googleCredential = googleCredential.CreateScoped(PublisherClient.DefaultScopes);
```
worked!  Thanks!

**Comment by jskeet** [comment]
Great - it's good to have a workaround. I'm sure you'll be happy to hear we're not willing to let it rest there though :) Will leave this open while we work out the best next steps. In the meantime, see
https://github.com/google/google-api-dotnet-client/pull/1077

**Comment by hassanjahmed** [comment]
On
`Channel channel = new Channel(PublisherClient.DefaultEndpoint.Host,
                PublisherClient.DefaultEndpoint.Port,
                credential.ToChannelCredentials());`

I am getting:

>CS1061	'GoogleCredential' does not contain a definition for 'ToChannelCredentials' and no extension method 'ToChannelCredentials' accepting a first argument of type 'GoogleCredential' could be found

**Comment by jskeet** [comment]
You need a using directive - ToChannelCredentials is an extension method. I think it's in Grpc.Auth, but I'm on mobile so can't check right now.

**Comment by hassanjahmed** [comment]
I have this package installed 

> <package id="Google.Apis.Auth" version="1.28.0" targetFramework="net45" />

**Comment by jskeet** [comment]
It's not a matter of just packages - you need a using directive to make the extension method available. Visual Studio should suggest it to you if you put the cursor in ToChannelCredentials and hit ctrl-period.

**Comment by jskeet** [comment]
It's not a matter of just packages - you need a using directive to make the extension method available. Visual Studio should suggest it to you if you put the cursor in ToChannelCredentials and hit ctrl-period.

**Comment by hassanjahmed** [comment]
@jskeet That did work, I appreciate your help.

**Comment by jskeet** [comment]
Given that we now know that adding scopes fixes the issue, and we're making it easier to load credentials via a file, I'm going to close this. We still want to know why scopes are required though...
