### ISSUE TITLE
BigQueryParameter.Type + BigQueryParameter.ArrayType names

### ISSUE THREAD

**Issue by benwulfe** [GoogleCloudPlatform/google-cloud-dotnet#1403]
I'm not changing right now, but logging this for tracking.

These are potentially confusing.
Better names for each would be:

BigQueryParameter.Type -> BigQueryParameter.BigQueryDbType  (propertyname == typename as done in ADO.NET)

BigQueryParameter.ArrayType -> BigQueryParameter.ArrayElementType  (as done in reflection).

**Comment by jskeet** [comment]
Both sound fine to me, yes.
