### ISSUE TITLE
BigQuery - Datatypes not properly detected when using UploadCsv

### ISSUE THREAD

**Issue by juliuscesarnl** [GoogleCloudPlatform/google-cloud-dotnet#1406]
Hi,

When I upload a CSV-file in which all values are surrounded by double quotes and when using the AutoDetectSchema option, it detects all the values as a STRING datatype. Uploading the same CSV-file using the BigQuery UI and auto-detection works great though. We would really appreciate it if you can resolve this issue.

With kind regards,
juliuscesarnl

**Comment by jskeet** [comment]
I'll ask internally, but it's not really something the client library can fix, as we're just passing the data up and letting the server side detect the schema.

To be honest, I'd personally *expect* values surrounded by double quotes to be detected as strings - if you want non-string detection, is there any reason you're putting the values in quotes? If you could give a concrete example of what you're doing with some (non-confidential) test data, including the types you'd expect to be detected, that would be very helpful.

**Comment by juliuscesarnl** [comment]
Hi Jon,

Thank you for the quick reply and for looking into this. You're absolutely right that anything surrounded by double-quotes is expected to be detected as strings. The reason that the values are enclosed in double-quotes is because we download these reports using the Bing SDK, which has this behavior. In the attached file you can see the test data - the expected datatypes are included in the column headers.

[exampleData.txt](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/files/1260126/exampleData.txt)

The result of using the library can be seen in the following picture.

![image](https://user-images.githubusercontent.com/19571792/29819753-4dea0bb6-8cc2-11e7-98a6-43fe0dff1052.png)

Off-topic: I still find it odd that the BigQuery UI and API show different behaviors. I hope that the API team is working towards unifying them in terms of functionality.

**Comment by jskeet** [comment]
Hmm... I've just tried to reproduce this with your sample data, and it's worked fine for me.

I notice that you've not got field names either - it's not just that the types are wrong. Here's the schema I get from using the client library:

![schema](https://user-images.githubusercontent.com/17011/29821054-81f2136c-8cbe-11e7-8f39-807b71322c63.png)

Here's the code I'm using:

```csharp
using (var stream = File.OpenRead("exampleData.txt"))
{
    client.UploadCsv("demo", "issue1406code", null, File.OpenRead("exampleData.txt"), new UploadCsvOptions { Autodetect = true });
}
```

Could you post the code that you're using to upload the file?

**Comment by juliuscesarnl** [comment]
That is very weird since I'm basically using the same code. I'm on the latest published version (v1.0.0-beta17). Here's my code:

```
var uploadCsvOptions = new UploadCsvOptions
{
    FieldDelimiter = options.FieldDelimiter,
    NullMarker = options.NullMarker,
    WriteDisposition = WriteDisposition.WriteAppend,
    Autodetect = options.AutoDetectSchema,
    SkipLeadingRows = skipHeader ? 1 : 0
};

using (var stream = File.OpenRead(options.FilePath))
{
    LogHandler.LogWriter($"Uploading {options.FileName} to table: {finalTableName}",
        LogHandler.MessageType.INFO);

    // Upload data to table/partition
    var job = options.Dataset.UploadCsv(finalTableName, null, stream, uploadCsvOptions);

    HandleJob(job);

    LogHandler.LogWriter("Upload successful", LogHandler.MessageType.INFO);
}
```

**Comment by jskeet** [comment]
I'm using the same version in my test code. I didn't find that `SkipLeadingRows` made any difference, as presumably Autodetect detects which are the header rows anyway.

I assume this is definitely a new table? What are you setting as NullMarker and FieldDelimiter? Could you try my exact code (with the exact sample file you provided me) to see whether you see the same behaviour? We can then start narrowing down the differences.

**Comment by juliuscesarnl** [comment]
This is a new table indeed. What I use for FieldDelimiter is `","` and for NullMarker `""`.
I did some testing using your code exactly and what I found is that `SkipLeadingRows` is definitely causing this issue. I tried different combinations of properties and as soon as I set the `SkipLeadingRows` property, it had my previous screenshot as a result. In every other case it worked as it should. FYI, I set the property to 0.

**Comment by jskeet** [comment]
Ah, interesting - I'd only ever tried setting it to 1, which appears to be okay.

But when I set it to 0, the upload job fails entirely with an error:

> CSV table encountered too many errors, giving up. Rows: 1; errors: 1.

I'm not sure why you're getting a successful job with inappropriate types/field names...

**Comment by juliuscesarnl** [comment]
I'm also not sure why we're getting different results here. Could the difference be that I'm using .NET Framework 4.6.1? Just for clarity, see the code I used below. When I remove the `SkipLeadingRows` property, it works as expected.

```csharp
var client = BigQueryClient.Create(Settings.Default.ProjectId);

var uploadCsvOptions = new UploadCsvOptions
{
    Autodetect = true,
    FieldDelimiter = ",",
    NullMarker = "",
    WriteDisposition = WriteDisposition.WriteAppend,
    SkipLeadingRows = 0
};

string filePath = Path.Combine(Environment.CurrentDirectory, "reports", "test", "datasource1", "exampleData.csv");

using (var stream = File.OpenRead(filePath))
{
    client.UploadCsv("testDataset", "testTable", null, stream, uploadCsvOptions);
}
```

**Comment by jskeet** [comment]
The version of .NET definitely shouldn't make a difference. If you change the body of your `using` statement to:

```csharp
var job = client.UploadCsv("demo", "testTable1", null, stream, uploadCsvOptions);
job.PollUntilCompleted().ThrowOnAnyError();
```

does that complete successfully? It fails for me, with the exact options you've got. Changing `SkipLeadingRows` to 1, the job completes.

**Comment by juliuscesarnl** [comment]
I tested it with your code and it still doesn't fail. When I change `SkipLeadingRows` to 1, it does work as expected. I guess the workaround for now is either to not set that property or to set it to something > 0.

**Comment by jskeet** [comment]
How very odd. Do you want me to ask internally to try to account for this discrepancy, or shall we just close this issue now we know how to work around it? (I'm sure the client library is sending up the request as expected - the code involved is trivial.)

**Comment by juliuscesarnl** [comment]
If this is an API issue then I think it should be fixed because other devs could encounter this issue as well. For now this workaround is fine by me and therefore the issue can be closed. Thank you for all the help, we really appreciate it!
