### ISSUE TITLE
Upload Object hashing

### ISSUE THREAD

**Issue by EatonZ** [GoogleCloudPlatform/google-cloud-dotnet#1417]
The `UploadObject` and `UploadObjectAsync` methods should include `md5Hash` and `crc32c` properties in `UploadObjectOptions`. According to the [documentation](https://cloud.google.com/storage/docs/hashes-etags#_JSONAPI), supplying these will enforce server-side validation of the uploaded data to ensure it was not tampered with during transit.

After reviewing the source code, it appears there is hash validation for download, but not upload. There should be something in place to verify uploads.

**Comment by EatonZ** [comment]
I am looking at a temporary solution, but your `Crc32c` class is internal.. is that something you'd consider making public so people can use it without having to add another implementation?

**Comment by jskeet** [comment]
I attempted to implement this at the same time as download validation, sending a crc32 with each chunk, but I never managed to provoke the server into rejecting a download. (I deliberately introduced incorrect hashes.) I haven't found any way of specifying an overall object hash at the *end* of a resumable upload.

GCS has multiple protocols for uploading data, not all of them publicly documented, which makes this tricky to find out about.

Rather than making Crc32c public, could you give details about what you were planning on doing? If you've found a way of getting the server to validate the upload, I'd love to just roll it into the library itself.

**Comment by EatonZ** [comment]
I did not check and see if the server would actually reject a tampered upload. I just assumed the documentation was correct, and didn't see the point in trying since the library won't let me specify hashes or anything.

My solution was to reuse the stream provided to `UploadObjectAsync`, MD5 it, and compare it to the MD5 returned from the upload.

You could probably implement this in your library too. However, note that some streams people provide may not be re-readable.

```
var storageClient = StorageClient.CreateAsync().Result;
using (var fileStream = File.OpenRead("file.txt"))
{
    var uploadedObject = storageClient.UploadObjectAsync("sample-bucket", "file.txt", "application/octet-stream", fileStream).Result;
    using (var md5 = MD5.Create())
    {
        fileStream.Position = 0;
        if (!XtraFunctions.CompareByteArray(md5.ComputeHash(fileStream), Convert.FromBase64String(uploadedObject.Md5Hash)))
        {
            //Invalid!
        }
    }
}
```

**Comment by jskeet** [comment]
Ah, so perform the validation on the *client* side. For some reason I hadn't considered that, but that definitely sounds like an option. I'd probably just check the crc32c hash as the one the Storage team prefers over md5, but that sounds feasible.

Of course, it does mean that if there's a problem and we only spot it afterwards, the incorrect object will already have been created, which is far from ideal. Better than nothing though.

I'll mark this as a P1 enhancement request - but we don't have any imminent storage releases (and I've got a lot of work to do on other APIs) so I don't expect to get to this *particularly* soon.

I'll have to check whether the infrastructure I put into ResumableUpload to support the hashing in the first place is still there. It's possible that I dropped that on the grounds of it not being necessary - the corresponding download code is in [this PR](https://github.com/google/google-api-dotnet-client/pull/882).

**Comment by EatonZ** [comment]
I don't really like my workaround because it introduces additional overhead by re-reading the stream, and can be expensive for large files.

Anyway, I took a look at this again this morning.

Using Fiddler to intercept and modify the request payloads generated by the library, I introduced an **invalid** md5Hash value into the first POST request. That request goes through just fine.

With the second request, which uploads the file data (PUT) I see an expected error message. As I expected, providing the MD5 in the first request will enforce a validation at the end of the upload.

Perhaps the storage team finally added/fixed this since the last time you tried. Regardless, I still suggest introducing MD5 and CRC properties in `UploadObjectOptions`. Additionally, making `Crc32c` public so people can use it without adding their own code, which could potentially be incorrect since Google uses a different CRC.

![1](https://user-images.githubusercontent.com/3020941/29934662-fee222ae-8e49-11e7-8e83-062fcde2231b.PNG)

![2](https://user-images.githubusercontent.com/3020941/29934663-fee52ff8-8e49-11e7-9e15-778df838a2c1.PNG)

**Comment by jskeet** [comment]
Firstly, I agree that we shouldn't read the stream twice.

I'm nervous of adding client-specified hashes into the options - it feels like something that *should* be autogenerated by the library, but specified at the end if at all possible. (Or per-chunk otherwise.)

I'll have another look at this when I get time, but at the moment I have a lot of other higher-priority work. Thank you very much for the investigation you've already done - it will certainly be useful.

I'd *prefer* not to make Crc32c public at the moment, to maintain flexibility of implementation. (It's gone through a few different designs already.) Over time, when we're comfortable with the API surface, I'd be happier to do so.

**Comment by jskeet** [comment]
Reducing this to P2 to indicate that I'm not expecting to get to this soon - mostly because I still don't really know what the best option is. I'll talk to the Storage team about options though.

**Comment by jskeet** [comment]
Just to keep everyone in the loop, I'm looking at this again now. The plan will be:

- Modify the REST support library to provide a hook. Importantly, we don't want to see the same data multiple times: the hash should only be updated when a chunk has been accepted
- Modify the Storage library to check the hash in the object that's returned at the end of the upload, and throw an exception if necessary
- Have an *option* to delete the just-uploaded object (with massive caveats) if the hash violation is dtected

The first step is trickier than I'd hoped - that'll probably take me a few days to work out.

**Comment by jskeet** [comment]
@EatonZ If you want to test this, it's now merged. Deleting is the *default* btw, as this fits with what gsutil does - but there are options for just throwing, or not even checking at all.

So glad to finally get this in...

**Comment by EatonZ** [comment]
@jskeet Great work! I'll take a look soon and let you know.

**Comment by jskeet** [comment]
I've just released Google.Cloud.Storage.V1 version 2.1.0-beta02 that contains this, so that should make it easier to try :)

**Comment by EatonZ** [comment]
@jskeet Finally getting around to checking this out.
Is there anything else I need to know besides setting `UploadObjectOptions.UploadValidationMode`?

**Comment by jskeet** [comment]
You shouldn't need to set anything unless you want a different option to `DeleteAndThrow` (the default).

It's now been released as 2.1.0 GA btw. No need for betas :)

**Comment by EatonZ** [comment]
@jskeet I have tested it and it appears to work as expected. Uploads work fine and a tampered hash throws the expected exception.

My only comment is about the `generation` query string you include on the DELETE call. I don't think you need that since the upload should technically be the latest version of the object, but I guess it doesn't hurt to include it to be safe.

**Comment by jskeet** [comment]
While it's unlikely, it's possible that between our code finishing the upload and trying to delete it, another version is uploaded from somewhere else. We wouldn't want to delete that file.
