### ISSUE TITLE
Expose a function to create a logging provider for Google.Cloud.Diagnostics.AspNetCore

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#1425]
ASP.NET Core 2.0 adds logging providers in a slightly different way than 1.0 did.  To allow for supporting the best way to add a logging provider in ASP.NET Core 2.0 we should expose a provider.

cc: @csells

**Comment by csells** [comment]
Also update docs on GH and cloud.google.com/docs as appropriate.

**Comment by iantalarico** [comment]
If you look at the section "[How to add providers](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging?tabs=aspnetcore2x)" You can see the suggested ways of adding providers in 1.0 and 2.0.

Using the 1.0 method works both in 1.0 and 2.0 with the ILoggingFactory.  The ILoggingBuilder is used only in 2.0.

cc: @jskeet

**Comment by iantalarico** [comment]
We can add a expose a function to create a logging provider so a user would call:

` loggingBuilder.AddProvider(GoogleLogger.Provider("[GOOGLE-PROJECT-ID]"))"`
