### ISSUE TITLE
Concern about IExceptionLogger implementation

### ISSUE THREAD

**Issue by cilerler** [GoogleCloudPlatform/google-cloud-dotnet#1426]
I was checking the documentation [here](http://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNetCore/#log-exceptions) and it provides a sample below;

```csharp
/// <summary>
/// The <see cref="IExceptionLogger"/> is populated by dependency injection.
/// </summary>
public void ReadFile(IExceptionLogger exceptionLogger)
{
    try
    {
        string scores = File.ReadAllText(@"C:\Scores.txt");
        Console.WriteLine(scores);
    }
    catch (IOException e)
    {
        exceptionLogger.Log(e);
    }
}
```
this should not be the way of logging an exception.

`Microsoft.Extensions.Logging.ILogger` already accepts `Exception` object and it can be extracted from there.

> _I understand that there are different needs however if this is a  _**DotNet** API_, it should rely on native abstractions_

# reference purpose

```csharp
namespace Google.Cloud.Diagnostics.Common
{
  /// <summary>A generic exception logger.</summary>
  public interface IExceptionLogger
  {
    /// <summary>Logs an exception that occurred.</summary>
    /// <param name="exception">The exception to log. Cannot be null.</param>
    /// <param name="context">Optional, the current HTTP context. If unset the
    /// current context will be retrieved automatically.</param>
    void Log(Exception exception, HttpContext context = null);

    /// <summary>Asynchronously logs an exception that occurred.</summary>
    /// <param name="exception">The exception to log. Cannot be null.</param>
    /// <param name="context">Optional, the current HTTP context. If unset the
    /// current context will be retrieved automatically.</param>
    /// <param name="cancellationToken">Optional, The token to monitor for cancellation requests.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    Task LogAsync(Exception exception, HttpContext context = null, CancellationToken cancellationToken = default (CancellationToken));
  }
}
```

```csharp
namespace Microsoft.Extensions.Logging
{
  /// <summary>Represents a type used to perform logging.</summary>
  /// <remarks>Aggregates most logging patterns to a single method.</remarks>
  public interface ILogger
  {
    /// <summary>Writes a log entry.</summary>
    /// <param name="logLevel">Entry will be written on this level.</param>
    /// <param name="eventId">Id of the event.</param>
    /// <param name="state">The entry to be written. Can be also an object.</param>
    /// <param name="exception">The exception related to this entry.</param>
    /// <param name="formatter">Function to create a <c>string</c> message of the <paramref name="state" /> and <paramref name="exception" />.</param>
    void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);

    /// <summary>
    /// Checks if the given <paramref name="logLevel" /> is enabled.
    /// </summary>
    /// <param name="logLevel">level to be checked.</param>
    /// <returns><c>true</c> if enabled.</returns>
    bool IsEnabled(LogLevel logLevel);

    /// <summary>Begins a logical operation scope.</summary>
    /// <param name="state">The identifier for the scope.</param>
    /// <returns>An IDisposable that ends the logical operation scope on dispose.</returns>
    IDisposable BeginScope<TState>(TState state);
  }
}
```

**Comment by jskeet** [comment]
I've assigned this to @iantalarico as he's our expert on this API, although I believe he's away for most of the next few weeks. I *believe* you can still use the `ILogger` interface, and `IExceptionLogger` is just an optional extra - I'd have to check though.

**Comment by cilerler** [comment]
@jskeet thanks for the quick response.  You are correct it does support it, however alternative methods will be technical debt in your _(and our hand in the future)_  What I'm trying to say here is, there should be only 1 way to log for everyone's sake.

I was playing around and trying to decide if I should implement the library into the projects.  However I realized API is not supporting **Microsoft.Extensions.Logging.2** which has breaking changes from **MEL1**.  API should support .NetStandard2 immediately.

Additionally and the last part is, it only supports retrieving credentials from environment variable which is an issue.  Like the **Google Storage Api** it should be settable by `GoogleCredential.FromJson(...)` 

Thanks again...

**Comment by jskeet** [comment]
> What I'm trying to say here is, there should be only 1 way to log for everyone's sake.

IIRC, the `IExceptionLogger` interface is present precisely to enable code reuse between the ASP.NET and ASP.NET Core implementations - it allows all the nitty-gritty to be implemented in a single place, in Google.Cloud.Diagnostics.Common. I suspect it doesn't make much sense to be used directly by consumers, and (if I'm right about its purpose) we could certainly clarify the documentation.

> API should support .NetStandard2 immediately.

I'm sure we'll be looking at various options, but please be aware that like all other teams, we're resource constrained and have lots of other projects on the go. Note that as we target netstandard1.5, it's netstandard2.0 compatible. Adding support for a specific dependency is not the same as adding support for netstandard2.0 as a target - and is tricky, as we wouldn't want to *require* that dependency. It may need to be a whole separate integration library, which is unfortunate. See #1425 for more thoughts on ASP.NET Core 2.0 though.

> Additionally and the last part is, it only supports retrieving credentials from environment variable which is an issue. 

I *thought* there was a way of specifying a credential, but if there isn't, that would make sense.
(I don't believe it's "only from an environment variable" at the moment - it's "only the default credentials" which tries various options... in particular, from a Google Cloud deployment, I'd expect the ambient credentials to work fine.)

**Comment by cilerler** [comment]
About `IExceptionLogger`; makes sense to support legacy stuff.  So no longer complaining. 😜 

About **.NetStandard2**; I hear you and agree mostly.  However, as one of the technology leader, we need a really quick responses from you when there is a major upgrade on another leader.  I know it is not completely fair but in a sense it is, we really should not wait you guys to upgrade our libraries.

> Note that as we target netstandard1.5, it's netstandard2.0 compatible. Adding support for a specific dependency is not the same as adding support for netstandard2.0 as a target - and is trick

Code wise you are right, however change is at behaviour side.  It means Google's library needs to read the settings different way or allow us the push those manually etc.  _(well it may already support it, didn't check that yet)_  Bottom line is you should be able to release latest compatible libraries _(at least fixes for the breaking changes)_ in a very short time frame. 👮 

_since it is covered by 1425 no further complaining here_ 😜

About **Credentials**; glad to be on same page... 👍 

Thank you for your time and attention 🤗
