### ISSUE TITLE
Can't access the table resource

### ISSUE THREAD

**Issue by mastoj** [GoogleCloudPlatform/google-cloud-dotnet#1428]
I need to update the metadata on a lot of tables, so I thought I would write a small F# script to do it. To figure out if a table need to be updated I need to look at the table resource data, but it seems like the resource is not properly popluated. Short example of what I'm doing:

```
#load ".paket/load/net45/Google.Cloud.BigQuery.V2.fsx"

open Google.Cloud.BigQuery.V2

let client = BigQueryClient.Create("projectId")

let datasetsList = ["datasets"; "that"; "contains"; "tables"]

let datasets = 
    datasetsList 
    |> List.map (fun datasetName -> client.GetDataset(datasetName))

datasets 
|> List.map (fun (ds:BigQueryDataset) -> ds.ListTables() |> Seq.toList)
|> List.concat
|> List.map (fun table -> table.FullyQualifiedId, table.Resource.CreationTime, table.Resource.FriendlyName, table.Resource.CreationTime, table.Resource.Description, table.Resource.ETag, table.Resource.Id, table.Resource.Kind)
|> List.iter (printfn "%A")
```
I would expect this to print the all the data specified in the last `map`, but instead only the `FullyQualifiedId` is printed, all the fields on the `Resource` property is printed as `null`.

To run the code above do the following:

* Follow instructions here: https://fsprojects.github.io/Paket/getting-started.html
* Add nuget: `mono .paket/paket.exe add Google.Cloud.BigQuery.V2 -V 1.0.0-beta17`
* Generate load script: `mono .paket/paket.exe generate-load-scripts --framework net45`
* Make sure the code above is in a file in the same folder as the `.paket` folder, so the `#load` directive can find the generated load script.

### Workaround

To get the actual resource data you need to use `dataset.GetTable`. I think this is a design that most likely will result in some issues in the long run.

**Comment by jskeet** [comment]
This is inherent in the [list tables API](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/list) I'm afraid - it simply doesn't return all the data within a table.

That said, it looks like there *is* more information that we could populate [here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryTable.cs#L66) - in particular, any time partitioning and the creation time. The description and etag simply aren't present in the data.

The Id, Kind, FriendlyName and TableReference should be populated though - are you saying that's not the case?

**Comment by jskeet** [comment]
(Assigned both "bug" and "enhancement request" here - if the properties we *expect* to populate aren't being populated, that's a bug I can fix. I can also populate more properties based on the response. The properties that aren't in the list tables result would be an API feature request, which I could potentially log with the API team if you want.)

**Comment by mastoj** [comment]
No need to file this to the API team, since I think they are doing the right thing. For me it is the .NET API that is a little bit awkward as I see it (might be a personal opinion). The `Table` data that is returned from `list` and `get` or two different types of resources as I see it, yes they rely on the same underlying data but they aren't the same since they differ in data. I would rather have another "smaller" type in the .NET API that was returned by the .NET API for `list`, and maybe that type might be used in the result of `get` as well. Mainly to avoid having objects with all null.

You're right regarding the fields that should have value, they does. It was some line breaks that made it hard to read. 

This is in no way a huge problem for me, I discovered it now when I was doing a one time job, but I found the API strange so I filed the issue.

**Comment by jskeet** [comment]
In your case it makes it more awkward - in other cases it makes it simpler. While we *could* introduce inheritance into the mix (a sort of `BigQueryBaseTable` followed by `BigQueryFullTable` and `BigQueryListTable` or similar), I think it would make the whole API more complicated. (Additionally, while at the moment we don't have any way of saying "fetch me a table only populating a certain set of fields" it's entirely possible we might in the future. The API already supports that with the `fields` query parameter.)

Once you're aware of the difference, it's very easy to work with it, fetching the table if you need the full details. (You can easily check if you've got the details you want.)

I've currently got the `Resource` property documented as:

> The data within the resource may be incomplete, depending on how it was obtained.

Would it have been helpful to you if that comment had been more specific? Perhaps if the `ListTables` methods indicated that the resources were incomplete in some cases?

**Comment by mastoj** [comment]
Didn't actually read the comment, I almost always browse the properties and expect them to be there. It can have something with me using F# to do, since I don't expect null.

I definitely see that it is simpler in some situation, both in implementation and to some extent consuming the API. But simpler might result in unexpected bugs as I see it. 

I totally agree that inheritance will make things more complicated. Also, if you want to support the feature where you specify fields, as you mention, then this is probably the best route to take.

This is no biggie for me, I just raised it because I thought it was a bug with all those, for me, unexpected null values. Since it seems to be by design I think you can close it.

**Comment by jskeet** [comment]
Will leave this open for now to remind me to add the extra properties that we *can* copy, but will then close - thanks for the confirmation.
