### ISSUE TITLE
Can't load gRPC native library in ASP.NET web site

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1429]
(Creating issue as a way of keeping track of repro and progress.)

**Comment by jskeet** [comment]
Diagnostics log:

- Start VS2017
- Create new ASP.NET Framework project, selecting the WebForms template, targeting .NET 4.6.1
- Start the project just to show everything working
- In "Manage NuGet dependnecies" add Google.Cloud.Datastore.V1, version 2.0.0 as a dependency
- In Contact.aspx.cs, add a `public string Message { get; set; }` property and set it to a dummy value in Page_Load
- In Contact.aspx, replace the address part with `<p><%: Message %></p>`
- Rerun to see the message in the contact page

(At this point, we have the dependencies we want, and a simple way of diagnosing issues.)

- Change the code in `Page_Load` to:

```csharp
try
{
    var channel = new Channel("127.0.0.1:8080", ChannelCredentials.Insecure);
    Message = $"Created channel: {channel.Target}";
}
catch (Exception ex)
{
    Message = ex.ToString();
}
```

Just creating a channel (without connecting it) loads the native extension.

Run (with F5) - seems fine.

- Try using Datastore itself:

```csharp
try
{
    var datastore = DatastoreDb.Create("(my project ID)");
    var keyFactory = datastore.CreateKeyFactory("book");
    var key = datastore.AllocateId(keyFactory.CreateIncompleteKey());
    Message = $"Created key: {key}";
}
catch (Exception ex)
{
    Message = ex.ToString();
}
```

Again, it looks fine.

**Comment by jskeet** [comment]
Now reproduced:

- Create new empty web *site* in VS (not a regular ASP.NET project) targeting .NET 4.5.2
- Add the Grpc.Core 1.4.1 nuget package
- Add a new web form
- In the code behind, add this single line of code:

        var channel = new Channel("localhost:8001", ChannelCredentials.Insecure);

- Add a using directive for Grpc.Core
- Debug: bang

I'm updating the title of this bug to indicate the new information, and will then look at the project differences.

**Comment by jtattermusch** [comment]
Yes, thanks!

**Comment by jskeet** [comment]
Closing this in favour of https://github.com/grpc/grpc/issues/12570
