### ISSUE TITLE
uploading a file to a non-existing bucket yields an unhelpful error message

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-dotnet#143]
If I try to upload a file to a non-existent bucket, e.g.

var bucketName = Guid.NewGuid().ToString();
StorageClient.Create().UploadObject(bucketName, "foo.txt", "", Stream.Null);

I get an ArgumentNullException instead of a NoSuchBucketException, which makes it extremely difficult to track down (about 10 minutes in my case).

**Comment by jskeet** [comment]
Is this `ArgumentNullException` saying that `baseUri` is null? If so, that's a known bug which I've fixed but we haven't built a new version of the support library yet. (It's planned for this coming week.) And yes, if it's that bug, it's *supremely* annoying, and you did well to "only" waste 10 minutes on it. Apologies for it still being a problem right now - hopefully not for much longer.

If it was something else, I'll look into it.

**Comment by csells** [comment]
Nope. That’s it.

On May 7, 2016, at 9:01 AM, Jon Skeet <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this ArgumentNullException saying that baseUri is null? If so, that's a known bug which I've fixed but we haven't built a new version of the support library yet. (It's planned for this coming week.) And yes, if it's that bug, it's supremely annoying, and you did well to "only" waste 10 minutes on it. Apologies for it still being a problem right now - hopefully not for much longer.

If it was something else, I'll look into it.

**Comment by jskeet** [comment]
Cool. Will leave this open for the moment, so I can see what error message we get when it *is* fixed - it may still be a bit obscure.

**Comment by jskeet** [comment]
(Should now be able to test this easily. Will do so...)

**Comment by jskeet** [comment]
New exception:

```text
Unhandled Exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Not Found [404]
Errors [
        Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]
```

So it's now obvious that *something's* not found. Is that good enough? I suspect that going any further may involve guessing, which risks getting it wrong.

Assigning to Chris to comment or close.

**Comment by jskeet** [comment]
Ping? (Trying to reduce the number of open issues at the moment...)

**Comment by jskeet** [comment]
Ping for @csells to confirm he's happy enough with this.

**Comment by csells** [comment]
Would it be possible to have the name and type of the thing not found in the error message, i.e. "bucket foo not found"?

**Comment by jskeet** [comment]
Well, it would be a matter of catching each exception, trying to detect exactly what's meant, adding information (somewhere) and rethrowing. Then do that for every condition we're interested in, for every exception. We might find it would be better to ask the API team to put more information in the message... that way everyone would benefit, with no per-language work. (There may be a reason it's impossible, of course.)

**Comment by Capstan** [comment]
@jskeet That's the right answer. It's an extremely common request that just hasn't gotten traction.

**Comment by jskeet** [comment]
Closing within this repo as it shouldn't be fixed by code here, and it sounds like the Storage team is already tracking the request separately.

**Comment by marioeu** [comment]
Hi jskeet, I believe that would be great if you could reopen this ticket as we still experience this behavior. Lost few hours trying to understand the issue... till hit this ticket...
Anyway, thanks guys for the light...!

**Comment by jskeet** [comment]
@marioeu: I'd rather only have open issues within this repository for things that can be fixed in this repository. The change we're hoping for is server-side, which wouldn't be a change in this repository.
