### ISSUE TITLE
Avoid exposing Google.Apis.* in public APIs for gRPC projects

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1446]
As per https://googlecloudplatform.github.io/google-cloud-dotnet/docs/guides/gax-dependencies.html we'd like to remove our dependencies on `Google.Apis.*` in gRPC-based projects. (REST-based projects already have an indirect dependency which won't go away.)

As such, gRPC projects should not have any members that:

- Derive from Google.Apis.* types
- Use them as return types
- Use them as parameter types

Currently `SpannerConnectionString.Credential` is an `Google.​Apis.​Auth.​OAuth2.​IToken​Access`, which we'll need to work around somehow. (That's annoying, as it would otherwise be a perfectly fine type to put there.) There may be other places where we've got the same issue.

We should have a Roslyn analyzer to check this as well.

cc @benwulfe @evildour

**Comment by evildour** [comment]
I can look into making an analyzer for this. I don't think it should be too difficult.

**Comment by jskeet** [comment]
@evildour: Yes please! I think for the first pass, just "anything with a namespace starting with Google.Apis" would be good to ban.

**Comment by benwulfe** [comment]
Confused -- whats the replacement?  BigQuery uses GoogleCredential which is from the same namespace and implements ITokenAccess.  I suppose we can remove credential altogether and just have setters to pass in files or streams of the json file?

**Comment by jskeet** [comment]
BigQuery is a REST-based API, which means it already implicitly depends on all of this. We don't have anything as a replacement at the moment, unfortunately. (Basically we have a plan in place to remove our current dependency, but it *is* a current dependency.)

We *could* expose a `ChannelCredentials` or `CallCredentials`, but I'd probably just remove the properties for the moment and have the methods to load credentials from a file. I know it's ugly, but it's the best we've got for now :(

**Comment by jskeet** [comment]
@evildour: Just checking the status of this - the analyzer is in, but the Spanner code still has this issue. I'm surprised it's all building. Is there an explicit opt-out for Spanner at the moment somewhere, or are our analyzers not being picked up properly in CI? If you don't know offhand, I'll look into it.

@benwulfe: Do you have a timeline for addressing this in Spanner?

**Comment by jskeet** [comment]
Got it - Google.Cloud.Spanner.Data uses gRPC, but doesn't have a "type" of gRPC, so we don't have the CodeAnalysisRuleSet element. Will create a PR to fix that, but we won't be able to merge it until Spanner.Data is fixed.

**Comment by jskeet** [comment]
This is now enforced by #1496.
