### ISSUE TITLE
Can't add reference to Google.Cloud.Diagnostics.AspNetCore in VS2017

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1449]
- Create an ASP.NET Core **1.0** application
- In "Manage NuGet packages" try to install Google.Cloud.Diagnostics.AspNetCore

Error:

```text
Restoring packages for C:\Users\skeet\Test\Projects\Issues\Issue1448\Issue1448\Issue1448.csproj...
Detected package downgrade: Microsoft.Extensions.Logging.Debug from 1.1.2 to 1.0.2. Reference the package directly from the project to select a different version. 
 Issue1448 (>= 1.0.0) -> Google.Cloud.Diagnostics.AspNetCore (>= 1.0.0) -> Microsoft.Extensions.Logging.Debug (>= 1.1.2) 
 Issue1448 (>= 1.0.0) -> Microsoft.Extensions.Logging.Debug (>= 1.0.2)
Package restore failed. Rolling back package changes for 'Issue1448'.
Time Elapsed: 00:00:01.9913824
```

VS2017 version 15.3.4

The problem is that the default csproj file contains:

```
<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.2" />
```

... whereas we depend on 1.1.2.

Options for user:

- Update the dependency to 1.1.2 or higher
- Remove the explicit dependency
- Use ASP.NET Core 1.1 from the start

Given that ASP.NET Core 2.0 is now the default, maybe this isn't an issue... but I thought it worth recording, as we may want to document it.

**Comment by iantalarico** [comment]
@jskeet  Would it be worth downgrading this to 1.0.*? We don't need anything in 1.1.* that's not in 1.0.*

**Comment by jskeet** [comment]
Not sure which "this" you mean in terms of downgrading. The reference in our library? Not sure.
(Given #1448, we'll be creating a new major release anyway, so I guess it's okay to do that.)

**Comment by iantalarico** [comment]
Sorry I should have been more explicit.  Downgrade all of the Microsoft references to point to 1.0

**Comment by jskeet** [comment]
Right. I think that would probably make sense, yes.
