### ISSUE TITLE
Users want client-side encryption for Google Cloud Storage.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1451]

**Comment by jskeet** [comment]
Do we have more information about this - a precise set of requirements? It'll be hard to do any work on it otherwise.

**Comment by jskeet** [comment]
Closing for now having added this to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/BACKLOG.md)

**Comment by SurferJeffAtGoogle** [comment]
The client needs to do envelope encryption and store the KEK, IV, and KML key url in the file metadata.  The backlog seems like a good home for this feature request.

**Comment by amanda-tarafa** [comment]
This is being evaluated across client libraries.
Removing from backlog.
