### ISSUE TITLE
Add search functionality to the client library documentation

### ISSUE THREAD

**Issue by jsimonweb** [GoogleCloudPlatform/google-cloud-dotnet#1479]
As the documentation website for this client library continues to grow, adding a within-site search functionality would be helpful:
https://googlecloudplatform.github.io/google-cloud-dotnet/docs/index.html

**Comment by jskeet** [comment]
I can see how it would be helpful - I'm not sure how feasible it is while hosted on GitHub pages. (Ideally this would be part of a cross-language docs effort, I suspect.) Worth keeping track of though...

**Comment by jskeet** [comment]
Closing for now as I suspect this won't happen until/unless there's a complete overhaul in terms of how we host documentation :( (At that point, we can look for all the closed issues labelled "documentation"...)
