### ISSUE TITLE
Spanner client should allow multiple DDL statements to be specified while creating a database

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-dotnet#1487]
Cloud Spanner API allows one to also specify ddl statements while creating a database. But in the client code currently each ddl statement has to be executed individually after the database has been created. We should change the client code to allow users to specify DDL statements while creating a database and all of them should be sent to cloud spanner in a single rpc. That would be much more efficient and less error prone since if there is a problem with any DDL statement, the whole operation would fail and the database would not be created.

Similarly while updating DDL, one can specify multiple DDL statements. But the API does not guarantee that all of them will be applied atomically. Cloud Spanner applies them individually one by one and as soon as one fails it would cancel the subsequent statements. So essentially, a prefix list of that would succeed.

**Comment by vkedia** [comment]
https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.admin.database.v1#google.spanner.admin.database.v1.CreateDatabaseRequest

**Comment by benwulfe** [comment]
This can be addressed by allowing a params arg of additional ddl statements
to send along with the command.
Would only work with create and update.

**Comment by jskeet** [comment]
Ben, could you give a priority to this? (P1 if you think it's important enough that it needs to be in the next release; P2 if it can wait longer.)

**Comment by benwulfe** [comment]
this is fixed in master and will be deployed in our next release.

**Comment by benwulfe** [comment]
fixed in beta08
