### ISSUE TITLE
Add netcoreapp2.0 testing to Google.Cloud.Diagnostics.AspNetCore

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#1499]
Currently testing against netcoreapp2.0 causes a failure.

We need to wait for xunit 2.3.0-rc1-build3780 to be released.

See https://github.com/xunit/xunit/issues/1363

**Comment by jskeet** [comment]
We now use xUnit 2.3.0 (GA) by default, so it's worth trying this again now...
