### ISSUE TITLE
"dailyLimitExceeded" when using Translate API, even with no usage

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-dotnet#1503]
When using the Google Translate API, the client library throws with a quota error:

```
Daily Limit Exceeded [403]
Errors [
	Message[Daily Limit Exceeded] Location[ - ] Reason[dailyLimitExceeded] Domain[usageLimits]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at Google.Cloud.Translation.V2.TranslationClientImpl.TranslateText(IEnumerable`1 textItems, String targetLanguage, String sourceLanguage, Nullable`1 model) in C:\Users\jon\Test\Projects\google-cloud-dotnet\...
```

The error message seems reasonable, but I believe I am getting it in error.

The quotas page for the Translate API show I haven't made _any_ calls to the API, let alone more than I have allotted. (Requests per 100 minutes or characters per day.)

** Credentials? **
I'm not specifying any credentials, so I assume it is defaulting to the "application default credentials". However, even if I pass in `Google.Apis.Auth.OAuth2.GoogleCredential.GetApplicationDefault()` I get the same value.

```
    let client = TranslationClient.Create()
    let translation = client.TranslateText(text, targetCode, sourceCode)
```

** Billing? **

My project (ID 257650435437) has billing enabled.

*** API Enabled? **

Visiting https://console.cloud.google.com/apis/api/translate.googleapis.com/overview?project=XXX&organizationId=YYY&duration=PT1H I can confirm that the API is enabled. But (expectedly?) I don't see any requests against the API. Just "There is no data for this API in this time span".

Perhaps I'll try again tomorrow when this mysterious quota gets reset... though obviously this isn't an ideal solution if I were to, say, use this API for a production application.

**Comment by chrsmith** [comment]
To be clear, I doubt this is a problem with the client library so much as it is with my project/account. But it seems strange that I can issue requests with the client library and not see any mention of it on the API's quota page. So I wonder if it might be some disconnect between how we are reading the application default credentials and what my gcloud configuration is?

i.e. `gcloud auth application-default print-access-token` will get me an access token to act as _Google account_ X, but how does that get associated with a GCP _project + billing account_ Y?

**Comment by jskeet** [comment]
Thanks Chris - I'll ask someone from the Translate team to have a look.

**Comment by chrsmith** [comment]
I tried again this morning after switching from using an application default credential to a [service account](https://cloud.google.com/docs/authentication/getting-started) things started working again.

The more I think about it, I suspect the issue is in using application default credentials. (However, if that is right, then how come my app ever worked in the first place.) When you login to provide [application default credentials](https://developers.google.com/identity/protocols/application-default-credentials) you never specify a GCP project. So how does an API know where to charge the resources to?

**Comment by jskeet** [comment]
Yes - I think you're right about it being due to ADCs. Certainly for the other ML APIs we've recommended for a while that you use a service account. I don't want to go into too many details here, but I believe using a service account is the way forward.

**Comment by jskeet** [comment]
Closing as not an issue for the client libraries specifically. Hopefully the generic auth documentation will constantly improve...
