### ISSUE TITLE
Google.Cloud.Speech communication over grpc fails when using proxy server

### ISSUE THREAD

**Issue by InnovistaLucia** [GoogleCloudPlatform/google-cloud-dotnet#1504]
When using the google api for speech recognition in an intranet that forces communication through a proxy server, the requests of the SpeechClient (Google.Cloud.Speech.V1) fail. The reason seems to occur in the grpc framework wich is responsible for the communication.
Interestingly, using the speech recognition in combination with an prior upload of the audio file to the google storage shows that the StorageClient (Google.Cloud.Storage.V1) takes care of the proxy setting.
If you define the proxy for this process via the "System.Net.WebRequest.DefaultWebProxy" Property, the Rest Api used by the StorageClient will respect this setting for the storage requests.
The SpeechClient (and maybe all APIs relying on grpc) are currently ignoring this setting. Is there a workaround? Tried to use some grpc known environment-variables but without success.

**Comment by jskeet** [comment]
I wouldn't expect this to be anything that the client library has to do - I'd expect Grpc.Core to take care of this appropriately. I don't even know where I'd set a proxy in gRPC. Could I suggest you file an issue on https://github.com/grpc/grpc?

**Comment by InnovistaLucia** [comment]
Ok, thank you - i will do that and keep this post updated for other people researching this problem.

**Comment by jskeet** [comment]
If you could just link to the new gRPC issue from here, I think that'll be fine - folks can subscribe to that one easily enough. I'll close this issue here now.

**Comment by MachauGames** [comment]
> I wouldn't expect this to be anything that the client library has to do - I'd expect Grpc.Core to take care of this appropriately. I don't even know where I'd set a proxy in gRPC. Could I suggest you file an issue on https://github.com/grpc/grpc?

have you got the solution for how to setup gRPC proxy? we are also trying to set up the same but couldn't find how to establish it. we have a simple server client connection with gRPC and need to establish the gRPC proxy server.

**Comment by jskeet** [comment]
@MachauGames: It sounds like you're not actually using the Google Cloud .NET libraries - in which case this isn't really a suitable repo in which to ask for advice. You might want to create a new issue in https://github.com/grpc/grpc-dotnet, with a lot more details than you provided here.

**Comment by amanda-tarafa** [comment]
@MachauGames This repo is for Google Cloud .NET Client Libraries.

If you are using gRPC directly, possibly Grpc.Core (https://github.com/grpc/grpc) or Grpc.Net.Client (https://github.com/grpc/grpc-dotnet), it's best if you file an issue directly with them.
Note there's a known issue for Grpc.Net.Client (https://github.com/grpc/grpc-dotnet/issues/1832) that although fixed, is yet to be released.

If you are using Google Cloud .NET Client Libraries, pleaese create a new issue, specifying which library and which version of the library you are using, which .NET version you are targetting, etc. But possibly, first go through #8834 which contains most of the relevant information.
