### ISSUE TITLE
pubsub: streaming pull needs keepalive

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-dotnet#1505]
With default configuration, streaming pull will hang if the stream is idle for a few minutes. This usually happens when the subscription has no more messages. In Go, we set gRPC keepalive to 5 minutes [(CL)](https://code-review.googlesource.com/#/c/gocloud/+/17070/). A similar option should be available in C#, though I'm not sure what the code to pass in the option looks like.

**Comment by chrisdunelm** [comment]
OK, thanks, I'll take a look.

**Comment by chrisdunelm** [comment]
I'm currently unable to test this, as in tests pubsub server terminates idle streamingPull RPCs every ~2 minutes with error UNAVAILABLE, with the message "The service was unable to fulfill your request. Please try again. [code=8a75]".
UNAVAILABLE is a recoverable error, so the the streamingPull RPC is restarted, to be terminated again in ~2 minutes.
This is being followed up offline.

**Comment by chrisdunelm** [comment]
The two-minute StreamingPull termination is a work-around until clients implement keep-alive.

Fixed in https://github.com/googleapis/gax-dotnet/pull/226
