### ISSUE TITLE
Deploy Google.Cloud.Language.V1  as an Azure Function in a C# project

### ISSUE THREAD

**Issue by JonKragh** [GoogleCloudPlatform/google-cloud-dotnet#1512]
Hi!

Perhaps this is an Azure issue. When I attempt to deploy the use of Google.Cloud.Language.V1 in an Azure function, I get the following error.

Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: ParseGrammar2 ---> System.IO.FileNotFoundException : Could not load file or assembly 'Google.Apis.Auth, Version=1.21.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The system cannot find the file specified.

NuGet is only allowing me to add Google.Apis.Auth, Version=1.29.1.0 

Detected package downgrade: Google.Apis.Auth from 1.29.1 to 1.21.0. Reference the package directly from the project to select a different version. 
 myfunctions (>= 1.0.0) -> Google.Api.Gax.Grpc (>= 2.1.0) -> Google.Apis.Auth (>= 1.29.1) 
 myfunctions (>= 1.0.0) -> Google.Apis.Auth (>= 1.21.0)

Is there a hard reference to  Google.Apis.Auth 1.21.0.0 someplace?

Thanks!
Jon

**Comment by JonKragh** [comment]
This seems like an Azure Functions issue and not allowing assembly redirect.

https://github.com/Azure/azure-webjobs-sdk-script/issues/992

**Comment by jskeet** [comment]
It's still unclear to me what's trying to use 1.21.0 at all... what dependencies do you have?

(The lack of assembly binding redirects does sound like a pretty worrying problem. These days there are so many versions of so many assemblies, all claiming to follow SemVer, that I take it for granted that this kind of thing will be okay.)

I'm happy to try to help diagnose this a bit further if you'd like, but I don't think we're going to be able to do anything from our side about the redirect - the best we can do is try to figure out what's trying to use 1.21.0 to start with, and see if that can be upgraded to 1.29.1...

**Comment by JonKragh** [comment]
Hi John-

Thank you for the reply. I moved to a standard API but it would be cool to get this going as a function.

I tried multiple versions of Google.Cloud.Language.V1 (including 1.0.0), something kept trying to load 1.21.0

Here are the references in my function project:

   <PackageReference Include="Google.Api.Gax.Grpc" Version="2.1.0" />    
    <PackageReference Include="Google.Apis.Auth" Version="1.29.1" />    
    <PackageReference Include="Google.Cloud.Language.V1" Version="1.0.0-beta10" />    
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.2" />    
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />

I'd chalk this up to Azure right now, but if you're interested in diving deeper together to get the Natural Language API to work as an Azure function, I'm here to work with you!

Jon

**Comment by jskeet** [comment]
Hmm. That is very odd indeed.

@chrisdunelm can you think of anything that would cause this? Can you remember anything special about 1.21.0?

**Comment by chrisdunelm** [comment]
I'm fairly sure there's nothing special about v1.21; v1.10 and v1.25 are special for legacy platforms, but not v1.21
I'm also fairly sure there's no hardcoded references in any of our code to v1.21.0; a quick github search appears to confirm this.

Could "myfunctions (>= 1.0.0) -> Google.Apis.Auth (>= 1.21.0)" in the original error imply that something in Azure functions is adding the direct reference to v1.21.0?

Definitely a bit mysterious.

**Comment by jskeet** [comment]
Well, I've managed to reproduce it locally, which is a start - it's nice not to have to deploy anything. I'll dig into where the dependency is coming from.

**Comment by jskeet** [comment]
Okay, I've got it. `Grpc.Auth.dll` depends on `Google.Apis.Auth` version 1.21.0.

Without assembly binding redirects, there's not a lot we can do to make this work, as far as I can think.

**Comment by JonKragh** [comment]
@jskeet good stuff! I guess this can be closed. Hopefully, Azure Functions will support assembly redirects soon. Until that time, I moved my implementation to a standard REST API.

On another topic, do you know if there are plans for a streaming type of API? I'd love to have a more real-time kind of interactive typing experience where I can analyze text on the fly.

The current usage pricing would make this very costly to do.

Thanks much!

**Comment by jskeet** [comment]
I'm afraid I don't know of the plans for future features of the API, but I'll pass your comments onto the API team. I'll close this issue for now.

**Comment by jboarman** [comment]
@jskeet 

I'm trying to access Google Datastore from Azure Functions, and I'm getting a very similar error, but for a different dependency:

````
Could not load file or assembly 'Google.Api.Gax.Grpc, Version=2.2.1.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47' or one of its dependencies.
The system cannot find the file specified.
````

Here are my assembly references:

```
<PackageReference Include="Google.Api.Gax" Version="2.3.0" />
<PackageReference Include="Google.Api.Gax.Grpc" Version="2.3.0" />
<PackageReference Include="Google.Apis" Version="1.32.2" />
<PackageReference Include="Google.Apis.Auth" Version="1.32.2" />
<PackageReference Include="Google.Apis.Core" Version="1.32.2" />
<PackageReference Include="Google.Cloud.Datastore.V1" Version="2.1.0" />
<PackageReference Include="Google.Cloud.Storage.V1" Version="2.1.0" />
```

It sounds like we're still quite a bit away from a resolution on the binding redirect problem with AZ functions.  Pretty sad on that front.  However, I would think that I should be able to manipulate the dependencies to fix them so that they all line up.

Changing the Grpc dependency version to `2.2.1` seems to trigger yet other conflicts as I really have to go back in time to some point when everything is aligned to share common dependencies.

Any suggestions for making this Rubik's Cube fit together?

**Comment by jskeet** [comment]
> However, I would think that I should be able to manipulate the dependencies to fix them so that they all line up.

Not really - if the DLL in (say) Google.Cloud.Storage.V1 depends on a different version of Google.Api.Gax (via Google.Api.Gax.Rest in this case) to Google.Cloud.Datastore.V1, you *need* assembly binding redirects to handle that.

One thing you *could* do is clone the code and build your own release, making sure everything targets the same versions. You'd probably target Google.Api.Gax.* version 2.3.0, which means hopefully you only need to build the Datastore and Storage DLLs.

Sorry not to have a better solution for this, but assembly binding redirects really are pretty crucial these days.
