### ISSUE TITLE
Spanner: ExecuteReader (sync) fails due to passing CancellationToken to grpc

### ISSUE THREAD

**Issue by benwulfe** [GoogleCloudPlatform/google-cloud-dotnet#1541]
related to: https://github.com/grpc/grpc/issues/12355

Where grpc does not accept the cancellation token.
We need more sync test cases as well as the tactical workaround of not sending the token to grpc.

**Comment by benwulfe** [comment]
This no longer fails but will not cancel. Leaving this open for now until we get a better solution in place.

**Comment by jskeet** [comment]
This was fixed in Grpc.Core 1.7.0, so we should be able to just pass the cancellation token into Read now.

**Comment by jskeet** [comment]
Still needs doing:
https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/ReliableStreamReader.cs#L129
