### ISSUE TITLE
Google.Cloud.Diagnostics.* Tests are failing with the upgrade to xUnit 2.3.0

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#1569]
apis\Google.Cloud.Diagnostics.Common\Google.Cloud.Diagnostics.Common.Tests> dotnet test

These tests will fail for netcoreapp 1.0.  netcoreapp 2.0 and netdesktop 4.6 pass.
Google.Cloud.Diagnostics.Common.Tests.ErrorReportingContextExceptionLoggerTest.Log*

Downgrade xUnit to "2.3.0-beta5-build3769" the above tests will all pass

**Comment by benwulfe** [comment]
I had to upgrade to the full 2.3 release to get .net core 2.0 tests working.  Can we do something other than downgrade back to a beta?

**Comment by iantalarico** [comment]
We need the 2.3.0 for 2.0.  I don't want to downgrade that.

It's failing on jenkins for the some of the diagnostics tests.  

I need to dig into this more.  It seems like an odd failure

**Comment by benwulfe** [comment]
FWIW, I can still run .netcore 1.0 tests on my box.  Maybe its as simple as updating the Jenkins machines?

**Comment by iantalarico** [comment]
@benwulfe I just emailed you the failure.  The Jenkins machines are able to run .netcore 1.0 and 2.0.

**Comment by iantalarico** [comment]
Test run for <Google.Cloud.Diagnostics.AspNetCore.IntegrationTests.dll**(.NETCoreApp,Version=v1.0)**>
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.1054007]   Discovering: Google.Cloud.Diagnostics.AspNetCore.IntegrationTests
[xUnit.net 00:00:01.2939945]   Discovered:  Google.Cloud.Diagnostics.AspNetCore.IntegrationTests
[xUnit.net 00:00:01.3010773]   Starting:    Google.Cloud.Diagnostics.AspNetCore.IntegrationTests
...
Failed   Google.Cloud.Diagnostics.AspNetCore.IntegrationTests.ErrorReportingTest.LogsException
...
Failed   Google.Cloud.Diagnostics.AspNetCore.IntegrationTests.ErrorReportingTest.LogsMultipleExceptions
...
Failed   Google.Cloud.Diagnostics.AspNetCore.IntegrationTests.ErrorReportingTest.ManualLog
...

**Total tests: 19. Passed: 16. Failed: 3. Skipped: 0.**
Test Run Failed.
Test execution time: 2.1501 Minutes
Test run for <Google.Cloud.Diagnostics.AspNetCore.IntegrationTests.dll**(.NETCoreApp,Version=v2.0)**>
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.8947035]   Discovering: Google.Cloud.Diagnostics.AspNetCore.IntegrationTests
[xUnit.net 00:00:00.9857636]   Discovered:  Google.Cloud.Diagnostics.AspNetCore.IntegrationTests
[xUnit.net 00:00:00.9916888]   Starting:    Google.Cloud.Diagnostics.AspNetCore.IntegrationTests
[xUnit.net 00:02:07.4974060]   Finished:    Google.Cloud.Diagnostics.AspNetCore.IntegrationTests

**Total tests: 19. Passed: 19. Failed: 0. Skipped: 0.**
Test Run Successful.
Test execution time: 2.1454 Minutes
Test run for <Google.Cloud.Diagnostics.AspNetCore.IntegrationTests.dll**(.NETFramework,Version=v4.6)**>
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.2586977]   Discovering: Google.Cloud.Diagnostics.AspNetCore.IntegrationTests
[xUnit.net 00:00:01.7511778]   Discovered:  Google.Cloud.Diagnostics.AspNetCore.IntegrationTests
[xUnit.net 00:00:01.7555060]   Starting:    Google.Cloud.Diagnostics.AspNetCore.IntegrationTests
[xUnit.net 00:02:12.5122279]   Finished:    Google.Cloud.Diagnostics.AspNetCore.IntegrationTests

**Total tests: 19. Passed: 19. Failed: 0. Skipped: 0.**
Test Run Successful.
Test execution time: 2.2156 Minutes

**Comment by benwulfe** [comment]
That's odd that it only affected 3 tests.
Given that it was a failed "Assert.False", it can only be one of these two lines:
        private void VerifyErrorEvent(ErrorEvent errorEvent, string testId, string functionName) {
. . . 
            Assert.False(string.IsNullOrWhiteSpace(errorEvent.Context.HttpRequest.Url));
                Assert.False(string.IsNullOrWhiteSpace(errorEvent.Context.ReportLocation.FilePath));

maybe something is now being included in the context that wasn't before?  maybe we should print these values?

**Comment by iantalarico** [comment]
I know the tests are failing on ReportLocation's FilePath and line number.  So for .netcoreapp 1.0 with that version of xUnit the filepath and line number of exceptions are not getting populated.

**Comment by benwulfe** [comment]
possibly the test runner isn't pulling in the correct pdbs -- either the path is wrong its loading the wrong ones?  maybe there is a switch to give dotnet an extra searchpath for pdbs.

**Comment by iantalarico** [comment]
Possibly related:
https://github.com/xunit/xunit/issues/1501

**Comment by benwulfe** [comment]
+1 seems like its it. maybe we can disable that part of the test until xunit fixes itself?

**Comment by iantalarico** [comment]
@benwulfe Are we okay with going back to a prerelease?  Switching to "2.3.1-rc2-build3844" fixes the issues.  If not I can disable the tests.

cc: @jskeet

**Comment by jskeet** [comment]
I'm okay with going forward, but to another pre-release. While being off pre-release bits was nice, the main benefit of 2.3.0 was fixing the gRPC issue.

**Comment by benwulfe** [comment]
I'm good with moving forward to pre-releases.  I just would prefer not to go back.
If there are issues with the pre-release, at least they should be new issues :)

**Comment by iantalarico** [comment]
So now all the 1.0 tests pass and the 2.0 tests fail on the CI machine.

Everything is passing locally

**Comment by jskeet** [comment]
2.3.1 is now available. Will give it a try...

**Comment by jskeet** [comment]
Ian, could you check if this is okay now?

**Comment by iantalarico** [comment]
All is green :) Thanks Jon!
