### ISSUE TITLE
BigTable CheckAndMutateRow flattenings don't have a predicate parameter

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-dotnet#1584]
E.g. https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/BigtableClient.cs#L706

Making these flattenings essentially useless.

This may well be a gapic.yaml problem, I haven't yet checked.

**Comment by evildour** [comment]
Yup, noticed that too and I literally just submitted the GAPIC config change to fix this 91 minutes ago. It should propagate to googleapis soon (if it hasn't already), and then I'll regenerate. Note that it actually can be used without the predicate (I too was wrong about this). No predicate checks to see if the row has any values at all.

**Comment by evildour** [comment]
Actually, I'll probably wait until #1585 is merged to avoid any issues.

**Comment by evildour** [comment]
Fixed with #1597
