### ISSUE TITLE
Remove streaming gRPC cancellation workaround from SimpleSubscriber

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-dotnet#1591]
Now gRPC 1.7.0 is released, which supports cancelling within `MoveNext()` we can remove the workaround.

**Comment by jskeet** [comment]
Am I right in saying this was done in #1683?

**Comment by chrisdunelm** [comment]
Yes it was done in #1683, although unfortunately this is incorrect.
It really does need to use a `CancellationToken.None` in the `MoveNext()` call because cancelling `MoveNext()` cancels the entire streaming RPC. This is undesirable, because if it's a user-requested cancellation then there may still be further acks to send to the server over the same streaming RPC.
The next PR will fix this with a explanatory comment.

**Comment by chrisdunelm** [comment]
It is required to not use a cancellation token in the call to `MoveNext()`. There is a comment in #1724 explaining why.
