### ISSUE TITLE
Check our uses of default literals with nullable types

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1594]
Just found this:

https://github.com/dotnet/roslyn/issues/22578

If we're using `default` in any parameter lists for nullable value types, that could end up causing a problem.

Not sure of the best way to detect that - @evildour how simple would a Roslyn analyzer be to find that? Any alternatives you can think of? A quick text search for `? [a-zA-Z0-9]+ = default` might be a good first pass...

**Comment by evildour** [comment]
Should be pretty simple to make an analyzer for this. Looking into it now.
