### ISSUE TITLE
PubSub Slow Subscriber.  Pooling?

### ISSUE THREAD

**Issue by NPSF3000** [GoogleCloudPlatform/google-cloud-dotnet#1607]
Hi,

We just ran a quick test.  A 4 core VM (in GCP) running a .Net client with 4 threads can consume PubSub at about 200Mbps.  A similar 16core VM (running 16 threads) can consume at 300Mbps... not a drastic improvement.

However in the second example if we fire up the application 3 times we consume at 900Mbps.  This indicated the bottle neck is not in the VM or the network, but inside the .Net subscriber code.  We create a separate subscriber per thread, but I note the library seems to use pooling for its 'channel's.

Is it possible to create PubSub subscribers that don't pool connections, have the connection pool scale for performance, or any other technique to increase throughput?

Thanks!

**Comment by chrisdunelm** [comment]
@NPSF3000 Are you using the [`SimpleSubscriber`](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SimpleSubscriber.cs#L48) class? This is most suitable class to use.  Please can you show the code where you create the subscriber class, and start the subscription? Thanks.

**Comment by NPSF3000** [comment]
@chrisdunelm A rough overview of the code is the following:

`for (int i = 0; i < Environment.ProcessorCount * 3; i++)
            {
                Task.Run(async () =>
                {
                    try
                    {
                        var subscriber = SubscriberClient.Create();
                        while (true)
                        {
                            var response = await subscriber.PullAsync(devmainsubscriptionName, returnImmediately: true, maxMessages: 1000);
                            var messages = response.ReceivedMessages.Select(m => m.Message.Data.ToStringUtf8());

                            if (!messages.Any())
                                continue;

                            // Acknowledge the message so we don't see it again.
                            var ackIds = new string[response.ReceivedMessages.Count];
                            for (int j = 0; j < response.ReceivedMessages.Count; ++j)
                                ackIds[j] = response.ReceivedMessages[j].AckId;
                            await subscriber.AcknowledgeAsync(devmainsubscriptionName, ackIds);
                        }
                    }
                    catch (Exception e)
                    {
                        //...
                    }
                });`

Looks like we might be creating 3 tasks per core.

**Comment by chrisdunelm** [comment]
@NPSF3000 Thanks for the code.

Please use the `SimpleSubscriber` instead. It will automatically create multiple channels to the pubsub service, ensuring there is no network/channel bottleneck.
There is a simple example here: https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/SubscriberClientSnippets.cs#L120

**Comment by NPSF3000** [comment]
@chrisdunelm thanks.  We'll take a look and comment back if any issue arise.  Much appreciated.

**Comment by chrisdunelm** [comment]
Closing, please re-open if this doesn't work as expected.

**Comment by adhikaribi** [comment]
Hi @chrisdunelm, 

We are facing a different issue with the message not being acknowledged using the SimpleSubscriber. (Note: we did not have this issue with SubscriberClient before)

We tried with around 500k records residing in the subscription and it was accurate and same number of items were inserted into the buffer (READMAINLOGCOUNTER value was accurate too)

but as soon as we tried with around 20 Million records we got the random number of items inserted into the buffer and READMAINLOGCOUNTER was off by millions (it was 25M, 28M, 30M completely random on various tests). This means it was not properly acknowledging the message after reading it.

The buffer is a ConcurrentQueue.

 ```
Task.Run(async () =>
            {
                SimpleSubscriber simpleSubscriber = await SimpleSubscriber.CreateAsync(devmainsubscriptionName);
                await simpleSubscriber.StartAsync((msg, cancellationToken) =>
                {
                    if (msg != null)
                    {
                        buffer.Add(msg.Data.ToStringUtf8());
                        Interlocked.Add(ref READMAINLOGCOUNTER, 1);
                        // Return Reply.Ack to indicate this message has been handled.
                        return Task.FromResult(SimpleSubscriber.Reply.Ack);
                    }
                    return Task.FromResult(SimpleSubscriber.Reply.Nack);
                });
            });

// add method of buffer			
public void Add(T item)
{
            if (addFinished) throw new Exception("Buffer was set to add finished!");
            queue.Enqueue(item);
 }
		
```
As mentioned, please let us know what could be the reason it worked completely fine with fewer records and completely off with more and any improvement/suggestion for the code above.

Thanks,

Bibek
