### ISSUE TITLE
Google.Cloud.PubSub.V1.IntegrationTests BulkMessaging test hangs on deadlock

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#1610]
Jon, Chris: Not sure which of you is best to talk to on this.  This is showing up on the Windows CI.  Just using this as a place holder so we don't lose track.

I have had two tests run that hang for about 30 min.

**Comment by jskeet** [comment]
Definitely Chris :)

**Comment by iantalarico** [comment]
This is still happening

**Comment by chrisdunelm** [comment]
@iantalarico Is this now resolved? I've looked at some of the integration test failures, and they don't seem be caused by pubsub.
Can this issue be closed?

**Comment by iantalarico** [comment]
Yea, I haven't seen this failure in awhile.
