### ISSUE TITLE
[Speech] streamingRecognize for real time always hint: Shutdown has already been called

### ISSUE THREAD

**Issue by zhongyzh** [GoogleCloudPlatform/google-cloud-dotnet#1612]
I use SpeechApi to translate real time voice to text, and I uncounted the GRPC error, can give some suggestion:
static async Task StreamingMicRecognizeAsync(int seconds)
{
//if (NAudio.Wave.WaveIn.DeviceCount < 1)
//{
// Console.WriteLine("No microphone!");
// return -1;
//}
var speech = SpeechClient.Create();
var streamingCall = speech.StreamingRecognize(null, new BidirectionalStreamingSettings(10240));
// Write the initial request with the config.
try
{
await streamingCall.WriteAsync(
new StreamingRecognizeRequest()
{
StreamingConfig = new StreamingRecognitionConfig()
{
Config = new RecognitionConfig()
{
Encoding =
RecognitionConfig.Types.AudioEncoding.Linear16,
SampleRateHertz = 16000,
LanguageCode = "en",
},
InterimResults = true,
}
});
}
catch (Exception ex)
{

            Console.WriteLine("WriteAsync 0.error:{0:x}", ex.HResult);
        }

        // Print responses as they arrive.
        Task printResponses = Task.Run(async () =>
        {
            while (await streamingCall.ResponseStream.MoveNext(
                default(CancellationToken)))
            {
                foreach (var result in streamingCall.ResponseStream
                    .Current.Results)
                {
                    foreach (var alternative in result.Alternatives)
                    {
                        Console.WriteLine(alternative.Transcript);
                    }
                }
            }
        });
        // Read from the microphone and stream to API.
        object writeLock = new object();
        bool writeMore = true;
        var waveIn = new NAudio.Wave.WasapiCaptureRT();
        //waveIn.DeviceNumber = 0;
        waveIn.WaveFormat = new NAudio.Wave.WaveFormat(48000, 2);
       
        waveIn.DataAvailable +=
            (object sender, NAudio.Wave.WaveInEventArgs args) =>
            {
                lock (writeLock)
                {
                    if (!writeMore)
                        return;
                    Console.WriteLine("recording:{0:d}", args.BytesRecorded);
                     
                    byte[] newBuffer = new byte[args.BytesRecorded / 6];
                    for (int i = 0; i < args.BytesRecorded / 6; i +=6)
                    {
                        UInt16 first = (UInt16)((args.Buffer[i * 2 + 1] << 8) | args.Buffer[i * 2]);
                        UInt16 second = (UInt16)((args.Buffer[i * 2 + 5] << 8) | args.Buffer[i * 2+4]);
                        UInt16 third = (UInt16)((args.Buffer[i * 2 + 9] << 8) | args.Buffer[i * 2+8]);
                        UInt16 newOne = (UInt16)((UInt32)(first + second + third) / 3);
                        newBuffer[i] = (byte)(newOne & 0X08);
                        newBuffer[i+1] = (byte)(newOne >> 8 );
                    }
                    StreamingRecognizeRequest request = new StreamingRecognizeRequest()
                    {
                        AudioContent = Google.Protobuf.ByteString.CopyFrom(newBuffer, 0, args.BytesRecorded / 6)
                    };
                    try
                    {
                        streamingCall.WriteAsync(request).Wait();
                    }
                    catch (Exception ex)
                    {

                        Console.WriteLine("WriteAsync.error:{0:x}",ex.HResult);
                    }
                }

            };
        //waveIn.RecordingStopped += (object sender, StoppedEventArgs stoppedEventArgs) =>
        //{

        //};
        waveIn.StartRecording();
        Console.WriteLine("Speak now.");
        await Task.Delay(TimeSpan.FromSeconds(seconds));
        // Stop recording and shut down.
        waveIn.StopRecording();
        lock (writeLock) writeMore = false;
        await streamingCall.WriteCompleteAsync();
        await printResponses;
        return 0;
    } 
**At this line: streamingCall.WriteAsync(request).Wait(); will receive the exception.**

**Comment by zhongyzh** [comment]
codes is OK.
the reason is  var task = StreamingMicRecognizeAsync(10 * 60);
        need wait the task:    **task.Wait();**

**Comment by jskeet** [comment]
So just to check, we can close this issue, yes? (I wouldn't recommend calling `task.Wait()` - you should be awaiting the task instead - but that's sort of a side matter.)

**Comment by zhongyzh** [comment]
Hi, Jon:
Yes, please close it. At same time, think for your suggestion.
Thanks


[https://www.cisco.com/c/dam/m/en_us/signaturetool/images/banners/standard/10_standard_graphic.png]




Nemo Zhu
TECHNICAL LEADER.ENGINEERING
zhongyzh@cisco.com<mailto:zhongyzh@cisco.com>
Tel: +86 571 2807 1876










Cisco Systems, Inc.
6F Technology Mansion, East Software Par No.90 Wensan Road
HANGZHOU
310012
China
cisco.com



[http://www.cisco.com/assets/swa/img/thinkbeforeyouprint.gif]

Think before you print.

This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.
Please click here<http://www.cisco.com/c/en/us/about/legal/terms-sale-software-license-agreement/company-registration-information.html> for Company Registration Information.
