### ISSUE TITLE
Trying to Read null string from Spanner using Spanner.Data (ADO.NET) Fails with Exception

### ISSUE THREAD

**Issue by alyaros** [GoogleCloudPlatform/google-cloud-dotnet#1613]
Query Example:
```
using (var connection = new SpannerConnection(connectionString))
{
     connection.Open();

      var reader = await connection.CreateSelectCommand("SELECT TagId, Name FROM 
      Tags").ExecuteReaderAsync();
      
    while (reader.Read())
    {
        Console.WriteLine(reader.IsDBNull(1));
    }                                        
}
```
In case Name is null string the reader throws NPE.

**Comment by alyaros** [comment]
The Error: (Object reference not set to an instance of an object.)
```
at Google.Cloud.Spanner.Data.SpannerDataReader.IsDBNull(Int32 i) in C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Spanner.Data\Google.Cloud.Spanner.Data\SpannerDataReader.cs:line 217
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
```

**Comment by benwulfe** [comment]
Hi alyaros@, are you attempting to use our spanner EF provider (which is still under development) or are you creating your own?

**Comment by alyaros** [comment]
Already created my own.
The problem is in the Ado driver and not in the ef core 2 adapter.

**Comment by alyaros** [comment]
@benwulfe Can you share where can I find the EF Provider code you wrote\writing?

**Comment by benwulfe** [comment]
This issue has been fixed along with the in progress work on the EF provider -- which is in this repo under https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/apis/Google.Cloud.EntityFrameworkCore.Spanner.

I will do a release as soon as possible to get this fix out to you.

Also, if you are interested in getting early releases of our EF provider, you can send me a PM at benwu@google.com and we may be able to work something out...

**Comment by benwulfe** [comment]
Fixed in beta08.  Please let me know if you see any issues.
