### ISSUE TITLE
Stop using deprecated type Hashtable

### ISSUE THREAD

**Issue by evildour** [GoogleCloudPlatform/google-cloud-dotnet#1625]
(flagged by the [API Analyzer](https://www.nuget.org/packages/Microsoft.DotNet.Analyzers.Compatibility/))

Spanner has some uses of `Hashtable`, which is deprecated. Change these to `Dictionary<string, object>`

**Comment by jskeet** [comment]
This is documented to be returned by default from `SpannerDataReader.GetFieldValue(string)` for struct fields - I suspect that means we can't fix it now. Do you agree?

**Comment by chrisdunelm** [comment]
Which documentation is this?

**Comment by jskeet** [comment]
https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Spanner.Data/api/Google.Cloud.Spanner.Data.SpannerDbType.html#Google_Cloud_Spanner_Data_SpannerDbType_StructOf_System_Collections_Generic_IDictionary_System_String_Google_Cloud_Spanner_Data_SpannerDbType__

**Comment by chrisdunelm** [comment]
Oh right. And it's GAed, so now can't be changed presumably. That's a (small) shame.

**Comment by jskeet** [comment]
I think we can close this issue now as we've done as much as we can without breaking compatibility.
