### ISSUE TITLE
PubSub SimpleSubscriber not acknowledging the message properly

### ISSUE THREAD

**Issue by adhikaribi** [GoogleCloudPlatform/google-cloud-dotnet#1643]
Hi, 

We are facing an issue with the message not being acknowledged properly using the SimpleSubscriber. (Note: we did not have this issue with SubscriberClient before)

We tried with around 500k records residing in the subscription and it was accurate and same number of items were inserted into the buffer (the counter (READMAINLOGCOUNTER) value was accurate too) but as soon as we tried with around 20 Million records we got the random number of items inserted into the buffer and the counter (READMAINLOGCOUNTER) was off by millions (it was 25M, 28M, 30M completely random on various tests). This means it was not properly acknowledging the message after reading it.

Also, if we do not add the items to the buffer at all it was accurate. The counter (READMAINLOGCOUNTER) showed the exact amount of records in the subscription.
So we are wondering where in-between the issue lies, is there anything inside SimpleSubscriber that might be causing the issue or is it the buffer itself.
 
Please let us know what could be the reason it worked completely fine with fewer records and completely off with more and any improvement/suggestion for the code below.

The buffer is a ConcurrentQueue. Simplified Code Snippet is provided below:

 ```
Task.Run(async () =>
            {
                SimpleSubscriber simpleSubscriber = await SimpleSubscriber.CreateAsync(devmainsubscriptionName);
                await simpleSubscriber.StartAsync((msg, cancellationToken) =>
                {
                    if (msg != null)
                    {
                        buffer.Add(msg.Data.ToStringUtf8());
                        Interlocked.Add(ref READMAINLOGCOUNTER, 1);
                        // Return Reply.Ack to indicate this message has been handled.
                        return Task.FromResult(SimpleSubscriber.Reply.Ack);
                    }
                    return Task.FromResult(SimpleSubscriber.Reply.Nack);
                });
            });

// add method of buffer	
ConcurrentQueue<T> queue = new ConcurrentQueue<T>();		
public void Add(T item)
{
            if (addFinished) throw new Exception("Buffer was set to add finished!");
            queue.Enqueue(item);
 }
		
```

Thanks,

Bibek

**Comment by chrisdunelm** [comment]
Apologies for the delay in answering.
There are currently some issues with SimpleSubscriber that are being investigated and fixed. Receiving some duplicate messages is one of those issues.
We expect to have a new beta out fairly soon, which should resolve these issues.

Can I clarify one point: Do you mean that if you remove the `buffer.Add(...);` line, then `READMAINLOGCOUNTER` is reported the correct number of messages received - that is, the same number as you publish?
If so, this seems unexpected. Whether you're writing to a buffer or not shouldn't affect the behaviour of SimpleSubscriber.
I have two thoughts:
* If your code throws an exception within the message handler, then this will be interpreted as a message NACK, so it's expected that you will receive that message again.
* It's possible that if the buffer.add code is using significant CPU-time, then this may affect the SimpleSubscriber behaviour. That is, if there is little CPU-time for the Subscriber code to execute, then message acks and lease-extensions may not be getting back to the server in time.

**Comment by adhikaribi** [comment]
@chrisdunelm thanks for getting back. Yes, the problem is with SimpleSubscriber and Buffer used at the same time, it does not ACK the message on time.  It is true the behavior should not have changed if using buffer or not. The problem surely is with CPU bound wait, this is a pub-sub buffer and I have no other choice to use instead of it. I will see and improve on my side. Thank You once again

**Comment by chrisdunelm** [comment]
@adhikaribi Is this issue now resolved? Or are you still having problems with messages not being acknowledged?

If you're not already using the latest nuget version (`Google.Cloud.PubSub.V1` version 1.0.0-beta15), then please upgrade as this fixes all currently known issues.
Also note that a server update was made about 2 or 3 weeks ago that should have improved ACK reliability.

**Comment by chrisdunelm** [comment]
Closing. Please re-open if there is still a problem.
