### ISSUE TITLE
Google speech not good at split Chinese

### ISSUE THREAD

**Issue by zhongyzh** [GoogleCloudPlatform/google-cloud-dotnet#1644]
We use CPP Google Speech APIs to transfer voice into text, it works fine for English, but not good at split sentence for Chinese. At result, we can also received the last sentence text, didn't be cleared when new sentence start, not same as English.
Is there are any APIs to solve this issue ? 

Our codes are:
void Run()
{
	auto creds = grpc::GoogleDefaultCredentials();
	auto channel = grpc::CreateChannel("speech.googleapis.com", creds);

	std::unique_ptr<Speech::Stub> speech(Speech::NewStub(channel));

	StreamingRecognizeRequest request;
	auto * streaming_config = request.mutable_streaming_config();
	
	streaming_config->mutable_config()->set_language_code("zh");
	streaming_config->mutable_config()->set_sample_rate_hertz(RATE);
	streaming_config->mutable_config()->set_encoding(RecognitionConfig::LINEAR16);
	streaming_config->set_interim_results(true);
	streaming_config->set_single_utterance(false);

	grpc::ClientContext context;
	auto streamer = speech->StreamingRecognize(&context);
	streamer->Write(request);

	std::thread wavein_thread(&CSpeechClient::waveIn_Proc, streamer.get(), this);

	StreamingRecognizeResponse response;
	while (streamer->Read(&response))
	{
		for (int i = 0; i < response.results_size(); ++i)
		{
			auto result = response.results(i);
			std::cout << "Result stability: " << result.stability() << ", " << result.is_final()  << std::endl;
			for (int a = 0; a < result.alternatives_size(); ++a)
			{
				auto alternative = result.alternatives(a);
				if (result.stability() > 0.1 || alternative.confidence() > 0.1)
				{
					std::cout << alternative.confidence() << "\t" << alternative.transcript() << std::endl;
				}
			}
		}
	}
	grpc::Status status = streamer->Finish();
	wavein_thread.join();

	if (!status.ok())
	{
		std::cerr << status.error_message() << std::endl;
	}
};

**Comment by jskeet** [comment]
This doesn't look like it's using the .NET libraries at all - could you clarify whether that's the case? It also sounds like it's not so much a client library issue as something for the Speech API backend team to look at...

I suspect this may be best asked on https://groups.google.com/forum/#!forum/cloud-speech-discuss rather than in the repository (which is for the Google Cloud .NET client libraries).

**Comment by zhongyzh** [comment]
Moved to https://github.com/GoogleCloudPlatform/cpp-docs-samples/issues/28
