### ISSUE TITLE
Authentication error via DatastoreDb (implicitly)

### ISSUE THREAD

**Issue by hhblaze** [GoogleCloudPlatform/google-cloud-dotnet#1649]
Duplicates https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/1648#issuecomment-343515518

Environment variable is set,
![image](https://user-images.githubusercontent.com/486781/32667755-e2f7211e-c63b-11e7-8691-b3c8c9fc59e1.png)

![image](https://user-images.githubusercontent.com/486781/32667736-d340303a-c63b-11e7-855b-8bd1a89855f1.png)

Is there a way to connect to datastore supplying credential file explicitly?

Thank you!

**Comment by jskeet** [comment]
> Is there a way to connect to datastore supplying credential file explicitly?

Yes, although it's currently somewhat painful. You need to create the credentials, with the right scopes, and then create the channel from that. See https://googlecloudplatform.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis

**Comment by hhblaze** [comment]
You were completely right, despite the fact that ENV.VAR was set on the level of the system and my local user, command
  Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS");
returned null,
![image](https://user-images.githubusercontent.com/486781/32688136-a5eea9be-c6cb-11e7-9567-cc948c7c1a1f.png)

both cases have started to work after
Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", @"mypathtojson");
Though, after program restart this variable must be set again, because it answers for the env.variable of the current process.
