### ISSUE TITLE
Move to .NET Core 1.0 RTM and Preview 2 tooling

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#165]
Blocker at the moment for this: running `dotnet test` on Linux with a TFM of `net451` fails, which is apparently expected.

It's not clear at the moment whether the dotnet cli is really meant to support non-Core libraries/applications outside Windows.

Once all our libraries support Core of course, this won't be a problem...

**Comment by jskeet** [comment]
Currently blocked just on #251.

**Comment by sethmurphy18** [comment]
In order to build with .NET Core, you need to target `netcore` in your `project.json`. This is something Microsoft changed with the 1.0 release of .NET Core.

**Comment by jskeet** [comment]
@sethmurphy18: Not at all sure what you mean by that. You target netstandard1.x for libraries, and netcoreapp1.x for applications. That's what I've done in all my other projects... And it's fine to target net45 (for example) and still build with dotnet cli... on Linux you need to have Mono installed for that to work though.

**Comment by sethmurphy18** [comment]
You know what, you're right, I'm sorry, I forgot that they changed it again...they have changed this so many times, it's hard to keep up with.

**Comment by jskeet** [comment]
Done.
