### ISSUE TITLE
Incorrect links in docs from protos

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-dotnet#171]
E.g. https://github.com/GoogleCloudPlatform/gcloud-dotnet/blob/master/src/Google.Logging.V2/LoggingServiceV2Client.cs#L617
Some links from docs brought in from protos are relative URLs, not absolute. I guess these won't work properly?

**Comment by jskeet** [comment]
Urgh - no indeed. There are potentially lots of things to fix up in terms of docs from protos. In this case, I think we need to get the proto itself fixed.

**Comment by jskeet** [comment]
This is effectively a dupe of #110.
