### ISSUE TITLE
docs folder without a snippets directory breaks docs build

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#1743]
./docs/builddocs.sh currently fails on "Google.Cloud.EntityFrameworkCore.Spanner" the build docs script assumes any api with a docs directory has a snuppets projects.

Should we require the above to be true or update the script?

**Comment by jskeet** [comment]
I'll have a look tomorrow. Options are:

- Fix it to not require snippets at all
- Add some snippets for Spanner EF
- Add just an empty directory with a README.txt

The latter would be the simplest approach, I suspect, if it works. Will give it a try.
(Realistically, I think we *will* want snippets for all APIs, so I don't think it's worth going to too much trouble to make it handle this case.)
