### ISSUE TITLE
Setting VideoIntelligenceServiceClient programmatically in C#

### ISSUE THREAD

**Issue by amitchaudhary** [GoogleCloudPlatform/google-cloud-dotnet#1767]
I already understand the GOOGLE_APPLICATION_CREDENTIALS approach to provide the credentials.
But I'm working in the serverless programming model. Hence, wanted to pass the credentials at runtime to the VideoIntelligenceServiceClient in C#. But I don't see any sample to do it? 
Something like this - 
GoogleCredential credential = GoogleCredential.FromStream(jsonStream);
StorageClient storageClient = StorageClient.Create(credential); //VideoIntelligenceServiceClient ???

**Comment by jskeet** [comment]
See https://googlecloudplatform.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis

**Comment by amitchaudhary** [comment]
Just updated the comment for more details? any direct sample for VideoIntelligenceServiceClient?

**Comment by chrisdunelm** [comment]
Yes, this is not as simple and obvious as it should be.

You need to create a gRPC `Channel` instance using your credentials, then pass that to `VideoIntelligenceServiceClient.Create(channel);`

To create the `Channel` instance, and then the `VideoIntelligenceServiceClient` instance do something like this:

``` C#
using Google.Apis.Auth.OAuth2;
using Grpc.Auth;

GoogleCredential credential = GoogleCredential.FromStream(...); // Or however you want to load your credential
ChannelCredential channelCredential = credential.ToChannelCredentials();
ServiceEndpoint endpoint = VideoIntelligenceServiceClient.DefaultEndpoint;
Channel channel = new Channel(endpoint.Host, endpoint.Port, channelCredentials, options);

VideoIntelligenceServiceClient client = VideoIntelligenceServiceClient.Create(channel);
```

**Comment by jskeet** [comment]
Closing as Chris has provided the details.

**Comment by amitchaudhary** [comment]
Small typo/correction - 
ChannelCredentials channelCredential = credential.ToChannelCredentials();

**Comment by chrisdunelm** [comment]
@amitchaudhary Thanks, updated.
