### ISSUE TITLE
FireStore

### ISSUE THREAD

**Issue by AnidjarDavid** [GoogleCloudPlatform/google-cloud-dotnet#1781]
Hi,
I am trying the example from [http://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/index.html].
this is the main function in a dot.net console application.

`Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", @"C:\PathToJsonFile\xxxxxxxxxxxxxxxxx.json");
            var authFile = Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS");
            //GoogleCredential credential = await GoogleCredential.GetApplicationDefaultAsync();

            string projectId = "project-Id";
            FirestoreDb db = FirestoreDb.Create(projectId);
            
            // Create a document with a random ID in the "users" collection.
            CollectionReference collection = db.Collection("users");
            
            DocumentReference document = await collection.AddAsync(new { Name = new { First = "Ada", Last = "Lovelace" }, Born = 1815 });
            Console.ReadLine();`

At the AddAsync method i get the following exception: 
An exception of type 'Grpc.Core.RpcException' occurred in mscorlib.dll but was not handled in user code

Additional information: Status(StatusCode=PermissionDenied, Detail="Missing or insufficient permissions.")

**Comment by jskeet** [comment]
Did you change `"project-id"` in the example to your actual project ID? Have you definitely enabled Firestore? Are you able to use any of the other methods, e.g. listing collections?

**Comment by AnidjarDavid** [comment]
Hi thanks for responding.
Of course i did, otherwise i would not get to the AddAsync method

**Comment by jskeet** [comment]
> Of course i did, otherwise i would not get to the AddAsync method

Yes you would. Nothing until `AddAsync` makes any RPCs. The `db.Collection` method just creates a `CollectionReference` in memory - it doesn't ask the server for anything.

**Comment by AnidjarDavid** [comment]
Thanks again Jon.
This my first Firestore Project.
the rules for the database
`service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write;
    }
  }
}`

which mean it does not require any authentication

**Comment by jskeet** [comment]
Well you'll be using the authentication specified in the service account JSON file you set the environment variable to. Did you add those rules yourself, or were they there to start with? I've never had to change or even look at the rules for the database myself. It may be worth trying to get back to a blank slate.

**Comment by AnidjarDavid** [comment]
The rules were there to start with.
It is a newly and empty project. it is in a blank state.
I will try to struggle with it a bit more and the I guess I will follow tour suggestion
Thanks very much

**Comment by jskeet** [comment]
Okay, next thing to check is that the service account you're using really is the right one. Is it definitely associated with the project that owns that database? I know that due to the "No Firestore and Datastore in the same project" limits, I've got two projects I use.

**Comment by AnidjarDavid** [comment]
I have created a new mail account for this project and created a single project.

**Comment by jskeet** [comment]
You shouldn't need a new Google account - just a GCP project. And the JSON file is a service account for that project? It should look something like:

```text
{
  "type": "service_account",
  "project_id": "(project id here)",
  "private_key_id": "(stuff)",
  "private_key": "-----BEGIN PRIVATE KEY-----(stuff)\n-----END PRIVATE KEY-----\n",
  "client_email": "(email address here)",
  "client_id": "(id here)",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "(URL that mentions project ID)"
}
```

**Comment by AnidjarDavid** [comment]
Hi jon,
You were right!
I had another GCP project and the JSON file was not the correct one.
I changed it and now it seems to work!!

Thank you very much !!!!

**Comment by jskeet** [comment]
Excellent - very glad to hear that :) Closing.
