### ISSUE TITLE
Fix bigtable server-streaming method flattening before release

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-dotnet#1791]
GAPIC codegen currently doesn't support flattenings on server-streaming methods.
So a hand-written flattened method has been temporarily included. The code-gen must be fixed, and the code-gen'ed version must be used before release.

**Comment by chrisdunelm** [comment]
This applies to the `SampleRowKeys` method (and possibly more).

**Comment by jskeet** [comment]
Just checking, is this still the case, or has this been done?

**Comment by chrisdunelm** [comment]
I'll need to check, but I'm fairly sure this is still the case; i.e. the code-gen still doesn't generate server-streaming flattenings.

**Comment by jskeet** [comment]
@evildour: Can I check that you still need this functionality, too?

**Comment by evildour** [comment]
Yes it is still needed for ReadRows and SampleRowKeys in the Data API.

**Comment by chrisdunelm** [comment]
The manual streaming-flattened code needs removing. Re-opening until that is done.

**Comment by jskeet** [comment]
And we need to regenerate, presumably. I can do both of these today.

**Comment by chrisdunelm** [comment]
Yes, removal and re-gen. Hopefully should be quick and trouble-free :)

**Comment by jskeet** [comment]
This is now complete - closing.
