### ISSUE TITLE
Please add MessageParser<Value>.TryParse api

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#1793]
I would like to suggest that MessageParser base class should have TryParse function for additional to `ParseDelimitedFrom` `ParseFrom` and `ParseJson` that return boolean and out value

So we could check for message that it parsable and handle alternate logic if it not parsable instead of expensive try/catch

**Comment by jskeet** [comment]
Did you mean to post this in the google/protobuf repo? This repo is for the API client libraries. I don't anticipate that we'd add TryParse functionality to protobuf though - there'd be quite a significant API surface addition to add it, including to interfaces (which would be a breaking change).

Closing this issue; please reopen in the protobuf repo if you still think it's worth it.
