### ISSUE TITLE
[Bigtable] Support row filters for literal strings

### ISSUE THREAD

**Issue by evildour** [GoogleCloudPlatform/google-cloud-dotnet#1802]
In the Bigtable project, there is a `RowFilters` static class with factory methods for creating `RowFilter` instances. There are four `...Regex(string)` methods taking in regular expression patterns for matching row keys, column family names, column qualifiers, or cell values. For example, one would use `RowFilters.ValueRegex(@"A\d")` to create a cell value filter for matching cells with value 'A' followed by a digit.

Determine whether it would make sense (and be consistent with other languages) to offer associated literal string methods, such as `RowFilters.Value(@"A1")`, that would delegate to the `...Regex` versions with their parameters regex-escaped.

**Comment by jskeet** [comment]
Mike, was this fixed by #1823?

**Comment by evildour** [comment]
Yup, sorry I forgot I created an issue for this.
