### ISSUE TITLE
[FireStore Question] What's difference between Unary.IsNull and Binary.Equal null ? Are there Unary.NotNull?

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#1815]
What's difference between Unary.IsNull and Binary.Equal null ?

Is it has any difference behavior? Can we use it to find document that has specific field exist or not exist?

At first I look at UnaryOperator to find operator for NotNull

I have document like this

```JSON
{
    "_id" : "1",
    "result" : {}
}
{
    "_id" : "2"
}
{
    "_id" : "3",
    "result" : {}
}
```

I want to query for all document that already has any result. And also I want to query for any document that don't has any result yet too, how should I make query?

**Comment by jskeet** [comment]
As far as I can tell, you should use `Unary.IsNull` to check for null equality. I don't *think* there's a "not equal" operator in any sense, either for null or comparing for inequality with another value.

cc @schmidt-sebastian

**Comment by Thaina** [comment]
@jskeet Can `Unary.IsNull` also check for missing field?

**Comment by jskeet** [comment]
I don't know, I'm afraid - I suggest you just give it a try.

Given that this isn't .NET-specific, I'd suggest using one of the support mechanisms listed in https://firebase.google.com/support/ - that way you're more likely to interact with people who know a lot more about Firestore than I do. (I'm not on the Firestore or Firebase team; I'm only responsible for the C# libraries.)

**Comment by Thaina** [comment]
@jskeet Thank you very much

**Comment by jskeet** [comment]
Closing as not really an issue for the .NET libraries per se.

**Comment by schmidt-sebastian** [comment]
There is no "not equals" operator for any field type. You can check for the existing of a field by ordering by it. `query.order(field)` will only return results that have the key `field`.

**Comment by Thaina** [comment]
@schmidt-sebastian  Thanks for your suggestion but I try to avoid that because I would like to use ordering field for query other field

**Comment by Thaina** [comment]
@schmidt-sebastian I was curious, how was `null` and `array` and `map` would be sorted in firestore when we use ordering? Can we sort by `> null` to query everything that not null?

**Comment by schmidt-sebastian** [comment]
Yes, you can sort types against one another. Specifying `> null` would return everything that is defined and not `null` since `null` sorts first in Firestore. I don't know out of the top of my head if we have any publicly available documentation on our ordering semantics, but you can take a look here to see how types compare: https://github.com/googleapis/nodejs-firestore/blob/master/src/order.js#L29

**Comment by Thaina** [comment]
@schmidt-sebastian I was experiment with it myself and found that it not as expect. I contact the support team and they state this in email

> The value type ordering in our documentation is applied when you're using the orderBy() method or not using any range filters at all.

Not sure if this work with `StartWith'/'EndWith` but I think I could not rely on this in the meantime

**Comment by Thaina** [comment]
@schmidt-sebastian I don't have test environment with me right now. Would you please try this?

```C#
var snapshot = await firestore.collection('testcoll').orderBy('a').where("a",">=",null).get();
```

**Comment by schmidt-sebastian** [comment]
Firestore distinguishes between two kind of queries. Most types allow inequality comparisons (such as `>=`), but NaN and Null only allows for equality. In this specific example, you can work around this with `startAfter`. For now, `where("a",">=",null)` unfortunately does not work directly.

**Comment by Thaina** [comment]
@schmidt-sebastian Thank you very much for clarifying
