### ISSUE TITLE
Could we have ValueSerializer be public ?

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#1818]
https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/20147cde365ffc97ddf7b4d86e95ec50c5fc6171/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/ValueDeserializer.cs#L36

It useful when we use low level API

Also I would like to have implicit operator, at least for Bcl, in `Value` class

**Comment by jskeet** [comment]
I would rather not do either of these - at least for now.

While `ValueDeserializer` is internal, we can change it at will - which we may well want to do quite a bit. Having it as part of the public API would make it a lot harder to modify later. Once we're completely confident that we'll never need to change it, I would consider making it public, but I definitely don't want to do it now.

**Comment by Thaina** [comment]
@jskeet Thanks but then should you keep this issue open for being reminder in the meantime?

**Comment by jskeet** [comment]
I would rather not, as I think it'll be a very long time before it's stable enough, and it'll just clutter up our issues when I'm looking for things I want to work on actively. I'll add it to the backlog file though.
