### ISSUE TITLE
Other firebase service and Firestore for unity

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#1825]
In addition to firestore I would like to request including all firebase admin service in C# along with it in this repo, especially Auth and Database

Is there a plan to do so or it would be in other repo?

Also, is there a way to use dll from this repo in unity3D? I want to use firestore but there are no C# support in firebase unity package

**Comment by jskeet** [comment]
No, nothing here can be used from Unity at the moment. There are very significant technical difficulties in doing so. We'd like to do it in the future, but we have nothing to announce at this point.

Similarly while it's entirely possible that we'll be supporting other Firebase services in the future, it really depends on when they support gRPC, which is what the codegen used for packages in this repo depends on. That will be part of a much bigger set of decisions etc - the C# piece is only a small part of the puzzle.

**Comment by Thaina** [comment]
@jskeet GRPC for unity was now in beta. Would we have firestore API built upon it or would you switch the firebase unity SDK to wrapped on android/ios ?

https://github.com/grpc/grpc/tree/master/src/csharp/experimental#unity

**Comment by jskeet** [comment]
@Thaina: I would *definitely* use the Firebase Unity SDK from mobile. It has all kinds of code that's designed specifically for running on mobile platforms. It's the way you're *expected* to use Firestore from Unity.

(I also wouldn't regard "experimental" as the same as "beta".)

**Comment by Thaina** [comment]
@jskeet Do we have a repo for the wrapper or it would be auto generated code?

**Comment by jskeet** [comment]
@Thaina: I don't know details, I'm not working on that. It's definitely not *entirely* auto-generated though. The aim is to make it similar to the API I'm working on where possible.

**Comment by Thaina** [comment]
@jskeet Thank you and sorry for bother you, are there anyone working on that project I could contact with?

**Comment by jskeet** [comment]
As it'll be part of the Firebase SDK, I'd suggest asking through their normal channels - [Firebase Slack](https://firebase.community/) or the [Google Group](https://groups.google.com/forum/#!forum/firebase-talk).
