### ISSUE TITLE
iOS Unit Test/MockRespons Firestore Calls

### ISSUE THREAD

**Issue by deepthi-bhattachar** [GoogleCloudPlatform/google-cloud-dotnet#1826]
iOS:
Not able to find any articles related to Firestore calls unit testing. Is there anyway to mock the data? If yes, can you please share some links. 

Firestore.firestore().collection(COLLECTION_NAME)
            .whereField(Constants.DOCUMENT_CODE, isEqualTo: inviteCode)
            .addSnapshotListener { querySnapshot, error in
                guard let snapshot = querySnapshot else {
                    print("Error \(error!)")
                    return
                }
        }

**Comment by jskeet** [comment]
This is the github repo for the .NET code - which language were you looking for?

**Comment by deepthi-bhattachar** [comment]
Oops sorry... Dint see that. I am looking for iOS App - SWIFT.

How would you test for .NET?

**Comment by jskeet** [comment]
We're still considering how to best test Firestore apps on .NET, but I wouldn't necessarily expect the same approach as in Swift... and the mobile SDK is different anyway I believe.

It looks like https://github.com/firebase/firebase-ios-sdk is the repo to address this though, if it's a feature request.
