### ISSUE TITLE
Do we have BatchGetDocuments function in high level api?

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#1837]
I was seeing this API in grpc and use it from low level API. But it seem there was not mention in other SDK

Is the transaction API already cover the batchget or it not supported yet?

**Comment by jskeet** [comment]
We currently use `FirestoreDb.GetDocumentSnapshotsAsync` to fetch multiple snapshots, but that's not exposed directly.

@schmidt-sebastian: Any thoughts on whether/how this might be exposed?

**Comment by jskeet** [comment]
Have checked with @schmidt-sebastian offline, and yes, we'll add it. (Precise name TBD - it's `getAll(DocumentReference[])` in Java; it'll be async in C# so will *at least* end with an Async suffix.)

**Comment by jskeet** [comment]
Will probably try to get this done before the Watch API work, just because it should be easier to bite off and do a new (useful) release with...

**Comment by jskeet** [comment]
This is closed because the fix has been merged, but I want to wait a little while before doing another release as I may have more changes imminently.
