### ISSUE TITLE
Wanted to use logging lib “in the raw,” but found no snippets

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-dotnet#184]
I looked here: http://googlecloudplatform.github.io/gcloud-dotnet/index.html
and here: http://googlecloudplatform.github.io/gcloud-dotnet/api/Google.Logging.V2.html
but found no code samples about how to use the logging API.

**Comment by csells** [comment]
I also look here: https://github.com/googlecloudplatform/gcloud-dotnet#google-cloud-logging

**Comment by jskeet** [comment]
Yup, we have no snippets at the moment, partly as we're not expecting the API to be used directly. I'm sure we want to have snippets eventually, but we need to prioritise that against other work.

**Comment by jskeet** [comment]
All API members now have snippets. We don't have anything on the landing page for the API, but hopefully the reference docs are enough for now.
