### ISSUE TITLE
Catching rate limit exceptions

### ISSUE THREAD

**Issue by markwalsh-liverpool** [GoogleCloudPlatform/google-cloud-dotnet#1848]
I highly doubt I will reach the threshold of 400 reqs per second but just incase how should I handle any rate limit exceptions I might encounter, here is a sample of code I am using currently:

```
static void Main(string[] args)
        {
            var credential = GoogleCredential.FromFile(AppDomain.CurrentDomain.BaseDirectory + "license.json")
                .CreateScoped(ImageAnnotatorClient.DefaultScopes);
            var channel = new Grpc.Core.Channel(
                ImageAnnotatorClient.DefaultEndpoint.ToString(),
                credential.ToChannelCredentials());
            var client = ImageAnnotatorClient.Create(channel);
            // Load the image file into memory
            var image = Image.FromUri("http://lincolnshiretoday.net/mag/wp-content/uploads/2017/07/high-street-lbig-web.jpg");
            // Performs label detection on the image file
            var labels = client.DetectLabels(image);
            foreach (var label in labels)
            {
                // Description
                // Score
                Console.WriteLine(label.Description + " - " + label.Score);
                Console.WriteLine(Environment.NewLine);
            }
            Console.ReadLine();

        }

```

**Comment by jskeet** [comment]
That's really an application decision - you may want to wait and then retry, maybe wait and fail any incoming requests until then, or keep passing in requests until they start working again. Without more context it's hard to know what to recommend, I'm afraid.

**Comment by chrisdunelm** [comment]
Or did you mean what error will your client-side code see if you hit the rate limit?

I expect an [`RpcException`](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/RpcException.cs) would be thrown, with a `StatusCode` indicating the problem.
For a rate limit, I would expect a `StatusCode` of [`ResourceExhausted`](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/StatusCode.cs#L82), although I haven't checked this myself.

**Comment by markwalsh-liverpool** [comment]
Hello, thanks for the replies.  I do mean handling this via client-side code indeed!

I am thinking about implementing the batch functionality exposed to me but I wondered what would happen if I hit the 400 images per second threshold whilst I was processing these.  I would expect the status code of ResourceExhausted as you mentioned.

**Comment by jskeet** [comment]
Apologies for not updating this issue between calls.

Out of interest, have you tried deliberately making a huge number of requests to see what happens? If you haven't, I'm happy to try it for you.

**Comment by jskeet** [comment]
One side note by the way: `Image.FromUri` *doesn't* load the image into memory. Instead, the URI is sent in the request. If you want to load the image data into memory and then send that in a request, use `FetchFromUri` or `FetchFromUriAsync` instead.

Finally trying to provoke the error so I can confirm its status.

**Comment by jskeet** [comment]
Confirmed: the error status code is `ResourceExhausted`. I'd expect this to be consistent across APIs, and I know that's the case for Speech for example.

Closing as I think we've answered everything we can here - exactly how you *handle* that error is up to your application, as I mentioned before.
