### ISSUE TITLE
Spanner: Method Google.Api.Gax.Grpc.ClientHelper.BuildApiCall: type argument 'Google.Cloud.Spanner.V1.CreateSessionRequest' violates the constraint of type parameter 'TRequest'.

### ISSUE THREAD

**Issue by jerarl** [GoogleCloudPlatform/google-cloud-dotnet#1867]
Hey guys, we're using the latest Google.Cloud.Spanner.Data 1.1.0-alpha01 and our clients suddenly encounters this error during runtime which hurts their production.

Message : Method Google.Api.Gax.Grpc.ClientHelper.BuildApiCall: type argument 'Google.Cloud.Spanner.V1.CreateSessionRequest' violates the constraint of type parameter 'TRequest'.
Source : Google.Cloud.Spanner.V1

Nuget tags the Google.Cloud.Spanner.V1 (>= 1.1.0-alpha01) as a dependency but is surely raising this error
[Google.Cloud.Spanner.Data -Version 1.1.0-alpha01](https://www.nuget.org/packages/Google.Cloud.Spanner.Data/1.1.0-alpha01)

**Comment by jskeet** [comment]
Hmm... I can't reproduce this, and I can't see why it would be an issue: `BuildApiCall` is [here](https://github.com/googleapis/gax-dotnet/blob/1cf2fed0cebfa96a9d6ba418667fe8d660b3faf6/src/Google.Api.Gax.Grpc/ClientHelper.cs#L59) and has this declaration:

```csharp
public ApiCall<TRequest, TResponse> BuildApiCall<TRequest, TResponse>(
    Func<TRequest, CallOptions, AsyncUnaryCall<TResponse>> asyncGrpcCall,
    Func<TRequest, CallOptions, TResponse> syncGrpcCall,
    CallSettings perMethodCallSettings)
    where TRequest : class, IMessage<TRequest>
    where TResponse : class, IMessage<TResponse>
```

`CreateSessionRequest` is [here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Spanner.cs#L138) and definitely satisfies that constraint.

Are you able to reproduce this in a minimal example? Please include the exact versions of all dependencies (or ideally a project file, if it's a .NET Core project) - I suspect that whatever's wrong is something to do with a version mismatch somewhere, although that's a very odd issue to see.

**Comment by jerarl** [comment]
Unable to reproduce this running in a console with simple implementation. DLLs are running in a web and windows service and seems to be ok if we use the package Google.Cloud.Spanner.V1 -Version 1.0.0.

**Comment by jskeet** [comment]
Could you give more details of the versions of all libraries in the broken case? Also, if you're running a Windows service does that mean it's .NET Framework desktop rather than Core? Could you tell us the version of that as well please?

**Comment by jerarl** [comment]
<package id="Google.Api.CommonProtos" version="1.1.0" targetFramework="net471" />
  <package id="Google.Api.Gax" version="2.2.1" targetFramework="net471" />
  <package id="Google.Api.Gax.Grpc" version="2.2.1" targetFramework="net471" />
  <package id="Google.Apis" version="1.30.0" targetFramework="net471" />
  <package id="Google.Apis.Auth" version="1.30.0" targetFramework="net471" />
  <package id="Google.Apis.Core" version="1.30.0" targetFramework="net471" />
  <package id="Google.Cloud.Iam.V1" version="1.0.0" targetFramework="net471" />
  <package id="Google.Cloud.Spanner.Admin.Database.V1" version="1.1.0-alpha01" targetFramework="net471" />
  <package id="Google.Cloud.Spanner.Admin.Instance.V1" version="1.1.0-alpha01" targetFramework="net471" />
  <package id="Google.Cloud.Spanner.Data" version="1.1.0-alpha01" targetFramework="net471" />
  <package id="Google.Cloud.Spanner.V1" version="1.1.0-alpha01" targetFramework="net471" />
  <package id="Google.LongRunning" version="1.0.0" targetFramework="net471" />
  <package id="Google.Protobuf" version="3.4.1" targetFramework="net471" />
  <package id="Grpc.Auth" version="1.7.0" targetFramework="net471" />
  <package id="Grpc.Core" version="1.7.1" targetFramework="net471" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net471" />
  <package id="System.Interactive.Async" version="3.1.1" targetFramework="net471" />
  <package id="System.IO" version="4.3.0" targetFramework="net471" />
  <package id="System.Net.Http" version="4.3.1" targetFramework="net471" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net471" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net471" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net471" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net471" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net471" />

**Comment by jerarl** [comment]
That's the final packages were using and this gives us an error now:

Message : Method not found: 'Grpc.Core.ChannelCredentials Grpc.Auth.GoogleGrpcCredentials.ToChannelCredentials(Google.Apis.Auth.OAuth2.ITokenAccess)'.
	Source : Google.Cloud.Spanner.Data

But still works in a console app.

**Comment by jskeet** [comment]
That's very odd. It sounds like something is *very* confused about the versions of libraries. Is that new error a build-time error or an exception at execution time?

Does this happen on multiple machines, or just one?

**Comment by jerarl** [comment]
An exception during runtime. All machines seems to be affected.

**Comment by jerarl** [comment]
There seems to be some mixed up versions on some assemblies

![spanner-dependencies](https://user-images.githubusercontent.com/11646073/35564695-fc7babce-05f5-11e8-8914-157848e4096d.PNG)

**Comment by jskeet** [comment]
That screenshot is fine - that just shows a variety of dependency versions. The highest version should be loaded automatically.

If this is only reproducible in a web app, is it possible to create a minimal web app to demonstrate it? (Basically I'm stuck until I can reproduce it, but then we should be able to work out what's going on.)

**Comment by jerarl** [comment]
Just an update, since the application was running in a larger part of the system we added below to the main app config and the issue was resolve.

      <dependentAssembly>
      <assemblyIdentity name="Google.Protobuf" publicKeyToken="a7d26565bac4d604" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.4.1.0" newVersion="3.4.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.30.0.0" newVersion="1.30.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth.PlatformServices" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.30.0.0" newVersion="1.30.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.Gax" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.1.0" newVersion="2.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.Gax.Grpc" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.1.0" newVersion="2.2.1.0" />
      </dependentAssembly>```

**Comment by jskeet** [comment]
Excellent - glad it's fixed. I'd expect assembly binding redirects to be added automatically by NuGet, but it's probably not worth trying to reconstruct why they weren't in this case.
