### ISSUE TITLE
Firestore: allow batch-get of snapshots in a transaction

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1885]

**Comment by Thaina** [comment]
Would you pleased to make a release after this feature?

**Comment by jskeet** [comment]
Yes, that should be doable. I'm making a few other changes in the near future though, so I'll wait until that batch is complete before releasing.

**Comment by Thaina** [comment]
Would you please update nuget for batch functionality. I need to use batchget with masking data. I need some API that could check existing document without downloading bulk data. Or else I need to revert back to use low level API

**Comment by jskeet** [comment]
What do you mean by "with masking data"? If the current code doesn't do what you need, I'm afraid I won't be able to get to it in the next week and a half.

If you just need the current code released, I'll see what I can do in the next couple of days, but please be aware that I have *many* other things I'm working on besides Firestore. (I'd hoped to complete #1883 before releasing again too, but I think we can release without that for now.)

**Comment by Thaina** [comment]
@jskeet I don't know if you have make it support internally but I have seen at least batchGet API have a field named `mask` that could mask the returned document

https://cloud.google.com/firestore/docs/reference/rest/v1beta1/projects.databases.documents/batchGet#request-body

As I said I want to just query to check that document already exist or not. And this document is so large. So I wish I could get only some field to return from batch get

I just think the batchGet api was implement this functionality, or is it not?

**Comment by jskeet** [comment]
No, the batch-get functionality I've implemented (see #1888) just takes a collection of document references. It sounds like doing a release won't help you after all.

@schmidt-sebastian Did you have any plans around this?

**Comment by Thaina** [comment]
Can you make a release for firestore in nuget on this?

Are there any the pending task on firestore?

**Comment by jskeet** [comment]
I'm in the middle of implementing Watch, which is getting reasonably close now. There are some renames coming up too. I'd at least like to get the latter done before the next NuGet release.

**Comment by jskeet** [comment]
Okay, the rename stuff is going to take a little longer than I'd expected, so I'm going to publish a release with the current state of play (which doesn't include any public watch API) to unblock you for this.

**Comment by Thaina** [comment]
Thank you very much
