### ISSUE TITLE
SpannerDataAdapter fills DataTable with Timestamp instead of Date

### ISSUE THREAD

**Issue by jerarl** [GoogleCloudPlatform/google-cloud-dotnet#1890]
Can be reproduce by selecting a Date. Sample below:

> dataTable = new DataTable();
> cmd = connection.CreateSelectCommand("SELECT CAST('1971-10-07' AS DATE) AS BirthDate FROM DimCustomer LIMIT 1");
> adapter.SelectCommand = cmd;
> adapter.Fill(dataTable);
> 

Returns "10/07/1971 12:00:00 AM" instead of "1971-10-07"

**Comment by jskeet** [comment]
.NET doesn't have a date-only type. I suspect you're just seeing the string representation of a `DateTime` value.

**Comment by jerarl** [comment]
but using the SpannerDataReader returns "1971-10-07" using the same SQL

**Comment by jskeet** [comment]
What *exactly* do you mean by "but using the SpannerDataReader"? *How* are you using the SpannerDataReader?

**Comment by jerarl** [comment]
Yep, I see what's wrong now. The datareader reads the content as String while the datatable is using DateTime. Thanks!
