### ISSUE TITLE
Add support for BigQuery customer-managed encryption keys

### ISSUE THREAD

**Issue by choenden** [GoogleCloudPlatform/google-cloud-dotnet#1892]
BigQuery customer-managed encryption keys allow users to specify a Cloud KMS key to protect their BigQuery table.

API:
Jobs: https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs
In a job, there is a destinationEncryptionConfiguration field, which indicates which Cloud KMS key should be used for the destination.

Tables: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables
In a table, there is a encryptionConfiguration field, which indicates which Cloud KMS key protects (or should protect in case of CreateTable) a BigQuery table.

These are the main APIs that are required for day-to-day interaction.
With lower priority, support for getServiceAccount would also be nice: https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/getServiceAccount
Note that unlike the other methods mentioned above, this would generally only be called once and the resulting value (the email address) does not change - so it can easily also be called from UI/API/CLI without much hindrance (hence lower priority).

**Comment by jskeet** [comment]
For my own future reference, this is the storage equivalent of getServiceAccount:
https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Storage.V1/api/Google.Cloud.Storage.V1.StorageClient.html#Google_Cloud_Storage_V1_StorageClient_GetStorageServiceAccountEmail_System_String_Google_Cloud_Storage_V1_GetStorageServiceAccountEmailOptions_

**Comment by jskeet** [comment]
Keeping this issue open for now, as full support should include:

- An integration test and/or snippet
- The get service account call

**Comment by tswast** [comment]
Also, I think full support should include the property at https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.BigQuery.V2/api/Google.Cloud.BigQuery.V2.CreateTableOptions.html as folks will want to set the encryption option when they create a table.

**Comment by tswast** [comment]
I started on a snippet at https://github.com/tswast/google-cloud-dotnet/commit/57ebcfcbf82444164f797934322e7070b336b7f6 but I couldn't figure out how to run the tests. Leaving it here for now, since @choenden offered to help with C# samples. I'll do a complete set in Python first.

**Comment by jskeet** [comment]
Note that the property *isn't* currently present for UploadJsonOptions (and CSV and Avro). I'm happy to be guided as to whether it should be.

**Comment by jskeet** [comment]
I suspect we'll want the "fetch service account" part before a complete snippet is feasible, so we can generate the key (rather than using a hard-coded one) and provide access to it. I'll happily have a look at that.

**Comment by tswast** [comment]
Interesting. I would have that UploadJsonOptions would derive from [CreateLoadJobOptions](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.BigQuery.V2/api/Google.Cloud.BigQuery.V2.CreateLoadJobOptions.html) but apparently it doesn't. What are UploadJsonOptions (and CSV and Avro) classes for? Do they create a load job?

> before a complete snippet is feasible

As discussed elsewhere, keys rings aren't deletable, so it'd be tough to do an end-to-end sample that we can run as an integration test.

My workaround in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4852 and https://github.com/tswast/google-cloud-dotnet/commit/57ebcfcbf82444164f797934322e7070b336b7f6 was to use a key which is usable for encryption/decryption for `allAuthenticatedUsers`. This means anyone can use that key to run the snippet as an integration test. In my opinion it makes for a better sample to show a real path to a key, also.

**Comment by jskeet** [comment]
> What are UploadJsonOptions (and CSV and Avro) classes for? Do they create a load job?

Yes - details all in https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.InsertData.cs.

Those options are tailored for the specific use cases though - while it would be quite nice to have common options via inheritance, it ends up getting messy quickly, so I've lived with duplication.

Sounds like I should create a new PR for those three options classes. Shouldn't be hard.

**Comment by choenden** [comment]
Oh, interesting. Thanks for catching it and looking into the fix Jon!

**Comment by jskeet** [comment]
Fix was implemented in #1898.
