### ISSUE TITLE
Google.Cloud.Firestore: authentication 

### ISSUE THREAD

**Issue by Hussamalsh** [GoogleCloudPlatform/google-cloud-dotnet#1899]
Hi,
I am using Google.Cloud.Firestore for my asp.net project, but i got this error =
"System.InvalidOperationException: 'The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/"

My question is how to authenticate the Firestore library to make request.

**Comment by jskeet** [comment]
Please tell us how you're *trying* to authenticate. Do you have the environment variable set as described?

**Comment by Hussamalsh** [comment]
This is my question, how i can authenticate to use this library in my project?

**Comment by jskeet** [comment]
Download a service account JSON file and then set the environment variable to point to it. See https://developers.google.com/identity/protocols/OAuth2ServiceAccount

**Comment by Hussamalsh** [comment]
Doesn't work for me, give me same error.

**Comment by jskeet** [comment]
Setting it from a command prompt won't affect the environment used by ASP.NET. You need to set the ambient environment variables.

**Comment by Hussamalsh** [comment]
used With Powershell:
$env:GOOGLE_APPLICATION_CREDENTIALS="C:\Users\hussa\Source\Repos\WebSite1\WebSite1\Trials4Us-4c192b52adf3.json" 

still same error

**Comment by jskeet** [comment]
Set the environment variable in the Windows environment settings instead.

**Comment by Hussamalsh** [comment]
https://www.awesomescreenshot.com/upload//795767/13456765-4af6-4489-400b-58526a1646d2.png
same error ^^

**Comment by jskeet** [comment]
And are you actually running as that user? (We don't have any context of how you're running this.) If you're getting that error, the environment variable isn't set as far as the code is concerned. I suggest you add some logging of the environment variable right at the start of your app.

**Comment by jskeet** [comment]
I'm afraid I can't help any more on this issue without more information - please see my previous comment.
(To avoid stale issues cluttering up github, I'll close this in about a week if there are no further replies. You could still reply later at which point I'd potentially reopen the issue, of course.)

**Comment by jskeet** [comment]
Closing as stale.

**Comment by peetjvv** [comment]
Seems this thread died, but for anyone else like me drowning in the docs and coming accross this thread, here is what I had to do to make it work:

 1. Add the json key file to your c# project.
 2. In the file properties window, set "Copy to Output Directory" to either "Copy always" or "Copy if newer"
 3. Use the following code to connect to your db:
```
Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", "app-c5a5afc0d7e5.json");
FirestoreDb = FirestoreDb.Create(Config["firestore:projectid"]);
```

**Comment by codymullins** [comment]
I had the same workaround as @peetjvv, came here hoping for another answer. I did find this related issue though: https://github.com/googleapis/google-cloud-dotnet/issues/1576

**Comment by h4rm** [comment]
The approach by @peetjvv works for me, when I call `FirebaseDB.Create` once.
However, when I later change the environment variable and create another DB, I get "failed permissions" because they create functions seems to still keep the old credential.

Any idea how to fix this?

**Comment by jskeet** [comment]
@h4rm: The default credentials are cached when they're first loaded. Changing the environment variables *within a single process* won't help. If you run a second time, it should be fine.

If you need to use two different sets of credentials within the same process, you'll need to use custom credentials - create a FirestoreClient as per https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis and then create a FirestoreDb with that client.

We're working on making it much easier to use custom credentials, but I don't expect that to be available in the Firestore library very soon.

**Comment by h4rm** [comment]
This was quick, thanks a lot @jskeet. I am going with the custom credentials then!
