### ISSUE TITLE
BigQuery: Unexpected cancellation at Google.Apis.Upload.ResumableUpload

### ISSUE THREAD

**Issue by UkrZilla** [GoogleCloudPlatform/google-cloud-dotnet#1900]
Hi guys,

Sometimes we catch unexpected cancellation at Google.Apis.Upload.ResumableUpload during uploading CSV file using method UploadCsvAsync, but we know that file uploaded successfully. So exception is not GoogleApiException type, what should we do in this case?

Our code something like that:
```
try
{
var pollSettings = BuildPollSetting(timeout);
var job = await client.UploadCsvAsync(datasetId, tableId, null, input, options, cancellationToken).ConfigureAwait(false);
var result = await job.PollUntilCompletedAsync(pollSettings: pollSettings, cancellationToken: cancellationToken).ConfigureAwait(false);
      result.ThrowOnError();
}
catch (GoogleApiException exc)
{
          await HandleGoogleException(exc, cancellationToken).ConfigureAwait(false);
}
```

Thanks

**Comment by jskeet** [comment]
I'm afraid I'm on vacation today, but I'll look at this first thing on Monday.

**Comment by jskeet** [comment]
Are you certain that it's during `UploadCsvAsync` rather than `PollUntilCompletedAsync`? Either way actually, it's always possible for the final request to be made just before the cancellation token times out, but at that point the server actually *has* all the data.

Are you observing that the exception is thrown at an expected time, in terms of your timeouts? If you're seeing a timeout much sooner than expected, that would be more unusual.

**Comment by jskeet** [comment]
(More information here would be really helpful in terms of working out what's going on. At the moment we don't know what your poll settings are like, or what cancellation token you're passing in.)

**Comment by UkrZilla** [comment]
Hi @jskeet 
1. We discovered that it happens when we reach full bandwidth of our Internet channel (100 Mbit/s) during 15 minutes and decided to urgently increase it
2. We use timeout=1h, and poll delay=5 seconds

I will inform you if the issue fixed

**Comment by jskeet** [comment]
Thanks. If you were saturating the network connection, it wouldn't entirely surprise me for the operation to time out. I'll wait for more details before doing any more investigation.

**Comment by UkrZilla** [comment]
Hi @jskeet 

Just increased bandwidth of our network connection and the issue fixed. Thanks

**Comment by jskeet** [comment]
Great - I'll close this issue in that case. Thanks very much for confirming!
