### ISSUE TITLE
Sample for retries with Cloud Spanner should use same SpannerConnection.

### ISSUE THREAD

**Issue by benwulfe** [GoogleCloudPlatform/google-cloud-dotnet#1906]
This is technically a sample bug.  When spanner throws a transient fault, you should really try to use the same session on subsequent retries as spanner gives higher priority to retries in high contention scenarios.  This can be achieved in the ADO.NET provider by using the same open connection (which reserves a single session for use).

So really the sample here:
https://cloud.google.com/spanner/docs/getting-started/csharp/#performing_retries_on_read-write_transactions

should demonstrate that. Instead of creating a new spanner connection each time, maybe we can create a helper method that takes in an open connection.

**Comment by jskeet** [comment]
Have filed https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/450 so it's in the right repo.
