### ISSUE TITLE
Datastore: Lookup key 0 never completes.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1916]
I created a key like this:
```cs
key_ = new KeyFactory(datastore.ProjectId, datastore.NamespaceId,
                ENTITY_KIND).CreateKey(0);
```

Later, I tried looking it up:
```cs
var task = datastore_.LookupAsync(key_);
```

That task never completes.  I expect it to complete and throw an exception, because key 0 is not a valid datastore key.

**Comment by jskeet** [comment]
Will look into reproducing tomorrow.

**Comment by jskeet** [comment]
Hmm... I couldn't reproduce this. I received an error very quickly:

> Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=InvalidArgument, Detail="Key path id is invalid. Must not be zero.")

Sample code (requires C# 7.1 for async main):

```csharp
using Google.Cloud.Datastore.V1;
using System;
using System.Threading.Tasks;

namespace Issue1916
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string projectId = "...";
            string namespaceId = "...";
            string kind = "...";
            var datastoreDb = DatastoreDb.Create(projectId, namespaceId);
            var key = datastoreDb.CreateKeyFactory(kind).CreateKey(0L);

            var result = await datastoreDb.LookupAsync(key);
            Console.WriteLine(result);
        }
    }
}
```

Could you try that code in your environment (after changing the project/namespace/kind appropriately)? We can then get a better idea of what's going on.

**Comment by jskeet** [comment]
@SurferJeffAtGoogle Ping for any updates? I'd like to close this if we can't reproduce it.

**Comment by SurferJeffAtGoogle** [comment]
Trying again....

**Comment by SurferJeffAtGoogle** [comment]
I can no longer reproduce.
