### ISSUE TITLE
Support connecting to Datastore emulator

### ISSUE THREAD

**Issue by Dafeesh** [GoogleCloudPlatform/google-cloud-dotnet#1923]
[Related issue in 'google-cloud-python' repo](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4840)

Support for connecting to the gcloud Datastore emulator is absolutely crucial for unit testing. Currently a whole host of issues arise when attempting to connect to the gcloud Datastore emulator. From what I understand this is because the gcloud emulator doesn't yet support gRPC(?).

**Comment by jskeet** [comment]
I'll have a look at this - I'm pretty sure it used to work, although you need to specify the endpoint and credentials explicitly, as per https://googlecloudplatform.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-emulators

I'll try that when I get a chance and report here.

**Comment by Dafeesh** [comment]
Thanks jskeet, I was finally able to get it working with the link you provided. An insecure channel was the answer.

I feel like this could be easier for a user to discover in the code base, bit it does look like you guys are working for a broader solution already which is good news.

**Comment by jskeet** [comment]
We definitely want to have a cleaner solution, but been I've been resisting doing this in dribs and drabs.

The good news is that if that code worked for you from C# then the emulator definitely *does* still support gRPC, and other languages should be able to connect to it to.

Closing this issue now, as there's no work required for the moment.
