### ISSUE TITLE
Determine when retry settings aren't generated for streaming call

### ISSUE THREAD

**Issue by evildour** [GoogleCloudPlatform/google-cloud-dotnet#1930]
Despite having idempotent retry settings [in the GAPIC config](https://github.com/googleapis/googleapis/blob/399ee9300491ddf376bf82dd8bc9c776f1d19840/google/bigtable/v2/bigtable_gapic.yaml#L104), the generator [does not generate the RetrySettings for BigtableClient's MutateRows](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/80a56f78d90be847cd5e286275889da43c0a6477/apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/BigtableServiceApiClient.cs#L186), so they have been manually written to [overwrite the default settings](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/80a56f78d90be847cd5e286275889da43c0a6477/apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/BigtableServiceApiClientPartial.cs#L33). Determine if this is a bug or intentional.

If the OnConstruction partial method is still needed for the client settings after this, update the generator to support this (as mocked [here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/pull/1924/commits/c235acd38f49ad3c9ec50c2262b819627f13e908)) and determine if that is the right way to specify the default retry settings.

cc @chrisdunelm

**Comment by jskeet** [comment]
Chris, could you have a look at this? It would be nice to remove the extra settings code as soon as we could.

Is it possibly related to MutateRows being a server-side streaming call?

**Comment by chrisdunelm** [comment]
Yes, this is because `MutateRows` is a server-streaming call.

**Comment by chrisdunelm** [comment]
In the general case, we cannot do retry when server-streaming. So hand-written in this special case is most likely the correct thing to do.

**Comment by evildour** [comment]
Ok thanks Chris, so I'll add the OnConstruction partial to the generator. @jskeet, do you still have questions/issues about how I'm replacing the settings here?

**Comment by jskeet** [comment]
Yes, I think we need to check what retry on a server streaming call will actually retry. Chris knows more about that than I do.

**Comment by evildour** [comment]
Actually, we should always be stripping out the retry settings and use them manually, but I see now that the way I have it setup, they're being sent down to the first call and only being stripped out for the retry calls. If I fix that up so we never pass down the retry settings to the underlying call, would you be ok with this approach?

**Comment by jskeet** [comment]
I think I see what you mean, but I'm not sure of the right approach. Anyone using the generated underlying client would still end up seeing the retry settings, which won't actually do what they expect. I wonder whether the right thing to do is leave the default call settings for the call, but then in the manual code derive some retry settings from whatever you're given. Does that make sense?

**Comment by evildour** [comment]
Well I don't think we want anyone to use the underlying client, but just in case, it may be best to not mess with the settings. So are you saying the retry settings shouldn't really be customizable though (directly)? I guess we could do that and just expose a separate property/option on the higher-level client to control that if we get any requests for it.

**Comment by jskeet** [comment]
I'm saying that changing the settings in the way that we're doing at the moment isn't ideal - it could easily cause confusion, and has indeed confused us.

Exposing a new property is probably the simplest option, yes.

**Comment by evildour** [comment]
Ok, sounds good. Do you think the `BigtableServiceApiSettings` is the right place for it even though it will be ignored if someone _does_ use the underlying client? I think it would be best to keep all the settings in one place.

**Comment by jskeet** [comment]
I'd be happy enough with that - @chrisdunelm does that sound okay to you?

**Comment by chrisdunelm** [comment]
SGTM
