### ISSUE TITLE
Log names in ASP.NET Core logging

### ISSUE THREAD

**Issue by henkmollema** [GoogleCloudPlatform/google-cloud-dotnet#1932]
We have integrated the `Google.Cloud.Diagnostics.AspNetCore` package into our project and noticed that the logger passes the "category name" (`ILogger<TCategory>`) of the logger instance to `LogTarget` which creates a `logName` property:

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/d0c81fd0756e69b664610b4438f4240f42d0f005/apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleLogger.cs#L74

This results in a `logName` property like:
```
projects/my-project/logs/Microsoft.AspNetCore.Hosting.Internal.WebHost
``` 

Such logging names makes filtering all the applications logs in the Log Viewer pretty difficult: 
![image](https://user-images.githubusercontent.com/1521207/36779600-d526ac68-1c70-11e8-9629-ab77bf2e8364.png)

Is it possible consolidate the logger name to just one, such as `projects/my-project/logs/aspnetcore`, and still keep the full logger name available in another property for fine-grained filtering?

I might be missing out on something, so please point it out if my reasoning isn't correct.

**Comment by henkmollema** [comment]
I would like to send a PR if any changes are necessary 😄

**Comment by iantalarico** [comment]
@henkmollema Always glad to hear about customers using our bits and engaging with us! :-)

Some info about the reason for the current design:
- The [convention](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#log-category) is to use the full class name (given how Stackdriver shows the logs I can understand this may be a little painful).
- If you create an ILogger manually you can see the category you created in the UI:
```
public SomeClass(ILoggerFactory factory)
{
  _logger = factory.CreateLogger("super-cool-log");
}
```

The current solution to this is the inverse of what you are suggesting.  You can add custom labels to all of your logs with the LoggerOptions:
https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/d0c81fd0756e69b664610b4438f4240f42d0f005/apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/LoggerOptions.cs#L66

You can then filter the logs with an advanced filter `resource.labels.some_label="aspnetcore"`

So it is technically possible to consolidate the logger name for all logs and then put the full name in the labels. However, I'm more inclined to stick with the current solution for the reasons above but I am open to discussion on the matter.  Thoughts?

**Comment by henkmollema** [comment]
@iantalarico kudos to you and the rest of team for providing such a great experience with Google services and .NET! 😄 

I understand that the design is to use full class names for the logger category. That's also the problem with your second point: I'd like to follow this convention and Microsoft follows it as well (e.g. `Microsoft.AspNetCore.Hosting.Internal.WebHost`). These Microsoft logger instances are out of my control so `factory.CreateLogger("super-cool-log")` is not possible.

Personally I think that your first option, putting full class name in a label and consolidate the log name, makes more sense and provides a better UX. Using the logger category as log name just doesn't really seem a good fit. This is also similar to Application Insights' logging implementation in ASP.NET Core.

**Comment by iantalarico** [comment]
@henkmollema That sounds reasonable.  Let me think on it some more.

@jskeet Does this sound reasonable to you?  Can we do this swap in a minor change or would this require a major version?

**Comment by jskeet** [comment]
Re versioning: it's a tricky change, much like the one I'm facing with Spanner at the moment. I think it would *probably* be okay, but it's a bit uncomfortable, certainly.

One thing to bear in mind is that you should (I think) be able to filter categories with wildcards - so you could use "Microsoft.AspNetCore.*" - you'd need to set up that filter by clicking on *one* of the names and then editing the resulting filter in the UI.

**Comment by henkmollema** [comment]
@jskeet thanks for the tip about filtering. I will check that out in a bit. However, that would mean I have to add a filter for each unique first part of a namespace. E.g. `Microsoft`, `MyCompany`, `ThirdPartyComponent`.

**Comment by iantalarico** [comment]
Code complete and will be in our next major release w/in the next month or so.

**Comment by henkmollema** [comment]
Great, thanks! 😄
