### ISSUE TITLE
ASP.NET Core logging request correlation

### ISSUE THREAD

**Issue by henkmollema** [GoogleCloudPlatform/google-cloud-dotnet#1933]
Currently the ASP.NET Core logger adds the request trace identifier to every log message, for example:
![image](https://user-images.githubusercontent.com/1521207/36781223-90ce6a4c-1c75-11e8-9ac8-d04eb4213865.png)

However, it's not possible to easily filter on this ID as it's embedded in the log message not available as a standalone property. Is it possible for the logger to add custom properties to log messages?

**Comment by henkmollema** [comment]
It would be nice if these log messages could be correlated to the nginx request log as well:
![image](https://user-images.githubusercontent.com/1521207/36781407-118c969a-1c76-11e8-8c1f-bdc54c20b292.png)

**Comment by iantalarico** [comment]
@henkmollema This is possible but I think we be fairly complicated and edge case.  The information the logger gets when logging isn't much and mostly just formats the message and adds it to the log entry.

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/d0c81fd0756e69b664610b4438f4240f42d0f005/apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleLogger.cs#L86

As for filtering on the RequestId I think in most cases the id is unique enough do a text search?  For example I just did this search:
![logs](https://user-images.githubusercontent.com/5264734/36801954-434da1a0-1c68-11e8-8159-04c77dfc7861.png)

**Comment by henkmollema** [comment]
Yeah, I figured a text search would help out. Thanks!

Are there any hooks to populate telemetry with additional data? For example, Application Insights has a concept of [telemetry intializers](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling#add-properties-itelemetryinitializer).

**Comment by henkmollema** [comment]
Thanks! I'll open an issue and think about a possible implementation. 👍
