### ISSUE TITLE
Pubsub keeps giving me the same messages despite my handler returning SubscriberClient.Reply.Ack

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1936]
I'm using the SubscriberClient API:
```cs
           subscriberClient_.StartAsync(
                (message, token) => ProcessOneMessage(message, token));
```
```cs
        async Task<SubscriberClient.Reply> ProcessOneMessage(
            PubsubMessage pubsubMessage, CancellationToken cancellationToken)
        {
            string text = pubsubMessage.Data.ToString(Encoding.UTF8);
            Message message;
            try
            {
                message = JsonConvert.DeserializeObject<Message>(text);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Bad message in subscription {0}\n{1}",
                    MySubscription, text);
                return SubscriberClient.Reply.Ack;
            }
            var moves = new Stack<GameBoard>();
            moves.Push(message.Board);
            bool isDumb = await idumb_.IsDumbAsync();
            while (moves.Count > 0)
            {
                if (cancellationToken.IsCancellationRequested)
                {
                    _logger.LogInformation(
                        "Cancellation requested in ProcessOneMessage().");
                    return SubscriberClient.Reply.Nack;
                }
                counter_.Increase(1);
                solveStateStore_.IncreaseExaminedBoardCount(
                    message.SolveRequestId, 1);
                GameBoard board = moves.Pop();
                if (!board.HasEmptyCell())
                {
                    // Solved!
                    await solveStateStore_.SetAsync(message.SolveRequestId,
                        board);
                    return SubscriberClient.Reply.Ack;
                }
                // Enumerate the next possible board states.
                if (isDumb)
                {
                    await Publish(message.SolveRequestId,
                        board.FillNextEmptyCell());
                }
                else foreach (var move in board.FillNextEmptyCell())
                {
                    moves.Push(move);
                }
            }
            return SubscriberClient.Reply.Ack;
        }
```
I've stepped through the code in a debugger, and I see my code returning SubscriberClient.Reply.Ack for literally millions of messages.  But then those same messages are once again delivered to ProcessOneMessage().

Current code is here:
https://github.com/SurferJeffAtGoogle/csharp-docs-samples/blob/sudoku/appengine/flexible/Sudokumb2.0/WebLib/Solver.cs

**Comment by chrisdunelm** [comment]
pubsub doesn't not guarantee only-once message delivery, it only guarantees once-or-more delivery.
However, having said that, it *usually* only delivers a message once.

In tests I have run, when I'm publishing millions of messages rapidly, there are always a some duplicate messages received.

Do you now what proportion of messages you're seeing duplicated? And are you getting two copies of these messages, or more than 2?

**Comment by chrisdunelm** [comment]
(This is being followed up internally)

**Comment by chrisdunelm** [comment]
Since this bug report, there have been server and client changes that should improve this; however, there is still no guarantee of once-only message delivery, so duplicate messages must be handled.
@SurferJeffAtGoogle Please can you try the latest client library, [v1.0.0-beta18](https://www.nuget.org/packages/Google.Cloud.PubSub.V1/1.0.0-beta18), and see if the situation is improved?

**Comment by chrisdunelm** [comment]
Closing for now. Please leave a comment if this is still being seen, and we can re-open.
