### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-dotnet#1939]
All the links from https://googlecloudplatform.github.io/google-cloud-dotnet/ are 404s.
And it looks like some CSS might be missing from the index page.

**Comment by jskeet** [comment]
Eek. Looking now.

**Comment by jskeet** [comment]
Now fixed :) We had docs/index.html as index.html from my last releasebuild. Our instructions need updating.

**Comment by iantalarico** [comment]
@jskeet The instructions need updating or the release script?  I'm happy to fix this as I'm fairly sure I broke it :)

**Comment by jskeet** [comment]
@iantalarico: Having checked, it's buildrelease.sh itself. This:

```sh
mv ../docs/output/assembled/index.html ./
```

should be

```sh
mv ../docs/output/assembled/index.html docs
```

That's all :)

**Comment by iantalarico** [comment]
@jskeet Yes just sent out PR #1940   :)
