### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS -- Is  this this ONLY way to auth for Datastore Client?

### ISSUE THREAD

**Issue by jboarman** [GoogleCloudPlatform/google-cloud-dotnet#1941]
I need to access Google Datastore from an Azure resource.  In this particular environment, all keys are maintained in the Key Vault.

However, it _seems_ like an actual _physical_ file is required to be referenced in an environment variable called `GOOGLE_APPLICATION_CREDENTIALS` to provide the path to the raw json text file.

Is there not a way to stream in the credentials by calling `GoogleCredential.FromStream(kvstream)...`?  I've used this pattern in other Google APIs, but I'm just not seeing how to do that with the .NET Datastore client.  Is this missing, or am I just missing something?

**Comment by jboarman** [comment]
I think I'm finding clues for how to provide the `GoogleCredential` directly, based on content from @jskeet:

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/f4fe517002f0636de6321c2c3e8e0c2ac99a1fcc/docs/root/faq.md

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/adhoc/Google.Cloud.ScopeTesting/Api.cs

I'll keep digging through this and see if I can make it work.

**Comment by jskeet** [comment]
This isn't as simple as we'd like it to be, but here are the instructions for how to provide credentials for gRPC-based APIs:
https://googlecloudplatform.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis

(Closing as for the moment, that documentation is all we can do. We are working on a new auth library, and when that's available we should be able to make this much simpler.)

**Comment by samgithub-duplicate** [comment]
Are there any updates on this? I have the same situation/requirement as jboarman.

Is there an approx timeline?

**Comment by jskeet** [comment]
No, there's no more progress on this, and I don't expect there to be for a while (as it will depend on a new auth library).

It's not a *huge* amount of code to write, as I showed you in #2191. Yes, we'd like it to be simpler, but for the moment you can put those 5 lines of code into a method you call appropriately.
