### ISSUE TITLE
Update Table Column value in BigQuery using BigQueryClient

### ISSUE THREAD

**Issue by Mayank050191** [GoogleCloudPlatform/google-cloud-dotnet#1959]
I am uploading my data on daily basis into Bigquery tables from c# application using BigQueryClient UploadJson Method. For few rows , columns value updates after some time duration which I need to update in Bigquery too. It seems Bigquery don't allow updating table column values from c# application. Is it possible to update table it using BigQueryClient ?

**Comment by jskeet** [comment]
As far as I'm aware, the only way of updating data in BigQuery is to use [DML](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-manipulation-language). Note that there are pretty strict [DML quota limits](https://cloud.google.com/bigquery/quotas#data_manipulation_language_statements). You should be able to execute the DML just like a regular query from `BigQueryClient`.

BigQuery is more designed as an append-only database. Have you considered creating new rows with a later timestamp, and just finding the latest rows with any particular identifier, as a way of effectively making it semi-updatable?

**Comment by jskeet** [comment]
@Mayank050191: Can you see any further changes you'd expect in the C# client library with respect to this issue? I'd like to close issues which don't require further action in this repository.

**Comment by Mayank050191** [comment]
@jskeet  Thanx for the suggestion to append new row with a updated date, is seems that is the only possible way to fulfill the requirement. We can close this issue.
