### ISSUE TITLE
Memory leak when creating many ImageAnnotatorClient instances

### ISSUE THREAD

**Issue by markwalsh-liverpool** [GoogleCloudPlatform/google-cloud-dotnet#1966]
Unsure what the root cause of the issue is but I noticed that creating a lot of **ImageAnnotatorClient** instances causes a consistent rise in unmanaged memory (first guess is - it's creating a lot of HttpClients):

![image](https://user-images.githubusercontent.com/1950856/37102862-c44026d0-2220-11e8-8d9d-bb901b032b19.png)

I was initialising a ImageAnnotatorClient per image and I am sending 50-100 images per second so I was quite quickly running out of memory.  Now, I just reuse the same ImageAnnotatorClient for each batch of images and I now see fairly consistent memory usage (sorry for the differing pictures, the bottom graph shows the unmanaged memory - and it's basically flatlined):

![image](https://user-images.githubusercontent.com/1950856/37103041-392c485c-2221-11e8-9283-5fa8dd4f0a18.png)

I was just wondering whether:

1. It's okay to reuse the client, several hundred times?
2. Whether I've exposed a bug (maybe something isn't being GC'd?)...

Is this possibly a duplicate/symptom of [this issue](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/1502) or perhaps [this issue](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/1060)

These are my installed packages:

```
  <package id="Google.Api.CommonProtos" version="1.2.0" targetFramework="net46" />
  <package id="Google.Api.Gax" version="2.2.1" targetFramework="net46" />
  <package id="Google.Api.Gax.Grpc" version="2.2.1" targetFramework="net46" />
  <package id="Google.Apis" version="1.32.2" targetFramework="net46" />
  <package id="Google.Apis.Auth" version="1.32.2" targetFramework="net46" />
  <package id="Google.Apis.Core" version="1.32.2" targetFramework="net46" />
  <package id="Google.Cloud.Vision.V1" version="1.1.0" targetFramework="net46" />
  <package id="Google.Protobuf" version="3.5.1" targetFramework="net46" />
  <package id="Grpc.Auth" version="1.10.0" targetFramework="net46" />
  <package id="Grpc.Core" version="1.10.0" targetFramework="net46" />
```

**Comment by jskeet** [comment]
It should be fine to either use the same `ImageAnnotatorClient` or to use a new one each time, assuming you just use `ImageAnnotatorClient.Create` - the same gRPC channel is pooled in that case. Creating a new client does require creating a bunch of objects, but they should be eligible for garbage collection anyway.

Are you able to use a different profiler to see what type of object is sticking around in your first situation?

**Comment by markwalsh-liverpool** [comment]
Hello Jon,

I was indeed creating the client using the static method.  This was the method before I started reusing the client:

`
public ImageAnnotatorClient Create()
        {
            var credential = GoogleCredential
                .FromFile(AppDomain.CurrentDomain.BaseDirectory + "google-cloud-vision-license.json")
                .CreateScoped(ImageAnnotatorClient.DefaultScopes);
            var channel = new Channel(ImageAnnotatorClient.DefaultEndpoint.ToString(),
                credential.ToChannelCredentials());
            var client = ImageAnnotatorClient.Create(channel);
            return client;
        }
`

I will run my profiler again and report back on what object is not being cleaned up

**Comment by jskeet** [comment]
Apologies, I wasn't clear enough - I'd meant (but definitely didn't write!) `ImageAnnotatorClient.Create()`, which would use the default credentials.

With that code, you're creating channels but never disposing of them... that's a bad idea in terms of creating more network connections than you need *and* potentially leaving garbage. I'd expect the garbage to be cleaned up eventually, but I wouldn't be surprised if it took longer.

For this situation I'd definitely create a single client.

**Comment by markwalsh-liverpool** [comment]
Okay, great that makes perfect sense.  In case anyone else is reading and finds they have the same problem I modified my code to be:

```
        private static ImageAnnotatorClient _client;
        public ImageAnnotatorClient Create()
        {
            if (_client == null)
            {
                // Untested code please do not modify, this is simply wrapping the creation of the ImageAnnotatorClient
                var credential = GoogleCredential
                    .FromFile(AppDomain.CurrentDomain.BaseDirectory + "google-cloud-vision-license.json")
                    .CreateScoped(ImageAnnotatorClient.DefaultScopes);
                var channel = new Channel(ImageAnnotatorClient.DefaultEndpoint.ToString(),
                    credential.ToChannelCredentials());
                _client = ImageAnnotatorClient.Create(channel);
            }

            return _client;
        }
```

Thanks Jon!

**Comment by evildour** [comment]
Note that if you're using this from multiple threads, you may want to use `Lazy<T>` instead:
```csharp
private static readonly Lazy<ImageAnnotatorClient> _client = new Lazy<ImageAnnotatorClient>(() => {
    var credential = GoogleCredential
        .FromFile(AppDomain.CurrentDomain.BaseDirectory + "google-cloud-vision-license.json")
        .CreateScoped(ImageAnnotatorClient.DefaultScopes);
    var channel = new Channel(ImageAnnotatorClient.DefaultEndpoint.ToString(),
        credential.ToChannelCredentials());
    return ImageAnnotatorClient.Create(channel);
});
```
