### ISSUE TITLE
Cloud Storage Client: Payload format not set when configuring notifications

### ISSUE THREAD

**Issue by thedmi** [GoogleCloudPlatform/google-cloud-dotnet#1992]
I'm trying to use the cloud storage client to create a notification that publishes changes to a PubSub topic [as described here](https://cloud.google.com/storage/docs/reporting-changes). 

```
var storageClient = StorageClient.Create(...);

await storageClient.CreateNotificationAsync(bucketName, 
    new Notification { PayloadFormat = "json", Topic = topic });
```

I'm confident the `bucketName` and `topic` are sensible values. The above call fails with the following exception:

```
Google.GoogleApiException : Google.Apis.Requests.RequestError
You must specify a payload format in the 'payload_format' field. [400]
Errors [
	Message[You must specify a payload format in the 'payload_format' field.] Location[ - ] Reason[required] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__34.MoveNext()
   at ...
```

However, the payload format is clearly set in the request, so I assume this is a bug. Note that the behavior is the same for the synchronous API.

I'm using `Google.Cloud.Storage.V1` version `2.1.0`.

**Comment by jskeet** [comment]
Ah, got it - this isn't a bug in the library, just an unfortunate disconnect between the `gsutil` command line and the API. The payload format should be `JSON_API_V1`, not `json`. I'll report a bug internally that the error message is misleading though, as you *have* specified a payload format, just not one the service recognizes.

For a complete C# example of notifications, see https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Storage.V1/index.html

I'll close this issue as there won't be any further changes in the client library for this; the server issue will be separate and internal.

**Comment by thedmi** [comment]
👍 indeed, it works with `"JSON_API_V1"`, thanks. Is there a reason why this isn't modeled as enum in the client library?

**Comment by jskeet** [comment]
Firstly, I'm really glad it's working for you, and I'm sorry you had to go through this piece of frustration first.

The fact that it's not modeled as an enum is an unfortunate implementation detail, I'm afraid. The Storage client library you're using is a wrapper over the generated client library, which is where the `Notification` type is defined. In many places, enums are represented as strings in the generated libraries.

What we could do in the future is create an overload accepting topic name and a payload enum value within Google.Cloud.Storage.V1, and translate that into the `Notification` type ourselves. As this is a reasonably new feature, I'd rather wait to see what other feedback we get first though, along with any other changes the service may be making to it.

I definitely acknowledge that it's far from ideal though.

**Comment by thedmi** [comment]
Thank you for the quick help, like this it didn't even start being frustrating yet :-)

I understand, thanks for the insights!
