### ISSUE TITLE
Firestore UpdateAsync with Nested Field Path (dot notation) Error

### ISSUE THREAD

**Issue by ryanmats** [GoogleCloudPlatform/google-cloud-dotnet#2006]
I'm creating a code sample to show how to update nested fields using dot notation (https://cloud.google.com/firestore/docs/manage-data/add-data#update_fields_in_nested_objects):

// Assume the document contains:
// {
//   name: "Frank",
//   favorites: { food: "Pizza", color: "Blue", subject: "recess" }
//   age: 12
// }

However, when creating my Dictionary<FieldPath, object> for updates to pass into the UpdateAsync function, I get [this error](https://gist.github.com/ryanmats/7efc444b9214dbab149d54f7fd446381).

[Program.cs file](https://gist.github.com/ryanmats/b075b76c2c854683be02a9c94a82f1e4) - run using 'dotnet run update-nested-fields YOUR_PROJECT_ID'.
[AddData.csproj file](https://gist.github.com/ryanmats/e0a8e512fa4acee0b51326ce3f0125f9)
[Field Path Documentation](http://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/api/Google.Cloud.Firestore.FieldPath.html)
[DocumentReference.UpdateAsync Documentation](http://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/api/Google.Cloud.Firestore.DocumentReference.html#Google_Cloud_Firestore_DocumentReference_UpdateAsync_System_Collections_Generic_IDictionary_Google_Cloud_Firestore_FieldPath_System_Object__Google_Cloud_Firestore_Precondition_System_Threading_CancellationToken_)

Should dot notation work for the FieldPath, or do I need to do something differently to update a nested field? Thanks!

**Comment by jskeet** [comment]
You're currently constructing a non-nested field path for a field that contains a dot.

If you update your code to

```csharp
{ new FieldPath("Favorites", "Color"), "Red" },
```

that works. Note that in the current non-released code, you'd be able to specify the field names as string instead, and at that point dot-separated names *would* work:

```csharp
Dictionary<string, object> updates = new Dictionary<string, object>
{
    { "Age", 13 },
    { "Favorites.Color", "Red" },
};
```

If you were updating a single field, you could do that without using a dictionary at all:

```csharp
WriteResult updateResult = await frankDocRef.UpdateAsync("Age", 13);
```

Would it be useful for me to do a beta03 release with the current code? I'd been hoping to get the Listen API implemented before doing so, but it's easy enough to do. Note that there are a number of breaking changes (renamed methods, for the most part) so we'd need to fix any samples too. I can help with that.

**Comment by ryanmats** [comment]
Thanks for the clarification.

I'm fine with holding off on releasing the dot-separated names feature until later.
