### ISSUE TITLE
Provide 'structure' log ability in Google.Cloud.Diagnostics.AspNetCore

### ISSUE THREAD

**Issue by marfenij** [GoogleCloudPlatform/google-cloud-dotnet#2019]
Microsoft.Extensions.Logging provide structure logging out of box [MS docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#log-message-template)
But this feature should be supported in **ILogger** implementation.

I see that google logs support several payloads for log entry, but for logging used simple textPayload which hold bare text. I found what **GoogleExceptionLogger** used jsonPayload to store information in more useful way.

So, I make little experiment:
rewrite **GoogleLogger.Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)** method:
```csharp
...
var jsonPayload = new Struct
{
    Fields = { { "Message", Value.ForString(message) } }
};

if (GoogleLoggerScope.Current != null)
{
    jsonPayload.Fields.Add("Scope", Value.ForString(GoogleLoggerScope.Current.ToString()));
}

if (state is IEnumerable<KeyValuePair<string, object>> structure)
{
    var properties = new Struct();
    foreach (var pair in structure)
    {
        if (pair.Key.Equals(OriginalFormatKeyValue))
        {
            continue;
        }

        properties.Fields.Add(pair.Key, Value.ForString(pair.Value.ToString()));
    }

    if (properties.Fields.Count > 0)
    {
        jsonPayload.Fields.Add("Properties", Value.ForStruct(properties));
    }
}

if (eventId.Id != 0 || eventId.Name != null)
{
    var eventStruct = new Struct();
    if (eventId.Id != 0)
    {
        eventStruct.Fields.Add("Id", Value.ForNumber(eventId.Id));
    }

    if (!string.IsNullOrEmpty(eventId.Name))
    {
        eventStruct.Fields.Add("Name", Value.ForString(eventId.Name));
    }

    jsonPayload.Fields.Add("EventId", Value.ForStruct(eventStruct));
}

LogEntry entry = new LogEntry
{
    Resource = _loggerOptions.MonitoredResource,
    LogName = _logName,
    Severity = logLevel.ToLogSeverity(),
    Timestamp = Timestamp.FromDateTime(_clock.GetCurrentDateTimeUtc()),
    JsonPayload = jsonPayload,
    Labels = { _loggerOptions.Labels },
    Trace = GetTraceName() ?? "",
};
...
```
and that send log w/o any error to GCP (also put eventId information).

Also I have configured out sink to BigQuery, and jsonPayload fit to table perfectly as record.

**Comment by iantalarico** [comment]
@marfenij Thanks for bringing this up. 

I think moving to a JSON payload would be beneficial.  However I am unsure about the check on a state being `IEnumerable<KeyValuePair<string, object>> structure`.  This seems like a very specific corner case.

**Comment by marfenij** [comment]
Hi @iantalarico this structure is more abstract than [FormattedLogValues](https://github.com/aspnet/Logging/blob/release/2.0/src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs)
cause I think people like use extensions to log something [LoggerExtensions](https://github.com/aspnet/Logging/blob/release/2.0/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs) 👍 

if not - they got same string message (but wrapped in json)

**Comment by iantalarico** [comment]
@marfenij I see, thanks for extra context!

I'll see what I can do here.

**Comment by marfenij** [comment]
@iantalarico thank a lot.

P.S Where I can subscribe to check when this release are roll out ?

**Comment by iantalarico** [comment]
@marfenij You can watch this [repo's releases](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/releases).

**Comment by marfenij** [comment]
leave for future ...
this is atom feed for subscribe https://github.com/GoogleCloudPlatform/google-cloud-dotnet/releases.atom
