### ISSUE TITLE
Add SourceReference to Error Reporting Reports if it exists.

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#2028]

**Comment by iantalarico** [comment]
cc: @SurferJeffAtGoogle

**Comment by iantalarico** [comment]
@jskeet I would like to add this feature to the diagnostics library but it looks like our error reporting library (v1beta1) is either out of date or missing a field[ `sourceReferences`](https://cloud.google.com/error-reporting/reference/rest/v1beta1/ErrorContext#sourcereference).  Can we update the library?  

As a note I only want the updated error reporting library for testing the error reports are correct.

**Comment by jskeet** [comment]
We can update the library if necessary, but I don't see it in [the proto](https://github.com/googleapis/googleapis/blob/29ceea5759b4d405365ec5716f3e016fef46fb33/google/devtools/clouderrorreporting/v1beta1/common.proto#L97) :(

**Comment by iantalarico** [comment]
Closing this issue for now.  Will come back if this ever is added.
