### ISSUE TITLE
[Google.Cloud.PubSub.V1] How to publish message with attributes

### ISSUE THREAD

**Issue by chikien276** [GoogleCloudPlatform/google-cloud-dotnet#2041]
My current version is : `1.0.0-beta16`
I've been searching every where but still dont know how to.
There is an attr in `PubsubMessage`
```public MapField<string, string> Attributes { get; }```
but as you can see, it has private set.

**Comment by jskeet** [comment]
Yes, you can't replace the map completely - but you can modify it. Typically you'd do this in an object initializer with indexers, e.g.

```csharp
var message = new PubsubMessage
{
    Attributes = 
    {
        ["x"] = "y",
        ["key"] = "value"
    }
};
```

Or prior to C# 6 using a collection initializer:

```csharp
var message = new PubsubMessage
{
    Attributes = 
    {
        { "x", "y" },
        { "key", "value" }
    }
};
```


The same approach is used for repeated fields, where you'd just use a collection initializer:

```csharp
var message = new SomeMessageType
{
    RepeatedField = { "first", "second", "third" }
}
```

I'll close this issue as there's no required change in the libraries, but of course, feel free to ask more questions.
