### ISSUE TITLE
Xamarin Support

### ISSUE THREAD

**Issue by StefanNenchev** [GoogleCloudPlatform/google-cloud-dotnet#2045]
Hello team,

I am not sure whether this is the correct place to ask this, however, I am currently evaluating the different services in Xamarin and came across different issues and unexpected errors. I want to know whether Xamarin is supported so I can investigate the behavior in more details at my end.

The following issue states that the technology is not fully supported for Storage:
https://github.com/google/google-api-dotnet-client/issues/1162

Is this the official statement with all your services or it is just the object storage.

Thanks

**Comment by jskeet** [comment]
No, Xamarin isn't supported right now. We would like to have as broad support as possible, but supporting mobile platforms can present various challenges, particularly in the authorization space where browser interaction is required.
