### ISSUE TITLE
[FireStore]if there is any authentication method?

### ISSUE THREAD

**Issue by mhh12121** [GoogleCloudPlatform/google-cloud-dotnet#2046]
Like login, logout, I can't find it in documentation.

**Comment by jskeet** [comment]
No, the underlying API doesn't have anything like that as far as I'm aware. This library is for storage specifically, and would typically authenticate using a service account rather than with user credentials - I'd expect a potentially different service to perform general Firebase authentication.

**Comment by mhh12121** [comment]
Thank you! So it means that if I set some authentication rules in FireStore, I can't access it anymore from C#?

**Comment by jskeet** [comment]
Not that I'm aware of, I'm afraid. I'll ask a member of the Firestore team to chime in though.

**Comment by schmidt-sebastian** [comment]
The Server SDKs use Service Account based authentication. The credentials get created when you initialize the Firestore GCloud client. In a lot of Google environments, this is done automatically for you - and if you want to switch Service Accounts, you have to create a new instance of Firestore with manual authentication and stop using the old one. There is no explicit concept of login and logout.

Firebase Rules don't apply to these Service Accounts. They apply to the Mobile SDKs (for iOS, Android and the Web), which use Firebase App and Firebase Auth to handle third-party authentication. Firebase Auth allows you to change the signed in user over its lifetime: https://firebase.google.com/docs/reference/js/firebase.auth.Auth

So, if you specify a "no one can read" rule in the Firebase Console (or via the CLI), then you will be able to read from the Server SDKs, but not via the Mobile SDKs.

**Comment by mhh12121** [comment]
Nice! I tried it before and it did work perfectly like what you said!!! Thank you very much!!!
