### ISSUE TITLE
Is Xamarin supported

### ISSUE THREAD

**Issue by StefanNenchev** [GoogleCloudPlatform/google-cloud-dotnet#2047]
Is Xamarin supported by all services that have .NET implementation?

**Comment by jskeet** [comment]
I don't understand what you mean by "all services that have .NET implementation"... but one of the biggest problems is performing user-based auth in an idiomatic way, and we *don't* have Xamarin support for that at the moment. Additionally, APIs within this repo that rely on gRPC also need a native binary library for gRPC - which again, isn't supported everywhere that Xamarin is.

For the moment, our broad statement is that we don't support Xamarin. We'd like to eventually, and it's possible that for *some* libraries on *some* flavours of Xamarin it will work, but you're basically working in an unsupported environment at that point, and if you run into problems we're unlikely to want to spend time trying to investigate them.

**Comment by StefanNenchev** [comment]
Thank you for the answer, Jon. Have a great rest of the week.
