### ISSUE TITLE
Unwrap AggregateExceptions in generated code where possible

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-dotnet#206]
Similar to #121, for generated code (e.g. pubsub).
E.g. When calling PublisherClient.Create() without valid credentials an AggregateException is thrown, it should be unwrapped to the inner InvalidOperationException.

**Comment by jskeet** [comment]
Is this actually a matter of fixing `ChannelPool.GetChannel`? (It's handy if we can fix this in GAX rather than needing to change the generated code.)

**Comment by jskeet** [comment]
(It will only be useful when we update dependencies, but that's fine.)
