### ISSUE TITLE
grpc_csharp_ext.x64.dll error after install Google.Cloud.Vision.V1 Nuget Package

### ISSUE THREAD

**Issue by matheusborguete** [GoogleCloudPlatform/google-cloud-dotnet#2061]
I'm going to use the Google.Cloud.Vision.V1 1.1.0 package in my project but after install it and try to build my project I'm getting the following problem: Could not load file or assembly 'file:///C:LMS\bin\grpccsharpext.x64.dll' or one of its dependencies. The module was expected to contain an assembly manifest.

Details: VS 2017, W10 x64, .Net MVC 4.5, building to Any CPU.

Is there anything I can do to solve this problem?

Thank you in advance!

**Comment by jskeet** [comment]
Do you have any other dependencies on Google APIs? (In particular, which version of gRPC are you depending on? 

In particular, Google.Cloud.Vision.V1 version 1.1.0 depends on Google.Api.Gax.Grpc version 2.2.1, which depends on Grpc.Core 1.7.1.

Have you tried explicitly building for x86 or for x64? Maybe that's the problem.

**Comment by matheusborguete** [comment]
In a old version I've already used the Google packages for create a short link, but after one week I decided to remove these packages because Google turned down the support. Actually, I'm not sure which package is responsible for this dll, but I'm gonna list all packages which contains Grpc in the name: 
- Grpc.Core V1.10.1
-Grpc.Auth V1.10.1
-Google.Api.Gax.Grpc V2.3.0

In order to install the Google.Cloud.Vision.V1 package, I allowed to install all the dependecies automatically...

I've already tried build in all the three ways, x86, x64 and Any CPU

**Comment by jskeet** [comment]
Well Vision version 1.1.0 shouldn't have installed that dependency. Did you add the dependency on `Grpc.Core` directly? I'd still expect it all to work, but it's possible that the assembly binding redirects have become confused. Can you check what those look like? (The exact nature of the error may then be due to the file being a native library rather than an assembly.)

I can try to reproduce this tomorrow, but not right now.

**Comment by matheusborguete** [comment]
No, I just added the Google.Cloud.Vision.V1 package and it installed all the others dependecies. 
Of course, I'm gonna paste here all the dependecies of app.config:

`<dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>`
`<dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.32.2.0" newVersion="1.32.2.0" />
      </dependentAssembly>`
`<dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth.PlatformServices" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.32.2.0" newVersion="1.32.2.0" />
      </dependentAssembly>`
`<dependentAssembly>
        <assemblyIdentity name="Google.Protobuf" publicKeyToken="a7d26565bac4d604" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.1.0" newVersion="3.5.1.0" />
      </dependentAssembly>`
`<dependentAssembly>
        <assemblyIdentity name="Google.Api.CommonProtos" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.0.0" newVersion="1.2.0.0" />
      </dependentAssembly>`
`<dependentAssembly>
        <assemblyIdentity name="Google.Api.Gax.Grpc" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.3.0.0" newVersion="2.3.0.0" />
      </dependentAssembly>`
`<dependentAssembly>
        <assemblyIdentity name="Google.Api.Gax" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.3.0.0" newVersion="2.3.0.0" />
      </dependentAssembly>`

I don't know if it changes something but in my solution, I've my Web Project and I created another one just for this API so when I add the dependece and build it I get the error. I also already tried to add the package directly in my project but still doesn't work.
Observation: thanks for your attention.

**Comment by jskeet** [comment]
I've just tried this from scratch, and it worked fine first time. Steps:

- Open Visual Studio
- Create a new solution containing a new ASP.NET project using MVC 5
- Run it to check it works
- From "Manage NuGet packages" install Google.Cloud.Vision.V1 version 1.1.0
- Add code in the `HomeController.About()` method to use the Vision API to detect landmarks
- Run it - it works.

At that point, my packages.config contains:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net45" />
  <package id="bootstrap" version="3.0.0" targetFramework="net45" />
  <package id="Google.Api.CommonProtos" version="1.1.0" targetFramework="net45" />
  <package id="Google.Api.Gax" version="2.2.1" targetFramework="net45" />
  <package id="Google.Api.Gax.Grpc" version="2.2.1" targetFramework="net45" />
  <package id="Google.Apis" version="1.30.0" targetFramework="net45" />
  <package id="Google.Apis.Auth" version="1.30.0" targetFramework="net45" />
  <package id="Google.Apis.Core" version="1.30.0" targetFramework="net45" />
  <package id="Google.Cloud.Vision.V1" version="1.1.0" targetFramework="net45" />
  <package id="Google.Protobuf" version="3.3.0" targetFramework="net45" />
  <package id="Grpc.Auth" version="1.7.0" targetFramework="net45" />
  <package id="Grpc.Core" version="1.7.1" targetFramework="net45" />
  <package id="jQuery" version="1.10.2" targetFramework="net45" />
  <package id="jQuery.Validation" version="1.11.1" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.0.6" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.8" targetFramework="net45" />
  <package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.Net.Compilers" version="1.3.2" targetFramework="net45" developmentDependency="true" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Modernizr" version="2.6.2" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net45" />
  <package id="Respond" version="1.2.0" targetFramework="net45" />
  <package id="System.Interactive.Async" version="3.1.1" targetFramework="net45" />
  <package id="System.Net.Http" version="4.3.1" targetFramework="net45" />
  <package id="WebGrease" version="1.5.2" targetFramework="net45" />
</packages>
```

- The "Manage NuGet packages" UI shows 30 packages that can be updated.
- Update Google.Api.Gax.Grpc to 2.3.0 (so Grpc.Core is now 1.10.0)
- Run again - it still works

So I'm not sure what's going on with your project. Can I check that `LMS\bin\grpccsharpext.x64.dll` is where you'd expect to find the gRPC library? Is that your project path?

**Comment by jskeet** [comment]
I don't know whether that's the right path, because I don't know whether LMS is your project. If it's picking it up from some completely other application and happens to be in your path, that would be a different matter.

I think the best thing now is for you to compare the packages that project with the one where it fails. We need to work out where the difference is.

**Comment by matheusborguete** [comment]
Ok... So we have the LMS project and the API project in the same solution and the Test Solution... (The difference between the API's package and the Test's package will be in the last code block)
The packages in the LMS project are:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net45" />
  <package id="Boleto.Net" version="2.1.0.141" targetFramework="net45" />
  <package id="CommonServiceLocator" version="1.3" targetFramework="net45" />
  <package id="DataAnnotationsExtensions" version="1.1.0.0" targetFramework="net45" />
  <package id="DataAnnotationsExtensions.MVC3" version="1.1.0.0" targetFramework="net45" />
  <package id="elmah.corelibrary" version="1.2" targetFramework="net45" />
  <package id="Elmah.Mvc" version="2.1.2" targetFramework="net45" />
  <package id="Facebook" version="7.0.6" targetFramework="net45" />
  <package id="Fluentx" version="2.0.4" targetFramework="net45" />
  <package id="Fluentx.Mvc" version="1.0.4" targetFramework="net45" />
  <package id="GAtec.GDFNitro.Business" version="1.0.9" targetFramework="net45" />
  <package id="GAtec.GDFNitro.Domain" version="1.0.9" targetFramework="net45" />
  <package id="GAtec.GDFNitro.Rest" version="1.0.9" targetFramework="net45" />
  <package id="GAtec.GDFNitro.Util" version="1.0.9" targetFramework="net45" />
  <package id="GAtec.Reporting.Resources" version="1.0.0" targetFramework="net45" />
  <package id="GAtec.Reporting.ViewModel" version="1.0.0" targetFramework="net45" />
  <package id="HtmlAgilityPack" version="1.4.9" targetFramework="net45" />
  <package id="Iesi.Collections" version="3.2.0.4000" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.0.6" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.Azure.KeyVault.Core" version="1.0.0" targetFramework="net45" />
  <package id="Microsoft.Data.Edm" version="5.7.0" targetFramework="net45" />
  <package id="Microsoft.Data.OData" version="5.7.0" targetFramework="net45" />
  <package id="Microsoft.Data.Services.Client" version="5.7.0" targetFramework="net45" />
  <package id="Microsoft.Identity.Model.Extensions" version="2.0.1459.0" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Microsoft.Web.RedisSessionStateProvider" version="2.2.6" targetFramework="net45" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="2.0.3" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net45" />
  <package id="NHibernate" version="3.4.1.4000" targetFramework="net45" />
  <package id="NHibernate.Caches.SysCache" version="3.3.3.4000" targetFramework="net45" />
  <package id="NHibernateProfiler.Appender" version="3.0.3091.0" targetFramework="net45" />
  <package id="NPOI" version="2.1.3.1" targetFramework="net45" />
  <package id="OpenHtmlToPdf" version="1.12.0.0" targetFramework="net45" />
  <package id="PushSharp" version="3.0.1.0" targetFramework="net45" />
  <package id="RestSharp" version="105.2.3" targetFramework="net45" />
  <package id="StackExchange.Redis.StrongName" version="1.2.6" targetFramework="net45" />
  <package id="System.Net.Http" version="4.3.1" targetFramework="net45" />
  <package id="System.Spatial" version="5.7.0" targetFramework="net45" />
  <package id="Telerik.Reporting" version="1.0.0" targetFramework="net45" />
  <package id="Unity" version="4.0.1" targetFramework="net45" />
  <package id="Unity.Interception" version="4.0.1" targetFramework="net45" />
  <package id="Unity.Mvc" version="4.0.1" targetFramework="net45" />
  <package id="WebActivator" version="1.2.0.0" targetFramework="net45" />
  <package id="WebActivatorEx" version="2.2.0" targetFramework="net45" />
  <package id="WebGrease" version="1.5.2" targetFramework="net45" />
  <package id="WindowsAzure.Storage" version="7.1.2" targetFramework="net45" />
</packages>
```

and the packages in API project are:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Google.Api.CommonProtos" version="1.2.0" targetFramework="net45" />
  <package id="Google.Api.Gax" version="2.3.0" targetFramework="net45" />
  <package id="Google.Api.Gax.Grpc" version="2.3.0" targetFramework="net45" />
  <package id="Google.Apis" version="1.32.2" targetFramework="net45" />
  <package id="Google.Apis.Auth" version="1.32.2" targetFramework="net45" />
  <package id="Google.Apis.Core" version="1.32.2" targetFramework="net45" />
  <package id="Google.Cloud.Vision.V1" version="1.1.0" targetFramework="net45" />
  <package id="Google.Protobuf" version="3.5.1" targetFramework="net45" />
  <package id="Grpc.Auth" version="1.10.1" targetFramework="net45" />
  <package id="Grpc.Core" version="1.10.1" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net45" />
  <package id="System.Interactive.Async" version="3.1.1" targetFramework="net45" />
  <package id="System.Net.Http" version="4.3.3" targetFramework="net45" />
</packages>
```
and the packages from Test Solution
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net45" />
  <package id="bootstrap" version="3.0.0" targetFramework="net45" />
  <package id="Google.Api.CommonProtos" version="1.2.0" targetFramework="net45" />
  <package id="Google.Api.Gax" version="2.3.0" targetFramework="net45" />
  <package id="Google.Api.Gax.Grpc" version="2.3.0" targetFramework="net45" />
  <package id="Google.Apis" version="1.32.2" targetFramework="net45" />
  <package id="Google.Apis.Auth" version="1.32.2" targetFramework="net45" />
  <package id="Google.Apis.Core" version="1.32.2" targetFramework="net45" />
  <package id="Google.Cloud.Vision.V1" version="1.1.0" targetFramework="net45" />
  <package id="Google.Protobuf" version="3.5.1" targetFramework="net45" />
  <package id="Grpc.Auth" version="1.10.0" targetFramework="net45" />
  <package id="Grpc.Core" version="1.10.0" targetFramework="net45" />
  <package id="jQuery" version="1.10.2" targetFramework="net45" />
  <package id="jQuery.Validation" version="1.11.1" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.0.6" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.7" targetFramework="net45" />
  <package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.Net.Compilers" version="1.3.2" targetFramework="net45" developmentDependency="true" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Modernizr" version="2.6.2" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net45" />
  <package id="Respond" version="1.2.0" targetFramework="net45" />
  <package id="System.Interactive.Async" version="3.1.1" targetFramework="net45" />
  <package id="System.Net.Http" version="4.3.1" targetFramework="net45" />
  <package id="WebGrease" version="1.5.2" targetFramework="net45" />
</packages>
```
and the difference between the API's package and the Test's package are(the packages with different version will remain at the code block):
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net45" />
  <package id="bootstrap" version="3.0.0" targetFramework="net45" />
  <package id="Google.Apis" version="1.32.2" targetFramework="net45" />
  <package id="Grpc.Auth" version="1.10.0" targetFramework="net45" />
  <package id="Grpc.Core" version="1.10.0" targetFramework="net45" />
  <package id="jQuery" version="1.10.2" targetFramework="net45" />
  <package id="jQuery.Validation" version="1.11.1" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.0.6" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.2.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.7" targetFramework="net45" />
  <package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.Net.Compilers" version="1.3.2" targetFramework="net45" developmentDependency="true" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Modernizr" version="2.6.2" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net45" />
  <package id="Respond" version="1.2.0" targetFramework="net45" />
  <package id="System.Interactive.Async" version="3.1.1" targetFramework="net45" />
  <package id="System.Net.Http" version="4.3.1" targetFramework="net45" />
  <package id="WebGrease" version="1.5.2" targetFramework="net45" />
</packages>
```

**Comment by jskeet** [comment]
The LMS project doesn't appear to refer to gRPC at all, so I'm not sure why it's got the DLL there. I'm afraid I don't understand enough about the multiple projects and solutions you've got going on to really understand your comments. Are you able to reproduce this in a simpler environment, with just *one* solution, and either one or two projects? Have you tried updating all projects to use the same version of gRPC? (So either both using 1.10.0 or both using 1.10.1)

**Comment by matheusborguete** [comment]
In fact I believe it refers to gRPC but to a different version.  

I'll try to explain: I've two solutions, the first one is the LMS Solution and the second one is the Test Solution which I created only to do the test you asked me... 
At the LMS solution I've a lot of projects... Among then I've the LMS.WEB project and the Google.API project. The problem occurs when the LMS.WEB project references the Google.API project.
I tried to reproduce the error in a simple environment (the Test Solution) but I wasn't able to reproduce the same error.

I've already tried to consolidate all the packages in my solution...

**Comment by jskeet** [comment]
Hmm. So when you were trying to reproduce in the test solution, did you try with two projects there as well?

Have you tried cleaning the LMS solution completely, removing the bin and obj files? I wonder whether you had a stale DLL there.

**Comment by matheusborguete** [comment]
Creating two projects in the Test Solution and adding the reference didn't generate any error...

**Comment by jskeet** [comment]
Okay - in that case I'm afraid I won't be able to help until you've worked out the difference between your real solution and your test solution. You might want to try stripping all the Google-related references from both projects (and the assembly bindings) and then re-adding them.

**Comment by matheusborguete** [comment]
Ok, thank you so much for your patience and help! Any news I post here!

**Comment by matheusborguete** [comment]
Like I couldn't find any resolution for this problem I decided to create a new solution, only with my API and then I imported the API dll in my main solution(LMS Solution). Thank you!

**Comment by matheusborguete** [comment]
Probably is something really specific but I'm really thankful for your help!

**Comment by izverev86** [comment]
@matheusborguete remove package "WebActivator" from your references, and it should work

**Comment by vbisbest** [comment]
I just hit the same issue.  Using a Xamarin cross platform project and installing the Vision api nuget package.  Any other info on this?

**Comment by jskeet** [comment]
@vbisbest: Xamarin is not a supported platform for the Google Cloud Client Libraries right now.

**Comment by sdg002** [comment]
I just had the same issue .  My environment is a simple .NET Framework 4.6 Console EXE which calls a .NET Standard 2.0 assembly that in turn does "part of speech tagging" using the  "Google.Cloud.Language.v1"

I have listed the steps here to repro the problem and also how I worked around.  Please note that I faced 3 challenges sequentially.  I wonder what am I doing wrong. I think the mix of .NET Framework might be complicating matters. However, for my environment, we are still dependent on some .NET Framework only libraries so we cannot move to .NET 

**Steps to reproduce the issue**

1. Create Console EXE "MainConsoleApp"(.NET Framework 4.6)
2. Create Class library "DoSomeNLP"(.NET Standard 2.0)
3. Add Nuget reference to "Google.Cloud.Language.V1 1.2.0"
1. Added <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> to PropertyGroup of DoSomeNLP.csproj
2. Write some code to do Part of Speech tagging
3. Add a class file in "DoSomeNLP"
4. Compile and run the EXE
5. 

**Problem 1**
The EXE threw this exception
`System.IO.FileNotFoundException: Could not load file or assembly 'Google.Cloud.Language.V1, Version=1.2.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0' or one of
`
**Solution to Problem 1**
Added  CopyLocalLockFileAssemblies attribute to the csproj of the class library "DoSomeNLP". This ensured that all the assemblies are copied over to the Bin\Debug of the Console EXE

**Problem 2**
```
System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: C:\TrueTemp\GoogleNLPIssue\MainConsoleApp1\bin\Debug\grpc_csharp_ext.x64.dll,C:\TrueTemp\GoogleNLPIssue\MainConsoleApp1\bin\Debug\runtimes/win/native\grpc_csharp_ext.x64.dll,C:\TrueTemp\GoogleNLPIssue\MainConsoleApp1\bin\Debug\../..\runtimes/win/native\grpc_csharp_ext.x64.dll
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)


```
**Solution to Problem 2**

1. I examined the list of Dependencies for the project DoSomeNLP
2. It was referencing Grpc.Core (1.18.0)
3. Browse to the Nuget packages folder located under %USERPROFILE%\ .nuget and search for "grpc_csharp_ext.x64.dll". 
1. Copy this DLL to the .NET Standard class library project DoSomeNLP and Copy to output Directory=Always

**Problem 3**
```
System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.GetEntryAssembly()
   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment..ctor()

```
**Solution to problem 3**
Added the following nuget package to MainConsoleApp
`Install-Package System.Reflection.TypeExtensions -Version 4.0.0`

**Comment by jskeet** [comment]
@sdg002: Could you create anew issue for this? Even though it sounds similar, I suspect the underlying cause will be slightly different. (If you could clarify what you mean by "Added true to PropertyGroup of DoSomeNLP.csproj" that would be helpful too.) I'll try to reproduce the problem. I believe I have simpler solutions to both of these, but the third problem is definitely one I haven't encountered before.

**Comment by sdg002** [comment]
@jskeet  It was meant to be CopyLocalLockFileAssemblies =true in the "PropertyGroup" section of the .csproj file. I  have created a new issue. I think the angular brackets destroyed some of the formatting.
https://github.com/googleapis/google-cloud-dotnet/issues/3044
