### ISSUE TITLE
IIS Integration (UseIISIntegration) is not working when published

### ISSUE THREAD

**Issue by samgithub-duplicate** [GoogleCloudPlatform/google-cloud-dotnet#2067]
I am using windows=server-2016-1 with HttpRedirection installed.  I have configured a web.config to redirect ALL traffic to https.  This is not working.  Hopefully, this is the right platform for submitting this issue.  My web.config has these rewrite rules:

       <rewrite>
      <rules>
        <rule name="Redirect to HTTPS" enabled="true"
              stopProcessing="true">
          <match url="(.*)" />
          <conditions>
            <add input="{HTTPS}" pattern="^OFF$" />
          </conditions>
          <action type="Redirect"
                 url="https://{HTTP_HOST}/{R:1}"
                  redirectType="SeeOther" />
        </rule>
      </rules>
    </rewrite>

**Comment by samgithub-duplicate** [comment]
I am publishing to the Google Cloud Platform using the Google Cloud Client Libraries. From your response, I imagine that it's probably more of a GCP issue.  I just didn't know where to turn so I wrongfully assumed this platform was somehow involved with that.  Do you happen to know what "forum", if any, handles perceived issues with published AspnetCore on GCP?

Sorry for the inconvenience.


Thanks

Sam

________________________________

**Comment by jskeet** [comment]
Do you mean using the Visual Studio Google Cloud Extension? I'm still not quite sure how you're deploying. If it *is* the VS extension, my colleagues may be in a better position to help you. It may well be to do with GCP rather than anything in our team, but they may know more.

When you say it doesn't work, could you give more details about what does happen vs what you expected to happen?

**Comment by samgithub-duplicate** [comment]
Hi John:

What I expected to happen is that after a successful deployment using the IIS Configuration (in web.config) shown at the end of this email, ALL traffic will be directed to  HTTPS.


Examples:

a) mydomain.com  --->   https.mydomain.com

b) http://mydomain.con  ---> https://mydomain.com

c) http://mydomain.com/page1.html  --> https://mydomain.com/page1.html


Instead, what happens is that the results of (a, b, c) all remain at HTTP:............

Note: This is a commonly used configuration to allow IIS to rewrite the URL to HTTPS.

I suspect it's a GCP problem in that the GCP is not honoring the setting in web.config (unless,  publishing with Google Cloud Tools to Visual Studio is excluding "web.config"  --- perhaps?)

The IIS rewrite rule I am using is:

    <rewrite>
      <rules>
        <rule name="Redirect to HTTPS"
              stopProcessing="true">
          <match url="(.*)" />
          <conditions>
            <add input="{HTTPS}" pattern="^OFF$" />
          </conditions>
          <action type="Redirect"
                  url="https://{HTTP_HOST}/{R:1}"
                  redirectType="SeeOther" />
        </rule>
      </rules>
    </rewrite>



________________________________

**Comment by jskeet** [comment]
I doubt that the Visual Studio extension is looking at web.config at all. However, I'd suggest moving this issue to https://github.com/GoogleCloudPlatform/google-cloud-visualstudio as that's at least closer, and my colleagues there have more experience of ASP.NET deployments.

Before you report it, I suggest remoting into the GCP machine and looking at everything relevant on the box - check that it really does have the relevant rewriting extension installed, and that the web.config is exactly correct. (You haven't shown the ancestor elements of the `rewrite` element here - if those are wrong, that would definitely explain it.) Include all of that information in the issue.

**Comment by iantalarico** [comment]
@samgithub-duplicate I'm going to close this in favor of https://github.com/GoogleCloudPlatform/google-cloud-visualstudio/issues/937.  Is that okay?
