### ISSUE TITLE
API documentation needs prettifying

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#207]
Currently it wraps in an ugly way, and it also looks different to all the other gcloud API docs. We're using the plain docfx default template at the moment, but it's not clear whether the solution is to build our own template or move the API doc generation to something else.

Chris is looking into this.

**Comment by chrsmith** [comment]
Trying to track down the common template, etc. From JJG:

> It's an angular app that renders a common format for docs across languages -- basically accepts a JSON doc set with all the documentation parsed, and spits out a pretty page.
> 
> Documentation of all sorts is here: https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/site
> 
> Note that in the long run the goal is to have c.g.c consume this common doc format (or ask us to change it) so that docs can live there rather than github.io.

I'll try to create the page for PowerShell, and then the more ambitious project of doing that for C#.

**Comment by jskeet** [comment]
Would love it to be prettier, but I'm not the right person to do this work as both my design and HTML/CSS skills are poor...

**Comment by jskeet** [comment]
The front page needs work as per #663, around resizing.

**Comment by jskeet** [comment]
Closing this for now, as realistically it's not going to be a priority any time soon.
