### ISSUE TITLE
Method Not Found/Unimplemented

### ISSUE THREAD

**Issue by ischyrus** [GoogleCloudPlatform/google-cloud-dotnet#2080]
I'm guessing that the PubSub is still very very beta? Is there an estimate on when it'll be usable?

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Status(StatusCode=Unimplemented, Detail="Method not found: google.pubsub.v1.Subscriber/StreamingPull"))
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at ....Program.Main(String[] args) in ...\Program.cs:line 47

Inner Exception 1:
RpcException: Status(StatusCode=Unimplemented, Detail="Method not found: google.pubsub.v1.Subscriber/StreamingPull")

```

**Comment by chrisdunelm** [comment]
[`Google.Cloud.PubSub.V1`](https://www.nuget.org/packages/Google.Cloud.PubSub.V1) is late beta, and I would not expect to see this error.

Which version of `Google.Cloud.PubSub.V1` are you using?
Is this running under .NET Core, or the full .NET framework? And what kind of application is this (e.g. Console app, ASP.NET Core, ...)?

Please can you show the code that calls into PubSub that results in this error.

Thanks.

**Comment by ischyrus** [comment]
I should have kept that code, and I should have pasted it into the issue. Sorry about that.

This was in .NET Core. I was able to send\publish, and then this exception occurred while trying to listen. I'll code it up again, it was just a short snippet I had in a .NET Core console app. I probably won't get around to it until later in the week or over the weekend.

Cheers,
-Steven

**Comment by chrisdunelm** [comment]
Thanks @ischyrus. If you can reproduce the problem and let us see the code, that'd be really helpful.

**Comment by chrisdunelm** [comment]
Closing as unreproducable. If this error is seen again, please post a comment here with code and we'll re-open.
