### ISSUE TITLE
Deflake LoggingTest, Logging_TimedBuffer and DiagnosticsWebHostTests integration tests.

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#2083]
They have shown flakes on these.  I suspect it is the logger polling.

**Comment by amanda-tarafa** [comment]
Partially addressed in #2259

**Comment by amanda-tarafa** [comment]
Closing since this seems to have been all fixed by #2259.
Keep in mind that we might have to tweak waiting times further as we add new integration tests.
