### ISSUE TITLE
Error reporting not working from GKE

### ISSUE THREAD

**Issue by kYann** [GoogleCloudPlatform/google-cloud-dotnet#2086]
Hello,

I've setup error reporting on an asp .net core project that I've pushed to GKE.
Using the same docker image on GCE, I do have error reported but on GKE I don't.

Looking at the log from the container does show the stack trace of the exception i'm provoking, but no error about error reporting.
I did not provided the projectId as the library can retrieve those information by itself.
I've tried with the version 2.0 and 3.0-beta of the library.
I also tried to provide a serviceaccount using the env variable, the serviceaccount was owner of the project, but it did not help.

How can I troubleshot this issue ?

Thanks,

Yann

**Comment by iantalarico** [comment]
Hey Yann,

Can you share how you are setting up error reporting in your asp.net core application?  Specifically your `Configure` method?

Are you using other diagnostics bits? Logging or tracing?  Are you seeing them?

Thanks!
Ian

**Comment by kYann** [comment]
Hey Ian,

Thanks for taking the time to answer. I'm using the configuration on the builder : 

```
 WebHost.CreateDefaultBuilder(args)
                 .UseGoogleDiagnostics(serviceName: serviceName, serviceVersion: serviceVersion)
                 .UseStructureMap()
                 .UseStartup<Startup>()
		 .Build();
```
Yann

**Comment by iantalarico** [comment]
Are you seeing any logs or traces?

**Comment by kYann** [comment]
In the log I can see the error that I've caused. The log are from the container directly (not my app).

In the trace, I do have trace from my app (agent: google-cloud-csharp-diagnostics 3.0.0-beta01).
The stack trace is available on the trace, but the "HTTP status code" associated is 200. On the client side I did received an error 500.

**Comment by iantalarico** [comment]
thanks for the extra details.  

Can you look in your logs on the cloud console?  Error reporting puts logs under global -> stackdriver-error-reporting.
![nvfot5jxqka](https://user-images.githubusercontent.com/5264734/38880674-24fed4a2-421b-11e8-9adf-2c5e3f746760.png)

**Comment by kYann** [comment]
Inside Global I don't have the refinement "stackdriver-error-reporting", I only have "gcplogs-docker-driver"

**Comment by kYann** [comment]
Ok, so I thought I add trace, but the trace comes from the GCE instance (that I created to test). So no, I don't have any trace from the app running on GKE :(

**Comment by kYann** [comment]
This is the scopes of the clusters : 
"https://www.googleapis.com/auth/monitoring"
"https://www.googleapis.com/auth/devstorage.read_only"
"https://www.googleapis.com/auth/logging.write"
"https://www.googleapis.com/auth/compute"

**Comment by kYann** [comment]
I've also tried using a service accounts key with owner and it did not worked, same issue !

**Comment by iantalarico** [comment]
So in this case I don't think you should be seeing tracing.  Do you see any other logs?

**Comment by kYann** [comment]
Yes I can see the container logs (from gke)

**Comment by iantalarico** [comment]
Sorry I should have been more explicit, can you see any asp.net core logs?

**Comment by kYann** [comment]
No I don't have any :/

**Comment by iantalarico** [comment]
Sorry for all the back and forth here.  I just created a cluster with only "https://www.googleapis.com/auth/logging.write" and deployed to it and was able to get errors and logs.  Is the project you are working on open source by any chance?

Can you try looking for logs under GKE Container -> [cluster name] -> aspnetcore?


![ryjtmrmg7zf](https://user-images.githubusercontent.com/5264734/38890477-60131056-4236-11e8-81b6-1fc57cd69748.png)

**Comment by marfenij** [comment]
@iantalarico wrong - logs should be inside GKE Cluster Operations -> {your cluster} 

> aspnetcore

this feature are released?

**Comment by kYann** [comment]
First, thanks for taking the time to make those test ! I'm really grateful for your help.

Unfortunately my project is not opensource. But maybe I could try to deploy your project to my cluster, and then start from here to see the difference ?

**Comment by marfenij** [comment]
Yann can you provide part onk8s manifest where you setup sa.key ?

**Comment by iantalarico** [comment]
@marfenij  This is not wrong.  GKE Cluster operations is just that cluster operations.  The nuget package Google.Cloud.Diagnostics.AspNetCore (which @kYann is using) will log asp.net core logs to GKE Container -> [cluster name] -> aspnetcore.

@kYann I tested it with this [application](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/applications/googlehome-meets-dotnetcontainers/GoogleHomeAspNetCoreDemoServer)  and updated this [line](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/applications/googlehome-meets-dotnetcontainers/GoogleHomeAspNetCoreDemoServer/Program.cs#L39) to be `UseGoogleDiagnostics`

**Comment by kYann** [comment]
@marfenij 
```
spec:
  containers:
  - env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/secrets/google/whyse-qa-api-key.json
    volumeMounts:
    - mountPath: /var/secrets/google
      name: whyse-qa-api-key-volume
      readOnly: true
  volumes:
  - name: whyse-qa-api-key-volume
    secret:
      defaultMode: 420
      optional: false
      secretName: whyse-qa-api-key
```

I tried using GOOGLE_APPLICATION_CREDENTIALS before reaching out to you. And at that time I was focusing on Error reporting.
I've tried again using GOOGLE_APPLICATION_CREDENTIALS, I don't have any error reported, but **I do have trace reported** !

**Comment by marfenij** [comment]
@iantalarico GKE Container contains log which collected via fluentd - and it use app output and collect that as strings, this is not direct log from app to Stackdriver

**Comment by kYann** [comment]
Ok, I did the change. And the app is reporting an error. I'll move from this point to add everything available in my app to see the difference.

**Comment by iantalarico** [comment]
@kYann Great, let me know if you have other questions and also what the delta is that breaks things.

**Comment by kYann** [comment]
Found where the issue was. On your test application you have dependencies on other Google Library. Which means that some base library are newer than the one you get when you only reference Diagnostics.
I've updated Grpc.Core and Google.Api.Gax.Grpc and now it's working !

For your integration tests, you may wanna use a project that has no other reference to a google library.

**Comment by marfenij** [comment]
@iantalarico mb that point to update dependencies in Google.Cloud.Diagnostics.AspNetCore :-)

**Comment by iantalarico** [comment]
@kYann Thanks for the info!  It looks like Grpc.Core is v1.10.0 and the newest is 1.11.0.  

@jskeet It looks like our default for libraries is v1.10.0.  Any reason not to update?

**Comment by jskeet** [comment]
@iantalarico: 1.11.0 was only released two days ago. We don't release a new version of all libraries each time any of the dependencies updates, but we'll almost certainly update to 1.11.0 in Gax.Grpc when we release 2.4.0 of that. (That's our normal cadence - basically using Gax.Grpc as a proxy for Grpc.) We'll want to see if there are significant issues reported with 1.11.0 first though.

**Comment by iantalarico** [comment]
@jskeet ah okay.  Any insight into this failure?

**Comment by iantalarico** [comment]
@kYann I updated the deps and pushed 3.0.0-beta02.
