### ISSUE TITLE
Webhook call failed (Properties with "_" at the end of the name)

### ISSUE THREAD

**Issue by faelpires** [GoogleCloudPlatform/google-cloud-dotnet#2098]
I'm using the new classes in C#. But I get this error when I return the response:

Webhook call failed. Error: Failed to parse webhook JSON response: Cannot find field: simpleResponses_ in message google.cloud.dialogflow.v2beta1.Intent.Message.SimpleResponses.

Am I doing something wrong or is there an error in the class?

**Comment by jskeet** [comment]
Could you give more information about what you're doing? I don't know where the error is coming from or what your client code is doing at the moment.

I'm surprised that the error message talks about v2beta1, when I'd expect it to talk about v2, as that's what the library supports. Is it possible that you're still using the v2beta1 API somewhere else, and that's making the webhook call?

If you could give more information about what you're doing, that would be much appreciated.

**Comment by faelpires** [comment]
My code is very simple, a response to an intention. I'm just returning a SimpleResponse. However the result of JSON is including "_" and DialogFlow is reporting this error.

I changed the option to not use beta API in the agent settings. But the message remains basically the same.

"Webhook call failed. Error: Failed to parse webhook JSON response: Cannot find field: simpleResponses_ in message google.cloud.dialogflow.v2.Intent.Message.SimpleResponses."

![evidence](https://user-images.githubusercontent.com/13486065/38992955-a5290258-43b8-11e8-842f-702cf91c3f9f.png)

**Comment by faelpires** [comment]
My code:

```
var webhookResponse = new Google.Cloud.Dialogflow.V2.WebhookResponse
{
    FulfillmentMessages =
    {
        new Google.Cloud.Dialogflow.V2.Intent.Types.Message
        {
            SimpleResponses =
            {
                SimpleResponses_ =
                {
                    new Google.Cloud.Dialogflow.V2.Intent.Types.Message.Types.SimpleResponse
                    {
                        DisplayText = "Aqui está o 31º episódio.",
                        TextToSpeech = "Aqui está o 31º episódio, Progressive Web Apps."
                    }
                }
            }
        }
    }
};
```
JSON sent to DialogFlow

```
{
    "fulfillmentText": "test",
    "fulfillmentMessages": [
        {
            "simpleResponses": {
                "simpleResponses_": [      <= here is the problem
                    {
                        "textToSpeech": "Aqui está o 31º episódio, Progressive Web Apps.",
                        "ssml": "",
                        "displayText": "Aqui está o 31º episódio."
                    }
                ]
            },
            "platform": 8,
            "messageCase": 7
        }, continue....
```

**Comment by jskeet** [comment]
You've shown how you've declared the variable, but not how you're converting that into JSON. See my previous comment which explains that if you call `webhookResponse.ToString()` you'll get the appropriate JSON.

Your current code currently throws a `NullReferenceException` as you're not creating a new `SimpleResponses`, but having fixed that, calling `ToString()` produces the following JSON:

```json
{ "fulfillmentMessages": [ { "simpleResponses": { "simpleResponses": [ { "textToSpeech": "Aqui está o 31º episódio, Progressive Web Apps.", "displayText": "Aqui está o 31º episódio." } ] } } ] }
```

Again, no underscore.

**Comment by jskeet** [comment]
Okay, looking at the library more (I've never used Dialogflow myself - this is entirely generated code) I suspect I know what's going on.

The `SimpleResponses` type has a property named `SimpleResponses_` to avoid a naming collision. The Protocol Buffer support library knows about the desired JSON representation, so calling `ToString()` works fine - but if you convert it to JSON using something like Json.NET, that *won't* know about it.

So it sounds like this is just a matter of changing how you serialize your response. I don't know what you're using to implement your webhook, but if you can make it return a string response, you can just call `ToString()` on your `Intent` to get the JSON, and return that.

Here's a quick example as a console app:

```csharp
using Google.Cloud.Dialogflow.V2;
using System;
using static Google.Cloud.Dialogflow.V2.Intent.Types;
using static Google.Cloud.Dialogflow.V2.Intent.Types.Message.Types;

namespace Issue2098
{
    class Program
    {
        static void Main(string[] args)
        {
            var intent = new Intent
            {
                Messages =
                {
                    new Message
                    {
                        SimpleResponses = new SimpleResponses
                        {
                            SimpleResponses_ = { new SimpleResponse { DisplayText = "text" } }
                        }
                    }
                }
            };
            string json = intent.ToString();
            Console.WriteLine(json);
        }
    }
}
```

The output is:

```json
{ "messages": [ { "simpleResponses": { "simpleResponses": [ { "displayText": "text" } ] } } ] }
```

Note how there's no underscore in that JSON.

**Comment by jskeet** [comment]
(Apologies - my comments ended up out of order due to flaky wifi. I'm responding on a train...)

You've shown how you've declared the variable, but not how you're converting that into JSON. See my previous comment which explains that if you call webhookResponse.ToString() you'll get the appropriate JSON.

Your current code currently throws a NullReferenceException as you're not creating a new SimpleResponses, but having fixed that, calling ToString() produces the following JSON:

{ "fulfillmentMessages": [ { "simpleResponses": { "simpleResponses": [ { "textToSpeech": "Aqui está o 31º episódio, Progressive Web Apps.", "displayText": "Aqui está o 31º episódio." } ] } } ] }
Again, no underscore.

**Comment by faelpires** [comment]
The code I sent is wrong. I'm not on my personal computer, I'm at work. On my computer the code is the same as yours. Sorry about that. But your answer made me discover the problem. I was not calling the object's ToString() method. The serialization was being done by Newtonsoft.Json automatically. Now that's correct, thank you very much. Is there any documentation of this?

Changing the subject, do you know if there is any forecast for DialogFlow to support ImageDisplayOptions?
https://developers.google.com/actions/reference/rest/Shared.Types/ImageDisplayOptions

**Comment by jskeet** [comment]
I'm afraid I don't know anything Dialogflow-specific; the library is autogenerated and I mostly support the code generation and support libraries.

I suggest you ask Dialogflow-specific questions (both about documentation and ImageDisplayOptions) on the forum here: https://productforums.google.com/forum/#!forum/dialogflow

**Comment by faelpires** [comment]
I already did, but I was ignored. Anyway thanks a lot for the help.
