### ISSUE TITLE
webhookRequest.QueryResult.Parameters are not being filled

### ISSUE THREAD

**Issue by faelpires** [GoogleCloudPlatform/google-cloud-dotnet#2099]
The parameters are being sent, but are not being serialized in the request object.

![3](https://user-images.githubusercontent.com/13486065/39029891-cc535320-4434-11e8-8312-d83a3d259c2b.png)
![2](https://user-images.githubusercontent.com/13486065/39029889-ca66fa30-4434-11e8-8541-ac12e94f9426.png)
![1](https://user-images.githubusercontent.com/13486065/39029887-c81d4e0a-4434-11e8-9014-9f2b07b6a710.png)

**Comment by jskeet** [comment]
It sounds like this is another case of the parsing performed by Json.NET not being appropriate for `WebhookRequest`. If you can get the request as a string, you can use:

```csharp
WebhookRequest request = WebhookRequest.Parser.ParseJson(json);
```

I'm going to ask internally to see if there are full samples for C# coming soon, which will help to make all this a lot less frustrating.

**Comment by faelpires** [comment]
It works. However, it seems more like a workaround to me than a solution. I understand that Google.Cloud.Dialogflow classes should handle this. I'm wrong?

![4](https://user-images.githubusercontent.com/13486065/39076989-120d0384-44d5-11e8-9ecf-44eb207efb9a.png)

**Comment by faelpires** [comment]
This worked by calling from DialogFlow, but when calling from the Google Actions Simulator gives this error:
Google.Protobuf.InvalidProtocolBufferException: 'Unknown field: version'

```
  "originalDetectIntentRequest": {
    "source": "google",
    "version": "2",  <========  error!
    "payload": {
      "isInSandbox": true,
      "surface": {
        "capabilities": [{
          "name": "actions.capability.MEDIA_RESPONSE_AUDIO"
        }, {
          "name": "actions.capability.WEB_BROWSER"
        }, {
          "name": "actions.capability.AUDIO_OUTPUT"
        }, {
          "name": "actions.capability.SCREEN_OUTPUT"
        }]
      }
```

**Comment by jskeet** [comment]
Closing as I don't believe there's further work for this repo.

**Comment by vbucchare** [comment]
Hi jskeet, I'm having the same problem as above. Calling from DialogFlow works great, but when calling from the Google Actions Simulator gives this error:
Google.Protobuf.InvalidProtocolBufferException: 'Unknown field: version'

What was the work-around for this? I'm not using the Json.net serializer anywhere in my code.

Thanks,
Vince

**Comment by vbucchare** [comment]
Thanks for the reply @faelpires . Unfortunately I already have that feature off.

**Comment by jskeet** [comment]
@vbucchare: Could you file a separate issue for that please? It's something I'm not aware of, and I may need to investigate with the product team.

You can use a JsonParser with "ignore unknown fields" set though:

```csharp
var parser = JsonParser.Default.WithIgnoreUnknownFields(true);
var request = parser.Parse<WebhookRequest>(json);
```
