### ISSUE TITLE
API with transaction and write as parameter

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#2114]
I think `transaction.GetDocumentSnapshotAsync` and all similar api is not so convenient

Instead, could we write it as 

```C#
firestoreDB.Collection("players").Document(follow.Key).SnapshotAsync(transaction);
```

It could be just an extension method

```C#
public static Task<DocumentSnapshot> SnapshotAsync(this DocumentReference doc,Transaction transaction,CancellationToken cancellationToken = default(CancellationToken))
{
    return transaction.GetDocumentSnapshotAsync(doc,cancellationToken);
}

// same for query / create / set / update / delete
```

Also I wish this could be possible

```C#
firestoreDB.Value.Collection("players").StreamAsync(transaction); // no equivalence in transaction
```

**Comment by jskeet** [comment]
I'm not sure it makes much sense to stream results in a transaction. I'd expect streaming to be a relatively long-running aspect, whereas I believe a transaction is intended to be relatively short.

As for taking the transaction in an overload, personally I prefer to make it really clear that you're working with the transaction, right from the start. Of course, you could always add your *own* extension method if you want to - that doesn't have to be in the library.

@schmidt-sebastian Any comments? Have you seen similar requests in other languages?

**Comment by jskeet** [comment]
I do see what you mean about moving code into a transaction, but I'm still a little uncomfortable with it.

We'll see what Sebastian says, but I personally wouldn't want to put those extension methods in. But the beauty of extension methods is that you can do that yourself - you don't need the library to support you at all for that to work.

**Comment by Thaina** [comment]
Also I have seen internally we have
https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/2be9e34b54bd4c99ad717a23be61ed399b021e62/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Query.cs#L550-L557

So stream in transaction should be possible

Also now I remember that I was familiar with transaction as parameter because low level api is like this
https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/fdeff43831550f65783fab0a38244182e048824b/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Transaction.cs#L79-L81

**Comment by schmidt-sebastian** [comment]
Sorry, I just saw this.

This is the first time we have gotten this kind of feedback. Generally, we recommend reducing both the number and the scope of transactions in your code. Transactions acquire locks on the documents returned from the backend and can prevent other clients from making progress. 

The current API encourages a small scope for these locks and makes transaction boundaries very visible.  Furthermore, we are also actively working on API features that replace some of the functionality for which transactions are commonly used and hope that this can further alleviate your concerns.

If you want to mix & match transactions with regular code, you should take a look at our WriteBatch support. The WriteBatch API is very similar to the Transaction API, with the notable admission of document reads.

**Comment by Thaina** [comment]
@schmidt-sebastian If the obvious of transaction is your concerned I was propose this pattern

```C#
var docTransaction = await transaction.Collection("users").Document(key).SnapshotAsync();
docTransaction.Set(obj); // internally is transaction.Set(doc)
```

In anyway transaction was needed for safety to write value so locking is needed

I don't have a `mix & match transactions with regular code`. What I said above is, I have regular code written and work well. But then I would like to convert all of it into transaction. But the transaction API make it look somewhat difference from normal api. So I try to propose a way that make it look more familiar and could be convert more easily

And I don't propose this api to make it a large scope. Even in small scope or small block or actually any size of block, having convenient transaction api that could easily move in or out of transaction block is better

**Comment by schmidt-sebastian** [comment]
Have you look at the Precondition API? 
You can use `Precondition.LastUpdated(timestamp)` to lock during an `update()` call. You would pass the `updateTime` from a DocumentSnapshot (https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/DocumentSnapshot.cs#L59) and then use this Precondition in a normal call to update(): https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/DocumentReference.cs#L162

For single document updates, this achieves the same effect as a transaction (if we disregard optimistic versus pessimistic locking). You can even do this via the WriteBatch API and combine multiple updates with individual Preconditions.

**Comment by Thaina** [comment]
@schmidt-sebastian I use transaction as it should be. Unless you said transaction will be removed from firestore eventually I would not stop using it. You try to make me use precondition is relegate the management that transaction already did to me. I don't think it convenient

I use writebatch sometimes when read and write is far apart between many `await` but when it just straightforward set, I prefer transaction because it more convenient and in the scope

I know what I am doing. But I would like to have all possible option I could choose to solve problem. Please don't encourage me to go back using low level API

**Comment by schmidt-sebastian** [comment]
Transactions are definitely not going away! There is some overlap with other APIs that might help you and others in cases where running everything within the context of a single function is not the best option.

That being said, we value user feedback tremendously and are still very much evolving our API. We haven't gotten much feedback about this specific part of the API, and as such, value every opinion we can get on this matter. I will discuss your proposal with the rest of our team and keep you updated (likely by the end of next week).

**Comment by mikelehen** [comment]
Thanks very much for the feedback!

As I understand it, the proposal here is to change:
```
transaction.SnapshotAsync(docRef)
```
into
```
docRef.SnapshotAsync(transaction)
```
(and likewise for all the other transaction methods: Set, Create, etc.)

This would be another reasonable way to design the API, but we chose to do the former since:
1. Transaction.Set() is synchronous and returns Void while DocumentReference.SetAsync() is asynchronous and returns Task<WriteResult> and so they're not compatible.
2. WriteBatch and Transaction both follow the same pattern, and so for Set(), Create(), etc. we'd need overloads for accepting a `Transaction`, a `WriteBatch`, or neither. Having extra overloads starts to make it more difficult to use the API and expand it over time.
3. By hanging operations off of the `Transaction` and `WriteBatch` objects, it's very clear and discoverable to users (via statement completion) what operations you can do within a transaction or write batch.  Otherwise you'd need to search through all of the DocumentReference methods for the ones that accept a `Transaction` or `WriteBatch` in one of their overloads.

Alternatively, we could accept both ways of doing things (as I think you are suggesting with the extension method) but we generally try to avoid having multiple ways of doing the same thing unless there's a meaningful benefit, since it creates ambiguity when generating documentation, samples, etc. and increases the API surface area that we need to maintain (if we add an argument in one place we need to add it in the others as well).

In this case, since you can create these extension methods yourself, I think we'll probably hold off on incorporating them directly into the SDK. We're open to additional feedback and will certainly reconsider if there turns out to be substantial demand or compelling use cases we haven't considered.  

Thanks again for the thoughtful feedback! We appreciate it.

**Comment by Thaina** [comment]
@mikelehen By your side suggestion, in my case I was already write extension method for tuple `(transaction,document)`

And so I was writing code like this

```C#
firestoreDB.RunTransactionAsync(async(transaction) => {
    var doc = transaction.Collection("users").Document(uid); // Tuple<Transaction,DocumentReference>
    var user = await doc.SnapShotAsync();
    doc.Set("counter",user.Get("counter",0) + 1);
});
```

All the update API was reduced to sync version. I also made the same for writebatch. But I think that this api should be extended from the same source

I mean you could have something like IReadAsync,IWrite,IWriteAsync that implement the logic and used to compose into DB,Transaction and WriteBatch

DB : IReadAsync,IWriteAsync
Transaction : IReadAsync,IWrite
WriteBatch : IWrite

And all three sharing underlying code
What I see is Transaction and always hold DataBase so I think we don't necessary need to reference it again in transaction codeblock. It more clean that way

**Comment by mikelehen** [comment]
That's a reasonable suggestion, thanks!

We'll keep it in mind for the future and watch out for other people trying to write common code that works across Transaction and WriteBatch objects. If it's a common pattern it may be worth introducing the interface.

**Comment by jskeet** [comment]
I'm going to close this now as we have no plans to change the API design at the moment. The feedback is valuable though, and we'll bear it in mind for future options.
