### ISSUE TITLE
DialogFlow.v2 need documentation or samples

### ISSUE THREAD

**Issue by DomDumont** [GoogleCloudPlatform/google-cloud-dotnet#2115]
Hi,

I try to detect intents through an audio stream.
With the help of an old (V1) java sample, I  tried to write some c# code but it's not working yet.
can you help me ?
Thanks in advance

This is what I have so far

 

>            QueryInput queryInput = new QueryInput();
> 
>             InputAudioConfig myAudioConfig = new InputAudioConfig();
>             myAudioConfig.LanguageCode = "fr-FR";
>             myAudioConfig.SampleRateHertz = 16000;
>             myAudioConfig.AudioEncoding = AudioEncoding.Linear16;
> 
>             queryInput.AudioConfig = myAudioConfig;
> 
>             StreamingDetectIntentRequest myStreamingRequest = new StreamingDetectIntentRequest();
>             myStreamingRequest.Session = "MYSESSION";
>             myStreamingRequest.QueryInput = queryInput;
> 

and in my audio callback

>         private void RecorderOnDataAvailable(object sender,WaveInEventArgs e) {
>             // Console.WriteLine(e.Buffer[0]);
>             myStreamingRequest.InputAudio = ByteString.CopyFrom(e.Buffer,0,e.BytesRecorded);
>                }

but for example I don't know what to do with this :

>         StreamingDetectIntentStream responseStream = sessionsClient.StreamingDetectIntent();

**Comment by jskeet** [comment]
Sorry, I don't know anything about Dialogflow as an API, and certainly nothing about how to migrate a V1 application to a V2 application. If there's something that's specific to the C# library, I can help with that, but otherwise I suggest you ask on https://productforums.google.com/forum/#!forum/dialogflow

**Comment by DomDumont** [comment]
Thanks for the suggestion. will do

**Comment by jskeet** [comment]
I'm going to close this as I don't believe there's any work that is outstanding in *this* repository - but I already have an internal issue for the Dialogflow team to add samples to their product site.
