### ISSUE TITLE
Any plan for safer write in transaction?

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#2117]
Current transaction need us developer to care for not calling any `set` api before any `get` api while actually we could just defer all `set` of the transaction to batch it at the very end of transaction. And I think this task could actually be handle by the SDK

We could even manage the local `set` that, whenever we run `transaction.Get*` after `set` it would do local applied to the document that was set by the transaction object. So we could even really set the datas, get the data, and have the field we was setting it present

Is it really possible?

**Comment by jskeet** [comment]
I suspect the point is to avoid situations where you call set then get the same document, and expect to see the written value. As ever, this is more of a question for@schmidt-sebastian.

**Comment by Thaina** [comment]
Seem like @schmidt-sebastian was not mentioned

**Comment by schmidt-sebastian** [comment]
@jskeet  is correct. If you modify a document locally (before committing the transaction), we have no way to return the value you "think" you have just written. That's why this case is disallowed.

**Comment by Thaina** [comment]
@schmidt-sebastian I was thinking that, except ServerValue like timeStamp, we could _mocking_ the update we have did before `Get`. by simulate the `Set` and `Update` to that document like it would be done on the server when that document was downloaded


```C#
await firestoreDB.RunTransactionAsync(async(transaction) => {
    transaction.Update(docRef,"value",0);
    var doc = await transaction.Get(docRef);
    // internally it read a list of transaction and apply override
    // doc = transaction.Get(docRef); => doc["value"] = 0
});
```

**Comment by jskeet** [comment]
Closing as out of scope.
