### ISSUE TITLE
Default log entry labels with HTTP context info

### ISSUE THREAD

**Issue by henkmollema** [GoogleCloudPlatform/google-cloud-dotnet#2120]
Would you consider a default `ILogEntryLabelProvider` implementation (or multiple) which populate some labels related to an HTTP request useful for searching and correlating logging entries? It could be registered when you use `UseGoogleDiagnostics()` by default. I was thinking of the following values:

- The HTTP [`TraceIdentifier`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.traceidentifier?view=aspnetcore-2.0)
- The HTTP user identity name 
   - Might be a privacy issue, perhaps make configurable or just whether a request was authenticated
- Grab the exception from [`IExceptionHandlerPathFeature`](https://docs.microsoft.com/nl-nl/dotnet/api/microsoft.aspnetcore.diagnostics.iexceptionhandlerpathfeature?view=aspnetcore-2.0) (when available) and add the exception type/message

I find myself adding this provider to all of my projects hosted in GCP:

```cs
public void Invoke(Dictionary<string, string> labels)
{
    var httpContext = _httpContextAccessor.HttpContext;
    if (httpContext == null)
    {
        // Not in the scope of an HTTP request
        return;
    }

    // Add the trace identifier to correlate log entries from a single request
    labels["trace_identifier"] = httpContext.TraceIdentifier;

    // Add authenticated user info
    if (httpContext.User?.Identity?.IsAuthenticated == true)
    {
        labels["user_authenticated"] = bool.TrueString;
        labels["user_name"] = httpContext.User.Identity.Name;
    }

    // Add any exception info when available to quickly inspect 
    // and filter exceptions in the GCP Logging console
    var exceptionFeature = httpContext.Features.Get<IExceptionHandlerPathFeature>();
    var exception = exceptionFeature?.Error;
    if (exception != null)
    {
        labels["error_path"] = exceptionFeature.Path ?? "N/A";
        labels["error_type"] = exception.GetType().FullName;
        labels["error_message"] = exception.Message;
        labels["error_stacktrace"] = exception.ToStringDemystified();
    }
}
```

What are your thoughts about this?

cc @iantalarico

**Comment by iantalarico** [comment]
@henkmollema Definitely think this would be useful.  I need to think about this a little more in the context of defaults and privacy.

**Comment by iantalarico** [comment]
@henkmollema Thinking about this a little more I don't think we should put any of these in `UseGoogleDiagnostics` as adding a small amount of info to each log can add up (and logs aren't free).  It also would be pretty easy to add these after the fact.

I think splitting this up into 3 separate `ILogEntryLabelProvider`s would be a good move.  

I'm still want to think a little more about the `User` parts but I think it should be okay if we don't put it as a default.

@henkmollema Thoughts?

**Comment by henkmollema** [comment]
@iantalarico personally I think at least having a trace ID by default to correlate logs per request would be really useful. Today the logs for ASP.NET Core apps are just a big list of entries and it can be pretty difficult to correlate those messages.

I agree the other providers should be optional (and therefore split up).

As for the adding the exception information, I forgot about a little issue I ran into:  it requires for the `IExceptionHandlerPathFeature` to be set on the HTTP context. However, by default nothing is logged _after_ it's being set. The `ExceptionHandlerMiddleware` of ASP.NET [logs  its latest message before it's being set](https://github.com/aspnet/Diagnostics/blob/9cc72f7af159e84c695935d13ff1b8f3ba669e7e/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L56). In my own application I solved this by subscribing to the `Microsoft.AspNetCore.Diagnostics.HandledException` event of the diagnostics source and log another 'exception unhandled' message which causes the labels to be correctly populated. Although I personally find it useful, it might be out of scope and too opinionated  for this library. What do you think?

**Comment by henkmollema** [comment]
For what's it worth: I think beging able to filter log entries like this is pretty nice:

![image](https://user-images.githubusercontent.com/1521207/39425357-4d96e318-4c7b-11e8-8fb4-c453cd63599c.png)

**Comment by iantalarico** [comment]
@henkmollema I think you are right about the trace ID. I'm okay to add it to `UseGoogleDiagnostics` as long as it's well documented.

As for the error reporting bits I think that's doing a little too much.  I'd rather keep the library to a small core set.

**Comment by henkmollema** [comment]
@iantalarico I agree. Have you thought about adding a label for authenticated users as well?

**Comment by iantalarico** [comment]
@henkmollema I *think* it's okay as long as it's never a default.

@jskeet Jon do you see any issues here?

**Comment by henkmollema** [comment]
Would the `ILogEntryLabelProvider` implementation just be available as public class or should we add an extension method to easily configure it. Such as `AddUserInfoLoggingLabels()` or something. If so, would it be an extension on `IWebHostBuilder` or `IServiceCollection`?

**Comment by iantalarico** [comment]
I think it should just be a public class.  It's really only 1 line of code and I think would get confusing otherwise.  This makes adding more in the future easy, we can just dump them in a shared folder.

**Comment by henkmollema** [comment]
Sounds good to me, I'll see if I can find some time this week to implement this 👍

**Comment by iantalarico** [comment]
@henkmollema Awesome, thanks!
