### ISSUE TITLE
[NuGet: Google.Apis.CloudNaturalLanguage.v1] CloudNaturalLanguageService(...).Documents.AnalyzeEntities(...) returns -1 for BeginOffset when not specifying encoding

### ISSUE THREAD

**Issue by andras-ferencz** [GoogleCloudPlatform/google-cloud-dotnet#2136]
Exactly what the topic says.
``var response = client.Documents.AnalyzeEntities(new AnalyzeEntitiesRequest()
            {
                Document = new Document()
                {
                    Type = "PLAIN_TEXT",
                    Content = filteredInput.Trim()
                },
                EncodingType = "UTF8",               
            }).Execute();``

works fine.

``var response = client.Documents.AnalyzeEntities(new AnalyzeEntitiesRequest()
            {
                Document = new Document()
                {
                    Type = "PLAIN_TEXT",
                    Content = filteredInput.Trim()
                }
            }).Execute();``

works, but doesn't give the BeginOffset (they're all -1) for the Entities in the response .

<img src="https://i.ytimg.com/vi/d2xkpz-26jM/maxresdefault.jpg"/>

**Comment by jskeet** [comment]
If you're using the `Google.Apis.CloudNaturalLanguage.v1` NuGet package, then if this comment doesn't satisfy you, the issue should be refiled on https://github.com/google/google-api-dotnet-client - ideally with a complete example including some text. (And unless the clown picture is actually relevant somehow, it would be best to leave that off.) That's the repository for the Google.Apis.* packages.

However, I'd suggest you use the `Google.Cloud.Language.V1` NuGet package if you can, as that's the more current codegen which is designed to be easier to use.

All of that being said, I'm not sure there's any bug here - if you don't specify an encoding, the service has no real frame of reference to give you offsets in. I suspect you actually want "UTF16" as the encoding type if you want to use the offsets as indexes into a .NET string.

**Comment by jskeet** [comment]
Closing this issue as I don't believe there's a bug here.
