### ISSUE TITLE
Pub/Sub Streaming hangs randomly on a long running applications.

### ISSUE THREAD

**Issue by hkedjour** [GoogleCloudPlatform/google-cloud-dotnet#2144]
We have a bunch of applications relying on pub/sub. We are using the latest version of the pub/sub library beta 17. After a while, the applications stops receiving messages. (The problem was also on the previous versions, but it get worse with the latest version).

It's hard to produce the problem, it's random. Running *netstat* in a hanged machine (container) gives the following:

![pubsubhanging](https://user-images.githubusercontent.com/7966248/40056513-e7504842-584b-11e8-9f1e-153c5ed8a533.png)

For a working machine we get:

![pubsubworking](https://user-images.githubusercontent.com/7966248/40056673-5c86d720-584c-11e8-91eb-6bf3c012e33e.png)

I don't know if the connection are slowly going to *CLOSE_WAIT* state until the last one of them, than the application hangs.

P.S: We had also this problem when we used polling, but we didn't check the state of tcp connections.

**Comment by chrisdunelm** [comment]
Are you using `SubscriberClient` or `SubscriberServiceApiClient`? Please can you show code for how you create the client, with any settings that you might use, and how you start the streaming subscription.
When you were using polling (and also saw the problem), if you still have the code, please can you also show how you created the client, and how your polling loop worked?

Is this running on Linux?
What sort of application is it? Which framework is it targetting?

**Comment by hkedjour** [comment]
Here is a basic structure of an application:

```csharp
/// <summary>
/// Google Pub/Sub stream subscriber. Instances of this class are not reusable and the class should be registered as transient with dependency providers.
/// </summary>
/// <typeparam name="TMessage">Type of the message</typeparam>
public class GooglePubSubStreamSubscriber<TMessage> : GooglePubSub, IStreamSubscriber<TMessage> where TMessage : IMessage
{
    [NotNull] private readonly SubscriberClient _sub;

    public GooglePubSubStreamSubscriber(
        [NotNull]IOptions<GooglePubSubSubscriberConfiguration> configuration
        )
    {
        SubscriberServiceApiClient subscriberClientApi;

        if (IsEmulator) //  public static bool IsEmulator => !string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("PUBSUB_EMULATOR_HOST"));
        {
            // this one will run only if the envirnment variable "PUBSUB_EMULATOR_HOST" is defined
            logger.LogWarning(LogEvent.GooglePubSubUsingEmulator, "Google Pub/Sub is using the emulator because the environment variable PUBSUB_EMULATOR_HOST is set.");

            EnsuresSubscriptionOnEmulation(configuration.Value);

            subscriberClientApi = SubscriberServiceApiClient.Create(CreateEmulatorChannel());
        }
        else
        {
            // This is the part that runs on product.
            subscriberClientApi = SubscriberServiceApiClient.Create();
        }

        var subscriptionName = new SubscriptionName(configuration.Value.ProjectId, configuration.Value.SubscriptionName);

        _sub = SubscriberClient.Create(subscriptionName, new[] { subscriberClientApi }, new SubscriberClient.Settings
        {
            FlowControlSettings = new FlowControlSettings(configuration.Value.MaxSimultaneousMessages, null)
        });
    }

    /// <inheritdoc />
    public Task StartAsync([NotNull] Func<TMessage, CancellationToken, Task<bool>> handler)
    {
        return _sub.StartAsync(async (message, cancel) =>
            {
                    var tmsg = ..convert the message json data to TMessage....

                    var shouldAcknowledge = await handler(tmsg, cancel).ConfigureAwait(false);

                    if (shouldAcknowledge)
                    {
                        return SubscriberClient.Reply.Ack;
                    }
                    return SubscriberClient.Reply.Nack;
            }
        );
    }

    /// <inheritdoc />
    public Task StopAsync(CancellationToken cancellationToken = default(CancellationToken)) => _sub.StopAsync(cancellationToken);
}
////////////////////////////////////////////
///////////////////////////////////////////
main()
{
    ......
    await RunAsync(cancellationToken);
}
        public async Task RunAsync(CancellationToken serviceCancellationToken)
        {
            // IStreamingSubscriber.StopAsync should be called in order to stop the main loop.
            ThreadPool.RegisterWaitForSingleObject(serviceCancellationToken.WaitHandle,
                async (state, timeout) => await StopCurrentSubscriberAsync().ConfigureAwait(false), null, -1, true);

            while (!serviceCancellationToken.IsCancellationRequested)
            {
                try
                {
                    _currentSubscriber = _serviceProvider.GetRequiredService<IStreamSubscriber<ProcessImageMessage>>();
                    // When StartAsync raises an exception, the SubscriberClient goes to a faulted stated, that why we create a new instance each time

                    await _currentSubscriber.Value.StartAsync(async (message, cancellationToken) => ...ProcessTheMessage....).ConfigureAwait(false);
                }
                catch (OperationCanceledException)
                {
                    // logging
                }
                catch (RpcException e)
                {
                    _logger.LogError(LogEvent.ProcessingMessageQueue, e, "A Grpc exception occurred in the main loop, retrying in a moment");
                    await Task.Delay(TimeSpan.FromSeconds(5), serviceCancellationToken).ConfigureAwait(false);
                }
                catch (Exception e)
                {
                    _logger.LogError(LogEvent.ProcessingMessageQueue, e, "In messages pump, the operation will be retried");
                }
            }
        }

    
        /// <summary>
        /// Stops pub/sub streaming.
        /// </summary>
        /// <returns></returns>
        [NotNull]
        private async Task StopCurrentSubscriberAsync()
        {
            try
            {
                if (_currentSubscriber == null) return;

                await _currentSubscriber.StopAsync().ConfigureAwait(false);

                _logger.LogInformation(LogEvent.ProcessingMessageQueue, "Pub/Sub streaming stopped correctly.");
            }
            catch (Exception e)
            {
                _logger.LogError(LogEvent.ProcessingMessageQueue, e, "An error occurred while stopping pub/sub streaming.");
            }
        }
```
Everything is created by a default values except for `FlowControlSettings` which is used to limit the number concurrently received messages.

As far as I understand from the documentation, the default configuration is optimized for hi performance applications running on google cloud. Which is our case, we are running on Google Cloud Kubernetes.

The applications are all targeting .net core 2.0. They are run using the official mircosoft .net core image `microsoft/dotnet:2.0.6-runtime-stretch`. But we were having the same issue running on `mono`  and .net core 1(but mono was not that stable).

From what we get from the documentation is that the `SubscriberClient` is using a pool of `SubscriberServiceApiClient`, but there is no mention on how much should we create. So we stick with one. 

Will it help to pass multiple instance of `SubscriberServiceApiClient` while creating the `SubscriberClient`?
Is there a way to detect the things are hanging so we can recycle the instance?

**Comment by hkedjour** [comment]
I rolled back our application to *beta-16*, it's the same with *17*. So 17 is not worse as I mentioned before.

**Comment by chrisdunelm** [comment]
@hkedjour Are you able to try the new beta18 release? If so, do you still see this problem?

**Comment by hkedjour** [comment]
I've just deployed, I'll watch the logs and see.

**Comment by chrisdunelm** [comment]
@hkedjour Just wondering if you've noticed any further hangs since deploying with beta18? Thanks.

**Comment by chrisdunelm** [comment]
Closing, as this is likely fixed in a recent release. Please leave a comment if this is still being seen, so we can re-open.

**Comment by jtromans** [comment]
fwiw I think I'm getting this bug using Pub/Sub with the google cloud python API.

I repeatedly see the issue on both Windows and Linux (Ubuntu 18.04), running Python 3.6.5. When I try to get __version__ on the pubsub or google.cloud libraries, I am not provided with a helpful response to share here. Otherwise, the symptoms are exactly the same as the OP. @chrisdunelm let me know if there is a more recent version I should which I cannot obtain from pip install --upgrade google-cloud-pubsub

**Comment by manigandham** [comment]
@jtromans This is the repo for the C#/.NET libraries. The Python client libraries are here: https://github.com/GoogleCloudPlatform/google-cloud-python

It would be best to create a new issue there...
