### ISSUE TITLE
Consider to add possibility to inherit or Mock BigQueryTable class for unittesting without call to BigQuery api

### ISSUE THREAD

**Issue by AlexSkachkov** [GoogleCloudPlatform/google-cloud-dotnet#2170]
I need to compare Bigquery table schema with schema from other source and update it if it changes outside Bigquery. 

But when i started to cover that logic with unittests, i didn't found any possibility to create fake `BigQueryTable` object, and i have to create real project, dataset and table for unittesting. And it's very inconvenient.

Or maybe there is some better way to do that?

**Comment by jskeet** [comment]
I agree it's not ideal at the moment. We don't particularly want to make everything abstract and directly mockable, as that can be very difficult in terms of versioning concerns.

If you mock the `BigQueryClient`, all the `BigQueryTable` operations are performed via that; ideally, that should be the one place you'd want to mock. However, it's very possible that at the moment we don't provide enough public access to create a new `BigQueryTable` that refers back to your `BigQueryClient`. If we looked at that, would that be sufficient for you?

**Comment by AlexSkachkov** [comment]
I think public access to `BigQueryTable` creation will be sufficient for unittests, because it's possible to mock `BigQueryClient` and `Google.Apis.Bigquery.v2.Data.Table` have public constructor, so `BigQueryTable` can be created and used in tests without mocking or inheritance.

**Comment by jskeet** [comment]
Right, thanks. Will look at this alongside the other types (data set, job etc). Thanks for the feature request.
