### ISSUE TITLE
PubSub subscriber not acknowledging the messages properly.

### ISSUE THREAD

**Issue by rjangala02** [GoogleCloudPlatform/google-cloud-dotnet#2172]
As I am new to gcp and wrote simple subscription using available code snippets. Able to read messages correctly, after that messages are not cleared from subscription.

MessageReceiver receiver = new MessageReceiver() {
			@Override
			public void receiveMessage(PubsubMessage message, AckReplyConsumer consumer) {
				System.out.println("Received message: " + message.getData().toStringUtf8());
				consumer.ack();
			}
		};

		Subscriber subscriber = null;		

		try {
			FlowControlSettings flowControlSettings = FlowControlSettings.newBuilder()
					.setMaxOutstandingElementCount(10_000L).setMaxOutstandingRequestBytes(1_000_000_000L).build();

			subscriber = Subscriber.newBuilder(subscription, receiver).setFlowControlSettings(flowControlSettings)
					.setCredentialsProvider(credentialsProvider()).build();		
			
			
			subscriber.addListener(new Subscriber.Listener() {
				@Override
				public void failed(Subscriber.State from, Throwable failure) {
					// Handle failure. This is called when the Subscriber
					// encountered a fatal error and is shutting down.
					System.err.println(failure);
				}
			}, MoreExecutors.directExecutor());

**Comment by chrisdunelm** [comment]
@rjangala02 The code you've posted looks suspiciously like Java. If you're coding in Java, please re-submit this issue in the Java repo: https://github.com/GoogleCloudPlatform/google-cloud-java/issues

**Comment by chrisdunelm** [comment]
Closing. This issue has been re-opened here: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3308
