### ISSUE TITLE
Work remaining before NLog beta release

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-dotnet#2185]
* [x] Top-level documentation.
* [x] Make timeout configurable, not hardcoded to 1.5 seconds.
* ~~[ ] Consider allowing multiple concurrent `WriteLogEntriesAsync(...)` RPCs. Currently they occur sequentially.~~
* [x] Improve testing for situations where `WriteLogEntriesAsync(...)` RPCs are taking a long time, or failing.

**Comment by chrisdunelm** [comment]
@snakefoot If you can create a PR for the "*make timeout configurable*" item, that'd be great. Thanks :)

**Comment by snakefoot** [comment]
@chrisdunelm Created #2188 with TimeoutSeconds property

**Comment by chrisdunelm** [comment]
We'll leave the RPCs sequential for now. In a later release they could potentially be make concurrent.

**Comment by chrisdunelm** [comment]
This is now available on nuget: https://www.nuget.org/packages/Google.Cloud.Logging.NLog/
