### ISSUE TITLE
BigQuery's parsing of double doublequotes

### ISSUE THREAD

**Issue by AlexandreOuellet** [GoogleCloudPlatform/google-cloud-dotnet#2189]
I have a bunch of csv files that are under this format : 

"2017-09-12 00:00:00.0","{\\"orderId\\":\\"REDACTED\\"\\,\\"packageName\\":\\"REDACTED\\"\\,\\"purchaseTime\\":1505260135739}"

The first field is a timestamp (or even date), and is parsed properly, but the second field can't be parsed at all.  I need to essentially read the whole file, then replace all \" characters by "" characters (essentially doing a string.replace("\\\\\"", "\\"\\""), and then reupload those files, and now BigQuery is able to parse them.

Is there a way to configure Job options so that I can specify that the double doublequote character can be \" instead of "" ?

Right now, I have a lot of files this way, which are quite a pain to download, modify, upload.  It works, but it's gonna take a long time, and I was hoping that there was something within the API that could cover this case, but I can't find it.

**Comment by jskeet** [comment]
Unfortunately I don't think there's anything in the BigQuery API to do this - I'd expect to see it in the [configuration.load](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load) section if it were anywhere, but there's nothing obvious.

(The C# library just passes the data to BigQuery - it doesn't perform any other data manipulation, and I'd want to keep it that way. It wouldn't help for loading from storage etc anyway, which is what it sounds like you're doing.)

Sorry not to have a better answer for you :(

**Comment by AlexandreOuellet** [comment]
Agreed, the C# shouldn't do anything with the data itself.  As you said, I was expecting some kind of configuration to do that, but since it doesn't exist, I will have to download each and every file, modify them, and upload them back into a GCS or and create a separate job for BigQuery to load that, or simply upload the modified csv into BigQuery directly.  It will be slow, but it needs to happen somehow...I'll see how to parallelize that, but bandwidth will be my limiting factor.

Thanks for the help

**Comment by jskeet** [comment]
I'm on vacation until Wednesday, but then I'll ask internally around whether there are any workarounds. Either way, there's no change currently required in *this* repo, so I'll close this issue. Please don't take that as any indication that I think it's not a valid request - it definitely makes sense to me!

**Comment by AlexandreOuellet** [comment]
Sorry to bother you with this again, but any update, or any link where I can follow this issue?  It is almost a show stopper for me right now.  Downloading ~18k files, parsing them, then re-uploading them is quite a slow process, and I feel there is a good chance that this double quote feature might get in before I finish parsing those files (bandwidth is my limiting factor right now).

**Comment by jskeet** [comment]
I've raised a feature request [here](https://issuetracker.google.com/issues/80465397).
