### ISSUE TITLE
Move and rename Google.Cloud.Diagnostics.Common.Tests.Utils to Google.Cloud.ClientTesting

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/google-cloud-dotnet#2198]
... or at least all the parts of it that are of use for testing across all client libs and not just diagnostics.
See related comment on #2192

**Comment by iantalarico** [comment]
I think the only two we should move are `GetProjectIdFromEnvironment` and `IsWindows`, I don't think the others would be used by other libs.

**Comment by jskeet** [comment]
Makes sense - and even GetProjectIdFromEnvironment may not be necessary, as if you have a fixture deriving from CloudFixtureBase, that already exposes a ProjectId property.

**Comment by amanda-tarafa** [comment]
`GetTestId` is just returning a `Guid.NewGuid().ToString()` and I've seen that in several places, not as test id but as unique string, so it might be nice to have it as a helper somewhere, although is so small and simple...

True for the `CloudFixtureBase`, I think I will be using that one for `ProjectId` instead of the method.

**Comment by jskeet** [comment]
I'm going to have a look at this, including a common test method for Guid.NewGuid().ToString() that allows for truncation and maybe a prefix.

**Comment by jskeet** [comment]
Now complete.

**Comment by amanda-tarafa** [comment]
Closing via #2361, #2363, #2364
