### ISSUE TITLE
Consider making Google.Cloud.Diagnostics.Common.IntegrationTests.ErrorEventEntryPolling part of the public client lib.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/google-cloud-dotnet#2200]
See comments in #2192

**Comment by iantalarico** [comment]
@amanda-tarafa @jskeet I don't really think we should make this public for a few reasons:
* It's a horrible hacky polling bit I use for testing.
* I don't think we need to focus too much on users getting error events.  I think most users will just use the Cloud Console UI
* If the users are using this I don't know that polling is what they want.  My guess is they just want to grab error events at a time (but I may be wrong).

I may be missing something though.  Thoughts?

**Comment by amanda-tarafa** [comment]
My two cents, mainly, I think this is at most a nice to have.

- The hacky part can be fixed :)
- @iantalarico you are right about the UI being the most usual way in which users take a look at this.
- and @jskeet is right about increasing maitenance with anything public.
- I also don't have a lot of info about the need for polling errors, I can think of monitoring stuff that would benefit from polling, but I'm not sure what can be achieved in that sense with stackdriver monitoring or even with cloud functions and at what cost. And also clients can implemente their own polling mechanism.

Maybe I was to fast in opening an issue? Happy to close it, to keep things tidy, and mark it as "to reconsider" or something?

**Comment by jskeet** [comment]
Let's ponder over the weekend and close it if we feel the same way on Monday.

**Comment by iantalarico** [comment]
Let's leave it open and think on it like Jon said.  No harm in leaving it open.

**Comment by jskeet** [comment]
Given the time that's passed, I'd be happy closing this now - will leave that to you Amanda, so that you can decide not to if you've had a change of heart :)

**Comment by amanda-tarafa** [comment]
Closing then. Might not add much in the end.
