### ISSUE TITLE
BigQuery: Make backup for table that partitoned by arbitrary field

### ISSUE THREAD

**Issue by UkrZilla** [GoogleCloudPlatform/google-cloud-dotnet#2206]
Hi guys,

We are using BigQuery tables partitioned by not _PARITIONTIME, for example: Time. Yes, we now it is in beta.
For old tables partitioned by _PARITIONTIME we are using CreateExtractJobAsync but for new tables it is not working. Can we do something for this?

Thanks

**Comment by jskeet** [comment]
This is something we're looking at shortly - at least for a couple of features. (I can't remember whether that includes Create Extract Job, but I think it does.)

Assigning to Amanda who will probably be doing the work :)

**Comment by jskeet** [comment]
Just looking now, and time partitioning is not supported in the *extract* job configuration - only for load and query. So I'm afraid this isn't supported by the API at the moment as far as I can tell. If you think I've missed something, do let me know.

The options for exporting to multiple files are [here](https://cloud.google.com/bigquery/docs/exporting-data#exporting_data_into_one_or_more_files).

**Comment by UkrZilla** [comment]
Thanks, It's not in a hurry

**Comment by jskeet** [comment]
Well it's not so much a matter of my time, as that we can't support it from the client library if the API doesn't support it. You might want to [file a feature request](https://issuetracker.google.com/issues/new?component=187149&template=0) on the public tracker.

I'm going to close this issue for the moment, as there's no more work due in this repo at the moment. If BigQuery *does* start exposing the feature, it should be easy enough for us to support.
