### ISSUE TITLE
Add bufferingAppenderSkeleton support to Google.Cloud.Logging.Log4Net

### ISSUE THREAD

**Issue by phw198** [GoogleCloudPlatform/google-cloud-dotnet#2208]
I would like to make the `GoogleStackdriverAppender` appender operate in a similar way to `SmtpAppender` - ie. that it uses a lossy buffer that flushes when an `ERROR` level is logged. This way, I can get the context of the problem without writing large volumes of data into StackDriver.

Might this be possible or is there another way to achieve this?

```
  <appender name="CloudLogger" type="Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender,Google.Cloud.Logging.Log4Net">
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%-4timestamp [%thread] %-5level %logger - %message" />
    </layout>
    <projectId value="myProjectId" />
    <logId value="mySampleLog" />
    <bufferingAppenderSkeleton>
      <lossy value="true" />
      <bufferSize value="50" />
      <evaluator type="log4net.Core.LevelEvaluator">
        <threshold value="ERROR" />
      </evaluator>
    </bufferingAppenderSkeleton>
  </appender>
```
Thanks!

**Comment by chrisdunelm** [comment]
@phw198 Thanks for the request.
I think we're not likely to implement this directly within the `GoogleStackdriverAppender`.
However, I'm fairly sure you can use log4net's [BufferingForwardingAppender](https://logging.apache.org/log4net/release/sdk/html/T_log4net_Appender_BufferingForwardingAppender.htm) (and [see config example here](https://logging.apache.org/log4net/release/config-examples.html)) to do exactly what you're wanting.

**Comment by chrisdunelm** [comment]
Closing. If you consider the appender should be changed, please leave further comments here and we can re-open if necessary.

**Comment by phw198** [comment]
@chrisdunelm Perfect, that's just what I needed! Thanks for the help and sorry I haven't been able to respond sooner.

For anyone else that might end up here, I've ended up with
```
  <appender name="CloudLogger" type="Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender,Google.Cloud.Logging.Log4Net">
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%-4timestamp [%thread] %-5level %logger - %message" />
    </layout>
    <projectId value="myProjectId" />
    <logId value="mySampleLog" />
  </appender>
  
  <appender name="BufferingForwardingAppender" type="log4net.Appender.BufferingForwardingAppender" >
    <bufferSize value="50" />
    <lossy value="true" />
    <evaluator type="log4net.Core.LevelEvaluator">
      <threshold value="ERROR" />
    </evaluator>
    <appender-ref ref="CloudLogger" />
  </appender>
```
...and then referenced `BufferingForwardingAppender` (not `CloudLogger`) in the root element.
