### ISSUE TITLE
Issue installing in Visual Studio 2017 Pro

### ISSUE THREAD

**Issue by PI2R** [GoogleCloudPlatform/google-cloud-dotnet#2209]
Hi,
I am trying to install the google.cloud.vision.v1 through the manage nuget packages functionality,
But I keep getting the following error after hanging for 60-90 seconds:

Attempting to gather dependency information for package 'Google.Cloud.Vision.V1.1.2.0' with respect to project 'Test', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 1,27 min
Attempting to resolve dependencies for package 'Google.Cloud.Vision.V1.1.2.0' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'Google.Apis'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.
Time Elapsed: 00:01:15.9297873
========== Finished ==========

I can install other packages so it is not a connectivity issue.

Thanks in advance for your help
Pierre

**Comment by jskeet** [comment]
Hmm... I've just tried it, and it all went through fine, in a total of 13 seconds.

What happens if you try installing *just* Google.Apis through the NuGet dialog?

Has this been happening consistently, or was it possibly just a network glitch at that point?

**Comment by PI2R** [comment]
Thanks for looking at it so quickly,

I've been trying many times, tried to install as well goggle.Apis.Vision, .. but every time with the same result.
As you suggested, I tried to install Google.Apis through the Nuget packages manager and got this error:

Attempting to gather dependency information for package 'Google.Apis.1.34.0' with respect to project 'Test', targeting '.NETFramework,Version=v4.5'
An error occurred while retrieving package metadata for 'Google.Apis.1.34.0' from source 'nuget.org'.
  The download of 'https://api.nuget.org/v3/registration3-gz-semver2/google.apis/index.json' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
Time Elapsed: 00:01:00.5986043
========== Finished ==========

I tried from another VM I have locally (same public IP) and which has a Visual Studio 2015 and it worked straight away for Google.Apis

Could it be a windows firewall thing or is it an issue with VS2017?
Did you try with a VS2017 pro?

**Comment by PI2R** [comment]
Just tried to turn off windows firewall and same result...

**Comment by jskeet** [comment]
I only used VS2017 Community Edition, but it definitely sounds like it's a local issue with the networking. In particular, that URL downloads fine for me. What happens if you try to download that in a browser on the "broken" machine? Perhaps there's a proxy issue?

I'll close this issue as it's not about the *code* in any of the packages - but I suggest you look carefully at the networking configuration on that VM.

**Comment by PI2R** [comment]
Both VMs were on the same host (my local machine).
This URL does not work even from a browser from any of the VMs (even the one that worked with VS2015) or the loal host machine.
I get:
This site can’t be reached
The webpage at https://api.nuget.org/v3/registration3-gz-semver2/google.apis/index.json might be temporarily down or it may have moved permanently to a new web address.
ERR_SPDY_PING_FAILED

But if I remove the end of the URL and just try to browse to 
https://api.nuget.org/v3/registration3-gz-semver2/google.apis
Then it works straight away and returns

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:9183f0e1-701e-004a-4352-fb0032000000 Time:2018-06-03T15:46:42.8589401Z
</Message>
</Error>

So it does not look to be proxy issue to me.

**Comment by jskeet** [comment]
Indeed, that fails for me too, but I'm not sure why you'd expect to be able to change the URL arbitrarily.

https://api.nuget.org/v3/registration3-gz-semver2/google.apis/index.json still works for me (with Chrome and Edge, and curl). You might want to try asking on a nuget.org support page - I don't know why some packages would be failing for you and others not.

**Comment by jskeet** [comment]
(It's possible that your closest api.nuget.org server is having problems, of course - that would explain why it works for me but not for you. It wouldn't explain why other packages work though.)

**Comment by PI2R** [comment]
My point was not about the arbitray/shorter one not working, but about not having issues to be resolved. Meaning it might not be a proxy issue.

Also https://api.nuget.org/v3/registration3-gz-semver2/google.apis/index.json does not work either on the VM where I had no problem installing the client from VS2015

Meaning that this file might not be required for VS2015

I tried from a VM located else where (even in another country), and it worked!

So indeed, must be related to something around my area. But I am not in the desert either ;-)
