### ISSUE TITLE
Grpc System.ObjectDisposedException: Safe handle has been closed

### ISSUE THREAD

**Issue by fromm1990** [GoogleCloudPlatform/google-cloud-dotnet#2210]
When stopping a service using Pub/Sub and running on Google App Engine, the following stacktrace is received.

```csharp 
System.ObjectDisposedException: Safe handle has been closed
    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef
    at System.StubHelpers.StubHelpers.SafeHandleAddRef
    at Grpc.Core.Internal.ChannelSafeHandle.CreateCall
    at Grpc.Core.Internal.AsyncCall`2.CreateNativeCall
    at Grpc.Core.Internal.AsyncCall`2.Initialize
    at Grpc.Core.Internal.AsyncCall`2.StartDuplexStreamingCall
    at Grpc.Core.Calls.AsyncDuplexStreamingCall[TRequest,TResponse]
    at Grpc.Core.DefaultCallInvoker.AsyncDuplexStreamingCall[TRequest,TResponse]
    at Grpc.Core.Internal.InterceptingCallInvoker.AsyncDuplexStreamingCall[TRequest,TResponse]
    at Google.Cloud.PubSub.V1.Subscriber.SubscriberClient.StreamingPull
    at Google.Api.Gax.Grpc.ApiBidirectionalStreamingCall.<>c__DisplayClass0_0`2.<Create>b__0
    at Google.Api.Gax.Grpc.ApiBidirectionalStreamingCall`2.Call
    at Google.Cloud.PubSub.V1.SubscriberServiceApiClientImpl.StreamingPull
    at Google.Cloud.PubSub.V1.SubscriberClientImpl.SingleChannel.<StartAsync>d__18.MoveNext
```
For the project we use ASP.NET Core with [this](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.PubSub.V1/index.html) library to handle the Pub/Sub communication. The issue is not present while debugging locally, using the Pub/Sub emulator. Therefore, we assume that it has something to do with the way App Engine phases out the docker container? Only catching the exception will not be a satisfying solution as we risk leaving handled messages unacknowledged. Can we in any way fix this issue so we can stop our service in a safe way?

Thanks in advance.

**Comment by chrisdunelm** [comment]
@fromm1990 We've just released a new version of the pubsub library, [v1.0.0-beta18](https://www.nuget.org/packages/Google.Cloud.PubSub.V1/1.0.0-beta18).
Please can you try this new version and see if this fixes the problem?

Are you stopping the pubsub subscriber using `StopAsync(...)`, and waiting for the returned `Task` to complete, before the docker container is stopped? This is required to ensure all message Acks are sent.

But note that pubsub does not guarantee that a message is only received once. Your code must be prepared to handle duplicate messages.

**Comment by fromm1990** [comment]
I found out that the error was within my code... I am using an IHostedService in ASP.NET Core and stopping the subscriber with the following approach:

```csharp 
stoppingToken.Register(async () => await StopPubSub());
```

However this will fire and forget and will therefore not wait for the client to stop properly before disposing the objects inside the service provider. As I use Google.Cloud.Diagnostics.AspNetCore (which is registered in the service provider and uses Grpc) to log some useful debug statements, it is able to be disposed before end usage.

The bug where the application freezes while stopping the Pub/Sub SubscriberClient is still present, however, i should make this as an new issue.

**Comment by chrisdunelm** [comment]
@fromm1990 Thanks for updating this issue. I'll close it.
I see you've also updated #2243; if you discover anything further about a freeze on shutdown please add the details there. I've very occasionally seen shutdown take considerably longer than I would expect, but not seen a freeze; so more details would be very useful.
Thanks.
