### ISSUE TITLE
How I can use Firestore in C# ? FirestoreDb  is misising on internet.

### ISSUE THREAD

**Issue by anirugu** [GoogleCloudPlatform/google-cloud-dotnet#2246]
I have searched FirestoreDB on nuget, didn't find it there.  reading it in answer like this
 https://stackoverflow.com/questions/48310787/google-firestore-import-data-from-sql-server-with-c-sharp?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

someone tell me how I can do CRUD in firestore. I have installed beta5 in my c# project but not sure how to get started.

Thanks

---
http://jskeet.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore.Data/

**Comment by jskeet** [comment]
`Google.Cloud.Firestore` is definitely the library to use - if you didn't find it on NuGet, it may be that you weren't including pre-release libraries (it's at 1.0.0-beta05 at the moment).

The right place to go for documentation from this repo is [here](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/index.html) (and the [user guide](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/userguide.html)).

There's also the [main Firestore documentation](https://firebase.google.com/docs/firestore/) which includes samples in C#.

**Comment by anirugu** [comment]
@jskeet  thanks for the help, I later fix this.

**Comment by jskeet** [comment]
Okay, it sounds like it's fine to close this now.
