### ISSUE TITLE
ArgumentException: Conversion from DateTime to Timestamp requires the DateTime kind to be Utc Parameter name: dateTime

### ISSUE THREAD

**Issue by anirugu** [GoogleCloudPlatform/google-cloud-dotnet#2247]
I am reading from MySQL and adding that dynamic object to Firebase.

```
for each (dynamic a in ABC)
            {
                DocumentReference document = collection.AddAsync(a).Result;
            }
```

The problem is it doesn't work.  It's showing error ArgumentException: Conversion from DateTime to Timestamp requires the DateTime kind to be Utc
Parameter name: dateTime

Someone, please check it it's an issue, the date in MySQL table is 25 Jan 2018. it's not invalid neither it's null.
the object am I entering is reading from the database using dapper  (dapper's ienumerable<dynamic>)

**Comment by anirugu** [comment]
whoever see trouble like this, use this

 abc.a= DateTime.SpecifyKind(abc.a, DateTimeKind.Utc);

**Comment by jskeet** [comment]
That's the right approach if the date actually represented UTC already. It isn't always the right way - it depends on the context. This important point is that you need to come up with a UTC value, in whatever way makes sense for you.

Will close this issue now as I don't believe any changes are required in the code.

**Comment by anirugu** [comment]
If someone comes here from a search, I suggest you choose 2 option ( I didn't try it since I have moved on from this issue).

you can either do something with  dapper so all DateTime will be set as  UTC
https://stackoverflow.com/questions/12510299/get-datetime-as-utc-with-dapper

or you can modify your connectionstring to set the timzone UTC in MySQL, here is a nice answer on stackoverflow for doing it https://stackoverflow.com/a/36793896/713789
