### ISSUE TITLE
compiled 'DLL' google-cloud-dotnet

### ISSUE THREAD

**Issue by livein21st** [GoogleCloudPlatform/google-cloud-dotnet#2253]
Is it possible to create a DLL file from the current google -cloud-dotnet library and then use it in a platform like unity?

**Comment by jskeet** [comment]
There are DLLs in the NuGet packages already, but I'm afraid Unity is not a supported platform at the moment, for various reasons. (Most importantly, gRPC has a native component which would need packaging differently.) We would like to support Unity in the future, but it doesn't work at the moment.
