### ISSUE TITLE
Remove isWindows checks in Diagnostics code tests

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#2255]
This was adding when creating the libraries with very early versions of .NET Core.  I do nothing think this is an issue anymore.

**Comment by amanda-tarafa** [comment]
This is still not possible, the tests that depend on the isWindows check fail when targeting netcoreapp1.0 in the jenkins-ubuntu environment, netcoreapp2.0 does work in jenkins-ubuntu though.
Closing for now as infeasible.
