### ISSUE TITLE
Incomplete description Google.Cloud.Firestore.CollectionReference.Document()

### ISSUE THREAD

**Issue by DenSmoke** [GoogleCloudPlatform/google-cloud-dotnet#2263]
Method has description: 
"Creates a Google.Cloud.Firestore.DocumentReference for a child document of this reference."
But method also returns existing document when parameter "path" is specified.

**Comment by jskeet** [comment]
Could you let me know where you're seeing this? The source code has a comment of:

```csharp
/// Creates a <see cref="DocumentReference"/> for a direct child document of this collection with a random ID.
/// This performs no server-side operations; it only generates the appropriate <c>DocumentReference</c>.
```

Perhaps you're using an older version of the API?

**Comment by DenSmoke** [comment]
![image](https://user-images.githubusercontent.com/16131575/41483064-55bd773a-70e0-11e8-85ae-05c02225e775.png)
I have installed via NuGet Google.Cloud.Firestore 1.0.0-beta05.
I mean the description doesn't give full information about method. I was little confused how I should get a document from collection, because description says that method Document() only creates new document. I think description should be complemented

**Comment by jskeet** [comment]
Right, so you're looking at the documentation for `Document(string)`, not `Document()`. I was quoting the documentation for the parameterless `Document()` documentation.

But it doesn't say it creates a new document - it creates a new `DocumentReference`, which isn't the same thing at all. A `DocumentReference` doesn't necessarily exist server-side - it's like a file path. I don't think it would be appropriate to put all of those details in the summary documentation shown in Intellisense; it's much more appropriate for the [conceptual user guide](https://firebase.google.com/docs/firestore/data-model).
