### ISSUE TITLE
Problem with google.cloud.firestore on Windows 7 app.

### ISSUE THREAD

**Issue by gbaccetta** [GoogleCloudPlatform/google-cloud-dotnet#2264]
Hello, 

I'm having an issue using the library charged with nuget.
Using the release package I'm getting this error:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Google.Cloud.Firestore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0' or one of its dependencies. The system cannot find the file specified.
File name: 'Google.Cloud.Firestore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0'
```
Also, 
when running via visual Studio I get a different error:
```
Exception thrown: 'System.ArgumentNullException' in Google.Protobuf.dll
Exception thrown: 'Grpc.Core.RpcException' in mscorlib.dll
Exception thrown: 'Grpc.Core.RpcException' in mscorlib.dll
Exception thrown: 'Grpc.Core.RpcException' in mscorlib.dll
Exception thrown: 'Grpc.Core.RpcException' in mscorlib.dll
Exception thrown: 'Grpc.Core.RpcException' in mscorlib.dll
Exception thrown: 'Grpc.Core.RpcException' in mscorlib.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Exception has been thrown by the target of an invocation.
```
My App config:
```
<packages>
  <package id="Google.Api.CommonProtos" version="1.2.0" targetFramework="net45" />
  <package id="Google.Api.Gax" version="2.4.0" targetFramework="net45" />
  <package id="Google.Api.Gax.Grpc" version="2.4.0" targetFramework="net45" />
  <package id="Google.Apis" version="1.34.0" targetFramework="net45" />
  <package id="Google.Apis.Auth" version="1.34.0" targetFramework="net45" />
  <package id="Google.Apis.Core" version="1.34.0" targetFramework="net45" />
  <package id="Google.Cloud.Firestore" version="1.0.0-beta05" targetFramework="net45" />
  <package id="Google.Cloud.Firestore.V1Beta1" version="1.0.0-beta05" targetFramework="net45" />
  <package id="Google.LongRunning" version="1.0.0" targetFramework="net45" />
  <package id="Google.Protobuf" version="3.5.1" targetFramework="net45" />
  <package id="Grpc.Auth" version="1.12.0" targetFramework="net45" />
  <package id="Grpc.Core" version="1.12.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net45" />
  <package id="System.Collections.Immutable" version="1.4.0" targetFramework="net45" />
  <package id="System.Interactive.Async" version="3.1.1" targetFramework="net45" />
  <package id="System.Net.Http" version="4.3.1" targetFramework="net45" />
</packages>
```
any suggestion would be appreciated

**Comment by jskeet** [comment]
When you say "Windows 7 app" do you mean a UWP application? If so, I'm afraid that's not a supported platform. If you mean something else, please could you give us more information?

**Comment by gbaccetta** [comment]
Hello,
yes unfortinately I was speaking about a desktop application for end user. Now UPF but plain old executable but I guess it is the same. I lost quite some time trying to get it to work, now I understand why.
I switched to use plain REST API instead. Thank you

**Comment by jskeet** [comment]
"Plain old executable" could be anything really - more information would really help. Windows Forms? WPF? I'm afraid without more specific detail - and ideally a way of reproducing the problem - we're unlikely to be able to help.

**Comment by gbaccetta** [comment]
Oh, sorry, I understood that in any case that was not working for Windows seven.
It is a Windows Forms App developed on Visual Studio 15.5.0

**Comment by jskeet** [comment]
Okay, that's good to know.

If you still have the failing project, are you able to check whether there's a `grpc_csharp_ext.x64.dll` file in the directory you're running it from? (Presumably the bin directory.) If you have fuller logs of those exceptions, that would be useful too. (If this is a Windows 7 specific problem, I think it's unlikely that we'll try to solve it though, given that it's been outside mainstream support for the last few years.)

**Comment by gbaccetta** [comment]
Unfortunately right now I prefer to do not roll back to previous implementation since I need to keep my schedule. However, the `grpc_csharp_ext.x64.dll` is still in my project. However when I was encountering the issue I was running the program from another directory where that was not copied. Thus this may very well be the problem.
If I have some time this afternoon or tomorrow I'll try to make a quick roll back to check what it happens if I had the file manually in the launch directory.

**Comment by jskeet** [comment]
Ah - if the DLL wasn't in the same directory as the rest of the assemblies, that would certainly explain everything.

I'm going to close this as I don't think there's anything more to be done here, but if the problem comes back or you can reproduce it easily later, we can reopen at that point.
