### ISSUE TITLE
Google.Protobuf.InvalidProtocolBufferException: 'Unknown field: version'

### ISSUE THREAD

**Issue by vbucchare** [GoogleCloudPlatform/google-cloud-dotnet#2265]
When calling my fulfillment from DialogFlow everything is working great, however when I call it from Google Actions, a Google.Protobuf.InvalidProtocolBufferException: 'Unknown field: version' error is thrown.

I took the example below from #2099 as I couldn't pull my specific request, but the problem is the same. 

`"originalDetectIntentRequest": {
    "source": "google",
    "version": "2",  <========  error!
    "payload": {
      "isInSandbox": true,
      "surface": {
        "capabilities": [{
          "name": "actions.capability.MEDIA_RESPONSE_AUDIO"
        }, {
          "name": "actions.capability.WEB_BROWSER"
        }, {
          "name": "actions.capability.AUDIO_OUTPUT"
        }, {
          "name": "actions.capability.SCREEN_OUTPUT"
        }]
      }`

I've set IgnoreUnknownFields to True as work-around.

Thanks!

**Comment by jskeet** [comment]
Could I check that you mean "when I call it from the Google Actions Simulator" as per the other issue?

I suspect this is a bug either in the protobuf message itself or in the simulator, rather than in either the codegen or any manually-written code here, but I'll treat it as a bug anyway. I'm glad the workaround works for you in the mean time.

**Comment by vbucchare** [comment]
When executing my dialog flow intent from the Google Actions Simulator, that error is encountered. When using the DialogFlow "Try it Now" it works fine. The symptoms are exactly as the same as the other issue, #2099.

**Comment by jskeet** [comment]
I've reported this internally, as it's odd for the simulator to provide a field that is neither documented nor sent by the real product.

However, I think it actually makes sense to parse the JSON leniently anyway, to allow for the protocol expanding over time. So the workaround is probably the right thing to do anyway, basically.

I'm going to close this issue now as I don't believe there's anything specific to address in this repo - beyond the existing problem of not enough documentation for implementing web hooks.
