### ISSUE TITLE
Return Type of ListTopics

### ISSUE THREAD

**Issue by harrisse** [GoogleCloudPlatform/google-cloud-dotnet#2290]
Hello, I'm a little confused by the return type of `ListTopics` and was wondering if someone could help clarify. I want to list all topics for my project by paging through the `ListTopics` method. I was expecting to get a `ListTopicsResponse` back from `ListTopics` but actually got a `PagedEnumerable<ListTopicsResponse, Topic>` which exposes `IEnumerable<ListTopicsResponse> AsRawResponses()`. Does `AsRawResponses` always contain one `ListTopicsResponse`? If not, under what circumstances would it contain multiple, and in that case which `NextPageToken` do I pass to my next call to `ListTopics`?

**Comment by jskeet** [comment]
The aim of `PagedEnumerable` is to avoid you having to write the code to keep track of page tokens etc. The sequence returned by `AsRawResponses()` would contain multiple responses if the topics couldn't all be returned by a single RPC.

We have a [documentation page](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/guides/page-streaming.html) which explains things in more detail, including samples.

If that doesn't help, please let me know what you're trying to achieve, and I can help suggest how you'd do that with `PagedEnumerable<,>`.

**Comment by harrisse** [comment]
Ah perfect, thanks!
