### ISSUE TITLE
Call to RunQuery never completes.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#231]
Code is here:
https://github.com/SurferJeffAtGoogle/getting-started-dotnet/blob/datastoreVeneer/aspnet/2-structured-data/Models/DatastoreBookStore.cs

![runquery](https://cloud.githubusercontent.com/assets/11778530/16202771/058d2454-36cc-11e6-8378-0a503c6a1c2b.gif)

**Comment by jskeet** [comment]
Will try to reproduce, and if I can't reproduce I'll at least see if I can work out how to get more diagnostics.

**Comment by jskeet** [comment]
Just pulled and edited to use my project ID - and it's working for me. How many books are there in your project? I only have 3... I wonder whether that's relevant.

**Comment by SurferJeffAtGoogle** [comment]
There are between 10 and 20 books in my project.

**Comment by jskeet** [comment]
I think I *may* have it. I suspect the problem is how that old build did the pagination - I *suspect* it was requesting page after page, but never stopping due to #225. However, that doesn't explain why it was intermittent, or why the gRPC tracing didn't work. More to dig into.

**Comment by jskeet** [comment]
Is this now obsolete? Have you seen it in the last few months?

**Comment by jskeet** [comment]
Ping?

**Comment by SurferJeffAtGoogle** [comment]
Obsolete.
