### ISSUE TITLE
GoogleStackdriverAppender doesn't allow for custom credentials

### ISSUE THREAD

**Issue by eug48** [GoogleCloudPlatform/google-cloud-dotnet#2314]
There is a `CredentialFile` property but please consider something like `CredentialJson` or a more generic `Credential`. That would be useful for loading the credential data for example from encrypted storage, DPAPI, or some vault rather than from a plain file on disk.

Thanks!

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net/GoogleStackdriverAppender.cs#L204

**Comment by chrisdunelm** [comment]
Not including support for the more generic `GoogleCredential`, as we don't want to have any direct dependencies from libraries in this repo to auth in the `Google.Apis.Auth` package.

**Comment by chrisdunelm** [comment]
Now release to nuget.org as [2.3.0-beta01](https://www.nuget.org/packages/Google.Cloud.Logging.Log4Net/2.3.0-beta01)
