### ISSUE TITLE
PubSub: ack (or nack) messages in batches later

### ISSUE THREAD

**Issue by dmsolow** [GoogleCloudPlatform/google-cloud-dotnet#2326]
For my application I want to use the asynchronous API as follows:

1. Messages are received and added to batch
2. Once batch reaches target size, it is processed
3. If processing is successful, ack every message in batch. Otherwise nack every message in batch
4. Clear batch and continue

I've done this before in the Python client, but I'm having trouble with C#. My issue is that I can't figure out how to ack the message outside the callback that's passed to `StartAsync`. 

I don't think this kind use-case is unusual. It's often far more efficient to process things in batches.

I'm new to C# so there might be an obvious way to do this.

**Comment by chrisdunelm** [comment]
There is no way to ack the message outside of the callback.

However, the callback is async, and there will be no problem with your code returning a `Task` that completes when your batch processing is done.
The only thing to bear in mind is that the level of callback concurrency allowed is limited [by default to 10,000 messages or 20Mb](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClient.cs#L187); or this can be overridden by setting [`Settings.FlowControlSettings`](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClient.cs#L87). Make sure that your processing batch size is within the limits specified in the `FlowControlSettings`.

**Comment by dmsolow** [comment]
Thanks for your response. I managed to get this working as your described.

**Comment by chrisdunelm** [comment]
Glad to hear it's sorted out :)
