### ISSUE TITLE
[Google.Cloud.Datastore.V1]: v2.1.0 - broken NuGet references

### ISSUE THREAD

**Issue by hhblaze** [GoogleCloudPlatform/google-cloud-dotnet#2331]
After default installation via NuGet of Google.Cloud.Datastore.V1 with all its dependencies (.NET Framework 4.5), 
main assembly can't load "Google.Apis.Auth, Version=1.34.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab" and stops with System.IO.FileLoadException.

Careful look shows that there is no NuGet dependenciy on  "Google.Apis.Auth, Version=1.34" only on "Google.Apis.Auth, Version=1.30". 
Nevertheless, it needs v 1.34 

![image](https://user-images.githubusercontent.com/486781/42644009-d56f3106-85fa-11e8-9b9b-51b64d95b431.png)

Conclusion is that there is a difference between the dependency inside the Nuget manifest and real assembly dependency for one(or more) of the referenced DLLs. 
DLLs inside the Release folder are attached to the issue (except .dylib and .so libraries).

[Google.Net.DataStore.zip](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/files/2189301/Google.Net.DataStore.zip)

**Comment by jskeet** [comment]
Can you help us reproduce this? If I create a new console app targeting .NET 4.5 and add a reference *just* to Google.Cloud.Datastore.V1, would you expect that to demonstrate the problem? Is this an "old-style" project, or a "new-style" one?

My guess is that you've got a *separate* reference other than the ones you've shown here that depends on 1.34, but let's try to reproduce it first...

**Comment by jskeet** [comment]
Another possibility is that you've got assembly binding redirects that are doing the wrong thing - it's quite easy for those to get out of sync. Could you check that please?

**Comment by jskeet** [comment]
I've just tried this:

- Create a console app targeting .NET 4.5
- Add a NuGet reference to Google.Cloud.Datastore.V1 version 2.1.0
- Write the code below
- Run on the command line, passing in your project ID
- It should just finish with no exception

Code:

```csharp
using Google.Cloud.Datastore.V1;

namespace Issue2331
{
    class Program
    {
        static void Main(string[] args)
        {
            DatastoreDb db = DatastoreDb.Create(args[0]);
            var keyFactory = db.CreateKeyFactory("bogus");
            var entity = db.Lookup(keyFactory.CreateKey(1L));
            
        }
    }
}
```

Resulting assembly binding redirects:

```xml
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-1.30.0.0" newVersion="1.30.0.0" />
  </dependentAssembly>
  <dependentAssembly>
    <assemblyIdentity name="Google.Apis.Auth.PlatformServices" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-1.30.0.0" newVersion="1.30.0.0" />
  </dependentAssembly>
</assemblyBinding>
```

My guess is that if you look in your assembly binding redirects, they'll be using 1.34 for Google.Apis.Auth.

**Comment by hhblaze** [comment]
I will look asap, thanx!

**Comment by hhblaze** [comment]
if it is a pure installation via NuGet I got following binding redirects:

```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">     
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.30.0.0" newVersion="1.30.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth.PlatformServices" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.30.0.0" newVersion="1.30.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Protobuf" publicKeyToken="a7d26565bac4d604" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.6.0.0" newVersion="3.6.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.CommonProtos" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.3.0.0" newVersion="1.3.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Interactive.Async" publicKeyToken="94bc3704cddfc263" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.Gax.Grpc" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.4.0.0" newVersion="2.4.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.Gax" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.4.0.0" newVersion="2.4.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" /></startup></configuration>
```

and it fails with System.IO.FileLoadException:
"Google.Apis.Auth, Version=1.21.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab"

if I update via NuGet all Google dependency components, having e.g. Google.Apis.Auth of version 1.34.0
I got another binding redirects:

```XML
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.34.0.0" newVersion="1.34.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth.PlatformServices" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.34.0.0" newVersion="1.34.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Protobuf" publicKeyToken="a7d26565bac4d604" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.6.0.0" newVersion="3.6.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.CommonProtos" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.3.0.0" newVersion="1.3.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Interactive.Async" publicKeyToken="94bc3704cddfc263" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.Gax.Grpc" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.4.0.0" newVersion="2.4.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.Gax" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.4.0.0" newVersion="2.4.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
```

it also fails, but with another System.IO.FileLoadException:
"Google.Protobuf, Version=3.3.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604"

**Comment by hhblaze** [comment]
It ends as a DLL (GM_HurryCan.dll) that is dynamically loaded by the host. 
In a folder it looks like
![image](https://user-images.githubusercontent.com/486781/42708860-cf15fd50-86de-11e8-89d7-8d9647640020.png)

It is the first try to attach Datastore to this project. In Debug there is no problems - all works. When I compile the Release and try the standard load via the host it generates those (FileLoadException) mistakes and logs them.

**Comment by jskeet** [comment]
Right, this sounds like it has very little to do with our NuGet packages then - it sounds like the host isn't loading the config file and applying the assembly binding redirects. This will make it pretty much impossible to use for any significant number of dependencies in modern .NET... the chances of all the common dependencies being *exactly* the same version are pretty much nil.

I'm afraid we don't support environments where packages can't be used as expected like this. I don't know what "host" you're using, but it really needs to support assembly binding redirects.

I'm going to close this issue now as I don't see any evidence of this being a problem with the packages we're producing. If you come across such evidence, of course we can reopen the issue.

**Comment by hhblaze** [comment]
Absolutely right! Assembly was loaded via AppDomain.CreateDomain.
Problem is solved by explicit setting ConfigurationFile property as a  path to ".dll.config"
``
AppDomainSetup setup = new AppDomainSetup()
                {
                    ApplicationBase = AppDomain.CurrentDomain.BaseDirectory,
                    ConfigurationFile = "path to .dll.config")
                };

Thanx a lot!
