### ISSUE TITLE
Add Model and UseEnhanced to RecognitionConfig for Speech to Text

### ISSUE THREAD

**Issue by shaunbowe** [GoogleCloudPlatform/google-cloud-dotnet#2333]
This feature exists in the Python and Java SDKs. 

https://cloud.google.com/speech-to-text/docs/enhanced-models#speech-enhanced-model-protocol

**Comment by jskeet** [comment]
That's in the [v1p1beta1](https://github.com/googleapis/googleapis/blob/master/google/cloud/speech/v1p1beta1/cloud_speech.proto) release, which the Cloud Speech team hasn't asked us to generate for C# yet. I can ask on Monday whether they'd be happy for us to do so, but it may well be that they only want a more limited release for targeted feedback for now.

**Comment by shaunbowe** [comment]
I would greatly appreciate it. I tried with and without the UseEnhanced flag and it is a night and day difference. In the meantime if there is any way to use this SDK with those fields I would do that. I tried the Merge* methods with no success.

**Comment by jskeet** [comment]
This is now published as Google.Cloud.Speech.V1P1Beta1.
