### ISSUE TITLE
Implement Cloud Storage signedURL

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/google-cloud-dotnet#235]
Similar to signedURL on other gcloud-libraries:

http://googlecloudplatform.github.io/gcloud-python/latest/storage-blobs.html#gcloud.storage.blob.Blob.generate_signed_url

**Comment by jskeet** [comment]
Will have to look at what's involved here. This won't make the cut for beta, but we should be able to add it later. It's not immediately clear to me how it fits in with our authentication approach - as our library doesn't have access to the credentials necessarily, it could be a bit ugly - but we'll cross that bridge when we come to it.

**Comment by jskeet** [comment]
Done in #516 and #531.
