### ISSUE TITLE
[Firestore] Authenticate as Firebase user

### ISSUE THREAD

**Issue by ricsmania** [GoogleCloudPlatform/google-cloud-dotnet#2354]
I have a scenario in which I have a Node application that runs on each of my customer's hardware and connects to Firestore using the Firebase JS SDK (not admin), and I also authenticate with a Firebase user because each customer can only read and write their own data. Is there a way to do that with the .Net SDK?

**Comment by jskeet** [comment]
No, as far as I'm aware the Firestore Server SDKs *all* authenticate via Google Service Account credentials, not with Firebase credentials.

@schmidt-sebastian can confirm this.

**Comment by jskeet** [comment]
Closing the issue as there's no more work required for this repo.

**Comment by cirvladimir** [comment]
What would it take to get this to work? If I have the user session access token and all other app tokens in hand, can I just override some base grpc call to pass those on?

**Comment by jskeet** [comment]
@cirvladimir: No, I don't believe so. As @schmidt-sebastian said, this isn't a supported scenario.

**Comment by schmidt-sebastian** [comment]
While this is a popular feature request, this requires both backend and client work that is still pending. I am sorry that we don't have better news for now.

**Comment by ricsmania** [comment]
@schmidt-sebastian I understand the reasons, now I'm just curious about what would need to be changed on the backend. Isn't the backend code platform independent, so that the dotnet client could use the same authentication method as the Javascript SDK?
