### ISSUE TITLE
NLog serialization defaults

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-dotnet#2355]
From comment in PR #2300:
> Though it will probably require some logic to configure the serialiser  (Enum conversion, Dictionary-key-cleanup, Skip Exception TargetSite, RecursionLevel, ReferenceLoop-Handling, etc). Newtonsoft is nice for controlled types but can go crazy when random objects like exceptions (And their custom Data-dictionary).

This needs deciding and coding/testing before the next release

**Comment by snakefoot** [comment]
Created PR for improving on this #2384

**Comment by chrisdunelm** [comment]
@snakefoot I don't consider protection from "serializing the world" is required.
Users should recognise that they can't just throw ***any*** object at this and expect it to work. And if a user has a particular serialization requirement, then they can use a custom serializer.
So I'm happy to call this done and close this issue. What do you think?

**Comment by snakefoot** [comment]
@chrisdunelm Have thought about exposing the serialization logic in NLog a little more (used for JSON-output). Thus using that engine to provide controlled serialized output (Nested Collections of simple types).

But no need for this issue to stay open for that to complete.

**Comment by chrisdunelm** [comment]
OK, closing this issue.
