### ISSUE TITLE
Vision API Dependency Issue

### ISSUE THREAD

**Issue by aschlumpf** [GoogleCloudPlatform/google-cloud-dotnet#2358]
Hi,

I am trying to integrate Google Vision API into a UI on our IIS-based system, but I have run into an issue getting the API calls to work. To be clear, I have the API working successfully on a console application. However, in a separate use case, we need to make a .dll file for a UI. For this use case, we keep getting a dependency conflict for Google.Apis.Auth, expecting 1.21.0.0, but we have 1.32.2.0. The API was installed using Nuget, so I am unsure why this conflict is happening. We also had to add the assembles to the GAC to resolve a different issue. The solutions I have read in threads such as [this](https://stackoverflow.com/questions/51074434/having-issue-while-using-google-vision-ocr-api-when-hosted-on-iis) have not worked.

**Comment by jskeet** [comment]
> We also had to add the assembles to the GAC to resolve a different issue.

That sounds like it may well be part of the problem. That's certainly a scenario we haven't tested. I would strongly advise *removing* the Google assemblies from the GAC. We can have a look at this "different issue" separately.

Please then describe your situation in more detail, ideally with a way we can reproduce the problem. Note that the *application* should pick up all the dependencies via NuGet, or be configured with appropriate assembly binding redirects. If you've used NuGet to create a class library, but then added a direct file reference to the DLL from your UI project, that could explain the problem.

**Comment by aschlumpf** [comment]
When removing the assemblies from the GAC, we face a different but similar issue. Instead of there being a FileNotFoundException due to a versioning conflict with Google.Apis.Auth, a FileNotFoundException is thrown for Google.Cloud.Vision.V1 itself. The reason why we believed adding the assemblies to the GAC to be the solution is that when we add Google.Cloud.Vision.V1 to the GAC, a different assembly has this error. We go down the tree and arrive at having them all in the GAC. Once they're all in, this is when we encounter the error this thread was posted about.

For reference, the call we are testing this error with is simply

`ImageAnnotatorClient client = ImageAnnotatorClient.Create();

The exact error is:

System.IO.FileNotFoundException was unhandled by user code
  HResult=-2147024894
  Message=Could not load file or assembly 'Google.Cloud.Vision.V1, Version=1.2.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0' or one of its dependencies. The system cannot find the file specified.
  Source=GoogleVisionLinks
  FileName=Google.Cloud.Vision.V1, Version=1.2.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0
  FusionLog==== Pre-bind state information ===
LOG: DisplayName = Google.Cloud.Vision.V1, Version=1.2.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0
 (Fully-specified)
LOG: Appbase = file:///E:/Adam/Studios/Products/
LOG: Initial PrivatePath = E:\Adam\Studios\Products\bin
Calling assembly : GoogleVisionLinks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: E:\Adam\Studios\Products\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Google.Cloud.Vision.V1, Version=1.2.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/products/ad62903d/e2049733/Google.Cloud.Vision.V1.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/products/ad62903d/e2049733/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.DLL.
LOG: Attempting download of new URL file:///E:/Adam/Studios/Products/bin/Google.Cloud.Vision.V1.DLL.
LOG: Attempting download of new URL file:///E:/Adam/Studios/Products/bin/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/products/ad62903d/e2049733/Google.Cloud.Vision.V1.EXE.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/products/ad62903d/e2049733/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.EXE.
LOG: Attempting download of new URL file:///E:/Adam/Studios/Products/bin/Google.Cloud.Vision.V1.EXE.
LOG: Attempting download of new URL file:///E:/Adam/Studios/Products/bin/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.EXE.
LOG: Attempting download of new URL file:///E:/Adam/WorkingFolder/Assembly Cache/Google.Cloud.Vision.V1.DLL.
LOG: Attempting download of new URL file:///E:/Adam/WorkingFolder/Assembly Cache/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.DLL.
LOG: Attempting download of new URL file:///E:/Adam/WorkingFolder/Assembly Cache/Google.Cloud.Vision.V1.EXE.
LOG: Attempting download of new URL file:///E:/Adam/WorkingFolder/Assembly Cache/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.EXE.

  StackTrace:
       at GoogleVisionLinks.VisionLinkUI.CreateTable(Aspect a)
       at GoogleVisionLinks.VisionLinkUI.CreateSubmitDialog(Aspect a)
       at GoogleVisionLinks.VisionLinkUI.CreateChildControls()
       at System.Web.UI.Control.EnsureChildControls()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
  InnerException: 

Somehow this error causes such an issue that when debugging the method that the API call is in doesn't even get stepped into it. The API call is dozens of lines after the method definition, and the method doesn't seem to run at all when stepping line by line.`

**Comment by jskeet** [comment]
Okay, let's stick with "not in GAC" mode (as that's the supported one). Please could you provide a way of me reproducing the problem? The exact version of the framework you're targeting, project type and dependency list would be really useful. Once I can reproduce the problem, it'll be much easier to help you.

You should also have a look at the generated .config file to see what assembly binding redirects are present.

**Comment by aschlumpf** [comment]
> You should also have a look at the generated .config file to see what assembly binding redirects are present.

Do you mean the app.config? The redirects present there look appropriate. As for the framework - we are on 4.5, the project is a class library, and we have used Nuget to install Vision API and its dependencies.

**Comment by aschlumpf** [comment]
I decided to take an alternative route and have the API up and running without using a class library. I apologize for wasting your time.

**Comment by SysRobt** [comment]
@aschlumpf : What did you do to resolve this issue?
