### ISSUE TITLE
Google Speech client not getting created.

### ISSUE THREAD

**Issue by sleepy123** [GoogleCloudPlatform/google-cloud-dotnet#2371]
```
 public static async Task Initial1()
        { // a
          
            rec1 = true;
            speech = SpeechClient.Create(); //b
            streamingCall = speech.StreamingRecognize();
            writeLock = new object();
            writeMore = true;
            waveIn = new WaveIn();
            .......
         } //c
```
This is a part of my C# code. It is running fine till the 2nd line  speech = SpeechClient.Create();
This SpeechClient.Create is setting the speech variable as null and then jumping to 'c'.
It works perfectly on my computer which has Windows 10 but it is failing on a different computer which has windows 8.1 .
I tried building the app on my windows 10 computer and then running it on the windows 8 computer and it still failed at the same place. The same build is running perfectly on windows 10 computer.

**Comment by sleepy123** [comment]
Hi, i awaited everything but I am still not getting any exception. It is directly jumping from speech = SpeechClient.Create(); to await Initial1():

**Comment by jskeet** [comment]
That really would only happen in the case of an exception. Could you prepare a small but complete example so that I can reproduce the problem? Without being able to reproduce this, it's very hard to help further.

**Comment by jskeet** [comment]
Ping for more information. I'm afraid at the moment we're unable to help further. I *strongly* suspect this is just a matter of the `GOOGLE_APPLICATION_CREDENTIALS` environment being set correctly on one machine but not on another, leading to the task returned by `Initial1()` being faulted on the incorrectly-configured machine.

To avoid clutter in this issues list I'll close this issue in a few days if there aren't any more updates to it. If you are able to provide more information later on (I completely understand that you may be working on multiple projects at the same time) we can easily reopen it.

**Comment by jskeet** [comment]
Closing for now.
