### ISSUE TITLE
Why getting Grpc.Core.RpcException StatusCode=Unavailable, Detail=“Connect Failed”, with Google Cloud Firestore 1.0.0-beta05 C# SetAsync? HTTP/2.0 issue?

### ISSUE THREAD

**Issue by Eamonn-Duffy** [GoogleCloudPlatform/google-cloud-dotnet#2379]
Jon Skeet (@jskeet) suggested we file an issue here.

Jon provided a link that _suggests_ HTTP/2.0 may be used in all traffic.

Is this true?

We are behind a Company Proxy (squid-cache) and it **does not** allow HTTP/2.0 traffic.

If this is the issue, is there any way to downgrade the traffic to HTTP/1.1?

The original issue is as follows:

We are using C# with the Google.Cloud.Firestore.1.0.0-beta05 NuGet package, and we always get a Grpc.Core.RpcException when we try to call SetAsync.

Details:

1. Visual Studio 2017
2. .NET Framework V4.6.2
3. ASP.NET
4. Version: Google.Cloud.Firestore.1.0.0-beta05
5. Date Published: Thursday, June 07, 2018 (6/7/2018)
6. Environment Variable **GOOGLE_APPLICATION_CREDENTIALS** has been set.
7. Proxy configured in web.config per our Company setup.
8. Environment variables http_proxy and https_proxy have been set.

Can anyone help us understand why we get the following?

**Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Connect Failed")**

The relevant snippets follow.

Any help would be greatly appreciated.

Regards,

Eamonn

**C# Method:**

    private async Task FirebaseSetAsync(string projectId)
    {
        var database = FirestoreDb.Create(projectId: projectId);

        var docRef = database.Collection("users").Document("company");

        Dictionary<string, object> user = new Dictionary<string, object>
        {
            { "First", "Alan" },
            { "Middle", "Mathison" },
            { "Last", "Turing" },
            { "Born", 1912 }
        };

        try
        {
            var result = await docRef.SetAsync(user);
        }
        catch (Exception exception)
        {
            Log.Error("Exception.", exception);
        }
    }

**web.config snippet:**

    <system.net>
      <defaultProxy>
        <proxy proxyaddress="http://w.x.y.z:pppp/" />  
      </defaultProxy>
    </system.net>

**Log file snippet:**

20:15:26.938 [   7] [(null)] ERROR FirebaseFive.Controllers.HomeController - Exception.
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Connect Failed")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Firestore.WriteBatch.<CommitAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Firestore.DocumentReference.<SetAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FirebaseFive.Controllers.HomeController.<FirebaseSetAsync>d__1.MoveNext() in D:\Projects\Git\Firebase\FirebaseFive\FirebaseFive\Controllers\HomeController.cs:line 33

**Comment by chrisdunelm** [comment]
@Eamonn-Duffy The firestore package uses HTTP/2.0 only; and unfortunately there is currently no way to downgrade this to use HTTP/1.1

As far as I can see, squid-cache does not yet support HTTP2, so I guess the only options are to bypass the proxy somehow, or change the proxy to one that supports HTTP2.

**Comment by Eamonn-Duffy** [comment]
@chrisdunelm Thank you very much for the clarification. It explains a lot.

Our Systems people need a list of IP Addresses to bypass the Proxy.

Do you know if there is anywhere I can get such a list of IP Addresses for accessing Firestore and any other associated services/domains?

**Comment by chrisdunelm** [comment]
@Eamonn-Duffy I don't think there is a list of such IP addresses; partly because I would expect the IP addresses to change over time and location.

However the hostname used by firebase is "firestore.googleapis.com" ([see the code here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Firestore.V1Beta1/Google.Cloud.Firestore.V1Beta1/FirestoreClient.cs#L514)).

So you might be able to manually lookup the IP addresses used by this hostname - e.g. "nslookup firestore.googleapis.com", and then bypass your proxy for those IP addresses.
If this is just for dev work, you could possibly put one of those IP addresses in your local machine's "hosts" file to force only one IP address for the hostname, and then only bypass the proxy for that one IP address.
Note that I haven't tried this myself to check it definitely works.

**Comment by chrisdunelm** [comment]
@Eamonn-Duffy Thanks for your feedback; it would seem a shame if only a lack of proxy-HTTP2 support prevents you using firestore, especially as HTTP2 is not exactly new so I'm surprised there are still proxies that don't support it!

If we can be of any further help, please do open a new issue.

I'll close this issue now, but yes you can close an issue you open, and yes generally it's correct to close an issue once you feel it's been brought to a conclusion.
