### ISSUE TITLE
Can't use the API with asp.net core 1.0 because of Newtonsoft.Json 9.0.1

### ISSUE THREAD

**Issue by mbergeron** [GoogleCloudPlatform/google-cloud-dotnet#239]
Asp.net core 1.0 is now built agains Newtonsoft.Json 9.0.1.

It now fails to load the key.json for authentification.

Getting this error when trying to load the json key

`The type initializer for "Google.Apis.Json.NewtonsoftJsonSerializer" threw an exception". Could not load file or assembly "Newtonsoft.Json, Version=8.0.0,0`

I guess it comes from the incompatibility of the version 9.0.1 and 8.0.0.0?

Thanks,

**Comment by chrsmith** [comment]
Yes, I believe that is the case. We should probably bump the version of `Newtonsoft.Json` used by the .NET client libraries.

**Comment by jskeet** [comment]
Normally I'd have expected this to be handled by assembly bindings, but I've just experienced the same thing with Noda Time. I wonder whether there's some difference in the way Json.NET 9.0.1 handles versioning.

**Comment by mbergeron** [comment]
From what I understand, assembly bindings is not possible in a asp.net core app. I'm I wrong?
