### ISSUE TITLE
WebhookRequest not binding the parameters

### ISSUE THREAD

**Issue by YASSERRMD** [GoogleCloudPlatform/google-cloud-dotnet#2391]
Hi

I am trying to use parameters property in the WebhookRequest but always having null for the value of parameter property. but when i try get as dynamic i am having all the values.

```
 [HttpPost]
        public object Webhook([FromBody]WebhookRequest request)
        {
           
            request.QueryResult.Parameters // always getting null
```

the request json 

```
{
  "responseId": "b01b9bc0-3042-4305-8023-cccece336344",
  "queryResult": {
    "queryText": "fine number is 23",
    "parameters": {
      "fineno": 23,
      "anothertest":52
    },
    "allRequiredParamsPresent": true,
    "fulfillmentMessages": [
      {
        "text": {
          "text": [
            ""
          ]
        }
      }
    ],
    "intent": {
      "name": "projects/eternal-petal-178408/agent/intents/e1999a4e-5066-44f1-a01b-efbfd6703a83",
      "displayName": "fine"
    },
    "intentDetectionConfidence": 1,
    "languageCode": "en"
  },
  "originalDetectIntentRequest": {
    "payload": {}
  },
  "session": "projects/eternal-petal-178408/agent/sessions/3c47ef06-70b4-6707-71c8-959edb9ef77f"
}
```

**Comment by jskeet** [comment]
That will be using Json.NET to parse the request - which won't work, I'm afraid. You need to get the Google.Protobuf library to parse the request. At some point we want to make all of this simpler and provide samples, but it's buried in a list of other work to do at the moment.

If you look at #2238 however, you'll see a lot of discussion and code there. To simplify things, this should work for you:

```csharp
WebhookRequest request;
using (StreamReader reader = new StreamReader(Request.Body))
{  
    request = JsonParser.Parse<WebhookRequest>(reader);
}
```

You'll need to create the `WebhookResponse` object and then convert that to a string to get the JSON, then create a `ContentResult` with that JSON in... *don't* let Json.NET serialize the response.

**Comment by jskeet** [comment]
(I'll leave this open for the moment in case that doesn't cover it, but I believe you should be fine at that point.)

**Comment by YASSERRMD** [comment]
Thank you for the suggestion but your code snippet doesn't work for me but i have choose another way from your suggestion and it worked for me 

       ```
 [HttpPost]
        public object Webhook([FromBody]dynamic objRequest)
        {
            WebhookRequest request = WebhookRequest.Parser.ParseJson(objRequest.ToString());
```
