### ISSUE TITLE
Add Proper Documentation for DialogFlow V2 SDK

### ISSUE THREAD

**Issue by mehtanilay10** [GoogleCloudPlatform/google-cloud-dotnet#2414]
Required Proper documentation for DialogFlow V2 SDK for C#.
It is very difficult to find any example/snippet for using.
Even official docs directory contains an empty template.

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Dialogflow.V2/docs/index.md

**Comment by jskeet** [comment]
That's the *source* docs directory - the *result* documentation is at least slightly better: https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/index.html

However, that's still not all that's required, of course. While I'd like to see that page grow, that's not the location you should expect to find comprehensive documentation. The [Dialogflow site](https://dialogflow.com/docs/getting-started) is where most of the Dialogflow documentation lives. That's where there will be samples etc. As far as I'm aware, there aren't comprehensive .NET docs/samples there at the moment, but that's where I'd expect them to appear over time, developed by the Dialogflow team.

**Comment by mehtanilay10** [comment]
Hi, First of all, thanks for the link, it is really helpful.
I need to dynamically create DialogFlow apps. But each app required different Project too.
So can you help me to find out how to create Project via .Net SDK?

**Comment by jskeet** [comment]
Do you mean creating a Google Cloud Project? That wouldn't be part of the Dialogflow SDK - and I'm not sure how automatable it is at all.

**Comment by jskeet** [comment]
I've now added an example of how to implement a web hook in ASP.NET Core in the documentation:

https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/index.html

That was the most important bit of missing documentation, IMO. I'll let the Dialogflow team know about that example, and they can either include it themselves or link to it. I'm going to close this issue now as I believe we're as far along the docs line in *this* repo as I'd expect to be.
