### ISSUE TITLE
Google.Cloud.Dialogflow.V2 Problem using the built in ToString.

### ISSUE THREAD

**Issue by german95n** [GoogleCloudPlatform/google-cloud-dotnet#2415]
I have been using the Binding Redirect as explained in this website: https://codopia.wordpress.com/2017/07/21/how-to-fix-the-assembly-binding-redirect-problem-in-azure-functions/

But now I face this problem. Whenever I try to convert the WebhookRequest to string or the WebhookResponse to string so I can send back to Dialogflow the response. It gives me this error:

> "Exception while executing function: Function1 -> The type initializer for 'Google.Cloud.Dialogflow.V2.WebhookReflection' threw an exception. -> The type initializer for 'Google.Cloud.Dialogflow.V2.IntentReflection' threw an exception. -> The type initializer for 'Google.LongRunning.OperationsReflection' threw an exception. -> Could not load file or assembly 'Google.Api.CommonProtos, Version=1.1.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47' or one of its dependencies. The system cannot find the file specified. -> Could not load file or assembly 'Google.Api.CommonProtos, Version=1.1.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47' or one of its dependencies. The system cannot find the file specified.",
>     "errorDetails": "Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Function1 ---> System.TypeInitializationException : The type initializer for 'Google.Cloud.Dialogflow.V2.WebhookReflection' threw an exception. ---> System.TypeInitializationException : The type initializer for 'Google.Cloud.Dialogflow.V2.IntentReflection' threw an exception. ---> System.TypeInitializationException : The type initializer for 'Google.LongRunning.OperationsReflection' threw an exception. ---> System.IO.FileNotFoundException : Could not load file or assembly 'Google.Api.CommonProtos, Version=1.1.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException : Could not load file or assembly 'Google.Api.CommonProtos, Version=1.1.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47' or one of its dependencies. The system cannot find the file specified.\r\n   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName,String codeBase,Evidence assemblySecurity,RuntimeAssembly locationHint,StackCrawlMark& stackMark,IntPtr pPrivHostBinder,Boolean throwOnFileNotFound,Boolean forIntrospection,Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName,String codeBase,Evidence assemblySecurity,RuntimeAssembly locationHint,StackCrawlMark& stackMark,IntPtr pPrivHostBinder,Boolean throwOnFileNotFound,Boolean forIntrospection,Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef,Evidence assemblySecurity,RuntimeAssembly reqAssembly,StackCrawlMark& stackMark,IntPtr pPrivHostBinder,Boolean throwOnFileNotFound,Boolean forIntrospection,Boolean suppressSecurityChecks)\r\n   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)\r\n   at Project.Helpers.AssemblyBindingRedirectHelper.<>c__DisplayClass2_0.<RedirectAssembly>b__0(Object sender,ResolveEventArgs args)\r\n   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly,String assemblyFullName) \r\n   End of inner exception\r\n   at Google.LongRunning.OperationsReflection..cctor() \r\n   End of inner exception\r\n   at Google.LongRunning.OperationsReflection.get_Descriptor()\r\n   at Google.Cloud.Dialogflow.V2.IntentReflection..cctor() \r\n   End of inner exception\r\n   at Google.Cloud.Dialogflow.V2.IntentReflection.get_Descriptor()\r\n   at Google.Cloud.Dialogflow.V2.WebhookReflection..cctor() \r\n   End of inner exception\r\n   at Google.Cloud.Dialogflow.V2.WebhookReflection.get_Descriptor()\r\n   at Google.Cloud.Dialogflow.V2.WebhookRequest.get_Descriptor()\r\n   at Google.Cloud.Dialogflow.V2.WebhookRequest.pb::Google.Protobuf.IMessage.get_Descriptor()\r\n   at Google.Protobuf.JsonParser.Merge(IMessage message,JsonTokenizer tokenizer)\r\n   at Google.Protobuf.JsonParser.Merge(IMessage message,TextReader jsonReader)\r\n   at Google.Protobuf.MessageParser`1.ParseJson(String json)\r\n   at async Project.Function1.Run(HttpRequestMessage req,TraceWriter log)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) \r\n   End of inner exception\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken)\r\n   at Microsoft.Azure.WebJobs.Host.Executors.ExceptionDispatchInfoDelayedException.Throw()\r\n   at async Microsoft.Azure.WebJobs.JobHost.CallAsync(??)\r\n   at async Microsoft.Azure.WebJobs.Script.ScriptHost.CallAsync(String method,Dictionary`2 arguments,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager.HandleRequestAsync(FunctionDescriptor function,HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.Host.FunctionRequestInvoker.ProcessRequestAsync(HttpRequestMessage request,CancellationToken cancellationToken,WebScriptHostManager scriptHostManager,WebHookReceiverManager webHookReceiverManager)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.<>c__DisplayClass3_0.<ExecuteAsync>b__0(??)\r\n   at async Microsoft.Azure.WebJobs.Extensions.Http.HttpRequestManager.ProcessRequestAsync(HttpRequestMessage request,Func`3 processRequestHandler,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.ExecuteAsync(HttpControllerContext controllerContext,CancellationToken cancellationToken)\r\n   at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.WebScriptHostHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.SystemTraceHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async System.Web.Http.HttpServer.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)"

```
        [FunctionName("Function1")]
        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log)
        {
            var requestString = await req.Content.ReadAsStringAsync();

            WebhookRequest request = WebhookRequest.Parser.ParseJson(requestString);

            var algo = request.ToString();

            ...
```

**Comment by jskeet** [comment]
It's not clear to me exactly *what* binding redirects you provided - and personally I haven't tried that workaround.

To work out what redirects you would need, I would suggest creating a new .NET full-framework project, add all the dependencies you have in your Azure Function, and looking at the generated redirects. It's also worth checking the Google.Api.CommonProtos.dll is even being deployed. My *guess* is that you're getting a more recent version than the 1.1.0 that it's looking for, but it's worth checking that.

**Comment by german95n** [comment]
I have only specified the Google Protobuf in the local.settings.json: 

`"BindingRedirects": "[ { \"ShortName\": \"Google.Protobuf\", \"RedirectToVersion\": \"3.5.1.0\", \"PublicKeyToken\": \"a7d26565bac4d604\" } ]"`

The Google.Cloud.Dialogflow.V2 uses Google.Api.Gax.Grpc which uses Google.Api.CommonProtos (>= 1.3.0)

I will try to make a new project and see the redirects as you say.

**Comment by jskeet** [comment]
Right, yes, you should definitely be looking at *all* the dependencies and creating appropriate bindings for them. There are rather a lot of them you'll need to specify, I suspect.

**Comment by german95n** [comment]
I surrender.

While try again if there is proper documentation in the future, I will use plain anonymous objects for the moment.

**Comment by jskeet** [comment]
I hope that the underlying issue gets fixed by Microsoft at some point - I completely agree that it shouldn't be this hard :(

**Comment by german95n** [comment]
Yeah, I figured it now.

The problem was that I was trying to use the manual binding redirect as specified in the website in the V2 of the Azure Functions. .Net core doesn't actually use the functions that we build for the binding redirect, so that solution doesn't work.

I switched to the V1, applied that fix with the following bindings redirects, and it worked out!!!

> "BindingRedirects": "[ { \"ShortName\": \"Newtonsoft.Json\", \"RedirectToVersion\": \"11.0.2.0\", \"PublicKeyToken\": \"30ad4fe6b2a6aeed\" }, { \"ShortName\": \"Google.Protobuf\", \"RedirectToVersion\": \"3.5.1.0\", \"PublicKeyToken\": \"a7d26565bac4d604\" }, { \"ShortName\": \"Google.Api.CommonProtos\", \"RedirectToVersion\": \"1.3.0.0\", \"PublicKeyToken\": \"3ec5ea7f18953e47\" }, { \"ShortName\": \"Google.Api.Gax.Grpc\", \"RedirectToVersion\": \"2.5.0.0\", \"PublicKeyToken\": \"3ec5ea7f18953e47\" } ]"

with the following Nuget packages:

Google.Cloud.Dialogflow.V2 : 1.0.0-beta02
Microsoft.NET.Sdk.Functions: 1.0.13
Newtonsoft.Json: 11.0.2

Hopefully they figure out a way to specify the redirects for the V2 in the future so I can switch to that. But this will work for now.
