### ISSUE TITLE
Firestore BaseClientInitializer?

### ISSUE THREAD

**Issue by MrMonotone** [GoogleCloudPlatform/google-cloud-dotnet#2416]
I am aware of how to initialize using the environment variable. However, If I want to initialize in the code, could I do it with the baseclient?

```
                var test2 = new BaseClientService.Initializer
                {
                    ApplicationName = "Test",
                    ApiKey = "[YOUR_API_KEY_HERE]",
                };
```
How would I specify the credentials in Firestoredb object? I am assuming its somewhere in the client I just dont know where.

**Comment by jskeet** [comment]
No, `BaseClientService.Initializer` is how you initialize our REST-based clients. Google.Cloud.Firestore is a gRPC-based library. You'd need to create the `FirestoreClient` from a `Channel` with suitable authentication (not an API key) and then pass that `FirestoreClient` into the `FirestoreDb.Create` method.

See [this FAQ entry](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis) for creating the `FirestoreClient`. We want to make all of this easier, but that should help for now.

**Comment by jskeet** [comment]
(Please let me know if you need more help than that; otherwise I'll close this issue after a while.)

**Comment by MrMonotone** [comment]
@jskeet Thanks for the quick response. I have the necessary config for the javascript api I am just trying to convert that for use with the C# api. 

```
const config = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: ""
};
```

Is there a way for me to use these to authenticate?

**Comment by jskeet** [comment]
No, you can't use an API key to authenticate using Google.Cloud.Firestore.

**Comment by MrMonotone** [comment]
Sorry I guess that was redundant. But thanks for the quick response haha!

**Comment by BourgeoisDirk** [comment]
Does anyone have a code-sample or an answer on how to go about Authenticating coming from a validated User Credential (as in the initial Question) to connect it to Firestore ??
I would prefer not having to use the Service Account, and just use the End Users credentials to access the Firestore.

Is this possible or am I dreaming ?

**Comment by BourgeoisDirk** [comment]
Well, so far "Google.Apis.Firestore.V1" does work on the same principles, hence then BaseClientInitializer..
Alass the documentation is quite lacking to get things rolling, and almost everything online refers to the gRPC-based "Google.Cloud.Firestore" ...

**Comment by jskeet** [comment]
You can use `FirestoreDbBuilder` (in the latest beta) as an easy way of specifying credentials. For example:

```csharp
ITokenAccess credential = ...; // Populate your UserCredential any way you want
var db = new FirestoreDbBuilder
{
    ProjectId = "myprojectid",
    TokenAccessMethod = credential.GetAccessTokenForRequestAsync
}.Build();
```

However, this isn't the intended use for the API - it's intended to be used with service accounts, and I don't know whether it will work at all with a user credential. (The user credential would need to be associated with a GCP project which has Firestore enabled, I believe.)

If this isn't sufficient help, please file a new issue with more details - but I really would strongly recommend using service accounts, or default compute credentials if running on GCP.
