### ISSUE TITLE
Firestore "arrayContains" query and ArrayUnion/ArrayRemove ?

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#2417]
https://firebase.google.com/docs/firestore/query-data/index-overview?authuser=1#automatic_indexing

https://cloud.google.com/blog/products/gcp/expanding-the-cloud-firestore-beta-to-more-users

There was already exist in ios and js SDK. How was it in C# ?

**Comment by jskeet** [comment]
I was aware that was coming up, but hadn't realized it was already available. I'm currently working mostly on Spanner things, but will definitely get to this in time. (I'll review what's required and see if I can fit it in earlier.)

**Comment by jskeet** [comment]
Okay, this is now implemented. Do you have a particular time frame when you'd like a release, or just "as soon as possible"? (I'd rather not release on a Friday, but I could do next week.)

**Comment by Thaina** [comment]
@jskeet No it don't need to be hurried. I just want it to exist and so I could plan to fix my service sometimes in the future. Thank you very much

**Comment by jskeet** [comment]
I've released this as version 1.0.0-beta08. (NuGet will take a little while to update.)
