### ISSUE TITLE
Setting up output contexts object for DialogFlow.V2 in response

### ISSUE THREAD

**Issue by ssong3k** [GoogleCloudPlatform/google-cloud-dotnet#2420]
I need help creating context objects for storing information. The Parameter field inside of the Context object is Protobuf.WellKnownType.Struct and I have not managed to find any documentation on initializing its value. I simply want to add a key value pair of <string, List<string>>.

**Comment by jskeet** [comment]
`Struct` is designed to mimic JSON in structure. It's not as user-friendly as it might be, but if you could give me an example of a JSON document containing the kind of data you're looking for, I could translate that example into C# that generates the equivalent `Struct`, which should get you started.

**Comment by ssong3k** [comment]
Thanks for replying so fast. I want my output context to look like the picture below.
![image](https://user-images.githubusercontent.com/10621422/44057567-d0c110ee-9f08-11e8-85fb-efb8a961c33a.png)

The only difference is that I want the parameters to instead have "param" : <List of string identifiers>.

I have tried making my own JSON and parsing it in as a Struct but that gives me an issue where the DialogFlow client could not recognize the return object.

**Comment by jskeet** [comment]
Okay, here's an example:

```csharp
var response = new WebhookResponse
{
    OutputContexts =
    {
        new Context
        {
            Name = "projects/foo/agent/sessions/bar/contexts/context name",
            LifespanCount = 5,
            Parameters = new Struct
            {
                // Fields is a dictionary
                Fields =
                {
                    { "param", new Value { StringValue = "param value" } }
                }
            }
        }
    }
};
Console.WriteLine(response);
```

**Comment by ssong3k** [comment]
How about setting params to be a list of strings?

**Comment by ssong3k** [comment]
Also leaving a comment here for visibility. Context name apparently only need 
**$"{obj.Session}/contexts/accountList"**
![image](https://user-images.githubusercontent.com/10621422/44058488-76630e38-9f0b-11e8-9257-f063c5937787.png)

**Comment by jskeet** [comment]
It turns out there are static factory methods on `Value` that I'd forgotten about, that make this rather simpler:

```csharp
Parameters = new Struct
{
    // Fields is a dictionary
    Fields =
    {
        { "param", Value.ForList(Value.ForString("value 1"), Value.ForString("value 2")) }
    }
}

```

**Comment by ssong3k** [comment]
Thank you so much! I just tested it with a simple list and it works.
![image](https://user-images.githubusercontent.com/10621422/44058934-faf29c30-9f0c-11e8-9441-60daa69d4758.png)

**Comment by jskeet** [comment]
Great! I'll close this issue now. Glad it worked :)
