### ISSUE TITLE
dotnet sln add broken in our project generation

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#2430]
I've just generated a new API, and the solution file is empty. Running `dotnet sln add path/to/csproj` I get an error message of:

> Project '...Project.csproj' has an unknown project type and cannot be added to the solution file. Please contact your SDK provider for support.

I suspect this is related to the VS15.8 update...

**Comment by jskeet** [comment]
Looks like it's due to this: https://github.com/dotnet/cli/issues/9477

It appears to be fixed in SDK 2.1.400, so we could potentially update to that?

cc @chrisdunelm for thoughts.

**Comment by chrisdunelm** [comment]
Upgrading to 2.1.400 seems like the best option to me (assuming it really is fixed there!)

**Comment by jskeet** [comment]
It's definitely fixed there, yes - temporarily updating to that generated the correct solution file. My only concern is Travis/AppVeyor/Kokoro support. Will investigate.

**Comment by chrisdunelm** [comment]
sgtm
