### ISSUE TITLE
Please expose Google.Cloud.Firestore.Precondition.MustNotExists

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#2445]
It used for document creation id collision. So it would not update overwrite document that already exist

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/fdeff43831550f65783fab0a38244182e048824b/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Precondition.cs#L34-L40

**Comment by jskeet** [comment]
This is automatically applied on document creation operations. What's the use case for specifying it manually?

**Comment by Thaina** [comment]
@jskeet Sometimes I have operation on many documents. Some need to be `MustUpdate` and some `MustNot`

Currently I have write it as
```
foreach(var value in values)
{
if(value.MustExist)
   update(value.Doc,value.Data);
if(value.MustNotExist)
   create(value.Doc,value.Data);
}
```

I wish I could just

```
foreach(var value in values)
   update(value.Doc,value.Data,value.PreCondition); // value.MustNot become PreCondition.MustNotExist
```

**Comment by jskeet** [comment]
Okay, this is another decision for @schmidt-sebastian then. Personally I think I'd just write a helper method - you only need to do this in a single place, after all.

**Comment by jskeet** [comment]
Closing - at least for now.
