### ISSUE TITLE
Firestore get Inner exception "ECall methods must be packaged into a system module."

### ISSUE THREAD

**Issue by Watanyou** [GoogleCloudPlatform/google-cloud-dotnet#2452]
I'm using VS2017 and try to use Google.Cloud.Firebase with my project (That start dev with .Net 4.5.6 in VS2015 and moved to .Net 4.6.1) but I found a exception when I use FirestoreDb.Create() which I never seen or found before `"Exception has been thrown by the target of an invocation."`
and I'm looking Into Inner Exception it said `"ECall methods must be packaged into a system module."`
and Stacktrace ` at UnityEngine.Application.get_platform()`

**Comment by jskeet** [comment]
It sounds like you're trying to use the package from Unity, which isn't a supported platform at the moment, I'm afraid.

**Comment by Watanyou** [comment]
Problem Solved
It have a conflict with QRCoder which use UnityEngine

**Comment by jskeet** [comment]
Glad it's solved. Not sure I quite follow how you solved it, but I'll close this issue now anyway :)

**Comment by Watanyou** [comment]
Just change from QRCoder library to ZXing for building QR Code :)
