### ISSUE TITLE
Release Storage library

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-dotnet#2456]
Hi,

GCS CMEK is now GA. Based on developer feedback, developers are unable to use the CMEK features for DotNet as the features are only in `2.2.0-beta01`, [based on release history](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/releases/tag/Google.Cloud.Storage.V1-2.2.0-beta01). 

If possible, request is to release a non-beta version of `2.2.0-beta01` library so it will be picked up when a developer runs `dotnet add package Google.Cloud.Storage.V1`.

Thank you!

**Comment by jskeet** [comment]
Yes, I'll try to get to that today.

**Comment by frankyn** [comment]
Thanks @jskeet!

**Comment by jskeet** [comment]
Released as Google.Cloud.Storage.V1 version 2.2.0.
