### ISSUE TITLE
Sending a Simple Response back in Webhook Response for Dialogflow

### ISSUE THREAD

**Issue by ssong3k** [GoogleCloudPlatform/google-cloud-dotnet#2466]
I'm currently working on DialogFlow with Google Assistant and I would like to send a response with the fields display text and ssml. Specifically I want Google Assistant to say a phrase that is different than what is displayed in the chat bubble. Please point me in the right direction if this is not the correct repository to ask this question.

**Comment by jskeet** [comment]
I'm afraid contributors here don't have much experience with Dialogflow - you're best off at https://dialogflow.com/ for that - specifically the [fulfillment documentation](https://dialogflow.com/docs/fulfillment)

We *do* know more about the .NET side of things though. There's a sample for writing a web hook in ASP.NET Core on the [Dialogflow package page](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/index.html) which will help you avoid some pitfalls.

I'll close this issue now as I suspect we won't be able to help you further - hopefully those docs will be enough for you. Please add more comments if you run into problems that we may be able to help you with though.
