### ISSUE TITLE
Firestore - DocumentSnapshot.ConvertTo fails with ArgumentException

### ISSUE THREAD

**Issue by pauloevpr** [GoogleCloudPlatform/google-cloud-dotnet#2473]
I have found an interesting issue when using Firestore (currently 1.0.0-beta08) in my C# project. Calling `ConvertTo<T>()` from a document snapshot fails when T does not contain properties to accommodate all document's fields. An ArgumentException is thrown in this case.

This is how the issue can be reproduced:

Given the following POCO class:

```
[FirestoreData()]
private class MyDocument
{
    [FirestoreProperty()]
    public string Name { get; set; }
}
```

And the following Firestore document:

```
{
   "Name": "Some Name",
   "LastName": "Some Last Name"
}
```

An ArgumentException is thrown when calling:

`var myDocument = documentSnapshot.ConvertTo<MyDocument>();`

If this behavior has been intentionally implemented, it should be at least configurable (either by passing an argument to ConvertTo<T>() or by providing parameters to FirestoreDataAttribute). It completely breaks the flexibility of a document database, since adding new fields to the documents forcibly requires changing the code base. Backwards compatibility becomes then a hard task if not impossible.

**Comment by cjcurrie** [comment]
Any progress on this issue? It puts major restrictions on firestore access from C#.

**Comment by jskeet** [comment]
@cjcurrie: Yes, it was fixed in 2018, and you shouldn't be seeing an exception now. You can optionally see a warning if you've specified a warning logger via `FirestoreDb.WithWarningLogger`, and haven't specified a different `UnknownPropertyHandling` value for `FirestoreDataAttribute`. If you *are* getting an exception, it's probably a different issue - please file a new issue with details of how we can reproduce it.

**Comment by mikenlanggio** [comment]
Hi @jskeet , I have an issue with `ConvertTo`.
It worked fine when editor mode, but in the real device, It's throw exception

`
10-02 11:03:10.029: E/Unity(32125): InvalidOperationException: Type XXX has no parameterless constructor
10-02 11:03:10.029: E/Unity(32125):   at Firebase.Firestore.Internal.Preconditions.CheckState[T] (System.Boolean condition, System.String format, T arg0) [0x00000] in <00000000000000000000000000000000>:0 
10-02 11:03:10.029: E/Unity(32125):   at Firebase.Firestore.Converters.AttributedTypeConverter.CreateObjectCreator (System.Type type) [0x00000] in <00000000000000000000000000000000>:0 
10-02 11:03:10.029: E/Unity(32125):   at Firebase.Firestore.Converters.AttributedTypeConverter..ctor (System.Type targetType, Firebase.Firestore.FirestoreDataAttribute attribute) [0x00000] in <00000000000000000000000000000000>:0 
10-02 11:03:10.029: E/Unity(32125):   at Firebase.Firestore.Converters.AttributedTypeConverter.ForType (System.Type targetType) [0x00000] in <00000000000000000000000000000000>:0 
10-02 11:03:10.029: E/Unity(32125):   at Firebase.Firestore.Converters.ConverterCache.CreateConverter (System.Type targetType) [0x00000] in <00000000000000000000000000000000>:0 
10-02 11:03:10.029: E/Unity(32125):   at Firebase.Firestore.Converters.ConverterCache.GetConverter (System.Type targetType) [0x00000] in <00000000000000000000000000000000>:0 
10-02 11:03:10.029: E/Unity(32125):   at Fire


`

My `XXX` class has no parameter in the constructor.
Any idea?

**Comment by jskeet** [comment]
@mikenlanggio: It looks like that isn't using the Google.Cloud.Firestore library which is in this repo, but Firebase.Firestore, which is a separate codebase, supported by the Firebase team. I suggest you follow the steps in the [Firebase support page](https://firebase.google.com/support) - I'm afraid there are too many possibility for a Unity-specific or Firebase.Firestore-specific problem for me to help here.

**Comment by mikenlanggio** [comment]
> @mikenlanggio: It looks like that isn't using the Google.Cloud.Firestore library which is in this repo, but Firebase.Firestore, which is a separate codebase, supported by the Firebase team. I suggest you follow the steps in the [Firebase support page](https://firebase.google.com/support) - I'm afraid there are too many possibility for a Unity-specific or Firebase.Firestore-specific problem for me to help here.

Thank you for your quick reply. Have a nice day ^^
