### ISSUE TITLE
[Google.Cloud.Dialogflow.V2] When returning a WebhookResponse, the field FulfillmentText is marked as optional, but Actions on Google returns error.

### ISSUE THREAD

**Issue by german95n** [GoogleCloudPlatform/google-cloud-dotnet#2507]
I am trying to send back a response like:

```
            return new WebhookResponse
            {
                FulfillmentMessages =
                {
                    new Message
                    {
                        SimpleResponses = new SimpleResponses
                        {
                            SimpleResponses_ =
                            {
                                new SimpleResponse
                               {
                                  DisplayText = "Phrase"
                                  TextToSpeech = "Phrase"
                                }
                            }
                        }
                    }
                }
            };
```

But on Actions on Google I get:
MalformedResponse
'final_response' must be set.

If I send the same response with the field FulfillmentText set as "Phrase", then everything works.

**Comment by jskeet** [comment]
My *guess* is that you're letting Json.NET serialize the response. Don't do that - it won't work. Follow the example on https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/index.html so that you serialize the response properly.

If that isn't it, please provide some more context for the code.

**Comment by german95n** [comment]
I am using the ToString method from the Google Protobuf.

The thing is that It seems like the documentation of the field FulFillmentText from the WebhookResponse is wrong. I mean, Dialogflow parses correctly the response, but then when Dialogflow pases the response to Actions on Google, then Actions on Google throws the error specified before.

If I respond with this, then all works fine, Actions on Google understand everything.

```json
{
    "fulfillmentText": "This is a response for Actions on Google",
    "fulfillmentMessages": [
        {
            "simpleResponses": {
                "simpleResponses": [
                    {
                        "text_to_speech": "This is a response for Actions on Google"
                    }
                ]
            }
        }
    ]
}
```

But If I respond with this, then Actions on Google throws an error:

```json
{
    "fulfillmentMessages": [
        {
            "simpleResponses": {
                "simpleResponses": [
                    {
                        "text_to_speech": "This is a response for Actions on Google"
                    }
                ]
            }
        }
    ]
}
```

**Comment by german95n** [comment]
Wait a Second. Am I supposed to use the Payload field for the responses for Actions on Google and not use the FulfillmentMessages field?

**Comment by jskeet** [comment]
I'm afraid at this point we're way beyond my knowledge - the contributors here have to work with a *lot* of APIs; we don't know the APIs well, but we're good at finding out if there's a problem with the .NET-specific parts.

It sounds like you're able to produce the JSON you expect, at which point I don't think we can help you any further, so I'm going to close this issue. I'd suggest looking through the [Dialogflow support options](https://developers.google.com/actions/support/) as well as double-checking the [Actions on Google fulfillment documentation](https://developers.google.com/actions/build/json/dialogflow-webhook-json). I'm sorry we can't help you further :(

**Comment by german95n** [comment]
I was my fault. I was misunderstanding the documentation.

What I needed to do is to mark the message with the appropriate platform. And if you want to send a card back to Actions on Google, you need to provide a simple response too.

```csharp
            var webhookResponse = new WebhookResponse
            {
                FulfillmentMessages =
                {
                    new Message
                    {
                        Platform = Platform.ActionsOnGoogle,
                        SimpleResponses = new SimpleResponses
                        {
                            SimpleResponses_ =
                            {
                                new SimpleResponse
                                {
                                    TextToSpeech = "Text to speech.",
                                    DisplayText = "Something different."
                                }
                            }
                        }
                    },
                    new Message
                    {
                        Platform = Platform.ActionsOnGoogle,
                        BasicCard = new BasicCard
                        {

                        }
                    }
                }
            };
```
