### ISSUE TITLE
Update "gcloud" to "google-cloud" in API Ref Landing Page

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-dotnet#268]
Not sure if this update needs to be done in "gcloud-common" and if so, we can ignore this issue for now.

**CURRENT SETUP**
Navigating to https://googlecloudplatform.github.io/google-cloud-dotnet/0.1.0/index.html will show the term "gcloud" in many places to refer to the client library in general or to the gcloud-dotnet client library specifically.

**EXPECTED RESULT**
Everything that refers to the client library (in general or dotnet specific) should change to "google-cloud".

**Comment by jskeet** [comment]
Looks like I hadn't pushed the changes I'd made. Most should now be fixed... but only for google-cloud-dotnet, not gcloud-java etc.

**Comment by jskeet** [comment]
(I haven't got a better title than "gcloud" in the top left yet, btw. Suggestions welcome. Other than that, I think this is done.)

**Comment by jskeet** [comment]
Fixed gcloud to google-cloud, so closing this.
