### ISSUE TITLE
Add a way to download file range

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#270]
I want to download a file range.  Like this user wants to:
http://stackoverflow.com/questions/36886537/how-to-download-part-of-file-from-google-storage

**Comment by jskeet** [comment]
I think we may want extra support in Google.Apis for this... it feels like it should be something available within the media downloader. But yes, then we'll want to expose it in Google.Storage.V1 as well.

**Comment by jskeet** [comment]
@chrisdunelm Does our recent ResumableDownload feature help on this front?

**Comment by chrisdunelm** [comment]
The recent work was on ResumableUpload, not download. Having had a quick look at the [media downloader code](https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/GoogleApis/Apis/[Media]/Download/MediaDownloader.cs) there's no support for this, although as mentioned on the [stackoverflow post](http://stackoverflow.com/questions/36886537/how-to-download-part-of-file-from-google-storage) it's certainly possible to do it yourself, but it's not completely trivial.
Jess has [a sample](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/storage/api/StorageSample.cs#L127) of how to do it.

I agree that it would be nice if this was exposed directly on the MediaDownloader, as I expect it would be useful for quite a few people.
