### ISSUE TITLE
RunQuery never returns when an exception is thrown

### ISSUE THREAD

**Issue by apolcyn** [GoogleCloudPlatform/google-cloud-dotnet#287]
here is the stack trace of when it was hanging:

 	System.Core.dll!System.Linq.Enumerable.First<Google.Api.Gax.FixedSizePage<Google.Datastore.V1Beta3.Entity>>(System.Collections.Generic.IEnumerable<Google.Api.Gax.FixedSizePage<Google.Datastore.V1Beta3.Entity>> source)	Unknown
>	2-structured-data.dll!GoogleCloudSamples.Models.DatastoreBookStore.List(int pageSize, string nextPageToken) Line 123	C#
 	2-structured-data.dll!GoogleCloudSamples.Controllers.BooksController.Index(string nextPageToken) Line 37	C#
 	[Lightweight Function]	
 	System.Web.Mvc.dll!System.Web.Mvc.ActionMethodDispatcher.Execute(System.Web.Mvc.ControllerBase controller, object[] parameters)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.ReflectedActionDescriptor.Execute(System.Web.Mvc.ControllerContext controllerContext, System.Collections.Generic.IDictionary<string, object> parameters)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(System.Web.Mvc.ControllerContext controllerContext, System.Web.Mvc.ActionDescriptor actionDescriptor, System.Collections.Generic.IDictionary<string, object> parameters)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeSynchronousActionMethod.AnonymousMethod__39(System.IAsyncResult asyncResult, System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation innerInvokeState)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult<System.__Canon, System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation>.CallEndDelegate(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase<System.__Canon>.End()	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive.AnonymousMethod__3d()	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive.AnonymousMethod__3f()	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeActionMethodWithFilters.AnonymousMethod__32(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult<System.__Canon>.CallEndDelegate(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase<System.__Canon>.End()	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction.AnonymousMethod__1c()	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction.AnonymousMethod__1e(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult<bool>.CallEndDelegate(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase<bool>.End()	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Controller.BeginExecuteCore.AnonymousMethod__1d(System.IAsyncResult asyncResult, System.Web.Mvc.Controller.ExecuteCoreState innerState)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid<System.Web.Mvc.Controller.ExecuteCoreState>.CallEndDelegate(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase<System.Web.Mvc.Async.AsyncVoid>.End()	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Controller.EndExecuteCore(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Controller.BeginExecute.AnonymousMethod__15(System.IAsyncResult asyncResult, System.Web.Mvc.Controller controller)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid<System.__Canon>.CallEndDelegate(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase<System.Web.Mvc.Async.AsyncVoid>.End()	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Controller.EndExecute(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.MvcHandler.BeginProcessRequest.AnonymousMethod__5(System.IAsyncResult asyncResult, System.Web.Mvc.MvcHandler.ProcessRequestState innerState)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid<System.Web.Mvc.MvcHandler.ProcessRequestState>.CallEndDelegate(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase<System.Web.Mvc.Async.AsyncVoid>.End()	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.MvcHandler.EndProcessRequest(System.IAsyncResult asyncResult)	Unknown
 	System.Web.Mvc.dll!System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(System.IAsyncResult result)	Unknown
 	System.Web.dll!System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()	Unknown
 	System.Web.dll!System.Web.HttpApplication.ExecuteStep(System.Web.HttpApplication.IExecutionStep step, ref bool completedSynchronously)	Unknown
 	System.Web.dll!System.Web.HttpApplication.PipelineStepManager.ResumeSteps(System.Exception error)	Unknown
 	System.Web.dll!System.Web.HttpApplication.BeginProcessRequestNotification(System.Web.HttpContext context, System.AsyncCallback cb)	Unknown
 	System.Web.dll!System.Web.HttpRuntime.ProcessRequestNotificationPrivate(System.Web.Hosting.IIS7WorkerRequest wr, System.Web.HttpContext context)	Unknown
 	System.Web.dll!System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(System.IntPtr rootedObjectsPointer, System.IntPtr nativeRequestContext, System.IntPtr moduleData, int flags)	Unknown
 	System.Web.dll!System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(System.IntPtr rootedObjectsPointer, System.IntPtr nativeRequestContext, System.IntPtr moduleData, int flags)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Web.dll!System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(System.IntPtr rootedObjectsPointer, System.IntPtr nativeRequestContext, System.IntPtr moduleData, int flags)	Unknown
 	System.Web.dll!System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(System.IntPtr rootedObjectsPointer, System.IntPtr nativeRequestContext, System.IntPtr moduleData, int flags)	Unknown
 	[AppDomain Transition]

**Comment by jskeet** [comment]
What do you mean by "when an exception is thrown" here? Depending on the RPC status, the GAX code may retry, but it shouldn't retry forever unless you've configured it that way.

**Comment by jskeet** [comment]
This looks like it was using the old Datastore library which had significant bugs in its query handling. Closing as obsolete.
