### ISSUE TITLE
Revisit BigQuery query results

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#295]
Currently the first page of BigQuery query results is cached, and the rest is loaded lazily. That's a really confusing way of behaving. We should try to make the exposed surface consistent with other APIs, if at all possible. This could take a bit of experimentation.

**Comment by jskeet** [comment]
Tricky part - we expose the schema, and that's only know when we've got the first response. Urgh.

**Comment by jskeet** [comment]
Okay, I'm trying to revisit this in terms of design.

Query results come from:

- `BigqueryTable.ListRows` / `BigqueryClient.ListRows`
- `BigqueryClient.ExecuteQuery`
- `BigqueryClient.GetQueryResults` / `BigqueryJob.GetQueryResults`

When listing rows, we may know the schema beforehand. In other cases, we won't. We always have a schema by the time we have rows.

So, some questions:

- Does the client ever want the schema before they fetch the first row? (Not sure.)
- Does the client ever want the schema if there *are* no rows? (Suspect that could be useful - e.g. for a UI.)
- Does the client ever need the rest of the response? (Not sure)

Java has two aspects here:

- `Table.list` returns a ` Page<List<FieldValue>`
- `Bigquery` has two methods:
  - `QueryResponse query(QueryRequest request)`
  - `QueryResponse getQueryResults(JobId job, QueryResultsOption... options)`

A `QueryResponse` has a `QueryResult`, which is present when it's done without errors. The `QueryResponse` extends `PageImpl<List<FieldValue>>` and also exposes the schema.

Not sure whether/how we expose errors at the moment, which is certainly something to feed into this design...

**Comment by evildour** [comment]
What about simply changing the Schema property to GetSchema(Async) methods. If it is already available, it can be returned immediately. Otherwise, the first request needs to be made to retrieve it (not sure what this does if there are no rows though). So you would only incur a delay when getting the schema or first row, but not both.

**Comment by jskeet** [comment]
It gets a bit more complicated than that, but I'm making progress. I keep getting drawn into other things while tackling it though...

**Comment by jskeet** [comment]
It's now much simpler than it was, as of #444. We probably want to rename BigqueryQueryJob, but that's a relatively trivial matter.
