### ISSUE TITLE
Datastore API reference never uses the word ancestor.  It should.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#301]
Reading the docs here:
https://cloud.google.com/datastore/docs/concepts/entities

It uses the word 'ancestor' a lot.  So I search the API docs here:
https://googlecloudplatform.github.io/google-cloud-dotnet/1.0.0-beta01/docfx/api/Google.Datastore.V1Beta3.KeyFactory.html

And I can't figure out how to create a Key with an ancestor because the word ancestor is never used.

**Comment by jskeet** [comment]
Would changing the `parent` parameter to `ancestorPath` work for you? I wouldn't want to call it just "ancestor" as every sub-path is an ancestor really.

Will create a PR and see what you think.

**Comment by jskeet** [comment]
Urgh... looking again, even there I don't think it makes much sense. What we're specifying really is the direct parent key for all keys created by this key factory. (Note that the documentation *also* talks about "parent" and "child" a lot...)

Perhaps we just need to mention ancestors in the remarks in some elements of the documentation? What would have helped you here?

**Comment by SurferJeffAtGoogle** [comment]
Yes: just mentioning the word ancestor in the docs would have helped a lot.

**Comment by jskeet** [comment]
@SurferJeffAtGoogle We don't have docs built for this yet, but if you could review https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/src/Google.Datastore.V1Beta3/KeyFactory.cs and see if that looks like it would be enough, please close this issue or give more details about how we can do better.

**Comment by jskeet** [comment]
Docs are now at https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Datastore.V1/api/Google.Datastore.V1.KeyFactory.html

**Comment by SurferJeffAtGoogle** [comment]
LGTM.
