### ISSUE TITLE
More convenient initializers for array values, please.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#302]
I want to say this:
```
            Entity task = new Entity()
            {
                Key = _db.CreateKeyFactory("Task").CreateKey("taskOne"),
                ["tags"] = new[] { "fun", "programming" },
                ["collaborators"] = new[] {"alice", "bob"}
            };
```

**Comment by SurferJeffAtGoogle** [comment]
I ended up writing this code instead:
```
            Entity task = new Entity()
            {
                Key = _db.CreateKeyFactory("Task").CreateKey("taskOne"),
                ["tags"] = new ArrayValue(),
                ["collaborators"] = new ArrayValue()
            };
            var tags = task["tags"].ArrayValue.Values;
            tags.Add("fun");
            tags.Add("programming");
            var collaborators = task["collaborators"].ArrayValue.Values;
            collaborators.Add("alice");
            collaborators.Add("bob");
```

**Comment by evildour** [comment]
It is not quite as clean as your desired code, but you could use this:
```
Entity task = new Entity()
{
    Key = _db.CreateKeyFactory("Task").CreateKey("taskOne"),
    ["tags"] = new ArrayValue { Values = { "fun", "programming" } },
    ["collaborators"] = new ArrayValue { Values = {"alice", "bob"} }
};
```

**Comment by jskeet** [comment]
I suspect we can get closer to Jeffrey's original aim using some more conversions... I'll look into it when I get back from vacation.

**Comment by SurferJeffAtGoogle** [comment]
evildour, your suggested fix looks nice.  But when I try it, I get this error;
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0200	Property or indexer 'ArrayValue.Values' cannot be assigned to -- it is read only	DatastoreTest	C:\Users\rennie\gitrepos\dotnet-docs-samples\datastore\api\DatastoreTest.cs	339	Active
````

**Comment by evildour** [comment]
Hmm, that's odd. I tried this in code before suggesting it, so it worked for me. Here is an explanation (by Jon actually) of what this kind of thing is actually doing and why it should be able to access a read-only collection: http://stackoverflow.com/a/5646336/489645

**Comment by jskeet** [comment]
Yes, Mike's code should definitely be fine, and works for me.

We'd see Jeff's error with this code:

```csharp
// Invalid
["tags"] = new ArrayValue { Values = new[] { "fun", "programming" } },
```

That said, I'd like to get to Jeff's original code if possible. I think it's only going to be feasible for single-type arrays, e.g. `string[]`, `int[]` etc... if you have `new object[] { "fun", 10.0 }` that's not going to fly... although hopefully you'll be able to use `new Value[] { "fun", 10.0 }`.

I could *possibly* support conversions from `List<T>` as well (but not `IEnumerable<T>`) but it'll start getting pretty bloated. Will do arrays first.

**Comment by evildour** [comment]
What about adding an Add method and IEnumerable\<Value\> interface to ArrayValue (both of which just delegate to values_)? Then this should be possible:
```csharp
["tags"] = new ArrayValue { "fun", 10.0 },
```

**Comment by jskeet** [comment]
@evildour: That's an interesting idea, yes. I could potentially do that *as well* as conversions from actual arrays (which I've basically started implementing). Hmm.

**Comment by evildour** [comment]
I think the array conversions are a good idea btw. I was just suggesting this as another possible way to support heterogenous arrays cleanly.

Also, another minor benefit of having IEnumerable\<Value\> is you can directly iterate over ArrayValue objects, which would clean up foreach loops a bit.

**Comment by jskeet** [comment]
Right. Also, one benefit of using `new ArrayValue { x, y, z }` over `new ArrayValue { Values = { x, y, z } }` is that we can transparently convert null references into null `Value` objects - and vice versa when iterating. I *think* that's the best thing to do, although it always gets tricky working out what to do with nullity.

We may also need to add conversions from `Value` to/from each specific array type, as I don't *think* the compiler will allow two implicit user-defined conversions to chain together. Will experiment.
