### ISSUE TITLE
Showing PropertFieldNumber, Descriptor, etc. in the docs doesn't help.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#305]
It clutters the docs.  I don't want to see it.  Example:
https://googlecloudplatform.github.io/google-cloud-dotnet/1.0.0-beta01/docfx/api/Google.Datastore.V1Beta3.Projection.html

**Comment by jskeet** [comment]
Well, they're part of the public API... it would be odd not to show them, IMO. (They'll definitely be shown in Intellisense, and it would be very confusing for a user to see them there, try to find them in the API documentation, and then not see them appear...)

There's certainly an argument for some sort of levels of filtering - for example, most users won't need to see the request proto messages at all if they're using the higher-level abstractions. That said, all of the way that documentation is built/consumed is in a certain amount of flux... I don't anticipate us working on filtering any time particularly soon. (I don't think I've seen it in any other API documentation, even though it's a potentially useful feature.)

**Comment by SurferJeffAtGoogle** [comment]
I agree it is a deviation from the standard pattern to hide these elements in the docs.  But as a user, I find myself constantly scrolling passed and annoyed by these elements.  I'll never need to use them.

They will pop up in Intellisense, but I'm used to ignoring things in Intellisense like the .Equals() method and the like.

**Comment by jskeet** [comment]
Thinking about it, I believe we may be able to do this with a tool to just prune the generated metadata. Will experiment and present a reduced docset in my repo.

**Comment by SurferJeffAtGoogle** [comment]
Cool.  Thank you for the continuing effort.

**Comment by jskeet** [comment]
Okay, it turns out docfx supports exclusion filters. Shame I only found that out *after* writing a bunch of code. Ah well.

Have a look at https://jskeet.github.io/google-cloud-dotnet/ and see what you think. I was pleasantly surprised.

**Comment by SurferJeffAtGoogle** [comment]
I like it!

**Comment by jskeet** [comment]
Have discovered that we were filtering a bit too aggressively. We have a new plan which will still remove all of these from protos, but shouldn't touch handwritten code such as BigqueryTable.ToString. Hope to get that done in the next day or two, and the new docs deployed then. Will keep this issue open until it's really done.

**Comment by jskeet** [comment]
Done now. The new version even omits the constructors for protos - which was unintentional, but turns out to be quite handy.
