### ISSUE TITLE
Support for gs:// paths on the Google.Storage.V1 library.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-dotnet#309]
Currently the user must specify the bucket and blob name separately in the API calls. It would be very useful to be able to use the gs:// paths instead as many other tools and some of the APIs do deal with this type of paths.

The gsutil tool for example treats gs:// paths as if they were local paths. The Google Vision API accepts gs:// paths as an [ImageSource](https://cloud.google.com/vision/reference/rest/v1/images/annotate#ImageSource).

Together with accepting gs:// paths there should be functionality to perform operations on them, something resembling a subset of the `System.IO.Path` class would be ideal.

**Comment by jskeet** [comment]
We're almost certainly going to postpone this until post 1.0 now.

**Comment by jskeet** [comment]
Closing until we decide we're interested in this (to avoid clutter).
