### ISSUE TITLE
Need to ensure we use lower-case gRPC header keys

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-dotnet#342]
**This might be a no-op, but please double check. Filing this issue just in case.**

We need to ensure that all headers used for gRPC are written in lower-case. Please review this [Pull Request](https://github.com/GoogleCloudPlatform/gcloud-python/pull/2212) for reference of what needs to be updated.

Again, perhaps this doesn't apply to your language. Feel free to comment and then close the issue (after double checking).

**Comment by jskeet** [comment]
We don't set any headers within this repo, but the x-goog-api-client header is set from GAX.
Fixed in https://github.com/googleapis/gax-dotnet/pull/68
