### ISSUE TITLE
Publish nuget package 1.0.0

### ISSUE THREAD

**Issue by operezfuentes** [GoogleCloudPlatform/google-cloud-dotnet#345]
Nuget package stil in https://www.nuget.org/packages/Google.Pubsub.V1/1.0.0-beta01

This package is builded with refererences to Grpc.Core 0.15.0 which contins some issues working with dotnet cli

It's possible to publish 1.0.0 package with updated references?

Thanks for your help

**Comment by jskeet** [comment]
No, we're not ready to publish 1.0.0 yet. When we publish 1.0.0-beta02, that will refer to Grpc.Core 1.0.0 (and Google.Protobuf 3.0.0).

We have a few more tweaks I'd like to get done before beta02, but I'm hoping it won't be much longer. Let me know if this is urgent, and I can look at promoting some recent CI builds to our public myget feed.

**Comment by operezfuentes** [comment]
Thanks Jon,

Not specially urgent but if you can promote to myget (not nuget) we'll be appreciated.

**Comment by jskeet** [comment]
The 1.0.0-beta02 packages are now published on nuget.org, and the 0.2.0 packages for Google.Cloud.{Speech,Vision,Language} are on Myget. All support dotnet cli (which is what we're using for building them now). Enjoy!
