### ISSUE TITLE
Include the version number in the user agent for REST-based libraries

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#355]
This affects BigQuery and Storage. We default the user agent to "google-cloud-dotnet" - it should be "google-cloud-dotnet/1.0.0-beta01" or whatever.

We can use code similar to https://github.com/googleapis/gax-dotnet/blob/master/src/Google.Api.Gax/UserAgentBuilder.cs to get the version number.

**Comment by chrsmith** [comment]
/CC @ivannaranjo is tracking this for the Visual Studio and PowerShell efforts.
