### ISSUE TITLE
Pubsub: Should return numeric StatusCode for Grpc.Core.RpcExceptions

### ISSUE THREAD

**Issue by jsimonweb** [GoogleCloudPlatform/google-cloud-dotnet#367]
Currently - working with the Pubsub V1 Google Cloud Library for .NET, when you make a call like 
publisher.CreateTopic() and a Grpc.Core.RpcException occurs,  a "StatusCode" 
is returned that contains a string. This should instead return a StatusCode 
that is numeric and use a field named something like "StatusText" to contain 
the string based representation of the status.

For example, the following code makes an "CreateTopic" RPC call. The only
way to currently check if the topic already exists is to check the string value
of "StatusCode".

```
//This is how the StatusCode must be checked currently
try
{
    RetryRpc(() =>
    {
        //Create Topic
        publisher.CreateTopic(topicName);
    });
}
catch (Grpc.Core.RpcException e)
{
    // A StatusCode of "AlreadyExists" is ok.  
    // It means the topic already exists.
    if (e.Status.StatusCode.ToString() != "AlreadyExists")
    {
        throw;
    }                    
}

//****************************************************
// This is how I would expect to check the StatusCode
// if it was a numeric value
//***************************************************
try
{
    RetryRpc(() =>
    {
        //Create Topic
        publisher.CreateTopic(topicName);
    });
}
catch (Grpc.Core.RpcException e)
{
    // A StatusCode of 409 is ok.  
    // It means the topic already exists.
    if (e.Status.StatusCode != 409)
    {
        throw;
    }                    
}
```

**Comment by jskeet** [comment]
`Status.StatusCode` isn't a string - it's a [`StatusCode`](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/StatusCode.cs), which is an enum.

So you can do:

```csharp
catch (RpcException e)  when (e.Status.StatusCode != StatusCode.AlreadyExists)
```

**Comment by jsimonweb** [comment]
Ah yes enum is better. Will use accordingly. Thanks!
