### ISSUE TITLE
Determine what ACL support is required

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#399]
Storage has a number of ways of specifying ACLs - we don't have much built-in support for that in the wrapper library.

We should see what is actually required, and implement it for GA.

**Comment by jskeet** [comment]
Jeff, am I right in saying you've managed to write all your samples to manipulate ACLs, and therefore no further support is necessary? Is there anything that would have made it simpler (without affecting other actions)?

**Comment by SurferJeffAtGoogle** [comment]
We have covered all the necessary ACL-related functions.

Some code seemed a little verbose.  For example:
```
private void AddBucketOwner(string bucketName, string userEmail)
        {
            var storage = StorageClient.Create();
            var bucket = storage.GetBucket(bucketName, new GetBucketOptions()
            {
                Projection = Projection.Full
            });
            if (null == bucket.Acl)
            {
                bucket.Acl = new List<BucketAccessControl>();
            }
            bucket.Acl.Add(new BucketAccessControl()
            {
                Bucket = bucketName,
                Entity = $"user-{userEmail}",
                Role = "OWNER",
            });
            var updatedBucket = storage.UpdateBucket(bucket, new UpdateBucketOptions()
            {
                // Avoid race conditions.
                IfMetagenerationMatch = bucket.Metageneration,
            });
        }
```

Ideally, that would look more like:
```
private void AddBucketOwner(string bucketName, string userEmail)
        {
            var storage = StorageClient.Create();
            var bucket = storage.GetBucket(bucketName);
            bucket.Acl.Add(new BucketAccessControl()
            {
                Bucket = bucketName,
                Entity = $"user-{userEmail}",
                Role = "OWNER",
            });
            var updatedBucket = storage.UpdateBucket(bucket, new UpdateBucketOptions()
            {
                // Avoid race conditions.
                IfMetagenerationMatch = bucket.Metageneration,
            });
        }
```

I think the most error-prone behavior is that it would be very easy to call GetBucket() and then UpdateBucket(), which getting the full projection in GetBucket().  You would then lose all the attributes not returned by the default projection.

It would also be easy to forget the `IfMetagenerationMatch =` condition and then suffer data races.

**Comment by jskeet** [comment]
Right... there's been suggestions that UpdateObject/UpdateBucket should *always* have preconditions, but I'm not sure about that. (Sometimes you may want "splat" behaviour.)

I suspect you don't need the nullity check in the current code (and I'd *definitely* recode it as the more idiomatic `xyz == null` instead of `null == xyz`) when you're fetching ACLs, as a bucket will always have *some* ACLs (as I understand it). That way you'll also fail if you call `GetBucket` without specifying the projection, as you'll end up with a `NullReferenceException`... not necessarily easy to diagnose, but at least you wouldn't be losing data.

The other *tiny* simplification you can make is removing the `()` when calling constructors as part of object initializers. Just `new BucketAccessControl { ... }` etc.

If we felt that adding ACLs was particularly common, we could add something like:

```csharp
public Bucket AddBucketAcls(string bucketName, params BucketAccessControl[] acls)
```
which could do the fetch, add, update and return the result. That would be simple enough to do, but is probably only worth it if `Add` is the only common option... there's no obvious equivalent for remove/update, unless we took an `Action<IList<BucketAccessControl>>` which you'd use to modify the list returned when fetching the bucket...

**Comment by SurferJeffAtGoogle** [comment]
I also don't like to ask the user to *always* do something.

But I'm thinking flipping the defaults may yield to fewer bugs written by
users.  For example, make Full projection the default projection.
Retrieving anything less is an optimization, no?  Leave that to the expert
users.  And, make the IfMetagenerationMatch the default update options.

**Comment by jskeet** [comment]
We can't make `IfMetagenerationMatch` a default update option, because we don't know what it would have to match. We could make it fail if you hadn't specified anything, unless you had a `ForceNoPreconditions` or something though... I quite like that idea.

In terms of fetching everything by default, I think it partly depends on what the performance penalty is like. I'll ask the Storage team about that.

**Comment by SurferJeffAtGoogle** [comment]
On Thu, Nov 17, 2016 at 9:38 AM, Jon Skeet <notifications@github.com> wrote:

> We can't make IfMetagenerationMatch a default update option, because we
> don't know what it would have to match.
>
How about the current value of bucket.Metageneration?

**Comment by jskeet** [comment]
Ah, I see - given that you're always providing a bucket. Yes, that's feasible, although it goes against the separation of options and other parameters that we've had elsewhere. (For example, when you fetch an object, it fetches the most recent version unless you specify otherwise.) 

Whatever we do for `UpdateBucket`, we should do for `UpdateObject` as well, of course. Okay - will have a think, and send a pull request (before I write tests) to see what you think.

**Comment by jskeet** [comment]
Closing this now, as #547 implements the precondition defaulting, which I think is all we still needed.
