### ISSUE TITLE
Review use of HttpClient

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#407]
We have some code which uses HttpClient to fetch resources

We should review these articles to work out what makes sense here.
- http://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/
- http://odetocode.com/blogs/scott/archive/2004/06/08/http-connection-limits.aspx
- http://byterot.blogspot.co.uk/2016/07/singleton-httpclient-dns.html

**Comment by evildour** [comment]
I recently saw this article which summarizes two of those links and also lists out the methods which are thread safe on HttpClient: https://www.infoq.com/news/2016/09/HttpClient

**Comment by manigandham** [comment]
The advice is basically that HttpClient is thread-safe and automatically manages multiple connections and requests so it should be a singleton for the lifetime of the application. It implements `IDisposable` but only because it has resources to be disposed, not because it needs to be disposed on every request. There's no need to use more than one instance for the entire application but it's not too big of a deal if major libraries use their own.

Reusing a single instance or allowing for an instance to be passed in the construction/config would likely be best.

**Comment by jskeet** [comment]
@manigandham: Except it's not quite that simple due to DNS caching as I understand it.

**Comment by manigandham** [comment]
@jskeet 

There is the `ServicePointManager.DnsRefreshTimeout` property specifically for controlling the DNS resolution cache settings for new connections to a service point (address). The default is 2 mins.

https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.dnsrefreshtimeout(v=vs.110).aspx

Will do some testing but never encountered any DNS problems with `HttpClient` before.

**Comment by jskeet** [comment]
@manigandham: I believe the problem is for new connections to the same name, when it's got a new IP address. See http://byterot.blogspot.co.uk/2016/07/singleton-httpclient-dns.html We can't know whether that's relevant to our users or not, unfortunately :(

**Comment by manigandham** [comment]
@jskeet 

That blog post seems to be confusing DNS TTLs with HTTP/TCP connection lifetimes.

HttpClient is just a wrapper around HttpClientHandler which uses the HttpWebRequest stack, and this stack uses connection pooling with `ServicePoint` objects managed by the `ServicePointManager`. HTTP/TCP connections stay open indefinitely and don't do DNS lookups again, which is the correct behavior. New requests on a new connection will do a new DNS lookup and get the updated address.

There is some client-side DNS caching but this can be tweaked by `ServicePointManager`. It's also possible to just use `Dns.GetHostAddresses` to get the IP first, then use that in HTTP requests to make it more explicit.

.NET Core doesn't actually have ServicePointManager anymore but it will be [back in .NET Core 2.0/NETStandard 2.0](https://github.com/dotnet/corefx/issues/11885). 

More discussion here: https://github.com/dotnet/corefx/issues/11224

**Comment by jskeet** [comment]
@manigandham: Thanks for the link - that's very helpful. Unfortunately what you wrote on that thread:

> If you want another DNS lookup to be done, you need to reset the connection on the client. You can force a max-lifetime of the TCP connection, send a connection: close header or just dispose the HttpClient or the underlying ServicePoint.

... makes me worry about keeping a static `HttpClient` within the library. *We* wouldn't know when to dispose of the client, because we're just a library - and I don't want to start doing things like exposing a `ResetClient` method. I may look at the `XDocument.Load` implementation to see what that does...

**Comment by chrisdunelm** [comment]
We need to resolve this issue, either through code changes or documentation.

**Comment by manigandham** [comment]
What exactly is the issue? `HttpClient` is a long-lived static resource so it shouldn't be recreated for every (seemingly) lightweight `StorageClient` - maybe allow users to pass in their own `HttpClient` instance as an option?

**Comment by jskeet** [comment]
You can already pass in your own HttpClient instance when creating a StorageService, but because we modify the HttpClient, we can't just reuse one across all services/clients. Basically `HttpClient` *can* be a long-lived static resource, but only if you know everything about how it's used.

**Comment by chrisdunelm** [comment]
I don't think it's possible to pass in an `HttpClient` at all, because the underlying `StorageService` (as in all REST-based services) requires a [`ConfigurableHttpClient`](https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/Google.Apis.Core/Http/ConfigurableHttpClient.cs) which inherits from `HttpClient`, not composing with it.

It is possible to provide a custom [`IHttpClientFactory`](https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/Google.Apis.Core/Http/IHttpClientFactory.cs#L43), but still doesn't allow anything as simple as just returning an `HttpClient`.

**Comment by chrisdunelm** [comment]
@jskeet The only way I can see to fix this is by making REST-based clients implement `IDisposable`. It's very not great due to the characteristics of `HttpClient`, but will fix *most* problems.
I can't see any way to enable `[Configurable]HttpClient` sharing; can you?

**Comment by jskeet** [comment]
Sharing could potentially be done by having an IHttpClientFactory that just returns the same ConfigurableHttpClient, so users could opt in that way... but I think making the clients implement IDisposable is almost certainly better.

**Comment by chrisdunelm** [comment]
The problem with sharing a `ConfigurableHttpClient` instance, is that it [directly references](https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/Google.Apis.Core/Http/ConfigurableHttpClient.cs#L28) a `ConfigurableMessageHandler` instance, upon which the user can directly mutate various things: E.g. [`NumRetries`](https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/Google.Apis.Core/Http/ConfigurableMessageHandler.cs#L221), [`NumRedirects`](https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/Google.Apis.Core/Http/ConfigurableMessageHandler.cs#L235), various [interceptors](https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/Google.Apis.Core/Http/ConfigurableMessageHandler.cs#L173), logging, etc...
So I don't see this as being a viable solution at all.
Hence `IDisposable` being the only solution I can see.

**Comment by jskeet** [comment]
Righto, SGTM. We can have suitable documentation (like we do for Channel) about the situations in which it's actually important to dispose.

**Comment by jskeet** [comment]
I'm just going to reopen this for now in order to add some more docs.

**Comment by jskeet** [comment]
We now have those docs.
