### ISSUE TITLE
PubSub: Supporting NetStandard

### ISSUE THREAD

**Issue by jose3m** [GoogleCloudPlatform/google-cloud-dotnet#413]
Hi.

Do you have any prevision to support NetStandard for the PubSub package?

Thank you.

**Comment by jskeet** [comment]
We'll support netstandard1.5 when gRPC does. The gRPC codebase already has experimental support - we're just waiting for it to be released. At that point, it should be easy to retarget the code in *this* repository to support it.

**Comment by jose3m** [comment]
Then we will have to wait.

Thank you very much for your good work.
