### ISSUE TITLE
Adding the GCP logo in browser tab

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-dotnet#422]
As things stand right now, we don't have any nice "cloud" logo in the browser tab:

![image](https://cloud.githubusercontent.com/assets/6609430/18976678/a765fb02-8668-11e6-9c11-71f13a44349e.png)

It would be great to add it - here's an example of what this looks like for Java:

![image](https://cloud.githubusercontent.com/assets/6609430/18976685/b7afa68e-8668-11e6-9458-0e1fe11e73f3.png)

**Comment by chrsmith** [comment]
We just need to add this to the `<header>` element on the page. Let me see if I can ninja the fix right now...
````
<link rel="shortcut icon" href="https://cloud.google.com/images/gcp-favicon.ico">
````

**Comment by jskeet** [comment]
Looks good to me now :)
