### ISSUE TITLE
the log4net code snippet should be for ASP.NET instead of a Console app

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-dotnet#430]
This may be useful input on how to prepare an ASP.NET sample that works for log4net:

http://www.codeproject.com/Articles/823247/How-to-use-Apache-log-net-library-with-ASP-NET-MVC

**Comment by jskeet** [comment]
Chris, I know you were looking at this at the tail end of last year - did you write up a sample?

**Comment by jskeet** [comment]
This was fixed a while ago.
