### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#433]
I click on the Overview Documentation link in http://googlecloudplatform.github.io/google-cloud-dotnet/, and I get a 404.

**Comment by chrsmith** [comment]
Link goes to:
http://googlecloudplatform.github.io/google-cloud-dotnet/docfx/index.html
Probably should be:
http://googlecloudplatform.github.io/google-cloud-dotnet/docs/index.html

**Comment by jskeet** [comment]
I've removed the link entirely, as it no longer *does* contain samples for all APIs.
