### ISSUE TITLE
The list of APIs are not links.  I want to click on them.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#434]
This list:
Google.Bigquery.V2
Google.Datastore.V1Beta3
Google.Logging.Log4Net
Google.Logging.V2
Google.Pubsub.V1
Google.Storage.V1

On this page:
http://googlecloudplatform.github.io/google-cloud-dotnet/

**Comment by jskeet** [comment]
Agreed, they should be. Unfortunately it'll take a bit of CSS magic to avoid ending up with dark blue on medium blue :) Will consult with more webby folks than myself. Should be simple then.

**Comment by jskeet** [comment]
Done. The colours aren't necessarily the nicest, but we can easily tweak them now.
(I've also fixed it to use Google.Datastore.V1 rather than V1Beta3.)
