### ISSUE TITLE
Bigquery: DeleteTable() fails

### ISSUE THREAD

**Issue by jsimonweb** [GoogleCloudPlatform/google-cloud-dotnet#443]
Currently working with the Bigquery V2 Google Cloud Library for .NET, 
when you make a call to client.DeleteTable(projectId, datasetId, tableId) 
it fails and throws the error: 

```
    Unhandled Exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
    Not found: Dataset [projectId]:[tableId] [404]
    Errors[
            Message[Not found: Dataset [projectId]:[tableId]] Location[- ] Reason[notFound] Domain[global]
    ]
```

Based on the error message it seems that the passed in "datasetId" argument is getting conflated with the passed in "tableId" argument.

All the permutations of DeleteTable() listed below fail and throw the same error noted above: 
```
           BigqueryClient client = BigqueryClient.Create(projectId);

           // [1] Call DeleteTable(projectId, datasetId, tableId)
           client.DeleteTable(projectId, datasetId, tableId);

           // [2] Call DeleteTable(datasetId, tableId)
           client.DeleteTable(datasetId, tableId);

           // [3] Call DeleteTable(TableReference)
           BigqueryTable tableToDelete = client.GetTable(datasetId, tableId);
           client.DeleteTable(tableToDelete.Reference);
```

**Comment by jskeet** [comment]
Odd. Hopefully it's just a typo. I've previously failed to automate tests for this as the table is "in use" after it's just been created, but I may well have missed something...

**Comment by jskeet** [comment]
Found the bug. Simple typo - having another go at testing...
