### ISSUE TITLE
Some objects excluded, creating missing words in documentation

### ISSUE THREAD

**Issue by jsimonweb** [GoogleCloudPlatform/google-cloud-dotnet#446]
In the documentation for Bigquery V2 Google Cloud Library for .NET
there are numerous missing words:
https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Bigquery.V2/api/Google.Bigquery.V2.BigqueryClient.html

Here is an example sentence from GetProjectReference:
"Creates a from the given project ID."

Here are some patterns to find the various occurrences of these issues:

"creates a and"
"creates a from"
"directly from a"

**Comment by jskeet** [comment]
I *suspect* these are issues that I've fixed by fixing up the XML documentation where I got warnings - hopefully it'll just be a case of regenerating the docs when I push the next beta. I'll leave this open until I can validate that though.

**Comment by jskeet** [comment]
Yup, looks like this is okay now. It won't show up until I do the next build, but I've rebuilt the docs locally and it should be okay.
