### ISSUE TITLE
Compile google.clouds.speech.v1beta1 dotnet.exe crash with visual studio 2015

### ISSUE THREAD

**Issue by xiaomingwang1234** [GoogleCloudPlatform/google-cloud-dotnet#448]
Compile google.clouds.speech.v1beta1 dotnet.exe crash with visual studio 2015

OS: window server 2012

Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

LightSwitch for Visual Studio 2015   00325-60002-99905-AA499
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00325-60002-99905-AA499
Microsoft Visual Basic 2015

Visual C# 2015   00325-60002-99905-AA499
Microsoft Visual C# 2015

Visual C++ 2015   00325-60002-99905-AA499
Microsoft Visual C++ 2015

Visual F# 2015   00325-60002-99905-AA499
Microsoft Visual F# 2015

AnkhSVN - Subversion Support for Visual Studio   2.5.12703.45
AnkhSVN - Subversion Support for Visual Studio 2.5.12703.45 
 * Ankh.Package 2.5.12703.45
 * Subversion 1.8.13 via SharpSvn 1.8013.3694.107

SharpSvn is linked to: Apr 1.5.1, Apr-util 1.5.4, Cyrus Sasl 2.1.25, eXpat 2.1.0, OpenSSL 1.0.2d 9 Jul 2015, serf 1.3.8, SQLite 3.7.17, Subversion 1.8.13-SharpSvn-1.8.13, ZLib 1.2.8
SharpSvn is optionally linked to: Berkeley DB 4.4.20, SharpPlink 0.64.0(SharpSvn)

Application Insights Tools for Visual Studio Package   7.8.00927.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20907.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft .NET Core Tools (Preview 2)   14.1.20907.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.30718.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.30718.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.30718.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   2.0.3.0
TypeScript tools for Visual Studio

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual Studio Tools for Universal Windows Apps   14.0.23121.00 D14OOB
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   3.11.837.0 (f10676f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   5.1.5.3 (f98871a95a479f6d71b3067b7e5834d41fcb2118)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   8.10.4.0 (6db87c53c073f4af2f5247fb738a27ea08c094fd)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration

**Comment by jskeet** [comment]
Can you give any more details of the error? You've given a lot of details about your environment, but not what you were doing or the exact result. (It's still fine for me, and CI seems okay...)

**Comment by xiaomingwang1234** [comment]
When I open google.clouds.speech.v12beta1.sln, VS 2015 is ask me install Microsoft Net.core 1.0.1 -SDK preview 2-003131(x64)
also I find   Microsoft Net.core 1 SDK 1.0.0 preview 2 (x64) installed.  Microsoft Net.core 1 SDK 1.0.1 VS 2015 tooling preview 2 (x64).  Now whenever Open solution it crash .

Error from VS 2015:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	dotnet.exe
  Application Version:	1.0.1.4500
  Application Timestamp:	576218d2
  Fault Module Name:	StackHash_a081
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c00000fd
  Exception Offset:	PCH_AE_FROM_Microsoft_DotNet_ProjectModel+0x0000000000067070
  OS Version:	6.2.9200.2.0.0.400.8
  Locale ID:	4105
  Additional Information 1:	a081
  Additional Information 2:	a081c3b14d504e6ea27bd946428a134c
  Additional Information 3:	6b8d
  Additional Information 4:	6b8d3cc592abc571cd7a2338bab2c0d6

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=190175

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

windiw evet view log:

Faulting application name: dotnet.exe, version: 1.0.1.4500, time stamp: 0x576218d2
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc00000fd
Fault offset: 0x000007fcdd1b7cc1
Faulting process id: 0x2938
Faulting application start time: 0x01d2257d46872229
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: unknown
Report Id: 8acfd943-9170-11e6-943a-005056a54822
Faulting package full name: 

Thanks for quick respond

**Comment by xiaomingwang1234** [comment]
another window event log:
Faulting application name: dotnet.exe, version: 1.0.1.4500, time stamp: 0x576218d2
Faulting module name: System.Private.CoreLib.ni.dll, version: 4.6.24410.1, time stamp: 0x57aa8203
Exception code: 0xc00000fd
Fault offset: 0x00000000004f3065
Faulting process id: 0x2b64
Faulting application start time: 0x01d2257cf66adc79
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.1\System.Private.CoreLib.ni.dll
Report Id: 3c3ba356-9170-11e6-943a-005056a54822
Faulting package full name: 
Faulting package-relative application ID:

**Comment by jskeet** [comment]
That sounds like it's a problem with the dotnet CLI... I can't see how it's a problem with the code in this repo.

Have you tried compiling from the command line instead of VS? Do any other solutions work?

**Comment by xiaomingwang1234** [comment]
I can compile C:\Users\wxiaoming\Downloads\dotnet-docs-samples-master\dotnet-docs-samples-master\speech\api  which I download from githurb. I can direct compile it. i do not need install anything, but for  Compile google.clouds.speech.v1beta1 I can not compile it at begining. error : missing Microsoft Net.core 1.0.1 -SDK preview 2-003131

Cloud you check your program and feature , Do you install Microsoft Net.core 1.0.1 -SDK preview 2-003131(x86)?

**Comment by jskeet** [comment]
Yes, as per the `global.json` file, this repository expects preview2-003131.

**Comment by xiaomingwang1234** [comment]
here is SKD path in my computer.
C:\Program Files\dotnet\sdk\1.0.0-preview2-003131

**Comment by xiaomingwang1234** [comment]
Here is my computer system information
OS Name	Microsoft Windows Server 2012 Datacenter
Version	6.2.9200 Build 9200
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	RD1223
System Manufacturer	VMware, Inc.
System Model	VMware Virtual Platform
System Type	x64-based PC
System SKU	
Processor	Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz, 2133 Mhz, 2 Core(s), 2 Logical Processor(s)
Processor	Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz, 2133 Mhz, 2 Core(s), 2 Logical Processor(s)
BIOS Version/Date	Phoenix Technologies LTD 6.00, 2012-06-22
SMBIOS Version	2.4
Embedded Controller Version	0.00
BIOS Mode	Legacy
BaseBoard Manufacturer	Intel Corporation
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Not Available
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	Canada
Hardware Abstraction Layer	Version = "6.2.9200.16442"
User Name	Not Available
Time Zone	Eastern Daylight Time
Installed Physical Memory (RAM)	10.0 GB
Total Physical Memory	10.0 GB
Available Physical Memory	4.36 GB
Total Virtual Memory	11.4 GB
Available Virtual Memory	5.42 GB
Page File Space	1.44 GB
Page File	C:\pagefile.sys
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by jskeet** [comment]
I suggest you report all of that to Microsoft - I'm afraid I can't help you, not having seen the same thing myself (and I compile this very regularly - and it's compiled on AppVeyor, Travis and Myget as well...)

**Comment by xiaomingwang1234** [comment]
Thanks a lot

**Comment by xiaomingwang1234** [comment]
I download latest githurb google-clound-dotnet , Now I can compile it
