### ISSUE TITLE
How to use Google-cloud-seech API v1beta1 do streaming operations?

### ISSUE THREAD

**Issue by xiaomingwang1234** [GoogleCloudPlatform/google-cloud-dotnet#450]
How to use Google-cloud-seech API v1beta1 do streaming operations?

for example method is used, callback method?

**Comment by jskeet** [comment]
You can go down to the gRPC layer to do so, but it's definitely not as user-friendly as we'd like it to be.

If you pull https://github.com/GoogleCloudPlatform/google-cloud-dotnet/pull/380 (or just look at it) you can see a bit more of what it looks like. It's all pretty low-level at the moment.

If you have any thoughts about what we *might* like to make strreams look like, I'd be very interested to hear them.

**Comment by xiaomingwang1234** [comment]
Hi, Jon Skeet,
 If you can warp all low level API to something like 

CloudSpeechNET.Manager = new CloudSpeechManager ();
 RecognitionConfig config = new RecognitionConfig { Encoding = AudioEncoding.Linear16, SampleRate = 16000 };
StreamingRecognitionConfig streamingConfig = new StreamingRecognitionConfig { Config = config };
CloudSpeechNET.Manager.RecognizerStream  = new RecognizerStream ();
CloudSpeechNET.Manager.RecognizerStream.AddConfigure(config);
CloudSpeechNET.Manager.RecognizerStream.StreamResponse  += new CloudSpeechManager.RecognizerStream.StreamResponseEventHanler(StreamResponseCallback);

//CloudSpeechNET.Manager.RecognizerStream class implement more events....

CloudSpeechNET.Manager.RecognizerStream.startRecording();

.....
 
CloudSpeechNET.Manager.RecognizerStream.stopRecording();
.....


 void StreamResponseCallback(object sender, CloudNET.Manager.RecognizerStream.Event.StreamResponseEvent e)
{

}

that will help user easy to use clouds speech API

**Comment by jskeet** [comment]
"StartRecording" and "StopRecording" wouldn't be feasible really, as there are so many different environments in which they could be used. Event handlers are a possibility for a stream wrapper though.

**Comment by xiaomingwang1234** [comment]
Hi, Jskeet, I am able to run you winformRecognizer demo. Thanks.
But sometime I got exception. hte detail as follow
in RecognizerStream.cs
line  public Task WriteAsync(TEffective message) => _underlyingStream.WriteAsync(_selector(message)); got exception sometime
=error: "Only one write can be pending at a time."

Any clue?

**Comment by jskeet** [comment]
That's surprising as the use of TPL is at least *intended* to stop that happening. It's almost certain that I'm not using it quite right at the moment - but I'm afraid I'm concentrating on other APIs right now, and don't have time to investigate Speech further. (This whole PR is really experimental.) If you want to investigate it further, the `RequestQueue<T>` class is the one to look at.

**Comment by xiaomingwang1234** [comment]
thanks a lot. I will dig into it

**Comment by jskeet** [comment]
Streaming is now supported in the Speech 1.0.0-alpha04 package.
Sample usage is in #711. It's inherently complicated, but I suspect it can't really be simplified much further. (Yes, we could have a call to make the initial request, but I don't think the benefits would warrant it unless there are other aspects to wrap.)
