### ISSUE TITLE
Should we be uniform in which Core versions we support?

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#455]
Currently our gRPC-based libraries target netstandard1.5, and the REST-based ones target netstandard1.3. Would it be better to target netstandard1.5 for everything, for simplicity and consistency?

**Comment by jskeet** [comment]
After some discussion, decided to stick with 1.3.

**Comment by chrsmith** [comment]
With .NET Core, I assume higher versions are backwards compatible? And the only reason to upgrade to a more recent version is just for new core libraries? If so, I'd imagine we would want to target the lowest version we can for as long as we can, right?

**Comment by jskeet** [comment]
The only benefits of targeting 1.5 instead of 1.3 would be:

- Consistency for all libraries
- Allowing netstandard1.5 code into Google.Api.Gax, although we have no requirements for that at the moment.

And yes, targeting 1.3 means it will be fine under 1.4, 1.5 etc.
