### ISSUE TITLE
Task Queue's?

### ISSUE THREAD

**Issue by chadbr** [GoogleCloudPlatform/google-cloud-dotnet#465]
Are there any plans to support task queues?

(is there a roadmap somewhere?)

  Thanks, Chad

**Comment by jskeet** [comment]
My personal understanding - which may well be flawed - is that task queues are only available on AppEngine Standard, and I'm not expecting .NET to run there any time soon. That said, I'll bring this up internally and see what the reaction is, or whether there's another non-AppEngine-specific API which we may be covering. (We have a lot of work already planned for the next year though...)

**Comment by chadbr** [comment]
FWIW, we use Task Queue's pretty extensively to do basic load balancing... Is there some architectural replacement (pubsub?)

Some related issues on the Java side:

GoogleCloudPlatform/google-cloud-java#22
GoogleCloudPlatform/google-cloud-java#682

**Comment by jskeet** [comment]
(Sorry for the delay - I'm still asking internally.)

**Comment by kimsterv** [comment]
Hi Chad,

I'm the product manager of our Task Queues service. I'd like to understand a bit more about your use case. We are about to release a new REST API for Pull Queues with App Engine (push) queues support shortly after. Are you looking to push tasks to GAE endpoints from outside of GAE or something different? What Task Queues features are important to you?

**Comment by chadbr** [comment]
@kimsterv Thanks Kim.

We have a pretty basic needs. We're using push queues to distribute load within AppEngine.

We receive data in pubsub and push it to different task queue's to do different processing tasks.

That's about it really -- the reason I'm asking in the dotnet side is we'd like to be able to start writing some of the processing in C#.

Does that help?

**Comment by jskeet** [comment]
Closing this for now, as it's not really relevant in this repo at the moment.
