### ISSUE TITLE
Getting started with Logging

### ISSUE THREAD

**Issue by ctaggart** [GoogleCloudPlatform/google-cloud-dotnet#466]
I'm having some difficulty getting started with nuget [Google.Logging.V2](https://www.nuget.org/packages/Google.Logging.V2/1.0.0-beta02). Sadly, this is still empty:
https://github.com/GoogleCloudPlatform/google-cloud-dotnet#google-cloud-logging

I was able to get our Go app working with Google Logging last week using [my fork of a Logrus hook](https://github.com/ctaggart/sdhook/blob/GoogleDefaultCredentials/sdhook.go). Now, I want to get the .NET client working since we have many more F# projects. Many of them are using NLog http://nlog-project.org/. I would be great to have an [NLog Target](https://github.com/nlog/NLog/wiki/Targets) for Google Logging.

I just got this to actually write log messages:

``` fsharp
module glog

open System.Collections.Generic

// https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Logging.V2/Google.Logging.Log4Net/Extensions.cs
let epochZero = System.DateTime(1970, 1, 1, 0, 0, 0, System.DateTimeKind.Utc)

let toTimestamp(dt: System.DateTime) =
    let sinceEpoch = dt - epochZero
    Google.Protobuf.WellKnownTypes.Timestamp(
        Seconds = sinceEpoch.Ticks / System.TimeSpan.TicksPerSecond,
        Nanos = (int)((sinceEpoch.Ticks % System.TimeSpan.TicksPerSecond) * (1000000000L / System.TimeSpan.TicksPerSecond))
    )

[<EntryPoint>]
let main argv =
    // https://github.com/GoogleCloudPlatform/google-cloud-dotnet#google-cloud-logging
    // https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Logging.V2/Google.Logging.Log4Net/GoogleStackdriverAppender.cs

    let client = Google.Logging.V2.LoggingServiceV2Client.Create()
    let rs = Google.Api.MonitoredResource(Type="global")

    let logName = Google.Logging.V2.LoggingServiceV2Client.FormatLogName("tachyusatmion", "fsharp-test")

    let le = Google.Logging.V2.LogEntry()
    le.TextPayload <- "2016-10-20 payload"
    le.InsertId <- sprintf "%s:%d" (System.Guid.NewGuid().ToString()) 1
    le.Severity <- Google.Logging.Type.LogSeverity.Debug
    le.Timestamp <- toTimestamp(System.DateTime.UtcNow)

    // let cs = Google.Api.Gax.CallSettings()

    let rsp = client.WriteLogEntries(logName, rs, Dictionary(), [le])

    printfn "%A" rsp
    0
```

Is it possible to see the http communication? I'm on my Mac. In Go, I'm able to `os.Setenv("HTTPS_PROXY", "http://127.0.0.1:8080")` and then start `mitmproxy` to see the communication.
![image](https://cloud.githubusercontent.com/assets/80104/19570187/c3558b16-96ad-11e6-9973-202dec511f8e.png)
<img width="598" alt="screen shot 2016-10-20 at 9 20 22 am" src="https://cloud.githubusercontent.com/assets/80104/19570196/ca0fe366-96ad-11e6-877e-16d1d994e32a.png">

Can I do something like that for this project? Is there a way to make the communication go through a proxy?

**Comment by jskeet** [comment]
The communication is over gRPC, which is then over HTTP 2.0. It looks like the Go client you're using is the HTTP/1.1 library. The equivalent of that would be [`Google.Apis.v2.Logging`](https://www.nuget.org/packages/Google.Apis.Logging.v2/) I don't think we're likely to have the bandwidth to add an NLog target at the moment, but of course if you would like to contribute one, we'd be happy to consider a pull request (after signing the contributor licence agreement etc).

**Comment by ctaggart** [comment]
I can't be the only only who finds this a big confusing. This project:

## Google Cloud Client Libraries for .NET
https://googlecloudplatform.github.io/google-cloud-dotnet/
https://www.nuget.org/packages/Google.Logging.V2/
https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/apis/Google.Logging.V2

The other autogenerated:
## Google API Client Libraries for .NET
https://developers.google.com/api-client-library/dotnet/
https://www.nuget.org/packages/Google.Apis.Logging.v2/
https://github.com/google/google-api-dotnet-client/tree/master/Src/Generated

- What are the pros/cons of using one vs the other?
- Do the Cloud libraries plan to be more efficient with the use of gRPC?
- What is the best way to debug the gRPC communication used by the Cloud Client Libraries for .NET?

**Comment by jskeet** [comment]
I agree it's all a bit confusing, and that's partly because it's not "done" yet, and we have some documentation work still to do (both here on Github and on Google-owned sites).

They're both autogenerated, at the moment - the Google.Logging.V2 library doesn't have any wrapper code yet, although it might in the future.

In terms of pros and cons, referring to Google.Apis.Logging.v2 as the REST API and Google.Logging.V2 as the gRPC API:

- The REST API is generated with stable codegen - it won't change until the next major version, whereas the gRPC API is still in flux. We believe it works, so it's *functionally* stable, but the API surface is still likely to change a bit before GA.
- The gRPC codegen is designed to take more advantage of known semantics in the underlying API, and we've spent a lot of time trying to make it as usable as possible.
- gRPC is more efficient than the REST API in terms of:
  - A binary format (protobuf) instead of JSON, for more efficient network transmission and parsing
  - Multiplexing over a single channel
  - More capabilities such as streaming, which isn't used by logging but is used by other APIs such as Speech

In terms of gRPC debugging, you need two steps at the moment:

- Set two environment variables, `GRPC_TRACE=all` and `GRPC_VERBOSITY=debug`
- Call `GrpcEnvironment.SetLogger` in your code, e.g. `GrpcEnvironment.SetLogger(new ConsoleLogger())` with suitable `using` directives

That will generate a *lot* of output - you can tinker with the environment variable values to limit the output.

**Comment by jskeet** [comment]
Anything else we need for this specific issue?

**Comment by ctaggart** [comment]
It was not super easy to get started. Here is what is working for me. It would help if there was a way to flush the `GoogleStackdriverAppender` before the program exited. If I don't sleep for a second, the messages don't get logged.

```
using System;
using System.IO;

``` csharp
class Program
{
    static void Main(string[] args)
    {
        // debug log4net
        //log4net.Util.LogLog.InternalDebugging = true;

        // debug grpc
        //Environment.SetEnvironmentVariable("GRPC_TRACE", "all", EnvironmentVariableTarget.Process);
        //Environment.SetEnvironmentVariable("GRPC_VERBOSITY", "debug", EnvironmentVariableTarget.Process);
        //Grpc.Core.GrpcEnvironment.SetLogger(new Grpc.Core.Logging.ConsoleLogger());

        //log4net.Config.XmlConfigurator.Configure(new FileInfo("log4net.xml"));

        var traceAppender = new log4net.Appender.TraceAppender();
        traceAppender.Layout = new log4net.Layout.PatternLayout { ConversionPattern = "%message" }; ;
        traceAppender.ActivateOptions();

        var gcloudAppender = new Google.Logging.Log4Net.GoogleStackdriverAppender();
        gcloudAppender.ProjectId = "myProject";
        gcloudAppender.LogId = "myLog";
        gcloudAppender.Layout = new log4net.Layout.PatternLayout { ConversionPattern = "%message" };
        gcloudAppender.ActivateOptions();

        var hierarchy = (log4net.Repository.Hierarchy.Hierarchy) log4net.LogManager.GetRepository();
        hierarchy.Root.AddAppender(traceAppender);
        hierarchy.Root.AddAppender(gcloudAppender);

        hierarchy.Root.Level = log4net.Core.Level.Info;
        hierarchy.Configured = true;

        var log = log4net.LogManager.GetLogger(typeof(Program));
        log.Info("An exciting log entry, 1!");
        log.Info("An exciting log entry, 2!");
        log.Info("An exciting log entry, 3!");

        // if GoogleStackdriverAppender was BufferingAppenderSkeleton, we could flush it
        //var appenders = hierarchy.GetAppenders();
        //foreach (var appender in hierarchy.Root.Appenders)
        //{
        //    var bufferingAppender = appender as log4net.Appender.BufferingAppenderSkeleton;
        //    if (bufferingAppender != null)
        //        bufferingAppender.Flush();
        //}

        System.Threading.Thread.Sleep(1000);
    }
}
```

**Comment by ctaggart** [comment]
fyi, I made a post about getting started here with much of the above code in F# here:
http://blog.ctaggart.com/2016/11/google-logging-from-log4net.html
https://twitter.com/cmr0n/status/803290458474483712
