### ISSUE TITLE
Google.Pubsub.V1 support for netstandard1.6

### ISSUE THREAD

**Issue by gibsonsyd** [GoogleCloudPlatform/google-cloud-dotnet#469]
Hi Guys, 

I'm a little confused as to which version of the Google PubSub library I'm supposed to use.

Google.Apis.Pubsub (Compatible with .net core but this is a [legacy API](https://developers.google.com/api-client-library/dotnet/apis/pubsub/v1)) 

OR 

Google.Pubsub ([newer](https://cloud.google.com/pubsub/docs/reference/libraries)?) ?

The error I get on a dotnet core class library when running "Install-Package Google.Pubsub.V1 -Pre" is:

"Package Google.Pubsub.V1 1.0.0-beta02 is not compatible with netstandard1.6"

Is there any planned support for dotnet core on the new API?

**Comment by jskeet** [comment]
Yes, there's absolutely support planned for .NET Core in Google.Pubsub.V1.
I'm *hoping* to get the first beta supporting it out in the next day or so.

However, that will still only be a beta. Google.Apis.Pubsub is still entirely valid, and has the benefit of being GA-released code (so the API won't change).

I'll look into making the "legacy" notice rather clearer...

**Comment by gibsonsyd** [comment]
Thank you for the feedback!
