### ISSUE TITLE
Google.Apis.Pubsub:V1 Documentation

### ISSUE THREAD

**Issue by gibsonsyd** [GoogleCloudPlatform/google-cloud-dotnet#470]
Where can I find detailed samples/documentation on the Google.Apis.Pubsub:V1 implementation? 

Everything seems to link to the beta docs for [Google.Pubsub](https://cloud.google.com/pubsub/docs/reference/libraries).

**Comment by jskeet** [comment]
I don't know of the location of any such documentation at the moment, I'm afraid.

The general getting started guide would be a good starting point though:
https://developers.google.com/api-client-library/dotnet/get_started

**Comment by gibsonsyd** [comment]
Thanks, I see those aren't very in depth.

**Comment by jskeet** [comment]
Yes, I know - hopefully we *should* be able to get better docs under https://cloud.google.com/pubsub/docs/reference/rest/, but I don't know how long that will take.

**Comment by jskeet** [comment]
I'm going to close this issue now, as it's not really on topic for this repo (where we're building the Google.Pubsub.V1 library instead).
