### ISSUE TITLE
Support generic Batch HTTP requests

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-dotnet#505]
We got feedback on this page that we don't have any code samples. https://cloud.google.com/bigquery/batch

The API clients support batch requests, https://developers.google.com/api-client-library/java/google-api-java-client/batch but I don't think the Cloud libraries do.

**Comment by jskeet** [comment]
Have been thinking about this a bit - it makes the API surface *much* more complicated, in terms of separating out the various responses etc.

For streaming inserts, we're already allowing a large amount of data to be sent in one go... I'm not sure that it's worth trying to go beyond that, personally.

It may well be simple enough in Node (which is more event driven) but I suspect more imperative languages are going to have trouble exposing generic batching cleanly.

**Comment by tswast** [comment]
Yeah. Might be more reasonable for asynch-first languages like Node.js and Go.

I contacted the person who sent the feedback to see what operations and language they want supported.
