### ISSUE TITLE
What would a BigQuery ADO provider look like?

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#519]
Opening this now so we can think about whether it affects any of the Google.Bigquery.V2 naming for GA.

Let's assume it's in a separate NuGet package, and possibly a separate namespace (e.g. `Google.Bigquery.V2.Ado`). The existing client library is _reminiscent_ of ADO.NET but without completely following the patterns (there's no connection object, the command object can't be executed directly, there's the whole matter of query jobs). What names would we want to give to the various ADO classes?

// cc @roji

**Comment by jskeet** [comment]
Closing for now, as we're not expecting to do this soon.

**Comment by Jetski5822** [comment]
Would love to get this, has there been any spiking on this?

**Comment by jskeet** [comment]
No, it's down in our list of priorities at the moment. I'm not saying it'll never happen, but I'm not planning on working on it imminently.

**Comment by jskeet** [comment]
No, it's down in our list of priorities at the moment. I'm not saying it'll never happen, but I'm not planning on working on it imminently.

**Comment by Jetski5822** [comment]
That's cool. Was thinking of using it as another backing store for Orchard Core.
