### ISSUE TITLE
Is resumable download required?

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#521]
Currently our underlying REST library only supports direct media download - a single HTTP request, which is downloaded in chunks. This has no "resume" functionality.

We used to perform downloads in chunks, but this was removed in https://github.com/google/google-api-dotnet-client/commit/0307285f1abe603dfab62d978d94e15909a25e69 to simplify the code... even then, there was no retry or resume.

**Comment by Capstan** [comment]
So long as there's a decent cancellation and resume model (e.g., the App needs to serialize and shut down and be relaunched later and pick up where it left off), that's fine. The less work the client has to do to make that happen, the better.

If there's just some async request floating around that will eventually be done, that doesn't work very well. If there's an object tracking the request the client has access to that has a pause/serialize/deserialize/reauthenticate/unpause, that makes it easier for the user than to try and just hard shutdown with outstanding async work, and then having to manually determine what progress had been made and continue from there.

**Comment by jskeet** [comment]
Okay. Will see what we can do.

**Comment by jskeet** [comment]
We have (or will have) a workaround for clients to do this themselves by specifying the range of data to download. We will punt on anything more until 1.1, when we'll probably have an extra set of methods to keep the simple case simple.

**Comment by jskeet** [comment]
Closing for the moment, as I'm not expecting to put any active work into this any time soon.
