### ISSUE TITLE
What's the preferred way to manage Cloud Storage and Datastore connection objects in ASP.NET?

### ISSUE THREAD

**Issue by markvincze** [GoogleCloudPlatform/google-cloud-dotnet#532]
I've been using the Datastore and the Cloud Storage in an ASP.NET (Core) application, and I'm wondering what's the preferred way to manage `DatastoreDb` and `StorageClient` instances.

Currently I'm creating a new instance on every request. Is there any more sophisticated support in the library to manage the connection objects, for example some kind of pool?

Thanks!

(Is this the proper place to ask questions like this, or should I rather post it to SO?)

**Comment by jskeet** [comment]
For gRPC-based APIs (such as Datastore) the connection (in the form of a `Channel`) will be pooled automatically. For Storage, you'll be creating a new `HttpClient` each time you create a new client instance.

Both `DatastoreDb` and `StorageClient` can be used from multiple threads - I'd generally recommend maintaining a single instance, usually via DI. It's hard to say anything more concrete without knowing your architecture though.

**Comment by markvincze** [comment]
Thanks for the info!

My application is pretty simple and straightforward: it's a REST Api with a handful of endpoints, and every request does 1 or 2 DataStore and Cloud Storage calls.

Before your suggestion I was always creating a new instance of the connection objects.  
Now I tried changing them to singletons (with DI), and the performance increased significantly. (These numbers don't mean much without context, but my request durations went from ~0.3-0.4 sec to under 0.1).

**Comment by jskeet** [comment]
That's interesting... which version of the libraries are you using? I wouldn't expect it to be nearly that expensive to construct them - I'll need to investigate that. Do you have any results that give information about whether it's Storage or Datastore that is most responsible for the difference? (I'll benchmark it myself, but the more you can tell me, the better :)

**Comment by markvincze** [comment]
I'm using `1.0.0-beta03` (I've just seen there is a new version).

I'll try to get around to isolate the calls and do some more focused measurements today, and will post the numbers here.

**Comment by jskeet** [comment]
That would be great - thanks ever so much :)

**Comment by markvincze** [comment]
Hey @jskeet,

I implemented some benchmarks and uploaded them to this [repo](https://github.com/markvincze/gcloud-dotnet-benchmark).
This was the result of one of the runs:
```
Starting the benchmark, 50 iterations

Executing benchmark with transient connection objects
Benchmarking the Datastore
Total elapsed: 00:00:07.8890224
Elapsed per lookup: 00:00:00.1580000

Benchmarking the Cloud Storage
Total elapsed: 00:00:07.8024711
Elapsed per lookup: 00:00:00.1560000

Executing benchmark with singleton connection objects
Benchmarking the Datastore
Total elapsed: 00:00:07.5032863
Elapsed per lookup: 00:00:00.1500000

Benchmarking the Cloud Storage
Total elapsed: 00:00:03.9868535
Elapsed per lookup: 00:00:00.0800000
```

Based on these results the Datastore lookup doesn't seem to be affected by whether the connection object is transient or singleton, but the Cloud Storage download is consistently faster if the connection object is a singleton.
On my machine the singleton version is almost twice as fast (the overhead seems to be around 50-100 ms, but I'd guess it depends on the connection).

Cheers,
Mark

**Comment by jskeet** [comment]
Thanks very much for that. My guess - still to be validated - is that the `HttpClient` creation in `StorageClient` is responsible.

**Comment by jskeet** [comment]
I've just done the same kind of test (calling StorageClient.GetBucket) and I'm seeing the same sort of 50% performance improvement. Looking into whether that can be mitigated - I *suspect* it may not be feasible, but we'll see...

**Comment by jskeet** [comment]
Right, just had a look at the traffic - and basically, with the "one instance" approach, it makes one request to accounts.google.com/o/oauth2/token and then N requests to www.googleapis.com/storage/...

With the "one instance per request" approach, each call requires one oauth token request and one storage request - so the doubling of time is pretty understandable.

Now the library could make `StorageClient.Create` cache the service if no other parameters are provided, but I'm not sure that's the best option. I'd *expect* the same credential object to be used each time, and for that to have (and keep) the oauth token. Will dig into that.

**Comment by jskeet** [comment]
Ah - I've found the problem, and it is indeed fixable from this repo... although the default application credentials are cached, the *scoped* credentials aren't. We just need to cache those, and the penalty goes away. Yay.

**Comment by markvincze** [comment]
Awesome! :+1:

**Comment by jskeet** [comment]
Right, I've got https://github.com/googleapis/gax-dotnet/pull/107 out for review. When that's in, we can update the dependencies and make the relevant change to BigQuery and Storage.

**Comment by philipri** [comment]
I think ran into this issue with the Datastore.

My repository created the DatastoreClient and DatastoreDb in it's constructor. This repository was stored as Scoped for DI (i.e. on each request). The DatastoreDb was using namespaces - so reusing it on every user's request wasn't feasible.

I switched to a Singleton (just to test) and the sample request went from down from 1000ms to 25ms.

My solution ultimately was to keep the DatastoreClient as a Singleton and the Repository (containing the DatastoreDB object) as Scoped (per request). I use DI to inject the client into the repository during construction.

Note these tests were on the local store.

**Comment by jskeet** [comment]
@philipri: When did you try this, out of interest? For Datastore and other gRPC-based APIs, "fairly recent" versions of the package will all share a common `Channel` if you're using default application credentials. You definitely shouldn't be seeing that issue.

When you say the tests were "on the local store" - if that means you were creating a new channel to the local emulator each time, that would explain it. You could keep _just the channel_ as a singleton and reconstruct the rest... but basically if you need a new connection on each request, that *will* be slow. You could also use the `ChannelPool` class in GAX to avoid having to create a new `Channel` each time. (That's *slightly* cleaner than keeping a static reference to the channel, although I admit there's not a lot in it.)

**Comment by philipri** [comment]
Results are with 1.0.0-beta04 and I am the local emulator (1.2.1).

I'm constructing my Channel in the Singleton as follows:
```
var channel = new Channel("localhost", settings.Value.DataStoreEmulatorPort, ChannelCredentials.Insecure);
_client = DatastoreClient.Create(channel);
```

The client seems relatively happy to be re-used as a Singleton. The DatastoreDb ideally I'd like to be Request specific (as it needs to be user specific for namespaces etc).

In production I'd expect just to be using default creds in a GKE container connecting to Datastore.

**Comment by jskeet** [comment]
@philipri: Right - that definitely explains it, as if you were constructing a new channel on each request, that would mean a new connection.

What you're doing is indeed fine. In production I'd expect you to be able to use `DatastoreDb.Create()` specifying just the namespace on each request - as that would use the default app credentials, it could keep a single channel open for all requests. That difference between local testing and production may be harder than just keeping a singleton client in both cases though. So long as there's nothing I don't understand, I think we're fine :)

As an aside, if you have any usability feedback on the `DatastoreDb` API, now would be an ideal time to give it while the surface is still somewhat malleable.

**Comment by philipri** [comment]
Thanks @jskeet !

I'm still feeling my way through the API right now and learning the overall Google stack. A couple of things I'm keeping a close eye on are:
a) the Key object (lots of abstractions to generate keys from application IDs like GUIDs)
b) some of the casting to the Google.Datastore.V1.Value (simple types are easy - but I foresee some complexity with more complex types etc etc).

All up - I'm enjoying it. No complaints :)
