### ISSUE TITLE
Support customer-supplied encryption keys

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#538]
Creating a signed URL
Upload an encrypted file
Download an encrypted file
Rotate encryption key

As seen in the code here.
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/storage/files.js

**Comment by jskeet** [comment]
Creating a signed URL is now present in the codebase, there just hasn't been a release yet.

The encryption side is a new requirement - I'll discuss it with Omar, but I strongly suspect it won't be in 1.0.

**Comment by jskeet** [comment]
I've renamed the issue to indicate that it's really just the crypto stuff that's missing now.

Looking at the [documentation](https://cloud.google.com/storage/docs/encryption) we need to add custom headers. I'm not sure that's feasible in the REST library we're sitting on top of at the moment - investigating...

**Comment by jskeet** [comment]
This would be a non-breaking change, so while I've left the Milestone as "GA" because we should *consider* it for GA, we may be able to postpone it until 1.1.

**Comment by jskeet** [comment]
Discussed with Omar: not a requirement for 1.0, but we'll try to add it for 1.1.

**Comment by jskeet** [comment]
This has now been implemented.
