### ISSUE TITLE
Should we allow metageneration-only preconditions for UpdateObject?

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#556]
Apparently the generation is meaningless without the metageneration, so I guess it might make sense to require the metageneration if we're specifying the generation...

// cc @Capstan for thoughts.

**Comment by Capstan** [comment]
That's exactly backwards. Metageneration only has context within a
particular generation.

**Comment by jskeet** [comment]
Whoops - right, so we should allow generation-only, but not metageneration-only? (Apologies for confusion.)

**Comment by jskeet** [comment]
The negative aspects feel harder to police here: if we have a "not match metageneration" condition it's not clear what generation condition we'd need.

**Comment by jskeet** [comment]
Discussed with DPEs - as soon as there are negative conditions (IfNot...) involved, it becomes harder to reason about what's logically valid.

Given that we're now automatically adding sensible preconditions, we won't do this - at least not yet.
