### ISSUE TITLE
Best Practice Datastore Class Mapping?

### ISSUE THREAD

**Issue by philipri** [GoogleCloudPlatform/google-cloud-dotnet#560]
Hi - I'm wondering if any class mapping / serialization helpers might be on the roadmap for Cloud Data Store or alternatively what the best practices for converting to/from POCOs to Entities are?

The BookStore sample uses hard coded methods to convert to/from the Book POCO to an Entity. See here: https://github.com/GoogleCloudPlatform/getting-started-dotnet/blob/master/aspnet/2-structured-data/Models/DatastoreBookStore.cs

Mongo's C# driver has some serialization features and can use Data Annotation Attributes to help define conversion behaviour (in this case between BSON and POCOs). Example: http://mongodb.github.io/mongo-csharp-driver/2.3/reference/bson/mapping/

It would be great to understand the intended current pattern for class conversion and if anything is on the roadmap.

**Comment by jskeet** [comment]
We're not expecting to add anything in the near future, at least. It's possible that there could be a higher level abstraction at a later stage, but the idea is *not* to provide an ORM for Datastore at this time.

**Comment by philipri** [comment]
Cool thanks @jskeet - good to know :)
