### ISSUE TITLE
can't build: .NET Core SDK version 1.0.0-preview2-003131 which is not installed or cannot be found

### ISSUE THREAD

**Issue by ctaggart** [GoogleCloudPlatform/google-cloud-dotnet#561]
I can't build this solution. I'm trying to troubleshoot an [Exception when using the logging library](https://github.com/ctaggart/SourceLink/issues/125), by building this, but I haven't been able to and I don't know why. I get this error about missing `1.0.0-preview2-003131`, but it is installed.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The project is configured to use .NET Core SDK version 1.0.0-preview2-003131 which is not installed or cannot be found. These components are required to build and run this project. Download the version of .NET Core SDK specified in global.json or update the SDK version in global.json to the version that is installed.	Google.Cloud.ClientTesting	C:\Users\cameron\cs\google-cloud-dotnet\tools\Google.Cloud.ClientTesting\GETSDKTOOLINGINFO	1	
```

You can see it is indeed installed:
```
PS C:\Users\cameron\cs\google-cloud-dotnet\tools> dotnet --version
1.0.0-preview2-003131
PS C:\Users\cameron\cs\google-cloud-dotnet\tools> ls "C:\Program Files\dotnet\sdk"


    Directory: C:\Program Files\dotnet\sdk


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/22/2016   9:40 AM                1.0.0-preview2-003131
da----       11/21/2016  12:06 PM                1.0.0-preview3-004056
```

![image](https://cloud.githubusercontent.com/assets/80104/20549334/19b2de7c-b0e0-11e6-9c8f-b94191cc85a0.png)

**Comment by jskeet** [comment]
Which version of VS is that, and are you able to build from the command line?

**Comment by ctaggart** [comment]
That was Visual Studio 2015 Update 3 (latest). I can't build from it, but I got I got the build script running on the command line, which is good enough for now.
