### ISSUE TITLE
Provide type information on fields

### ISSUE THREAD

**Issue by roji** [GoogleCloudPlatform/google-cloud-dotnet#584]
BigQueryRow currently provides access to fields, but doesn't not provide any knowledge as to types. It may be useful in some scenarios to be able to know in advance what type they're about to get before actually getting it. At the very least it would allow for efficient switching on the type enum (rather than checking the type of the returned object).

This could be provided by exposing the BigQueryDbType of the field (currently available internally only), and/or exposing the actual CLR type that would be returned (the latter is actually part of the ADO.NET API). Ideally we could have both.

If this makes sense I can submit a PR.

**Comment by jskeet** [comment]
I think *something* around this makes sense, yes. It's not immediately clear to me what - it gets trickier for repeated and record fields. You basically need to know both the type and the mode in order to get useful information.

We could potentially have a separate `Field` representation with all the relevant information using the enums defined in this library (rather than the text representations). That could be part of the alternative schema representation mentioned in the other PR... what do you think?

**Comment by roji** [comment]
At least in ADO.NET, you have access to 3 things:
* The database "data type", which is simply a string. It's completely database-specific. This is already accessible as `Type` on `TableFieldSchema`.
* The CLR type that would be returned for this field. It's not a huge improvement over simply getting the value and checking its type, but I guess in some scenarios it may allow better performance (i.e. user skips column based on the type that would be returned, so no conversions etc.). It would be good to provide this in the ADO.NET provider, although if it doesn't make sense for you in the non-ADO.NET API I can implement it there.
* On parameters, you also have the option of specifying the type as a database-specific enum (e.g NpgsqlDbType), to prevent ambiguity when mapping the CLR type to the database type. There actually isn't a getter in ADO.NET for this on *results*, although it seems like a good idea to me.

Regardless, you're right that repeated and record fields complicated things. From an enum perspective, the Npgsql solution was to use `[Flags]`, so an array of ints is represented as `NpgsqlDbType.Array | NpgsqlDbType.Integer`. However, for record fields there's nothing meaningful except simply saying it's a record.

None of this is extremely urgent, I'm documenting issues that are coming up as I work on the provider (you may want to add a bigquery label and maybe also an ado.net one).

**Comment by jskeet** [comment]
I'm going to close this for now, given that we expose the BQ type via `BigQueryRow.Schema` - albeit somewhat painfully.
