### ISSUE TITLE
Missing support for date/time types?

### ISSUE THREAD

**Issue by roji** [GoogleCloudPlatform/google-cloud-dotnet#585]
The library currently supports the BigQuery timestamp type, but apparently not the other date/time types (date, datetime, time, see https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types).

@jskeet I can submit a PR to add support for these, but I remembered you're the Nodetime guy so I thought I'd check with you first:)

**Comment by jskeet** [comment]
There are two different sets of types: the ones used by Standard SQL, and the ones used by the underlying BigQuery data. It's not yet clear to me whether the SQL types can be used everywhere, or only in SQL parameters, stored procedures etc. We should talk more about this aspect on a Hangout or similar...

**Comment by roji** [comment]
OK, I understand (you have a pending hangouts invitation from me). I encountered this issue while writing integration tests which do things like `SELECT DATE '2014-09-27'`, and getting an error from the client lib. That *seems* to indicate date is a distinct type, at least as far as the client library is concerned.  There's also nothing on [this page](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types) which indicates a difference between timestamp as a type and, say, date.

**Comment by jskeet** [comment]
The date and time types have now been added to the legacy SQL types, so I need to add those.
We *may* now be able to get away with a single type enum, although working with repeated/array types may be tricky.

**Comment by jskeet** [comment]
Looking at:

- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types
- https://cloud.google.com/bigquery/data-types

there are basically two sets of names, standard / legacy:

- STRING / STRING
- BOOL / BOOLEAN
- INT64 / INTEGER
- FLOAT64 / FLOAT
- BYTES / BYTES
- DATE / DATE
- TIME / TIME
- DATETIME / DATETIME
- TIMESTAMP / TIMESTAMP
- ARRAY / ??? (repeated fields)
- STRUCT / RECORD - sort of; need to check more closely

Now, we can probably get away with one enum, where you can't use `ARRAY` when specifying the type of a field when creating a schema. But which set of names should we use?

Options:

- Use legacy only
- Use standard only
- Use both, by giving both INT64 and INTEGER the same value, for example.

Thoughts?

**Comment by jskeet** [comment]
(I can start addressing the immediate issue before this is decided, of course.)

**Comment by roji** [comment]
I don't what the status of legacy SQL, but I would vote towards using the standard naming only - having two names may be confusing to users ("should I use Int64 or Integer, what's the difference?").

Regarding arrays, see [this comment](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/584#issuecomment-263217879) I made regarding the possibility of or'ing array with one of the other values. That would allow you to express "array of int64" with the enums.

So if I understand correctly, the idea is to retain only one enum (rather than the current situation with BGDbType and BGParameterType)?

**Comment by jskeet** [comment]
1) That sounds reasonable. The standard name is more precise anyway, so hopefully won't cause any confusion. The API will always return values in the legacy format, but hey...

2) Hmm. Given the record aspect, I think I'm happier just keeping the field mode separate when creating a table. Will keep considering though. I don't really want to make it a flags enum when it's not *really* a set of bits.

3) Yes, a single enum eventually. That may take a little while though.

**Comment by roji** [comment]
OK, sounds good!
