### ISSUE TITLE
Create an Error Reporting Instrumentation Library for ASP.NET Core

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#592]

**Comment by iantalarico** [comment]
This is code complete and needs to be pushed to alpha

**Comment by jskeet** [comment]
I'm hoping to do a release of a few different things later in the week - happy to include this in there.

**Comment by iantalarico** [comment]
Awesome, that would be great, I was just about to send an email to ask for this.  I was waiting for the trace bits so we could do an alpha push for the asp.net core bits and another beta push for the asp.net bits.

**Comment by jskeet** [comment]
Now pushed.
