### ISSUE TITLE
StorageClient.DownloadObject blocks forever if object does not exist

### ISSUE THREAD

**Issue by tommed** [GoogleCloudPlatform/google-cloud-dotnet#598]
Nuget package: `1.0.0-beta04`

```
this.credential = GoogleCredential.GetApplicationDefaultAsync().Result;
// ...
this.client = await StorageClient.CreateAsync(this.credential);
// ...
using (var stream = new MemoryStream())
            {
                this.client.DownloadObject(
                    this.bucketName, 
                    filename, 
                    stream);

                return await Task.FromResult(stream.ToArray());
            }
```

The code above works fine when files/objects exist in the bucket however, if you request a file that doesn't exist, DownloadObject continues to block - forever.

I have checked, and `IProgress<DownloadObject>` is fired when you call the async version, but the async never returns either. I have even tried listening out for the progress when the status is Failed and cancelling a `CancellationToken` which is passed into `DownloadObjectAsync`, but again, the call continues to block.

There is also no way of detecting if the file exists (other than `ListObjects`, but as this isn't recursive, it doesn't resolve my need) - so there is no workaround currently.

**Comment by jskeet** [comment]
That's definitely surprising - will look into it; thanks.

**Comment by jskeet** [comment]
I'm unable to reproduce this - I get a `GoogleApiException` for the 404 response that's coming back. That's for both the bucket name being wrong and the filename being wrong. (I'm about to send out a PR to add separate integration tests for both of those cases.)

Are you certain it's not just that your method is returning a faulted task, and you're not handling that properly?

Here's a short console app I've tried, using Google.Storage.V1.1.0.0-beta04:

```csharp
using Google.Storage.V1;
using System.IO;

namespace StorageBug
{
    class Program
    {
        static void Main(string[] args)
        {
            string bucket = "bugbucket";

            var client = StorageClient.Create();
            client.DownloadObject(bucket, "no-such-object", new MemoryStream());
        }
    }
}
```

It ended with:

```text
Unhandled Exception: Google.GoogleApiException: Not Found
```

Could you try the same app with your own bucket, and report back what happens?

**Comment by tommed** [comment]
Thanks @jskeet, it seems to be happening consistently from a machine running VS2017 RC and dotnet core 1.1.0 - I'm thinking that possibly the API is working correctly and the error is returning (on what you have said) however, there is something screwy in dotnet runtime that isn't throwing this exception out. Will continue to investigate and will update the thread, but for now can close this as it's not your problem ;)
