### ISSUE TITLE
AllowQuotedNewlines missing in UploadJsonOptions

### ISSUE THREAD

**Issue by roji** [GoogleCloudPlatform/google-cloud-dotnet#606]
@jskeet it exists in UploadCsvOptions but not in UploadJsonOptions. Apparently [it's supported](http://stackoverflow.com/a/16279170/640325), it may be a good idea to do a pass over other options as well.

**Comment by jskeet** [comment]
That's newline *delimited* JSON - I don't see anything in there about allowing quoted newlines within the data itself. That wouldn't make sense IMO, as it's not valid JSON.

**Comment by roji** [comment]
Apologies, I mixed things up...

If I understand correctly, the JSON format is even more limited than the CSV format in that quoted newlines aren't supported? That's surprising...

**Comment by jskeet** [comment]
I don't think it's particularly surprising - it would be invalid JSON. Whatever is producing the JSON should be encoding newlines as `\n` anyway, at which point it's fine. JSON is a rather better-specified format than CSV :) This definitely doesn't represent a limitation in what can be uploaded via JSON.

**Comment by roji** [comment]
Oh, was unaware of that... Apparently my grasp of standardized JSON is a bit flimsy.

Please ignore...
