### ISSUE TITLE
Update ReadMe to reflect quality levels of client libraries

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-dotnet#618]
We will soon have client libraries at different quality levels. Let's make sure we reflect this information in our top-level ReadMe file the moment we cut the new release.

The update for [PHP's ReadMe](https://github.com/omaray/google-cloud-php/blob/readme-update-beta/README.md) has already be done (as a [Pull Request](https://github.com/GoogleCloudPlatform/google-cloud-php/pull/274) for now) and can be used as the canonical example to follow. The list below highlights the main changes to follow for this repo.

## General
- [ ] P1: change from `Google Cloud Libraries for .NET` to `Google Cloud .NET Client` (for consistency)

## Listing Beta client libraries
- [ ] Remove the text "The Google Cloud Libraries for .NET support the following Google Cloud Platform services: "

- [ ] Create a section to show the Beta client libraries (see image right below for text & layout)

- [ ] Make the term `Beta` link to the **Versioning** section of the ReadMe (see image right below)

- [ ] Add the term `(Beta)` next to each API name (see image right below for text and visual):

![image](https://cloud.githubusercontent.com/assets/6609430/20909391/4b49169c-bb10-11e6-8409-7903c317937f.png)

## Listing Alpha client libraries
- [ ] Create a section to show the Alpha client libraries (see image right below for text and layout)

- [ ] Make the term `Alpha` link to the **Versioning** section of the ReadMe (see image right below)

- [ ] Add the term `(Alpha)` next to each API name (see image right below for text and visual):

![image](https://cloud.githubusercontent.com/assets/6609430/20909394/550feef8-bb10-11e6-8390-f6756bc2301b.png)

## Versioning section

- [ ] If the **Versioning** section doesn't exist, add one.

- [ ] Add the following content in the **Versioning** section:

![image](https://cloud.githubusercontent.com/assets/6609430/20909795/9c6eb1a6-bb12-11e6-93c4-4d4780368196.png)

**Comment by jskeet** [comment]
After discussion with Omar:

- We'll leave the name as it is. We have multiple libraries and no single "big" package, so it makes sense for it to be plural
- We'll have three pre-release version types: "late beta", "beta" and "alpha", where our "late beta" is like the "beta" above, and "beta" is "we're confident it works, but we expect API churn" vs "alpha" being "pretty experimental - stuff may not work". In future releases we may try to align with the simple alpha/beta, but for the moment these three different levels are useful
- As we'll now have redundancy between the readme and the docs, we'll have a tool to generate both sections (this may come later)
