### ISSUE TITLE
Multiple processes contend for GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#653]
When the library opens the file pointed to by GOOGLE_APPLICATION_CREDENTIALS, it opens the file in a locked mode.

So when 2 processes start at the same time and start invoking this library, one of them fails with the error:
'System.InvalidOperationException: Error reading credential file from location C:\users\root\Documents\silver-python2-b6dac6d6b9a8.json: The process cannot access the file 'C:\users\root\Documents\silver-python2-b6dac6d6b9a8.json' because it is being used by another process.

Discovered via https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/116

I expect to be able to launch 2 processes that invoke this library without error.

**Comment by jskeet** [comment]
This would need to be fixed in the support library - I've moved the issue there.
