### ISSUE TITLE
[Low prio] Website for dotnet has light css issues

### ISSUE THREAD

**Issue by Temikus** [GoogleCloudPlatform/google-cloud-dotnet#663]
![image](http://i.giphy.com/l0Hly17X26RrfH6a4.gif)

Reproducible when you squeeze the window a bit, just drag the border until it appears.
https://googlecloudplatform.github.io/google-cloud-dotnet

**Comment by jskeet** [comment]
Interesting - Java and Python have the same issue; Ruby, Node and Python don't. Will See if I can use their CSS, and ping the Java/Python folks...

**Comment by jskeet** [comment]
Related to #207 - again, not something I'd really be able to handle myself (having tried).

**Comment by jskeet** [comment]
Closing this in favour of #207 covering general doc web site prettiness, rather than having multiple bugs open.
