### ISSUE TITLE
Storage: Url Signer cannot generate signed URLs for objects with spaces in the name.

### ISSUE THREAD

**Issue by lostllama** [GoogleCloudPlatform/google-cloud-dotnet#667]
Steps to reproduce:

1. Upload a file to a bucket, e.g. **test_2016-12-19 07-31-31Z.json**
2. Use the URL signer to generate a signed GET URL.
3. Go to the URL - error code: SignatureDoesNotMatch

I'm assuming that when generating the signature, it doesn't escape the space, but the server does. For now, I've added code to ensure that I can't create objects with spaces in the name (I replace the space with -) and this is now working to generate URLs.

P.S. I'm running on the latest NuGet version as of today (2016/12/19)

**Comment by lostllama** [comment]
Looking at the [library code](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/UrlSigner.cs), it would appear that the sign method _does not_ escape the string, so the URL returned actually includes a space, but the browser automatically escapes the space with %20.

The bucket and object names taken for signing the URL are taken from the Object returned from the CreateObject method. I'm assuming the sign method should escape the URLs.

**Comment by jskeet** [comment]
@evildour Are you able to have a look at this?

**Comment by lostllama** [comment]
Sample code:

    public string UploadAndGetUrl()
    {
        Google.Apis.Storage.v1.Data.Object obj = null;
        using (var stream = GetKeyStream())
        {
            var cli = StorageClient.Create(GoogleCredential.FromStream(stream));
            var ms = new System.IO.MemoryStream(System.Text.Encoding.UTF8.GetBytes("Hello"));
            obj = cli.UploadObject("bucket", "key with spaces", null, ms);
        }
        using (var stream = GetKeyStream())
        {
            var urlSigner = UrlSigner.FromServiceAccountData(stream);
            return urlSigner.Sign(obj.Bucket, obj.Name, TimeSpan.FromHours(1), HttpMethod.Get);
        }
    }

**Comment by evildour** [comment]
@jskeet Yes, I'll look into this now
