### ISSUE TITLE
ErrorStatsServiceClient.ListEvents does not allow a time range to be passed in.

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#679]
Google.Cloud.ErrorReporting.V1Beta1.ErrorStatsServiceClient.ListEvents does not allow a time range (QueryTimeRange) to be passed in.

To use a filter the grpc client must be used.

**Comment by jskeet** [comment]
You just need to call the `ListEvents(ListEventsRequest)` method - you need to build the request yourself, but you can still use all the settings etc from the higher abstraction layer.

**Comment by iantalarico** [comment]
That's what I ended up doing.  I had thought you wanted me to point out when I had to use the request objects. Sorry!

**Comment by jskeet** [comment]
Sorry, that was before we had the ability to use arbitrary request objects and you had to drop down to the gRPC client. In general optional parameters won't have a "flattened" overload - but do shout if you think something is effectively required and there isn't a flattening for it.
