### ISSUE TITLE
A more modern logging library than log4net - logary

### ISSUE THREAD

**Issue by haf** [GoogleCloudPlatform/google-cloud-dotnet#681]
Hello,

What do you think of recommending a more modern logging library for .Net, than log4net? Logary also has StackDriver support now https://github.com/logary/logary#stackdriver-target-alpha-level – and *also* supports structured logging and metrics.

Cheers,
Henrik

**Comment by jskeet** [comment]
Our aim isn't to recommend that users migrate to a new logging library: we want to meet them where they are, instead. I'm sure we'd be happy to link to other libraries which integrate with StackDriver though - I'm not quite sure where, but probably on the main StackDriver page.

**Comment by haf** [comment]
Well, sometimes they're creating a new app, right? There is tremendous power in default choices. Here's the effective rate of consent to organ donation to illustrate the point:

![default-choices](https://cloud.githubusercontent.com/assets/193115/21643648/c3a6f72c-d289-11e6-84c3-62af00907111.png)

That said, would you be open to adding it to the StackDriver page?

**Comment by jskeet** [comment]
I'm certainly open to finding somewhere to list it as a StackDriver integration library. I very much doubt that we're going to start **recommending** one third-party library over another though.

**Comment by haf** [comment]
That's what you're doing implicitly with a default choice though: and currently it's log4net. Just a mention of Logary as an alternative is all I'm asking for :)

**Comment by jskeet** [comment]
Well, "mention" and "recommend" (as per the first comment) are _very_ different things. Mentioning it and perhaps providing a sample seem absolutely reasonable. I'm asking internally where the best location would be in the docs.

**Comment by haf** [comment]
I see your point. Looking forward to hearing what internal discussions come up with then 👍, thanks.

**Comment by jskeet** [comment]
I've added a link on https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Logging.V2/index.html for now, and filed an internal issue for *possibly* including it in https://cloud.google.com/logging/docs/ - although that may depend on uptake of Logary in general and the Stackdriver target not being in Alpha. (Obviously it'll be easier for the target to be fully released when Google.Cloud.Logging.V2 has hit GA....)
