### ISSUE TITLE
Support BigQuery partitioned tables

### ISSUE THREAD

**Issue by jcondit** [GoogleCloudPlatform/google-cloud-dotnet#692]
The current client libraries do not support table partitioning. In particular, CreateTableOptions should allow clients to set partitioning options for the created table:
https://cloud.google.com/bigquery/docs/creating-partitioned-tables

Requested by a user over here:
https://code.google.com/p/google-bigquery/issues/detail?id=872

**Comment by jskeet** [comment]
Thanks, that looks like it's eminently feasible. I probably won't provide explicit support for it on `BigQueryTable`, as `BigQueryTable.Resource` already exposes the relevant resource. I'll demonstrate that in a snippet though.

**Comment by pnaszarkowski** [comment]
Thanks Jon for a quick fix. Will use it right away!

**Comment by jskeet** [comment]
My pleasure. We're in the middle of a few other changes which make it *slightly* non-optimal to release a package right now (and I'm at a conference today) but I can add it to my work queue if a packaged version would unblock you. Otherwise, you could certainly fetch from github and package it yourself, if you're happy to do that.

**Comment by pnaszarkowski** [comment]
Fresh nuget would be nice. What is your timeline on releasing new one anyway?

**Comment by jskeet** [comment]
We may well have a fresh version of GAX within this week, to support the streaming work for Speech (see various PRs)... while we don't need the new version of GAX for BigQuery, it probably makes sense to put my Release Engineering hat on just once in the week, so to speak. If we can get a BigQuery release out this week (by Thursday evening UK time - I don't like releasing on a Friday) would that work for you?

**Comment by pnaszarkowski** [comment]
That is fine, thank you.

**Comment by jskeet** [comment]
The new version - 1.0.0-beta08 - is now live on nuget.org
