### ISSUE TITLE
Why is log4net required for Google APIs Client Library on .NET 4.5?

### ISSUE THREAD

**Issue by ctaggart** [GoogleCloudPlatform/google-cloud-dotnet#699]
Why is log4net required for Google APIs Client Library on .NET 4.5? Can you please get it removed as a dependency? Let me know if there is a better place to report this.

https://www.nuget.org/packages/Google.Apis/

![image](https://cloud.githubusercontent.com/assets/80104/22135279/0ea3aabe-de82-11e6-9739-276c7e8f87cd.png)

**Comment by jskeet** [comment]
The right repo for reporting bugs / feature requests for Google.Apis.* is https://github.com/google/google-api-dotnet-client, but as it happens we already have a request for this: https://github.com/google/google-api-dotnet-client/issues/849 - it looks like it's already fixed, just awaiting a new release :)

**Comment by ctaggart** [comment]
Thanks Jon!
