### ISSUE TITLE
Have away to fetch the project id from the environment

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-dotnet#70]
Currently we can fetch the authentication credentials from the environment, via gcloud's default app credentials, metadata server, etc... We should be able to do the very same for the project id, the metadata server serves that and it should be possible to get that from gcloud if necessary or even an environment variable.

I think that this would simplify the code even further and allow the code to be written without hardcoding the project id on it.

**Comment by jskeet** [comment]
Agreed - this is a request under consideration already on a cross-platform basis. I will check on the progress though...

**Comment by jskeet** [comment]
No update on this at the moment.

**Comment by jskeet** [comment]
Closing this as stale - I'm not expecting this to change any time soon, nice as it would be.
