### ISSUE TITLE
Publish ASP.NET Error Reporting MVC Filter

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#704]
The code was submitted in PR #697 but needs to be pushed to nuget.

Expected to be out by EOW

**Comment by iantalarico** [comment]
@csells FYI

**Comment by csells** [comment]
We'll need the How-To docs updated when this PR goes through.

**Comment by csells** [comment]
And we need to update the ER docs to show how to enable the ER API or no exceptions can happen once the app is deployed (and it will throw exceptions).

**Comment by jskeet** [comment]
Will update https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.ErrorReporting.V1Beta1/index.html when I've pushed the release (just to show the difference between MVC and Web API) but that won't include the API enabling or any other How-To docs. Ian, are you happy to own that?

**Comment by iantalarico** [comment]
I will add the API enabling and other how to docs.

**Comment by iantalarico** [comment]
I got side tracked by some related work to push events through the logs api to the error reporting api.  I will make updates to the ER doc about the change, how to use the error reporting api if desired (and in that case that the api must be enabled).
