### ISSUE TITLE
Travis "green" with failed tests?

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#715]
This build is troubling:

https://travis-ci.org/GoogleCloudPlatform/google-cloud-dotnet/builds/194887102

> === TEST EXECUTION SUMMARY ===  
>   Google.Cloud.Diagnostics.Common.Tests  Total: 54, Errors: 0, Failed: 1, Skipped: 0, Time: 2.212s  
> The command "./build.sh" exited with 0.  
> Done. Your build exited with 0.

I can't reproduce this, however - if I deliberately introduce a test failure, it fails properly. Worth keeping an eye on though... let's manually check the output before merging for the moment.

cc @iantalarico @chrisdunelm

**Comment by iantalarico** [comment]
I've been checking almost every passing test in the last 2 weeks run and haven't seen this pop up again.

**Comment by jskeet** [comment]
Let's close it for now, but keep an eye.
