### ISSUE TITLE
GCE metadata instanceId is an unsigned long, which Json.net v9.0.1 doesn't handle

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-dotnet#728]
GCE metadata instanceId is an unsigned long - see [doc here](https://cloud.google.com/compute/docs/reference/beta/instances).

On desktop we currently use Json.net v7.0.1, which handles this OK using a BigInteger.
On NetCore we use Json.net v9.0.1, which does not handle this, but throws a FormatException instead.
We need to upgrade to Json.net v9.0.2-beta, which does support using BigInteger on NetCore.
This dependency is buried deep down in [Google.Api.Core](https://www.nuget.org/packages/Google.Apis.Core/)'s [project.json](https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/GoogleApis.Core_dotnetcore/project.json#L5).

**Comment by jskeet** [comment]
Closing as obsolete - we're using a more recent version of Json.NET now (and hope to move away from it entirely in the future...)
