### ISSUE TITLE
Pub/Sub documentation incomplete

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-dotnet#734]
The Pub/Sub documentation needs some corrections & additions:

- PublisherClient & SubcriberClient links 404
- There are no code samples
- auth flow which relies on gcloud beta auth application-default login should point users to a resource on using service accounts, since pub/sub users are particularly vulnerable to low default quotas that come with end-user account auth flow with gcloud.  This can be done either by referencing the SDK page for application-default command or a see also to: (https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account)

**Comment by kir-titievsky** [comment]
The above refers to the github view of the page (https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.PubSub.V1/docs/index.md)

Re-reading the GitHub landing page, I see that this was meant to be consumed here:
 https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.PubSub.V1/index.html  But this is not the docs page that we link to from the auto-generated client libraries pages on cloud.google.com.

This might we WAI, but I'd like to keep this open while we decide if there is a discoverability problem.

**Comment by jskeet** [comment]
Could you say where the links are broken? The links on https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.PubSub.V1/index.html are working for me. There's not very *much* sample code, but there's a bit there and brief per-method samples within the API reference documentation.

I don't know what the plans are for a more organized set of samples on cloud.google.com - please contact me internally to talk about that. // cc @SurferJeffAtGoogle 

I'm happy to add more detail on the auth aspects.

**Comment by kir-titievsky** [comment]
@jskeet: I upon further inspection, I see that we do, in fact, link to the rendered API docs pages from cloud.google.com/ client library pages.  So my bad for false alarm. 

I'd appreciate a bit more detail on the auth point, however. Thanks!
