### ISSUE TITLE
grpc crashes my process when not authenticated.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#741]
I did **not** have GOOGLE_APPLICATION_CREDENTIALS set.
My gcloud auth was in a wonky state so that everything I tried failed with `invalid_grant`.
I called datastoredb to UpsertAsync() a new entity.  The process crashed with grpc at the top of the stack.
I expected to see an error message.

**Comment by jskeet** [comment]
Are you able to reproduce this with a minimal example (e.g. a tiny console app and a description of the "wonky state")?

**Comment by jskeet** [comment]
Ping for minimal example if possible...

**Comment by SurferJeffAtGoogle** [comment]
gcloud doesn't have to be in a wonky state.  Working on a sample...

**Comment by jskeet** [comment]
@SurferJeffAtGoogle: Did you get anywhere with this, and is it still an issue with Grpc.Core 1.3.6? (Would like to try to either address or close...)

**Comment by jskeet** [comment]
Closing for the moment as we need more information - and when we *do* have information, it sounds like it may well be an issue better filed on the gRPC repo.
