### ISSUE TITLE
Create ToStruct Classes for Classes in Google.Cloud.*

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#742]
Currently there is no way to convert types (such as Google.Cloud.ErrorReporting.V1Beta1.ReportedErrorEvent) to a struct without manually converting the type or converting from the object to json and from json to a struct.

**Comment by jskeet** [comment]
Could you refile this in https://github.com/google/protobuf? It's not really a google-cloud-dotnet issue.

**Comment by iantalarico** [comment]
Done. https://github.com/google/protobuf/issues/2672
