### ISSUE TITLE
Make StartSpan return an IDisposable?

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#791]
Looking at the sample code here:

```csharp
tracer.StartSpan(nameof(TraceHelloWorld));
Console.Out.WriteLine("Hello, World!");
tracer.EndSpan();
```

makes me wonder what will happen if an exception is thrown before I call `EndSpan`... or what would happen if I forget to call `EndSpan`. Would it make sense to have `StartSpan` return a disposable object, so I could use:

```csharp
using (tracer.StartSpan(nameof(TraceHelloWorld))
{
    Console.Out.WriteLine("Hello, World!");
}
```

**Comment by jskeet** [comment]
... and if we should actually be calling SetStackTrace (like TraceHeaderPropagatingHandler does), perhaps we should have `tracer.RunInSpan(Action)` and `tracer.RunInSpan(Func<T>)` options.

**Comment by iantalarico** [comment]
I think these are both very good ideas. will look into this this week. Thanks Jon!
