### ISSUE TITLE
LoggingServiceV2Client.WriteLogEntries requires not-null entryLabels

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/google-cloud-dotnet#796]
LoggingServiceV2Client.WriteLogEntries method has a number of parameters and one of them is entryLabels. These are supposed to be optional labels that you can attach to the log. However, you cannot pass in null for entryLabels. If you do, you get a "value cannot be null" error. So, in effect, these labels are not really optional. 

The workaround is to create an empty Dictionary and pass that for entryLabels but this is not ideal. 

You can use the following code to reproduce the problem, just replace entryLabels with null: 
https://cloud.google.com/logging/docs/reference/libraries#client-libraries-usage-csharp

**Comment by jskeet** [comment]
Assigning Chris to look into this - basically it's a case of parameter flattening. A couple of options:

- We could accept null for map/repeated fields, and simply not assign that when creating the request
- We could add extra flattenings

**Comment by chrisdunelm** [comment]
I've just seen that the gapic yaml contains a list of required_fields for each flattening. E.g.: https://github.com/googleapis/googleapis/blob/master/google/logging/v2/logging_gapic.yaml#L341
So I'll see if I can make a change to accept null, and not assign, for flattened parameters that are not specified as required.

**Comment by chrisdunelm** [comment]
This was fixed in toolkit[#1051](https://github.com/googleapis/toolkit/pull/1051), and the optionality of it can now be seen in [LoggingServiceV2Client.cs line 638](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingServiceV2Client.cs#L638).
