### ISSUE TITLE
Properly Dispose of all ASP.NET Core Middleware

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#802]
We currently do not properly clean up the ASP.NET Core Middleware's Resources

**Comment by iantalarico** [comment]
This should be easier once the IMiddleware interface is released.

**Comment by iantalarico** [comment]
Dropping to P2 as the resources are alive as long as the application

**Comment by jskeet** [comment]
Is this still an issue? Are we ever likely to address it? If not, let's close it.

**Comment by iantalarico** [comment]
It looks like the interface isn't in 1.0 so it cannot be used.
