### ISSUE TITLE
Properly Dispose of the ErrorReportingExceptionFilter

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#803]
We currently do not properly clean up the ErrorReportingExceptionFilter's Resources

**Comment by iantalarico** [comment]
Dropping to P2 as the resources are alive as long as the application

**Comment by jskeet** [comment]
Closing for now having added this to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/BACKLOG.md)

**Comment by amanda-tarafa** [comment]
ErrorReportingExceptionFilter is from the Diagnostics.AspNet package which we don't support (except for critical bug fixes) as per  #4828.
Removing this issue from backlog.
