### ISSUE TITLE
Inconsistency between trace and error-reporting/logging

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#813]
I'm trying to customize my gRPC clients so that I can modify retry.

For error reporting (somewhat tortuously) and logging (simply) I can just specify the client. For trace I need to specify a `Task<TraceServiceClient>`. Is there a good reason for the inconsistency, or did we modify most things to be synchronous but not trace?

**Comment by iantalarico** [comment]
I originally had all of them taking the Task but after speaking with you about how little time they take to initialize I've slowly been working that out.

I can front load this change if need be.

**Comment by jskeet** [comment]
No urgency - just wasn't sure whether it was deliberate :)
