### ISSUE TITLE
Idle gRPC channels cause Unavailable exceptions

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#822]
Currently only seen on GAE Flex and GKE, but without diagnosing why, it's hard to say how wide the effect would be.

Symptoms: after a leaving a Datastore or Logging channel open for a while, make a request which isn't classified as idempotent. It will fail with a status of Unavailable, but a subsequent request will work.

**Comment by jskeet** [comment]
This has now moved to Internal errors sometimes being thrown - which is odd, as I hadn't seen those before when retrying Unavailable. I haven't worked out which API they're from yet. Log entry:

> Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="{"created":"@1488460159.079369617","description":"Transport closed","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1072}

**Comment by jskeet** [comment]
Slight suspicion: I think when I had a solid service after retrying Unavailable, I may have been using gRPC 1.0, whereas now I'm using 1.1. I wonder whether 1.1 exposes an extra kind of error in a way that 1.0 didn't...

**Comment by jskeet** [comment]
Fixed via #917 which updates to Gax beta13, which in turn depends on gRPC 1.2.

**Comment by Thaina** [comment]
Got this error sometimes. "Transport closed" and "GOAWAY"

Using firestore in serverless lambda

**Comment by jskeet** [comment]
@Thaina: Is that when using the streaming Watch API? If so, that's a different situation, and one that the Watch API support in the client library will handle transparently.

**Comment by Thaina** [comment]
@jskeet I don't know is it internally used streaming watch API. I only use transaction, batch write, and normal get/query

**Comment by jskeet** [comment]
@Thaina: Please open a new issue with a lot more detail. At the moment we know almost nothing about your context.
