### ISSUE TITLE
Detect dev vs non-dev environment for Google.Cloud.Diagnostic.* Libraries

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#829]
Detecting dev vs non dev environments will allow for turning on and off features based on the environment.  This requires more investigation and thought about use cases.

cc @jskeet

**Comment by Jetski5822** [comment]
Injecting in IHostingEnvrionment and using IsDevelopment() could work for this. Whats the scenarios?

I did this  in Orchard Core, but instead registered the middleware and services based on Environment

**Comment by iantalarico** [comment]
We just want to make sure we don't report unneeded diagnostic info when we are in development mode.

**Comment by jskeet** [comment]
Closing for now having added this to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/BACKLOG.md)
