### ISSUE TITLE
Consider accessing IManagedTracers from the IHttpContextAccessor 

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#835]
Currently for Google.Cloud.Diagnostics.AspNetCore access for IManagedTracers is done by dependency injects and each IManagedTraceris scoped to the current request.  This requires users to have to inject the scope based IManagedTracers.

We should consider passing around instead a singleton Func<IManagedTracer> that relies on IHttpContextAccessor where the user would not have to worry about scoping.

cc: @jskeet

**Comment by jskeet** [comment]
That would be internal, right? I think we'd want it to just be a simple interface to inject - it just magically does the right thing. Whether that's IManagedTracer or something else (IContextManagedTracer?) is a different matter.

**Comment by iantalarico** [comment]
Yes this would be internal.  Thinking about it more it may be easier to just create an IManagerTracer that stubs out the calls via the IHttpContextAccessor

**Comment by jskeet** [comment]
We could reuse `IManagedTracer` but it might be cleanest to have something different so that if a user looks at the type they know whether it's a tracer or a proxy for a tracer, if you see what I mean. But we can definitely look at that later :)

**Comment by iantalarico** [comment]
Yea I think I see what you mean, I'll mull over this some more after Next ;)
