### ISSUE TITLE
Add a parameter Func<HttpRequest, bool?> to Google.Cloud.Diagnostics.AspNet.CloudTrace.Initialize

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#840]
This will allow users to make decisions about what is traced when a trace header is not set.

**Comment by jskeet** [comment]
So this is the AspNet version of the existing AspNetCore code?

**Comment by iantalarico** [comment]
Correct, I have a few changes made to the AspNetCore bits I needs to apply to the AspNet bits.

**Comment by iantalarico** [comment]
Fixed via #877
