### ISSUE TITLE
Allow user to specify failure mode for diagnostic libraries

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#842]
This is about the Google.Cloud.Diagnostics.* libraries rather than the underlying API packages, so only blocks the release of those higher level libraries.

If calls to Stackdriver APIs fail, what should we do? Currently, we just let the exception propagate:

- If that happens synchronously within a request, the request will fail. (Not sure when this would occur, but it could be interesting if Error Reporting middleware fails...)
- If that happens asynchronously due to log buffering, it will bring down the process

In *some* cases that may be what the user wants. Other options the user may want:

- Buffer for some time and retry periodically, failing if the diagnostic failure continues for a long time.
- Buffer for some time but then start throwing away log entries and other requests to avoid failing
- Don't even bother buffering - make diagnostics "best effort, but don't waste memory"

**Comment by iantalarico** [comment]
"If that happens asynchronously due to log buffering," Is this only for the background flushing?  I don't think bringing down the process is ever reasonable for the diag libs.

Do you think it's reasonable to allow the user to select the failure mode? 

Should we selectively propagate certain errors? Auth or config errors but not timeouts, service unavailable, ect?

**Comment by jskeet** [comment]
Ideally we'd expose some sort of health checking mechanism that diag can hook into and say "I'm not very healthy" - that would definitely be better than just taking down the process.

Until we have something like that, we probably want to just make sure it *never* takes down the process. How much failure buffering we provide is a different matter... I don't have firm opinions on that.

**Comment by iantalarico** [comment]
In the short term to avoid taking down the process do you think a silent failure in the timer is acceptable?

For the short term (and not GA) a request failing is okay with me but I want to process falling over.

**Comment by jskeet** [comment]
Yes, I think a silenced failure would be a good short term fix.

**Comment by iantalarico** [comment]
@jskeet Thinking about a solution for this more:
Retry: I think for retry we should just point users to Google.Api.Gax.Grpc.CallSettings.  
Failure:  Have an option on consumers to throw or swallow exceptions from Grpc calls.

Thoughts?

**Comment by jskeet** [comment]
Do you mean add that option to `CallSettings`, or have it specifically for logging? I'm more in favour of the latter than the former.

But the retry for logging is somewhat different to the one in `CallSettings`, in that we'd be buffering the data on overall call failure - sure, we'd retry that, but we might need different policies, amounts of data to buffer etc.

**Comment by iantalarico** [comment]
I mean use call CallSettings for logging, trace and error reporting and have a well defined default.

As for the buffer I think the 3 options you mentioned when you opened the bug would be a good starting point.

Does that work?

**Comment by jskeet** [comment]
Well, we can check that the defaults are set appropriately, certainly. But I think most of this issue is really about the situation when any "in-call" retries have already failed.

**Comment by iantalarico** [comment]
Leaving this open to track the unit and integration tests
