### ISSUE TITLE
Add a default filter for tracing to avoid certain traces

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#847]
The trace diagnostics library currently traces based on QPS however if running on app engine the health check url (/_ah/health) gets called frequently and causes spam in trace logs.  We should add a default filter for the Func<HttpRequest, bool?> param that will filter out these requests.

cc: @jskeet

**Comment by iantalarico** [comment]
Reopen this as I think we should have a default in general

**Comment by jskeet** [comment]
(Sorry, that comment wasn't intended to close this issue!)
