### ISSUE TITLE
500 error from backend when setting GCS Metadata value as null

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-dotnet#850]
When updating an existing GCS object, if you add Metadata and one of the values of the key/value pairs is null, you get a 500 error (but no helpful error message) from the backend.

Not sure how we should proceed. Do we prevent you from entering null values? (Throw at runtime... yuck.) Automatically replace with ""? (Modify user data... yuck.) Perhaps the only good thing to do is to request that the GCS API allows for null keys... but I imagine that won't happen.

So this is probably WAI, unfortunately.

```csharp
var obj = gcsClient.GetObject(CoversBucket, ObjectPrefix + book.ID);
obj.Metadata = new Dictionary<string, string>
{
    { "Language", LanguageUtils.FriendlyName(book.Language) },
    { "Title", book.ActualTitle },
    { "Color", book.CoverSettings.BackgroundColor.ToString() },
    { "Image", book.CoverSettings.ImageName }
};
gcsClient.UpdateObject(obj);
```

**Comment by jskeet** [comment]
I don't think that's quite WAI:

- It should be HTTP 400 rather than 500
- It should give a useful error message

cc @Capstan for advice on filing an internal bug on this.

(I can investigate what JSON is sent if that's useful.)

**Comment by jskeet** [comment]
Closing this issue as it's reported internally, and all further effort will be there.
