### ISSUE TITLE
Authentication with Xamarin?

### ISSUE THREAD

**Issue by Tgeo** [GoogleCloudPlatform/google-cloud-dotnet#851]
I'm not able to find a way to authenticate with an API key using this library with Xamarin; is this supported?

**Comment by jskeet** [comment]
No, API keys aren't supported for any of the APIs in this repository.

**Comment by Tgeo** [comment]
Understood. Is that on the roadmap? Also, as an aside -- is there anyone using this library with Xamarin?

**Comment by jskeet** [comment]
No, gRPC APIs don't support API keys at the server side - at least typically.

**Comment by Tgeo** [comment]
OK, thanks for the info! Closing.

**Comment by vbisbest** [comment]
So how are you authenticating in code?   I cannot figure out how to do this with the Vision API.  I am on mobile platform so setting a environment variable does not work.  I am trying to use this call:
var client = ImageAnnotatorClient.Create();

**Comment by jskeet** [comment]
@vbisbest: The gRPC-based libraries aren't supported on mobile at all at the moment. If they work in some environments, it's more through luck than design! (In particular, you'd need a version of the gRPC native library compiled for whatever architecture you're on.)

**Comment by danielbenedykt** [comment]
I installed the nuget into Xamarin and it seems to compile and start running without any issues.

But it's not clear to me how to authenticate.

How do I authenticate ?  using GOOGLE_APPLICATION_CREDENTIALS   or some other way ?

**Comment by jskeet** [comment]
> I installed the nuget into Xamarin

Which NuGet package? I wouldn't expect any package that uses gRPC to work unless you're running on an x86/x64 processor.

As for how you authenticate - you *could* use `GOOGLE_APPLICATION_CREDENTIALS` if you're happy to have a service account JSON file on the device, but that's not ideal in many cases. You could use other ways of getting user credentials, but the auth library doesn't support Xamarin either yet.

Fundamentally we don't support mobile scenarios at the moment, although we'd like to in the future.

**Comment by danielbenedykt** [comment]
Thanks for the quick response.

My bad,  it runs on iOS simulator (x64) but it does not run on the device.
