### ISSUE TITLE
ImageAnnotatorClient thread safety 

### ISSUE THREAD

**Issue by sia-s** [GoogleCloudPlatform/google-cloud-dotnet#856]
Is ImageAnnotatorClient thread safe? I have several working threads sending OCR requests to google vision cloud. Should create a new instance of ImageAnnotatorClient for every single request?

**Comment by jskeet** [comment]
You're absolutely fine to use a single client everywhere, and indeed that's encouraged :)

**Comment by moander** [comment]
@jskeet does this apply to all dotnet clients? Found this looking for info about FirestoreDb thread safety

**Comment by jskeet** [comment]
@moander: Yes, it should be fine for all clients.
