### ISSUE TITLE
Provide documentation on using emulators

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#859]
We're not baking emulator support into the client libraries at the moment, but we should provide documentation for how to do it.

**Comment by alexvanboxel** [comment]
Thanks, this gave me enough info how todo it:

`var publisher = PublisherClient.Create(new Channel("localhost", 8019, ChannelCredentials.Insecure))`

**Comment by jskeet** [comment]
Glad it helped - I definitely want to add more details though. In particular, when you provide the channel yourself, you're responsible for disposing of it or reusing it appropriately. I'm expecting to add this doc to the "main" APIs page (https://googlecloudplatform.github.io/google-cloud-dotnet/docs/index.html) as it will apply to multiple APIs.
