### ISSUE TITLE
NullReferenceException during DatastoreDb.Create in F# .NET Core app

### ISSUE THREAD

**Issue by dustinmoris** [GoogleCloudPlatform/google-cloud-dotnet#863]
In an empty F# .NET Core application this line of code throws a `NullReferenceException`:
```
let db = DatastoreDb.Create "<some-project-id>"
```

These are the exception details:
```
Exception message: Object reference not set to an instance of an object.

Exception type: System.NullReferenceException

Stack trace:    at Google.Api.Gax.Grpc.UserAgentBuilder.AppendDotNetEnvironment()
   at Google.Api.Gax.Grpc.ServiceSettingsBase..ctor()
   at Google.Cloud.Datastore.V1.DatastoreClientImpl..ctor(DatastoreClient grpcClient, DatastoreSettings settings)
   at Google.Cloud.Datastore.V1.DatastoreClient.Create(Channel channel, DatastoreSettings settings)
   at Google.Cloud.Datastore.V1.DatastoreDb.Create(String projectId, String namespaceId, DatastoreClient client)
   at Program.subscribeToMailingList(Subscriber subscriber)
```

**Comment by jskeet** [comment]
Thanks very much for reporting this. It sounds like `Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default` is probably returning null. We'll look into it.

**Comment by jskeet** [comment]
(Chris, I've assigned you to start with as you were looking into this before. Let me know if you want me to take it instead.)

**Comment by dustinmoris** [comment]
Hi, I wanted to provide more info yesterday, but I was too tired.

This is how you can reproduce it:

Create a new dotnet core application in F#:

```
mkdir GCloudTest
cd GCloudTest
dotnet new console -lang f#
```

Change the contents of the two files to the following:

##### GCloudTest.fsproj

```
<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" Version="4.1.*" />
    <PackageReference Include="FSharp.NET.Sdk" Version="1.0.*" PrivateAssets="All" />
    <PackageReference Include="Google.Cloud.Datastore.V1" Version="1.0.0-*" />
  </ItemGroup>
</Project>
```

##### Program.fs

```
open System
open Google.Cloud.Datastore.V1

[<EntryPoint>]
let main argv =
    let db = DatastoreDb.Create "dustins-private-project"
    printfn "Hello World from F#!"
    0
```

Then just run:

```
dotnet restore
dotnet build
dotnet run
```

and you'll get the following exception:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Google.Api.Gax.Grpc.UserAgentBuilder.AppendDotNetEnvironment()
   at Google.Api.Gax.Grpc.ServiceSettingsBase..ctor()
   at Google.Cloud.Datastore.V1.DatastoreClientImpl..ctor(DatastoreClient grpcClient, DatastoreSettings settings)
   at Google.Cloud.Datastore.V1.DatastoreClient.Create(Channel channel, DatastoreSettings settings)
   at Google.Cloud.Datastore.V1.DatastoreDb.Create(String projectId, String namespaceId, DatastoreClient client)
   at Program.main(String[] argv) in C:\Temp\FSharpNetCoreGCloudTest\Program.fs:line 8
```

I am on a Windows 10 x64 machine and my dotnet --version is:

```
dotnet --version
1.0.1
```

**Comment by dustinmoris** [comment]
UPDATE:

The issue is [this line of code](https://github.com/aspnet/PlatformAbstractions/blob/dev/src/Microsoft.Extensions.PlatformAbstractions/ApplicationEnvironment.cs#L29) in `Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment`:

```
GetEntryAssembly()?.GetCustomAttribute<TargetFrameworkAttribute>()?.FrameworkName
```

For some reason with the latest `FSharp.NET.Sdk` the assembly doesn't produce the `TargetFrameworkAttribute` which is why `ApplicationEnvironment.RuntimeFramework` returns `null`.

I tested it and it works with the preview F# compiler `"dotnet-compile-fsc":"1.0.0-preview2-*"`.

This code:

```
open System
open System.IO
open System.Reflection
open System.Runtime.Versioning
open Microsoft.Extensions.PlatformAbstractions

let getEntryAssembly() =
    let getEntryAssemblyMethod =
        match (typeof<Assembly>).GetMethod("GetEntryAssembly", (BindingFlags.Static ||| BindingFlags.NonPublic)) with
        | null -> (typeof<Assembly>).GetMethod("GetEntryAssembly", (BindingFlags.Static ||| BindingFlags.Public))
        | x -> x    
    (getEntryAssemblyMethod.Invoke(null, [||])) :?> Assembly

[<EntryPoint>]
let main argv =
    match getEntryAssembly() with
    | null -> printfn "NULL"
    | assembly ->
        assembly.GetCustomAttributes()
        |> Seq.iter (fun attr -> printfn "%s" (attr.ToString()))
        printfn "%s" (assembly.GetCustomAttribute<TargetFrameworkAttribute>().FrameworkName)

    printfn "Hello World from F#!"
    0
```

returns the following when building an older project with `dotnet-compile-fsc`:

```
Microsoft.FSharp.Core.FSharpInterfaceDataVersionAttribute
System.Reflection.AssemblyTitleAttribute
System.Reflection.AssemblyDescriptionAttribute
System.Reflection.AssemblyCopyrightAttribute
System.Reflection.AssemblyFileVersionAttribute
System.Reflection.AssemblyVersionAttribute
System.Reflection.AssemblyInformationalVersionAttribute
System.Reflection.AssemblyCultureAttribute
System.Resources.NeutralResourcesLanguageAttribute
System.Runtime.Versioning.TargetFrameworkAttribute
System.Diagnostics.DebuggableAttribute
.NETCoreApp,Version=v1.1
Hello World from F#!
```

but returns only this with `FSharp.NET.Sdk`:

```
Microsoft.FSharp.Core.FSharpInterfaceDataVersionAttribute
System.Diagnostics.DebuggableAttribute

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by dustinmoris** [comment]
### INTERMEDIATE WORKAROUND:

Until `FSharp.NET.Sdk` has been fixed I can manually set assembly attributes to workaround this issue.

In my project I created an `AssemblyInfo.fs` file (the name doesn't really matter) and set the following code:

```
namespace System

[<assembly:System.Runtime.Versioning.TargetFrameworkAttribute(".NETCoreApp,Version=v1.1")>]
do ()
```

Then added it to the list of compiled files in the fsproj:

```
<ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
```

and it works.

**Comment by dustinmoris** [comment]
This is not really a google cloud sdk issue anymore.

**Comment by jskeet** [comment]
Well, it sounds like it's at least *somewhat* a Google issue, in that we should work around it - we can log an "unknown" version for F# assemblies until it's fixed - that shouldn't be too hard to do.

Thank you so much for your diligent investigation: really above and beyond the call of duty :)

**Comment by dustinmoris** [comment]
Ok makes sense. Well.. that is sort of the beauty of OpenSource :) I love FSharp and the gcloud, this SDK is brilliant and my project relies on it and I don't want to be blocked until this is resolved, so it was kind of my duty to investigate until I can keep moving, right? ;)

Also happy to help where I can!

**Comment by davidfowl** [comment]
Interesting issue. We can update the logic to use AppContext.TargetFrameworkName when running on .NET Core (the API wasn't available at the time).

**Comment by enricosada** [comment]
thx @dustinmoris , added issue https://github.com/dotnet/netcorecli-fsc/issues/93

atm the intermediate file with these attributes is not generated.

**Comment by jskeet** [comment]
I think this was fixed by the GAX change...
