### ISSUE TITLE
Datastore LookupAsync not working

### ISSUE THREAD

**Issue by tomerNG** [GoogleCloudPlatform/google-cloud-dotnet#866]
I'm querying the Datastore using **LookupAsync** and specific key but the entity isn't returned (getting null).
However trying the same with **Lookup** succeed to get the entity.

Seems like **LookupAsync** not working... Anyone tested it?

**Comment by jskeet** [comment]
Could you provide a complete example? For example, are you calling `Lookup` in `DatastoreClient`, `DatastoreDb` or `DatastoreTransaction`?

**Comment by tomerNG** [comment]
Sure:
var db = DatastoreDb.Create("myprojectid");
var key = new Key().WithElement("mykindname", id);
var resAsync = await db .**LookupAsync**(key); // **Returns null**
var res = await db .**Lookup**(key); //**Returns the Entity**

**Comment by jskeet** [comment]
Okay, will see if I can reproduce - thanks.

**Comment by jskeet** [comment]
Hmm... it's working for me - I've just added an integration test [here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.IntegrationTests/DatastoreDbTest.cs#L141)

Are you able to provide a minimal example in a console app (or as an integration test) that demonstrates the failure? I'm very keen to reproduce this if at all possible...

**Comment by tomerNG** [comment]
I saw your test, but it's a bit different from my code.
In my example I'm building the key on my own without creating an entity ( var entity = new Entity), maybe this is the difference...
I'm just querying an existing entity in the DB just using the Key object.
Just like that:
var db = DatastoreDb.Create("myprojectid");
var key = **new Key().WithElement("mykindname", id)**;
var resAsync = await db .LookupAsync(key); // Returns null
var res = db .Lookup(key); //Returns the Entity

**Comment by jskeet** [comment]
It shouldn't matter how you obtained the key - if it's valid for `Lookup` it should be valid for `LookupAsync`. At *some* point you must have inserted the entity - I'm just doing the whole thing in a complete way so I can run just the test code. The important point is that I'm passing the same key to both `LookupAsync` and `Lookup`, and getting the same response - whereas you appear to be doing the same thing, but getting different results.

Again, could you provide a complete example that I can run to see the problem?

**Comment by jskeet** [comment]
Ignore me - I know what's wrong, and yes, your way of creating the key *does* make a difference. Will add an integration test for this case...

**Comment by jskeet** [comment]
On a side-note, if you use `db.CreateKeyFactory` you won't run into this and your code will be easier to read :)

**Comment by tomerNG** [comment]
Cool! That is indeed working, I'll use the createKeyFactory way :)

Thanks!
