### ISSUE TITLE
PubSub PUBSUB_EMULATOR_HOST variable is not recognised

### ISSUE THREAD

**Issue by alexvanboxel** [GoogleCloudPlatform/google-cloud-dotnet#870]
It seems that the **PUBSUB_EMULATOR_HOST** environment variable is not detected. This makes it impossible to use the PubSub emulator.

As an alternative we tried:

`PublisherClient.Create(new ServiceEndpoint("localhost", 8019))`

but that doesn't seem to work.

**Comment by jskeet** [comment]
It doesn't make it impossible to use the emulator - it means you have to get the value of the environment variable yourself, and create the channel yourself. Unfortunately just setting the endpoint isn't enough as the emulator rejects channel attempts with credentials.

I have #859 already to document how to do this.

I won't be providing support for the current environment variable, as I'm hoping for a rather better, easier-to-use solution "soon". (No timelines, I'm afraid.)
