### ISSUE TITLE
Test top 4 APIs on GAE Flex, GKE, and GCE

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-dotnet#878]
Test BigQuery, Storage, Datastore, and Logging client libraries on all the GCP platforms (don't include GAE Standard).

Close this issue once we confirm it all works.

**Comment by jskeet** [comment]
What level of testing are you looking for here? Is running our existing integration test suite on each platform enough? (Not that that makes it trivial, admittedly - but @chrisdunelm has recent experience in running tests on each platform.)

For GCE, what kinds of test do we need - vanilla Linux VM? Docker container in a Linux VM? Windows VM?

**Comment by omaray** [comment]
All great questions. I would say that on GCE since you have .NET then on Windows would make sense. I would say this is a sanity check.

And in general I'm looking really for a general sanity check here. We want to make sure there are no obvious bugs here or dead on arrival situations. I don't expect it at all - but we've hit some issues before actually. So trying out each of the 4 on these platforms would be great.

**Comment by jskeet** [comment]
Fortunately, we've tested BigQuery, Datastore and Logging already on GKE and GAE Flex while building and demonstrating the Cloud Next 2017 demo - I can do a sanity check of Storage in the same way.

Then we just need to make sure the integration tests run on Windows on GCE, which I think both @chrisdunelm  and @iantalarico have been looking at. At that point we can close this bug, although we'll want to automate similar tests in the future.

**Comment by jskeet** [comment]
Assigning to myself to test storage - then will assign to Chris for "run the integration tests on a Windows box in GCE manually" (as he has a suitable GCE instance already, I believe.)

**Comment by omaray** [comment]
SGTM.

**Comment by jskeet** [comment]
Validated Storage on GKE and Flex. Passing on to Chris now...

**Comment by chrisdunelm** [comment]
All integration tests passed on GCE.
Except for:
* Pubsub, because my project isn't whitelisted for StreamingPull
* Diagnostics.Common, due to a quota issue; not a client-side problem

So I think this issue can be closed.

**Comment by jskeet** [comment]
Thanks Chris! Closing.
