### ISSUE TITLE
PollUntilCompleted throws "Method not found: '!!0 Google.Api.Gax.Polling.PollRepeatedly"

### ISSUE THREAD

**Issue by UkrZilla** [GoogleCloudPlatform/google-cloud-dotnet#881]
Hi guys,

We do simple select queries to a few tables in BigQuery:

`connection.ExecuteQuery(command).PollUntilCompleted().GetRows();`

and for some small tables we have an exception:

`Method not found: '!!0 Google.Api.Gax.Polling.PollRepeatedly(System.Func`2,!!0>, System.Predicate`1, Google.Api.Gax.IClock, Google.Api.Gax.IScheduler, Google.Api.Gax.PollSettings)'.
at Google.Bigquery.V2.BigqueryClientImpl.PollQueryUntilCompleted(JobReference jobReference, GetQueryResultsOptions options, PollSettings pollSettings) at Google.Bigquery.V2.BigqueryQueryJob.PollUntilCompleted(PollSettings pollSettings) `

Could you explain what does it mean and how can we fix it?

Thanks

**Comment by jskeet** [comment]
That suggests you've got version mismatch between the libraries somehow. Could you let me know which version of `Google.Cloud.BigQuery.V2` you're using, and which version of `Google.Api.Gax`?

**Comment by UkrZilla** [comment]
Hi @jskeet 

Google.Cloud.BigQuery.V2: 1.21.0.785
Google.Api.Gax: 1.0.0-beta12

**Comment by jskeet** [comment]
Ah - that's a very old version of the BigQuery library. We changed the name back in December for consistency... we stopped "advertising" the Google.Bigquery.V2 library, but if you already had a Nuget reference to it, it would still be fetchable.

Please update to Google.Cloud.BigQuery.V2 instead - I'm afraid you'll need to change all your code that refers to "Bigquery" to refer to "BigQuery", and change your imports, but I think everything else should move very easily.

**Comment by UkrZilla** [comment]
Hi @jskeet ,

Thanks, it works

**Comment by jskeet** [comment]
Wonderful, thanks - closing this issue.
