### ISSUE TITLE
NRE in GoogleStackdriverAppender.OnClose

### ISSUE THREAD

**Issue by ctaggart** [GoogleCloudPlatform/google-cloud-dotnet#893]
![image](https://cloud.githubusercontent.com/assets/80104/24012974/26754792-0a3d-11e7-986c-caeb716c4108.png)

```
Exception Info: System.NullReferenceException
   at Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender.OnClose()
   at log4net.Appender.AppenderSkeleton.Close()
   at log4net.Appender.AppenderSkeleton.Finalize()
```

I'm disposing of the GoogleStackdriverAppender. A NRE is being thrown. I think it may occur when nothing is logged.

Google.Cloud.Logging.Log4Net (1.0.0-beta09)

**Comment by chrisdunelm** [comment]
How are you creating the `GoogleStackdriverAppender` instance?
Are you creating it through log4net configuration? Or creating it manually?
And how are you retrieving the instance and disposing of it?
Are you able to post some of your code?

This is most likely caused by an unconfigured `GoogleStackdriverAppender`, but I haven't been able to reproduce this in a test case yet.

**Comment by ctaggart** [comment]
Sure, this is based on http://blog.ctaggart.com/2016/11/google-logging-from-log4net.html

``` fsharp
type Log4NetLogger(projectId, logId) =

    let appender =
        let appender = new Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender()
        appender.ProjectId <- projectId
        appender.LogId <- logId
        appender.Layout <- log4net.Layout.PatternLayout ( ConversionPattern = "%message" )
        appender.ActivateOptions()
        let hierarchy = log4net.LogManager.GetRepository() :?> log4net.Repository.Hierarchy.Hierarchy
        hierarchy.Root.AddAppender appender
        hierarchy.Root.Level <- log4net.Core.Level.Debug
        hierarchy.Configured <- true
        appender

    interface ILogger with
        member x.Debug msg =
            let logger = log4net.LogManager.GetLogger logId
            logger.Debug msg

        member x.Info msg =
            let logger = log4net.LogManager.GetLogger logId
            logger.Info msg

        member x.Error msg =
            let logger = log4net.LogManager.GetLogger logId
            logger.Error msg

        member x.Exception msg ex =
            let logger = log4net.LogManager.GetLogger logId
            logger.Error(msg, ex)

        member x.AddLabel key value =
            appender.AddCustomLabel(Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender.Label(Key=key, Value=value))

    // https://github.com/ctaggart/SourceLink/blob/v1/SourceLink/PdbFile.fs#L152-L156
    member x.Dispose() =
        use appender = appender
        System.GC.SuppressFinalize x
    interface System.IDisposable with
        member x.Dispose() = x.Dispose() 
```

**Comment by chrisdunelm** [comment]
Is the exception thrown when you dispose of this Log4NetLogger class?
Please forgive my lack of F# knowledge, but where exactly is `appender.Dispose()` being called?

Would you be able to show some code that uses this `Log4NetLogger` class, and point out where the exception occurs?

**Comment by chrisdunelm** [comment]
On re-reading the initial stack trace, I now see that the appender was GCed, and `OnClose()` is being called from the `AppenderSkeleton` finalizer.
I've added a test that GCs an uninitialized `GoogleStackDriverAppender`, which reproduced the error shown; and I've added code to not attempt to close the `LogUploader` if it was never initialised.

However, I'm still confused how the code shown ended up in this situation, as you do call `appender.ActivateOptions()`.

**Comment by ctaggart** [comment]
Thanks. I don't have time to troubleshoot today, but perhaps next week. I think you are on the right track.

**Comment by chrisdunelm** [comment]
@ctaggart Did you get a chance to check this?

**Comment by ctaggart** [comment]
I didn't, but we haven't come across this lately. I'll reopen if it happens again.
