### ISSUE TITLE
Google.Cloud.BigQuery.V2.IntegrationTests.BigQueryParameterTest.NullParameter Fails on Linux

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#902]
The integration test  Google.Cloud.BigQuery.V2.IntegrationTests.BigQueryParameterTest.NullParameter is passing when running on Windows but faisl on Linux.

The failure is on [BigQueryParameterTest.cs @ line 97](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/0339b85ed4ad91412addb42e019800a17efcb610/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/BigQueryParameterTest.cs#L97)

On windows and linux the BQ table highscore is created it has two entries where the "player" is null.  One has a 'null' score.  The other has a score of '1'.

On windows only the entry with the score of '1' is returned while on linux both are returned.

**Comment by jskeet** [comment]
Hmm. I've now been able to reproduce this on my Linux box. I wonder if it's a test-ordering issue. I'll check whether anything else is inserting into that table.

**Comment by jskeet** [comment]
Got it - I think. I believe it's `InsertTest.Insert_BadData_IgnoreBadData`. Will change that to make it insert into a new table.
