### ISSUE TITLE
Add documentation about commit limits

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#903]

**Comment by jskeet** [comment]
(Only 500 entities per commit.)

**Comment by ILMTitan** [comment]
I have been thinking about this, and I think we should automatically batch for Insert requests. Insert does not make any promises about transactional logic, and if the user cared strongly, they would be using a transaction.

**Comment by jskeet** [comment]
I'd far rather be consistent, to be honest. It gets complicated *really* quickly in terms of retries and the like. It also means the library doesn't need to be changed if Datastore's limits change, for example.

**Comment by jskeet** [comment]
(Have asked internally for comment from the Datastore team.)

**Comment by jskeet** [comment]
Confirmed that this is really an application concern. (I know that feels like a cop-out, but the number of potential options required and inconsistency between inside/outside transactions is enough.)
