### ISSUE TITLE
Google.Cloud.Logging.Log4Net 1.0.0-beta09 not compatible with Dotnet Core

### ISSUE THREAD

**Issue by kmleow** [GoogleCloudPlatform/google-cloud-dotnet#934]
When installing, got the following error:

*is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Google.Cloud.Logging.Log4Net 1.0.0-beta09 supports: net45 (.NETFramework,Version=v4.5)*

Would be really handy to use Log4Net, hope that compatibility can be resolved not long from now.
Thank you

**Comment by jskeet** [comment]
The version of .NET we're targeting (2.0.5, which was the latest available when we first wrote this package) only targets net45. Now that later versions target netstandard1.3 as well, we should be able to target netstandard1.5 for the log4net adapter for Google.Cloud.Logging.

**Comment by chrisdunelm** [comment]
It appears to be difficult/impossible to iterate through all loaded assemblies/types under netcore, which means https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.Log4Net/GoogleStackdriverAppender.cs#L314 doesn't port easily to core.
This code isn't essential, it provides the assembly-qualified type name in the log entry.
I'll continue seeing if there is a way to do this for a little while, but might have to remove this functionality in core.

**Comment by jskeet** [comment]
This was fixed by #1032.
