### ISSUE TITLE
Google.Type namespace violates fxcop CA1724

### ISSUE THREAD

**Issue by benwulfe** [GoogleCloudPlatform/google-cloud-dotnet#936]
https://msdn.microsoft.com/en-us/library/ms182257.aspx

It conflicts with the classname "System.Type" which causes the error of "Type is a namespace but is used like a type".

Also @JimPrzybylinski mentions the conflicting classname Google.Api.Storage.Object which is slightly different, but still looks like it could cause an error.

**Comment by jskeet** [comment]
Unfortunately there's nothing we can do about this, really. (I've already done what I can for the well-known types, as otherwise we'd have `Google.Protobuf.Type` as a type name too.

It's certainly awkward, but that's just how the protos are defined :(
