### ISSUE TITLE
Add unit tests for receiving superset of expected API responses.

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-dotnet#949]
There was [a bug][] in the Node.js Vision client which was effectively that the client raised an exception if it ever got a key that it did not expect. This is relatively easy to do for any number of reasons:

```python
# `raw_response` is a dict that came back from the API.
key_map = {
    'alphaObject': 'alpha_object',
    'betaObject': 'beta_object',
}
new_response = {}
for k, v in raw_response.iteritems():
    new_response[key_map[k]] = v
```

This is an anti-pattern, because it strongly assumes that you will never get a new key that is not already in your key map. If the API adds a `gammaObject` key and this (Python) code were to run, suddenly what used to work now raises `KeyError`.

The solution: Add unit tests in each spot where we transform an API response into a custom object to ensure that unexpected key-value pairs are either passed through or dropped.

  [a bug]: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2034

**Comment by jskeet** [comment]
Protobufs in C# are strongly typed, and ignore unknown fields. (Later versions may add support for unknown fields, but it won't affect this.)

Basically, I don't believe we need to do this for C#, and I'd expect the same to be true for Java.

**Comment by lukesneeringer** [comment]
Are you always using the object that comes back directly (as opposed to making a custom one)?

**Comment by jskeet** [comment]
Even when we make a custom one, we get strongly typed objects with specific fields that we'd copy - we don't just take them out of a dictionary.
