### ISSUE TITLE
error CS1674: 'void': type used in a using statement must be implicitly convertible to 'System.IDisposable'

### ISSUE THREAD

**Issue by Jonathan34** [GoogleCloudPlatform/google-cloud-dotnet#951]
the following code fails on .net core 1.1 (in a controller):
```
public async Task<string> testAsync([FromServices] IManagedTracer tracer)
{
            using (tracer.StartSpan(nameof(testAsync)))
            {
...
            }
}
```
compile error:
`error CS1674: 'void': type used in a using statement must be implicitly convertible to 'System.IDisposable'`

the documentation says we can use it: http://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNetCore/
Am I missing something? 

(sorry to spam issues)

**Comment by jskeet** [comment]
I suspect this is a matter of the documentation being ahead of the released libraries.
I'm in the middle of preparing a release (the first for a few weeks). If you can hold off a little while, this may just fix itself...

**Comment by iantalarico** [comment]
@Jonathan34 jskeet is right I think our docs got a little ahead of the code release.

For now you can do (but we should have a new release soon!):
`
tracer.StartSpan(nameof(testAsync));
...
tracer.EndSpan();
`

**Comment by Jonathan34** [comment]
Yes I was using that but I noticed I had several returns in the middle and wanted to use a scoped object to dispose automatically... now i have to understand why nothing appears in the google console with startSpan/EndSpan :)

**Comment by iantalarico** [comment]
@Jonathan34 sorry about this! We should hopefully have a new release out soon that will make this much easier.

RE: "(sorry to spam issues)" please spam us with issues :) if something is wrong we want to know and will do our best to fix it.

**Comment by Jonathan34** [comment]
Good :)
Do you happen to have a slack channel in the google or .net slack teams?

**Comment by iantalarico** [comment]
We do have a slack channel for just this sort of thing:
https://googlecloud-community.slack.com/messages/C2ZV4FYV8

**Comment by Jonathan34** [comment]
works with 1.0.0-alpha08!
thanks, amazingly quick fix !

**Comment by jskeet** [comment]
@Jonathan34: I'd love to take credit for it being a really quick fix, but I spent many hours today sorting out the release - it was almost all ready by the time this was raised :)
