### ISSUE TITLE
Spanner API

### ISSUE THREAD

**Issue by tomerpeledNG** [GoogleCloudPlatform/google-cloud-dotnet#962]
Hi,

I was wondering when does the Spanner API will be official released?

Also, I've tried to work with the current implementation under this repository. Tried some simple snippet, such as follows:

```
SpannerClient spannerClient = SpannerClient.Create();
 // Initialize request argument(s)
DatabaseName database = new DatabaseName("myprojectid", "myinstance", "mydb");
// Make the request
Session response = spannerClient.CreateSession(database);
```

The CreateSession throws the following exception:
**Grpc.Core.RpcException: 'Status(StatusCode=InvalidArgument, Detail="Invalid CreateSession request.")'**

Anything I'm missing?

Thanks

**Comment by jskeet** [comment]
I wouldn't suggest working with the autogenerated code directly. It's there at the moment mostly to prove that it generates correctly - and I *have* used it successfully, so it definitely works - but the intention is to provide higher level abstractions on top. I can't give details at the moment, but watch this space.

As for why that request didn't work - I can't tell easily, to be honest. Does the project/instance/database definitely already exist?

**Comment by tomerpeledNG** [comment]
My bad - I fell on the instance name camel-case... It indeed works...

Ok, I'm planing to write this abstraction that you're talking about on top of this auto-generated code.
I'll start and see how things come up.

Any tips?

**Comment by jskeet** [comment]
Well, we already have resources allocated in Google for doing this work - so it's fine if you want to do that for the sake of interest, but you'll probably be duplicating work. You may well want to look at the Java code:  https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-spanner

**Comment by tomerpeledNG** [comment]
I understand, well we want to build it so that we can start to work with spanner on our .Net servers.

Can you tell if this lib implementation is on the roadmap for the near future (1-2 months)?

**Comment by jskeet** [comment]
We're expect work to *start* on it soon, but I expect it'll be a while before it's in even a beta release state. Designing this appropriately is not a trivial matter.

**Comment by tomerpeledNG** [comment]
Yes of course.
Maybe we'll start to work with Cloud SQL (MySQL) and Repository pattern in the meantime, just so that our models will be pretty much the same as with Spanner, and later on, when this lib will be ready, we will move to work with Spanner. 

Of course this will be only for the development phase, for production we will surely use Spanner anyhow (even if we'll need to write this lib on our own).

Thanks for the help and info!

**Comment by tomerpeled** [comment]
Just updating that I wrote some EFCore intergration on top of Spanner - currently it is working with this unofficial api.
Once this api will be official released I plan to integrate it as well...

https://github.com/NoGame/NG.Data.Spanner
