### ISSUE TITLE
Can ListRows work for Views as well as tables?

### ISSUE THREAD

**Issue by Jetski5822** [GoogleCloudPlatform/google-cloud-dotnet#963]
At the moment I get an error saying I cannot use this method for views, could this change?

**Comment by jskeet** [comment]
I assume this is about BigQuery? (Given the number of APIs this repo deals with, it's always worth stating which one you're using in the issue.)

It looks like this is a limitation of BigQuery itself. From https://cloud.google.com/bigquery/docs/views:

> You cannot use the TableDataList JSON API method to retrieve data from a view.

That's what the `ListRows` method calls. I wouldn't want to start trying to mimic `ListRows` behavior by performing queries on views instead. If your question was more a feature request from the underlying BigQuery API, I can pass that along to the product team, but I haven't heard any plans on that front.

**Comment by Jetski5822** [comment]
Okay cool

Currently on the BigQueryClinet we have methods for Creating table, i.e. CreateTable(), however we dont have a equivalent for Views... i.e. CreateView or GetOrCreateView... Will you introduce those? or should I write my own?

**Comment by jskeet** [comment]
I would expect views to be *read* in the same way as regular tables - while I haven't tried it, I'd expect ListTables to find the views. You'd need to look inside the REST resource to find the view information though.

For creating views, for now you'll need to drop down to the underlying REST API, but I'll add a feature request for creating a view - either by calling CreateTable with new options in CreateTableOptions, or with another call. I'll close this issue for now though, to avoid drift.
