### ISSUE TITLE
Spanner Commit

### ISSUE THREAD

**Issue by tomerNG** [GoogleCloudPlatform/google-cloud-dotnet#964]
Hi,

I'm trying to make an insert command via the commit and mutation api, with no success..
I'm getting the following error:
**RpcException: Status(StatusCode=InvalidArgument, Detail="Invalid Commit request.")**

My table has only one column: "tablecolumnname" which is defined as Int64

What am I missing?

This is my snippet:

```csharp
SpannerClient spannerClient = SpannerClient.Create();
DatabaseName database = new DatabaseName("myproject", "myintsance", "mydb");
Session sessionResponse = spannerClient.CreateSession(database);
IEnumerable<Mutation> mutations = new List<Mutation>
{
    new Mutation
    {
        Insert = new Mutation.Types.Write
        {
            Table = "mytable",
            Columns = {"tablecolumnname"},
            Values = {new ListValue
            {
                Values = { new Value
                {
                    NumberValue = 1
                }}
            }}
        }
    }
};
var res = await spannerClient.CommitAsync(new CommitRequest
{
    Mutations = { mutations },
    SessionAsSessionName = session
});
```

**Comment by jskeet** [comment]
As I've said before, we're discouraging end users from using this API directly - but it looks like you're missing the `Transaction` value from your `CommitRequest`.

**Comment by tomerNG** [comment]
Do I have to add the transaction?

I used the following snippet from the snippet file:

 public async Task CommitAsync_RequestObject()
        {
            // Snippet: CommitAsync(CommitRequest,CallSettings)
            // Create client
            SpannerClient spannerClient = await SpannerClient.CreateAsync();
            // Initialize request argument(s)
            CommitRequest request = new CommitRequest
            {
                SessionAsSessionName = new SessionName("[PROJECT]", "[INSTANCE]", "[DATABASE]", "[SESSION]"),
                Mutations = { },
            };
            // Make the request
            CommitResponse response = await spannerClient.CommitAsync(request);
            // End snippet
        }

**Comment by jskeet** [comment]
Yes, you have to either specify the value for the Transaction property, either as an existing transaction or a single use transaction. See https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/spanner.proto#L312

I would suggest this kind of thing is precisely why we're not supporting low-level use of the API...

**Comment by tomerNG** [comment]
OK, thanks.

I understand that this API isn't recommended, but we want to proceed with the Spanner integration and our servers are in .NET...

**Comment by jskeet** [comment]
Okay - just be aware that I won't have very much time to dedicate to this, and you'll almost certainly be doing things we haven't. I suggest you become very familiar with the linked proto file (and its peers), as well as reading the Java higher level abstraction code. Closing this issue for now.
