### ISSUE TITLE
LongRunningRecognize is not a member of SpeechClient C#

### ISSUE THREAD

**Issue by maciz84** [GoogleCloudPlatform/google-cloud-dotnet#977]
Hi Guys,

I am getting this when trying to use LongRunningRecognize??:

'LongRunningRecognize' is not a member of SpeechClient

I am using Google.Cloud.Speech.V1Beta1?

**Comment by jskeet** [comment]
Please update to Google.Cloud.Speech.V1, which is where that member was introduced. (The library is still in beta, but it's a V1 server API now.)

**Comment by maciz84** [comment]
Correct I have done this and all is well.

Thanks again for your help and just want to add your API is awesome.

**Comment by jskeet** [comment]
Yay - glad it's working well for you :) (I can't take any credit for the machine-learning smarts - I'm just making the hard work of my colleagues available to C# developers :)
