### ISSUE TITLE
Allow passing settings when creating a BigQuery Client

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#989]
Currently there is not way to pass options to the BigQuery client.  To set the timeout the user has to call:
```
BigQueryClient.Create("pid");
client.Service.HttpClient.Timeout = Timespan.fromSeconds(200).
```

Most of the other clients expose a settings object.  If this is by design we may want to add it to the docs.

**Comment by Jonathan34** [comment]
I ended up using Timeout.Infinite. Not even sure that is safe but i assume bigquery will always return... ultimately?
thanks @iantalarico

**Comment by jskeet** [comment]
I think actually there's a limit within the BigQuery service. If this is a query, the preferred approach is to call `CreateQueryJob` and poll for that to complete.

**Comment by jskeet** [comment]
Closing for the moment as I don't plan on any changes, unless more information is provided about what is trying to be achieved.
