### ISSUE TITLE
Logging - client.ListLogEntries() taking longer to complete causing test timeouts

### ISSUE THREAD

**Issue by jsimonweb** [GoogleCloudPlatform/google-cloud-dotnet#990]
Our automated [logging test ](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/logging/api/LoggingTest/LoggingTest.cs) which leverage this client library started timing out at Apr 12, 2017 4:39:00 PM (UTC). 

Our timeout configuration is currently set to allow the test to run for 5 minutes which it has successfully done for months since Nov. 2016. The tests suddenly started taking beyond the 5 minute threshold without any changes to the sample tests or to the VM/testing platform on which they run.

It appears that the call to client.ListLogEntries()  is taking considerably longer to complete than it used to causing our previously successful tests to time out.

**Comment by chrisdunelm** [comment]
I'm unable to reproduce this.

Steps I took:
* Took a fresh clone of https://github.com/GoogleCloudPlatform/dotnet-docs-samples.git
* Set up auth using a service account
* Opened [LoggingSample.sln](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/logging/api/LoggingSample.sln) in VS2015
* Ran the test [TestListEntries](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/logging/api/LoggingTest/LoggingTest.cs#L110), which passed in about 10 seconds.

I also directly ran the same program with the "list-log-entries" option, and it completed succesfully. Have you tried running this directly? Does it timeout too?

**Comment by jsimonweb** [comment]
Confirmed this library seems to be working as expected, so closing for now.
