### ISSUE TITLE
CancellationToken for DownloadObject

### ISSUE THREAD

**Issue by xclayl** [GoogleCloudPlatform/google-cloud-dotnet#994]
It'd be nice to be able to pass a CancellationToken to DownloadObject(Object, Stream).  And possibly return true/false if the download was successful/interrupted.  

The download for us can take some time and when we stop the Windows Service (triggering the CancellationToken), the only option we have is to kill the app.  
I'd prefer to be able to clean up the file in progress.  
When stopping the Windows Service, we have a 30s wait for it to finish naturally, so stopping our service can take some time if it's in the middle of downloading a file.

**Comment by jskeet** [comment]
Is there any reason you don't want to use `DownloadObjectAsync`, which already takes a `CancellationToken`? It's fairly rare to accept a `CancellationToken` in a synchronous API call.

**Comment by xclayl** [comment]
I guess I could "go async" for the one call. Or make everything async. 

I'll probably do the async method for the one call. Though, I'm not totally comfortable switching back and forth from sync to async (catching exceptions for instance)

**Comment by xclayl** [comment]
haha, know anyone who knows C# really well?  I just realised who I'm talking to. :)
